/* REQOO PKSK DASHBOARD V2 — canonical app.js */
const API='/api/pksk';
const $=id=>document.getElementById(id);
let LICENSE='',DASH=null,FILTER='all';
function device(){let id=localStorage.getItem('reqoo_pksk_device_id');if(!id){id='DEV-'+crypto.getRandomValues(new Uint32Array(3)).join('-')+'-'+Date.now().toString(36);try{localStorage.setItem('reqoo_pksk_device_id',id)}catch(_){}}return id}
async function api(action,data={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...data}),signal:controller.signal,cache:'no-store'});let d;try{d=await r.json()}catch(_){d={ok:false,error:`Respons server tidak sah (${r.status}).`}}if(!r.ok||d.ok===false)throw Error(d.error||'Sambungan server gagal.');return d}catch(e){throw Error(e?.name==='AbortError'?'Server mengambil masa terlalu lama.':e?.message||'Sambungan server gagal.')}finally{clearTimeout(timer)}}
function setMsg(text,kind=''){const m=$('msg');m.textContent=text;m.className='msg '+kind}
async function login(code,quiet=false){code=String(code||'').trim().toUpperCase();if(!code){if(!quiet)setMsg('Masukkan Access Code.','bad');return}if(!quiet){$('start').disabled=true;$('start').textContent='MENYEMAK…'}try{await api('validateAccess',{code});await api('registerDevice',{code,deviceId:device(),userAgent:navigator.userAgent});LICENSE=code;localStorage.setItem('reqoo_pksk_license',code);openDash()}catch(e){if(!quiet)setMsg(e.message,'bad');$('start').disabled=false;$('start').textContent='SEMAK & MASUK'}}
async function openDash(){$('login').style.display='none';$('dashboard').style.display='block';$('copy').classList.remove('hidden');$('logout').classList.remove('hidden');await load()}
async function load(){try{const r=await api('getCustomerDashboard',{code:LICENSE,deviceId:device()});render(r)}catch(e){localStorage.removeItem('reqoo_pksk_license');LICENSE='';$('dashboard').style.display='none';$('login').style.display='block';setMsg(e.message,'bad')}}
function padSet(n){return String(Number(n)||1).padStart(2,'0')}
function clamp(v,min=0,max=100){return Math.max(min,Math.min(max,Number(v)||0))}
function avg(list,fn){if(!list.length)return null;return Math.round(list.reduce((sum,x)=>sum+(Number(fn(x))||0),0)/list.length)}
function scoreCPercent(x){const n=Number(x?.scoreC||0);return clamp(n<=20?n*5:n)}
function niceDate(v){if(!v)return'';const d=new Date(v);if(!Number.isFinite(d.getTime()))return'';try{return new Intl.DateTimeFormat('ms-MY',{day:'numeric',month:'short'}).format(d)}catch(_){return''}}
function weakest(sets){const done=(sets||[]).filter(x=>x.completed&&Number.isFinite(Number(x.score)));return done.length?done.slice().sort((a,b)=>Number(a.score)-Number(b.score)||Number(a.setNo)-Number(b.setNo))[0]:null}
function strongest(sets){const done=(sets||[]).filter(x=>x.completed&&Number.isFinite(Number(x.score)));return done.length?done.slice().sort((a,b)=>Number(b.score)-Number(a.score)||Number(a.setNo)-Number(b.setNo))[0]:null}
function firstTarget(r){const sets=r.sets||[],inc=sets.find(x=>x.status==='incomplete');if(inc)return inc;const requested=sets.find(x=>Number(x.setNo)===Number(r.nextSet)&&x.status!=='completed');return requested||sets.find(x=>x.status==='not_started')||weakest(sets)||sets[0]||{setNo:1,status:'not_started'}}
function openSet(set,status='not_started'){const n=Math.max(1,Math.min(50,Number(set)||1));if(status==='completed'){if(!confirm(`Ulang Set ${padSet(n)} dari soalan pertama?\n\nMarkah lama kekal sehingga anda tamat dan hantar percubaan baharu.`))return}else if(status==='incomplete'){if(!confirm(`Mulakan semula Set ${padSet(n)} dari soalan pertama?\n\nPercubaan yang belum selesai pada peranti ini akan dimulakan semula.`))return}go(n)}
function actionFor(x){if(x.status==='completed')return'Ulang set';if(x.status==='incomplete')return'Mula semula';return'Mula set'}
function filteredSets(sets){if(FILTER==='all')return sets;if(FILTER==='retry')return sets.filter(x=>x.completed&&Number(x.score)<60);return sets.filter(x=>x.status===FILTER)}
function renderSets(sets){const list=filteredSets(sets||[]),grid=$('sets');$('setCount').textContent=`${list.length} set`;grid.innerHTML=list.map(x=>{const status=x.status||'not_started',done=status==='completed',inc=status==='incomplete',retry=done&&Number(x.score)<60,pct=done?clamp(x.score):inc?clamp(x.answered,0,99):0,badge=done?'Selesai':inc?'Belum lengkap':'Belum mula',score=done?`${Number(x.score||0)}%`:inc?`${Number(x.answered||0)}/100`:'—',date=niceDate(x.updatedAt),meta=done?`${date?'Terakhir '+date+' • ':''}${retry?'Disaran ulang untuk kukuhkan prestasi':'Set lengkap'}`:inc?`Sudah jawab ${Number(x.answered||0)} soalan • mula semula dari awal`:'30 A • 70 B • Penulisan',action=actionFor(x);return `<button type="button" class="set-card ${status}${retry?' retry':''}" data-set="${Number(x.setNo)}" data-status="${status}" aria-label="${action} Set ${padSet(x.setNo)}"><div class="set-top"><span class="set-title">Set ${padSet(x.setNo)}</span><span class="set-badge">${badge}</span></div><div class="set-score">${score}</div><div class="set-meta">${meta}</div><div class="setbar"><i style="width:${pct}%"></i></div><div class="set-action"><span>${action}</span><span>→</span></div></button>`}).join('')||'<div class="empty">Tiada set dalam kategori ini.</div>';grid.querySelectorAll('.set-card[data-set]').forEach(el=>el.addEventListener('click',()=>openSet(el.dataset.set,el.dataset.status)))}
function renderPerformance(sets){const done=(sets||[]).filter(x=>x.completed),a=avg(done,x=>x.scoreA),b=avg(done,x=>x.scoreB),c=avg(done,scoreCPercent);$('performanceCount').textContent=`${done.length} set dinilai`;[['perfA','perfABar',a],['perfB','perfBBar',b],['perfC','perfCBar',c]].forEach(([label,bar,value])=>{$(label).textContent=value==null?'—':`${value}%`;$(bar).style.width=`${value==null?0:clamp(value)}%`})}
function configureActions(r){const sets=r.sets||[],target=firstTarget(r),weak=weakest(sets),all=Boolean(r.allComplete),n=Number(target?.setNo||1),status=target?.status||'not_started';let primaryLabel,primaryTitle,primaryText,primaryRun;if(all&&weak){primaryLabel=`ULANG SET ${padSet(weak.setNo)} →`;primaryTitle='Ulang set paling lemah';primaryText=`Set ${padSet(weak.setNo)} • ${weak.score}%`;primaryRun=()=>openSet(weak.setNo,'completed')}else if(status==='incomplete'){primaryLabel=`MULA SEMULA SET ${padSet(n)} →`;primaryTitle=`Set ${padSet(n)} belum lengkap`;primaryText='Mulakan semula dari soalan pertama';primaryRun=()=>openSet(n,'incomplete')}else{primaryLabel=`MULA SET ${padSet(n)} →`;primaryTitle=`Mula Set ${padSet(n)}`;primaryText='Teruskan latihan seterusnya';primaryRun=()=>go(n)}$('nextBtn').textContent=primaryLabel;$('nextBtn').onclick=primaryRun;$('quickNextTitle').textContent=primaryTitle;$('quickNextText').textContent=primaryText;$('quickNext').onclick=primaryRun;const weakButtons=[$('weakBtn'),$('quickWeak')];if(weak){weakButtons.forEach(btn=>{btn.disabled=false;btn.onclick=()=>openSet(weak.setNo,'completed')});$('weakBtn').textContent=`ULANG SET ${padSet(weak.setNo)} • ${weak.score}%`;$('quickWeakText').textContent=`Set ${padSet(weak.setNo)} • ${weak.score}%`;}else{weakButtons.forEach(btn=>{btn.disabled=true;btn.onclick=null});$('weakBtn').textContent='ULANG SET PALING LEMAH';$('quickWeakText').textContent='Selesaikan satu set dahulu';}}
function renderActivity(activity){$('activity').innerHTML=(activity||[]).map(a=>`<div class="act"><span>${a.message||'Aktiviti'}</span><small>${niceDate(a.createdAt)||a.createdAt||''}</small></div>`).join('')||'<div class="empty">Belum ada set yang selesai.</div>'}
function render(r){DASH=r;const l=r.license||{},s=r.summary||{},sets=r.sets||[],total=Number(r.totalSets||50),completed=Number(s.completed||0),progress=Math.round(completed/Math.max(1,total)*100),best=strongest(sets);$('name').textContent=l.name||'Pelajar';$('deviceInfo').textContent=`${l.deviceCount||0} / ${l.maxDevices||3} peranti digunakan`;$('devices').textContent=`${l.deviceCount||0} / ${l.maxDevices||3}`;$('done').textContent=`${completed} / ${total}`;$('doneHint').textContent=`${progress}% modul selesai`;$('avg').textContent=s.average==null?'—':`${s.average}%`;$('heroProgressText').textContent=`${completed} / ${total} set`;$('heroProgressBar').style.width=`${progress}%`;if(best){$('best').textContent=`Set ${padSet(best.setNo)}`;$('bestHint').textContent=`${best.score}% • skor tertinggi`}else{$('best').textContent='—';$('bestHint').textContent='Belum ada keputusan'}if(r.allComplete)$('heroLead').textContent='Tahniah, semua set telah selesai. Gunakan prestasi di bawah untuk pilih set yang patut diulang.';else if(Number(s.incomplete||0)>0)$('heroLead').textContent='Ada latihan yang belum lengkap. Mulakan semula set tersebut atau teruskan ulang kaji daripada dashboard ini.';else $('heroLead').textContent='Teruskan latihan anda. Semua kemajuan disimpan pada akaun yang sama dan boleh dibuka semula pada peranti berdaftar.';renderPerformance(sets);configureActions(r);renderSets(sets);renderActivity(r.activity||[])}
function go(set){location.href='../simulator/?set='+encodeURIComponent(set)+'&start=1'}
$('filters').querySelectorAll('.filter-chip').forEach(btn=>btn.addEventListener('click',()=>{FILTER=btn.dataset.filter||'all';$('filters').querySelectorAll('.filter-chip').forEach(x=>x.classList.toggle('active',x===btn));if(DASH)renderSets(DASH.sets||[])}));
$('quickPerformance').onclick=()=>$('performanceSection').scrollIntoView({behavior:'smooth',block:'start'});
$('start').onclick=()=>login($('code').value);$('code').addEventListener('keydown',e=>{if(e.key==='Enter')login($('code').value)});$('paste').onclick=async()=>{try{$('code').value=(await navigator.clipboard.readText()).trim().toUpperCase()}catch(_){setMsg('Tekan lama pada kotak untuk tampal.','bad')}};$('logout').onclick=()=>{localStorage.removeItem('reqoo_pksk_license');location.reload()};$('copy').onclick=()=>{if(!LICENSE)return;navigator.clipboard?.writeText(LICENSE).then(()=>{$('copy').textContent='✓ DISALIN';setTimeout(()=>$('copy').textContent='SALIN KOD',1200)}).catch(()=>{})};
const q=(new URLSearchParams(location.search).get('code')||'').trim().toUpperCase(),saved=(localStorage.getItem('reqoo_pksk_license')||'').trim().toUpperCase();if(q){$('code').value=q;setTimeout(()=>login(q,true),120)}else if(saved){$('code').value=saved;setTimeout(()=>login(saved,true),120)}