/* REQOO PKSK DASHBOARD — canonical app.js */
const API='/api/pksk';
const $=id=>document.getElementById(id);let LICENSE='';
function device(){let id=localStorage.getItem('reqoo_pksk_device_id');if(!id){id='DEV-'+crypto.getRandomValues(new Uint32Array(3)).join('-')+'-'+Date.now().toString(36);try{localStorage.setItem('reqoo_pksk_device_id',id)}catch(_){}}return id}
async function api(action,data={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...data}),signal:controller.signal,cache:'no-store'});let d;try{d=await r.json()}catch(_){d={ok:false,error:`Respons server tidak sah (${r.status}).`}}if(!r.ok||d.ok===false)throw Error(d.error||'Sambungan server gagal.');return d}catch(e){throw Error(e?.name==='AbortError'?'Server mengambil masa terlalu lama.':e?.message||'Sambungan server gagal.')}finally{clearTimeout(timer)}}
function setMsg(text,kind=''){const m=$('msg');m.textContent=text;m.className='msg '+kind}
async function login(code,quiet=false){code=String(code||'').trim().toUpperCase();if(!code){if(!quiet)setMsg('Masukkan Access Code.','bad');return}if(!quiet){$('start').disabled=true;$('start').textContent='MENYEMAK…'}try{await api('validateAccess',{code});await api('registerDevice',{code,deviceId:device(),userAgent:navigator.userAgent});LICENSE=code;localStorage.setItem('reqoo_pksk_license',code);openDash()}catch(e){if(!quiet)setMsg(e.message,'bad');$('start').disabled=false;$('start').textContent='SEMAK & MASUK'}}
async function openDash(){ $('login').style.display='none';$('dashboard').style.display='block';$('copy').classList.remove('hidden');$('logout').classList.remove('hidden');await load() }
async function load(){try{const r=await api('getCustomerDashboard',{code:LICENSE,deviceId:device()});render(r)}catch(e){localStorage.removeItem('reqoo_pksk_license');LICENSE='';$('dashboard').style.display='none';$('login').style.display='block';setMsg(e.message,'bad')}}
function render(r){const l=r.license||{},s=r.summary||{};$('name').textContent=l.name||'Pelajar';$('deviceInfo').textContent=`${l.deviceCount||0} / ${l.maxDevices||3} peranti digunakan`;$('devices').textContent=`${l.deviceCount||0} / ${l.maxDevices||3}`;$('done').textContent=`${s.completed||0} / ${r.totalSets||50}`;$('incomplete').textContent=String(s.incomplete||0);$('avg').textContent=s.average==null?'—':s.average+'%';$('sets').innerHTML=(r.sets||[]).map(x=>{const label=x.status==='completed'?'✓ Selesai':x.status==='incomplete'?'⚠ Tidak lengkap':'Belum mula';const pct=x.completed?Math.max(0,Math.min(100,Number(x.score||0))):x.answered?Math.min(99,Math.round(Number(x.answered||0)/100*100)):0;return `<div class="set ${x.status}"><b>Set ${String(x.setNo).padStart(2,'0')}</b><small>${label}${x.completed?' • '+x.score+'%':''}</small><div class="setbar"><i style="width:${pct}%"></i></div></div>`}).join('');const all=r.allComplete,next=Number(r.nextSet||1);$('nextBox').classList.toggle('done',all);if(all){$('nextTitle').textContent='Semua 50 set selesai 🎉';$('nextText').textContent='Tahniah. Semua set telah diselesaikan. Anda boleh ulang mana-mana set dari menu simulator.';$('nextBtn').textContent='ULANG SET 01 →';$('nextBtn').onclick=()=>go(1)}else{$('nextTitle').textContent=`Set ${String(next).padStart(2,'0')} menanti`;$('nextText').textContent=`Tekan untuk mula Set ${String(next).padStart(2,'0')} dari soalan pertama. Set yang pernah tergantung tidak akan disambung di tengah.`;$('nextBtn').textContent=`MULA SET ${String(next).padStart(2,'0')} →`;$('nextBtn').onclick=()=>go(next)}$('activity').innerHTML=(r.activity||[]).map(a=>`<div class="act"><span>${a.message||'Aktiviti'}</span><small>${a.createdAt||''}</small></div>`).join('')||'<div class="empty">Belum ada set yang selesai.</div>'}
function go(set){location.href='../simulator/?set='+encodeURIComponent(set)+'&start=1'}
$('start').onclick=()=>login($('code').value);$('code').addEventListener('keydown',e=>{if(e.key==='Enter')login($('code').value)});$('paste').onclick=async()=>{try{$('code').value=(await navigator.clipboard.readText()).trim().toUpperCase()}catch(_){setMsg('Tekan lama pada kotak untuk tampal.','bad')}};$('logout').onclick=()=>{localStorage.removeItem('reqoo_pksk_license');location.reload()};$('copy').onclick=()=>{if(!LICENSE)return;navigator.clipboard?.writeText(LICENSE).then(()=>{$('copy').textContent='✓ DISALIN';setTimeout(()=>$('copy').textContent='SALIN KOD',1200)}).catch(()=>{})};
const q=(new URLSearchParams(location.search).get('code')||'').trim().toUpperCase(),saved=(localStorage.getItem('reqoo_pksk_license')||'').trim().toUpperCase();if(q){$('code').value=q;setTimeout(()=>login(q,true),120)}else if(saved){$('code').value=saved;setTimeout(()=>login(saved,true),120)}