function corsHeaders(request) {
  const origin = request.headers.get('Origin') || '';
  const allowed = new Set(['https://reqoo.co','https://www.reqoo.co','https://admin.reqoo.co','http://localhost:8787']);
  return {'Access-Control-Allow-Origin': allowed.has(origin) ? origin : 'https://reqoo.co','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS','Access-Control-Allow-Headers':'Content-Type, X-Admin-Key','Vary':'Origin'};
}
function json(data,status=200,request){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json',...corsHeaders(request)}})}
function slugify(value){return String(value||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function cleanProduct(input){const name=String(input?.name||'').trim();if(!name)throw new Error('Product name is required');return{name,slug:slugify(input?.slug||name),description:String(input?.description||'').trim(),price:Number(input?.price||0),images:JSON.stringify(Array.isArray(input?.images)?input.images.map(String).map(s=>s.trim()).filter(Boolean):[]),published:input?.published?1:0,sort:Number(input?.sort||0)}}
function output(row){if(!row)return null;return{...row,images:(()=>{try{return JSON.parse(row.images||'[]')}catch{return[]}})(),published:Boolean(row.published)}}
function authorized(request,env){const key=request.headers.get('X-Admin-Key');return Boolean(env.ADMIN_KEY&&key&&key===env.ADMIN_KEY)}
export default{async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders(request)});const url=new URL(request.url);if(url.pathname==='/health')return json({ok:true,service:'reqoo-catalog'},200,request);if(!url.pathname.startsWith('/products'))return json({error:'Not found'},404,request);try{if(request.method==='GET'){const published=url.searchParams.get('published')==='true';const query=published?'SELECT * FROM products WHERE published = 1 ORDER BY sort ASC, created_at DESC':'SELECT * FROM products ORDER BY sort ASC, created_at DESC';const{results}=await env.DB.prepare(query).all();return json(results.map(output),200,request)}if(!authorized(request,env))return json({error:'Unauthorized'},401,request);if(request.method==='POST'){const p=cleanProduct(await request.json()),id=crypto.randomUUID();await env.DB.prepare(`INSERT INTO products (id,name,slug,description,price,images,published,sort,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,datetime('now'),datetime('now'))`).bind(id,p.name,p.slug,p.description,p.price,p.images,p.published,p.sort).run();return json(output(await env.DB.prepare('SELECT * FROM products WHERE id = ?').bind(id).first()),201,request)}const id=decodeURIComponent(url.pathname.slice('/products/'.length));if(!id)return json({error:'Product id required'},400,request);if(request.method==='PUT'){const p=cleanProduct(await request.json());await env.DB.prepare(`UPDATE products SET name=?,slug=?,description=?,price=?,images=?,published=?,sort=?,updated_at=datetime('now') WHERE id=?`).bind(p.name,p.slug,p.description,p.price,p.images,p.published,p.sort,id).run();return json(output(await env.DB.prepare('SELECT * FROM products WHERE id = ?').bind(id).first()),200,request)}if(request.method==='DELETE'){await env.DB.prepare('DELETE FROM products WHERE id = ?').bind(id).run();return json({ok:true,id},200,request)}return json({error:'Method not allowed'},405,request)}catch(error){return json({error:error?.message||'Server error'},400,request)}}};
