const CUSTOMER_TOKEN_TTL=30*24*60*60*1000;
function jsonError(error,status){return new Response(JSON.stringify({ok:false,error}),{status,headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store'}})}
function b64u(v){return btoa(v).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function unb64u(v){return atob(String(v).replaceAll('-','+').replaceAll('_','/')+'='.repeat((4-String(v).length%4)%4))}
async function hmac(value,secret){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(String(secret)),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value));return b64u(String.fromCharCode(...new Uint8Array(sig)))}
async function safeToken(value,secret){const [payload,sig]=String(value||'').split('.');if(!payload||!sig||!secret)return null;const expected=await hmac(payload,secret);if(expected!==sig)return null;try{const data=JSON.parse(unb64u(payload));if(!data?.phone||Number(data.exp||0)<Date.now())return null;return data}catch{return null}}
async function protectPayment(request,env){const expected=String(env.ADMIN_API_KEY||'');if(!expected)return jsonError('PAYMENT_ADMIN_AUTH_NOT_CONFIGURED',503);if(request.headers.get('authorization')!==`Bearer ${expected}`)return jsonError('PAYMENT_ADMIN_UNAUTHORIZED',401);return null}
async function readShopInput(request,url){const actionFromUrl=url.searchParams.get('action');if(request.method==='GET'||!['POST','PUT','PATCH'].includes(request.method))return {data:{},action:actionFromUrl};const clone=request.clone();const type=(request.headers.get('content-type')||'').toLowerCase();if(type.includes('application/json')){try{const data=await clone.json();return {data:data||{},action:String(data?.action||actionFromUrl||'')}}catch{}}return {data:{},action:actionFromUrl}}
async function protectShopCustomer(request,env,url){const secret=String(env.SHOP_CUSTOMER_SECRET||'');if(!secret)return {error:jsonError('SHOP_CUSTOMER_AUTH_NOT_CONFIGURED',503)};const token=request.headers.get('x-reqoo-customer-token')||url.searchParams.get('customer_token');const customer=await safeToken(token,secret);if(!customer)return {error:jsonError('CUSTOMER_AUTH_REQUIRED',401)};const parsed=await readShopInput(request,url);const action=parsed.action;if(action!=='customerOrders'&&action!=='getOrder')return {request};if(action==='customerOrders'){if(parsed.data&&Object.keys(parsed.data).length){const next={...parsed.data,phone:customer.phone};return {request:new Request(request,{body:JSON.stringify(next)})}}url.searchParams.set('phone',customer.phone);url.searchParams.delete('customer_token');return {request:new Request(url,request)}}const key=String(parsed.data?.orderRef||parsed.data?.orderId||url.searchParams.get('orderRef')||url.searchParams.get('orderId')||'').trim();if(!key)return {error:jsonError('ORDER_REQUIRED',400)};if(!env.SHOP_DB)return {error:jsonError('SHOP_DB_BINDING_MISSING',503)};const row=await env.SHOP_DB.prepare('SELECT o.id,c.phone FROM orders o JOIN customers c ON c.id=o.customer_id WHERE (o.order_ref=? OR o.id=?) LIMIT 1').bind(key,key).first();if(!row||String(row.phone)!==String(customer.phone))return {error:jsonError('ORDER_NOT_FOUND',404)};return {request}}

export async function onRequest(context){
  const {request,env}=context;
  const url=new URL(request.url),host=url.hostname;
  if(host==='pksk.sim.reqoo.co'&&url.pathname==='/api/pksk-v56'){url.pathname='/api/pksk-v2';return context.next(new Request(url,request))}
  if(host==='sim.reqoo.co'&&!url.pathname.startsWith('/api/')){url.pathname=url.pathname==='/'?'/sim/':`/sim${url.pathname}`;return env.ASSETS.fetch(url)}
  if(host==='pksk.sim.reqoo.co'&&!url.pathname.startsWith('/api/')){let path=url.pathname;if(path==='/pksk'||path.startsWith('/pksk/'))path=path.slice('/pksk'.length)||'/';const isSimulator=path==='/simulator'||path.startsWith('/simulator/');const isAccess=path==='/'||path==='/access'||path.startsWith('/access/');url.pathname=path==='/'?'/sim/pksk/':`/sim/pksk${path}`;let response=await env.ASSETS.fetch(url);const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;if(isSimulator)return new HTMLRewriter().on('script[src="js/app.js?v=18"]',{element(el){el.remove()}}).on('body',{element(el){el.append('<script src="/sim/pksk/simulator/js/app-v2.js?v=2"></script>',{html:true})}}).transform(response);if(isAccess)return new HTMLRewriter().on('script',{element(el){el.remove()}}).on('body',{element(el){el.append('<script src="/sim/pksk/access/app-v2.js?v=2"></script>',{html:true})}}).transform(response);return response}
  if(host.endsWith('.sim.reqoo.co')&&host!=='sim.reqoo.co'&&!url.pathname.startsWith('/api/')){const child=host.slice(0,-'.sim.reqoo.co'.length);if(child&&!child.includes('.')){let path=url.pathname;if(path===`/${child}`||path.startsWith(`/${child}/`))path=path.slice(child.length+1)||'/';url.pathname=path==='/'?`/sim/${child}/`:`/sim/${child}${path}`;return env.ASSETS.fetch(url)}}
  if(host==='play.reqoo.co'&&!url.pathname.startsWith('/api/')){url.pathname=url.pathname==='/'?'/play/':`/play${url.pathname}`;return env.ASSETS.fetch(url)}
  if(host==='shop.reqoo.co'&&url.pathname.startsWith('/api/payment-v1')){const denied=await protectPayment(request,env);if(denied)return denied}
  if(host==='shop.reqoo.co'&&url.pathname==='/api/shop'){
    const parsed=await readShopInput(request,url);
    if(parsed.action==='customerOrders'||parsed.action==='getOrder'){const guarded=await protectShopCustomer(request,env,url);if(guarded.error)return guarded.error;return context.next(guarded.request||request)}
  }
  if(host==='shop.reqoo.co'&&!url.pathname.startsWith('/api/')&&!url.pathname.startsWith('/shop/')){url.pathname=url.pathname==='/'?'/shop/':`/shop${url.pathname}`;const response=await env.ASSETS.fetch(url),type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;return new HTMLRewriter().on('body',{element(el){el.append('<script src="/shop/payment-fallback.js?v=4"></script><script src="/shop/payment-fix.js?v=1"></script>',{html:true})}}).transform(response)}
  if(host==='admin.reqoo.co'&&!url.pathname.startsWith('/api/')){url.pathname=url.pathname==='/'?'/admin/':url.pathname;const response=await env.ASSETS.fetch(url),type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;return new HTMLRewriter().on('body',{element(el){el.append('<link rel="stylesheet" href="/admin/reqoo-admin-universal.css?v=3.2.0"><link rel="stylesheet" href="/admin/reqoo-admin-premium-v2.css?v=1.0.0"><script src="/admin/reqoo-admin-shell.js?v=1.0.0"></script>',{html:true})}}).transform(response)}
  return context.next();
}