(()=>{
'use strict';
const nativeFetch=window.fetch.bind(window),files=[],variantFiles=new Map(),$=id=>document.getElementById(id);
const token=()=>localStorage.getItem('reqoo_admin_token')||'';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function style(){if($('reqoo-admin-gallery-style'))return;const s=document.createElement('style');s.id='reqoo-admin-gallery-style';s.textContent='.reqoo-gallery-tools{margin-top:8px;padding:12px;border:1px solid #e2e8f0;border-radius:12px;background:#f8fafc}.reqoo-gallery-tools input{margin:6px 0}.reqoo-gallery-grid{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.reqoo-gallery-thumb,.reqoo-variant-thumb{width:76px;height:76px;border-radius:10px;object-fit:cover;border:1px solid #d7e0eb}.reqoo-gallery-note{font-size:11px;color:#64748b;line-height:1.45}.reqoo-variant-image{grid-column:1/-1;padding:8px;border:1px dashed #d7e0eb;border-radius:10px;background:#f8fafc}.reqoo-variant-image label{display:block}.reqoo-variant-preview{display:flex;gap:8px;align-items:center;margin-top:5px}.reqoo-variant-preview span{font-size:10px;color:#64748b}';document.head.appendChild(s)}
function addGalleryUI(){const f=$('pImageFile');if(!f||$('reqooGalleryTools'))return;f.multiple=true;const wrap=document.createElement('div');wrap.id='reqooGalleryTools';wrap.className='reqoo-gallery-tools';wrap.innerHTML='<b>Gallery produk</b><div class="reqoo-gallery-note">Pilih beberapa gambar sekali gus. Gambar pertama jadi cover; selebihnya dipaparkan sebagai gallery.</div><div class="reqoo-gallery-grid" id="reqooGalleryGrid"></div>';f.insertAdjacentElement('afterend',wrap);f.addEventListener('change',()=>{files.splice(0);files.push(...Array.from(f.files||[]));render()})}
function render(){const g=$('reqooGalleryGrid');if(!g)return;g.innerHTML='';files.forEach((f,i)=>{const im=document.createElement('img');im.className='reqoo-gallery-thumb';im.title=i===0?'Cover':'Gallery';im.src=URL.createObjectURL(f);g.appendChild(im)})}
function variantRows(){return [...document.querySelectorAll('#variants .variant')]}
function decorateVariants(){variantRows().forEach((row,i)=>{if(row.querySelector('.reqoo-variant-image'))return;const wrap=document.createElement('div');wrap.className='reqoo-variant-image';wrap.innerHTML='<label>Gambar variation</label><input type="file" class="reqoo-variant-file" accept="image/jpeg,image/png,image/webp,image/gif"><div class="reqoo-variant-preview"></div>';const input=wrap.querySelector('input');input.addEventListener('change',()=>{const f=input.files?.[0];if(f)variantFiles.set(row,f);else variantFiles.delete(row);const p=wrap.querySelector('.reqoo-variant-preview');p.innerHTML=f?`<img class="reqoo-variant-thumb" src="${URL.createObjectURL(f)}"><span>${esc(f.name)}</span>`:''});row.appendChild(wrap)})}
function refreshVariantOptions(){const p=$('promoProduct'),v=$('promoVariant');if(!p||!v)return;const prod=(window.__reqooAdminProducts||[]).find(x=>String(x.id)===String(p.value)),vars=(prod?.variants||[]).filter(x=>x.active!==false),old=v.value;v.innerHTML='<option value="">Semua variation</option>'+vars.map(x=>`<option value="${esc(x.name)}">${esc(x.name)} — RM${(Number(x.price||0)/100).toFixed(2)}</option>`).join('');if(vars.some(x=>x.name===old))v.value=old}
function hookPromo(){const p=$('promoProduct');if(p&&!p.dataset.reqooBound){p.dataset.reqooBound='1';p.addEventListener('change',refreshVariantOptions)}refreshVariantOptions()}
async function uploadFile(productId,file){const fd=new FormData();fd.append('file',file,file.name);fd.append('productId',productId);const r=await nativeFetch('/api/product-image',{method:'POST',headers:{'X-Admin-Token':token()},body:fd});const x=await r.json();return x.ok&&x.url?x.url:''}
async function uploadImages(productId){const urls=[];for(const file of files){const u=await uploadFile(productId,file);if(u)urls.push(u)}return urls}
async function uploadVariantImages(productId,data){const rows=variantRows(),items=Array.isArray(data.variants)?data.variants.map(x=>({...x})):[];for(let i=0;i<rows.length;i++){const file=variantFiles.get(rows[i]);if(!file||!items[i])continue;const u=await uploadFile(productId,file);if(u)items[i].imageUrl=u}return items}
function hasVariantFiles(){return variantFiles.size>0}
function clearFiles(){files.splice(0);variantFiles.clear();if($('pImageFile'))$('pImageFile').value='';document.querySelectorAll('.reqoo-variant-file').forEach(x=>x.value='');document.querySelectorAll('.reqoo-variant-preview').forEach(x=>x.innerHTML='')}
function hookFetch(){if(window.__reqooAdminGalleryHook)return;window.__reqooAdminGalleryHook=1;window.fetch=async function(input,init){const url=typeof input==='string'?input:(input?.url||''),method=(init?.method||input?.method||'GET').toUpperCase();if(method==='POST'&&url.includes('/api/shop-admin')){let data=null;try{data=typeof init?.body==='string'?JSON.parse(init.body):null}catch{}if(data?.action==='saveProduct'&&(files.length||hasVariantFiles())){const response=await nativeFetch(input,init);let j=null;try{j=await response.clone().json()}catch{}const productId=j?.productId||j?.product?.id||data.id;if(productId){try{let changed=false;const urls=await uploadImages(productId);if(urls.length){await nativeFetch('/api/shop-media',{method:'POST',headers:{'Content-Type':'application/json','X-Admin-Token':token()},body:JSON.stringify({action:'saveImages',productId,images:urls})});changed=true}const variants=await uploadVariantImages(productId,data);if(JSON.stringify(variants)!==JSON.stringify(data.variants||[])){await nativeFetch('/api/shop-admin',{method:'POST',headers:{'Content-Type':'application/json','X-Admin-Token':token()},body:JSON.stringify({...data,variants})});changed=true}clearFiles();if(changed)setTimeout(()=>window.loadAll?.(),200)}catch(e){console.error('REQOO media save',e)}}return response}}return nativeFetch(input,init)}}
async function loadProducts(){try{const r=await nativeFetch('/api/shop-admin',{method:'POST',headers:{'Content-Type':'application/json','X-Admin-Token':token()},body:JSON.stringify({action:'listProducts'})});const j=await r.json();window.__reqooAdminProducts=j.products||[];refreshVariantOptions()}catch{}}
function boot(){style();addGalleryUI();decorateVariants();hookFetch();hookPromo();loadProducts()}
boot();setTimeout(boot,500);setTimeout(boot,1500);new MutationObserver(()=>decorateVariants()).observe(document.body,{subtree:true,childList:true});
})();