(()=>{
'use strict';
const nativeFetch=window.fetch.bind(window),files=[],$=id=>document.getElementById(id);
function style(){if($('reqoo-admin-gallery-style'))return;const s=document.createElement('style');s.id='reqoo-admin-gallery-style';s.textContent='.reqoo-gallery-tools{margin-top:8px;padding:12px;border:1px solid #e2e8f0;border-radius:12px;background:#f8fafc}.reqoo-gallery-tools input{margin:6px 0}.reqoo-gallery-grid{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.reqoo-gallery-thumb{width:76px;height:76px;border-radius:10px;object-fit:cover;border:1px solid #d7e0eb}.reqoo-gallery-note{font-size:11px;color:#64748b;line-height:1.45}';document.head.appendChild(s)}
function addGalleryUI(){const f=$('pImageFile');if(!f||$('reqooGalleryTools'))return;f.multiple=true;const wrap=document.createElement('div');wrap.id='reqooGalleryTools';wrap.className='reqoo-gallery-tools';wrap.innerHTML='<b>Gallery produk</b><div class="reqoo-gallery-note">Pilih beberapa gambar sekali gus. Gambar pertama jadi cover; selebihnya dipaparkan sebagai gallery.</div><div class="reqoo-gallery-grid" id="reqooGalleryGrid"></div>';f.insertAdjacentElement('afterend',wrap);f.addEventListener('change',()=>{files.splice(0);files.push(...Array.from(f.files||[]));render()})}
function render(){const g=$('reqooGalleryGrid');if(!g)return;g.innerHTML='';files.forEach((f,i)=>{const im=document.createElement('img');im.className='reqoo-gallery-thumb';im.title=i===0?'Cover':'Gallery';im.src=URL.createObjectURL(f);g.appendChild(im)})}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function refreshVariantOptions(){const p=$('promoProduct'),v=$('promoVariant');if(!p||!v)return;const prod=(window.__reqooAdminProducts||[]).find(x=>String(x.id)===String(p.value)),vars=(prod?.variants||[]).filter(x=>x.active!==false),old=v.value;v.innerHTML='<option value="">Pilih variant</option>'+vars.map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('');if(vars.some(x=>x.name===old))v.value=old}
function hookPromo(){const p=$('promoProduct');if(p&&!p.dataset.reqooBound){p.dataset.reqooBound='1';p.addEventListener('change',refreshVariantOptions)}refreshVariantOptions()}
function hookFetch(){if(window.__reqooAdminGalleryHook)return;window.__reqooAdminGalleryHook=1;window.fetch=async function(input,init){const url=typeof input==='string'?input:(input?.url||'');const method=(init?.method||input?.method||'GET').toUpperCase();if(method==='POST'&&url.includes('/api/shop-admin')&&files.length){let data=null;try{data=typeof init?.body==='string'?JSON.parse(init.body):null}catch{}if(data?.action==='saveProduct'){const response=await nativeFetch(input,init);let j=null;try{j=await response.clone().json()}catch{}const productId=j?.productId||j?.product?.id||data.id;if(productId){try{const urls=[];for(const file of files){const fd=new FormData();fd.append('file',file,file.name);fd.append('productId',productId);const r=await nativeFetch('/api/product-image',{method:'POST',body:fd});const x=await r.json();if(x.ok&&x.url)urls.push(x.url)}if(urls.length)await nativeFetch('/api/shop-media',{method:'POST',headers:{'Content-Type':'application/json','X-Admin-Token':localStorage.getItem('reqoo_admin_token')||''},body:JSON.stringify({action:'saveImages',productId,images:urls})});files.splice(0);if($('pImageFile'))$('pImageFile').value=''}catch(e){console.error('REQOO gallery save',e)}}return response}}return nativeFetch(input,init)}}
async function loadProducts(){try{const r=await nativeFetch('/api/shop-admin',{method:'POST',headers:{'Content-Type':'application/json','X-Admin-Token':localStorage.getItem('reqoo_admin_token')||''},body:JSON.stringify({action:'listProducts'})});const j=await r.json();window.__reqooAdminProducts=j.products||[];refreshVariantOptions()}catch{}}
function boot(){style();addGalleryUI();hookFetch();hookPromo();loadProducts()}
boot();setTimeout(boot,500);setTimeout(boot,1500);
})();
