(()=>{
'use strict';
const API='/api/shop',MEDIA='/api/shop-media';
const state={products:[],byId:new Map()};
const money=n=>'RM'+Number(n||0).toFixed(2);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const imageUrl=u=>{u=String(u||'').trim();if(!u)return '';if(/^https?:\/\//i.test(u)||u.startsWith('/'))return u;try{return new URL(u.replace(/^\.\//,''),location.href).href}catch{return ''}};
function normVariant(v){if(Array.isArray(v))return {id:String(v[3]||''),name:String(v[0]||''),price:Number(v[1]||0),image:imageUrl(v[2]||'')};return {id:String(v?.id||''),name:String(v?.name||v?.title||''),price:v?.priceMinor!=null?Number(v.priceMinor)/100:Number(v?.salePrice??v?.price??0),image:imageUrl(v?.image||v?.imageUrl||'')};}
function normProduct(p){return {...p,id:String(p.id),name:String(p.name||''),category:String(p.category||p.productType||''),desc:String(p.desc||p.description||''),image:imageUrl(p.image),basePrice:Number(p.basePrice||0),variants:(Array.isArray(p.variants)?p.variants:[]).map(normVariant).filter(v=>v.name)}}
async function load(){try{const r=await fetch(API+'?action=listProducts&_='+Date.now(),{cache:'no-store'}),j=await r.json();if(!j.ok)throw Error(j.error||'catalog error');state.products=(j.products||[]).map(normProduct);state.byId=new Map(state.products.map(p=>[p.id,p]));return true}catch(e){console.warn('[REQOO Shop Core v7]',e);return false}}
async function media(action,id){try{const r=await fetch(MEDIA+'?action='+action+'&productId='+encodeURIComponent(id)+'&_='+Date.now(),{cache:'no-store'}),j=await r.json();return j.ok?j:{}}catch(e){return {}}}
function addStyles(){if(document.getElementById('reqoo-core-v7-style'))return;const s=document.createElement('style');s.id='reqoo-core-v7-style';s.textContent='.reqoo-v7-variants{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:14px}.reqoo-v7-variant{min-width:92px;border:1px solid #383838;background:#0b0b0b;color:#fff;border-radius:11px;padding:10px 12px;text-align:left;cursor:pointer}.reqoo-v7-variant.active{border-color:#d9b45e;box-shadow:0 0 0 1px #d9b45e}.reqoo-v7-variant small{color:#aaa}.reqoo-v7-gallery{display:flex;gap:7px;overflow:auto;margin-top:9px;padding-bottom:3px}.reqoo-v7-gallery button{flex:0 0 58px;width:58px;height:58px;padding:0;border:2px solid #333;background:#080808;border-radius:8px;overflow:hidden}.reqoo-v7-gallery button.active{border-color:#d9b45e}.reqoo-v7-gallery img{width:100%;height:100%;object-fit:cover}.reqoo-v7-price{color:#d9b45e;font-size:20px;font-weight:900}.reqoo-v7-variant-note{font-size:10px;color:#888;margin:0 0 10px}@media(max-width:700px){.reqoo-v7-variant{flex:1;min-width:calc(50% - 8px)}}';document.head.appendChild(s)}
function buildModal(p,images){const modal=document.getElementById('modal'),form=document.getElementById('form');if(!modal||!form)return;const vars=p.variants.length?p.variants:(p.basePrice>0?[{id:'',name:'Standard',price:p.basePrice,image:''}]:[{id:'',name:'Quotation',price:0,image:''}]);let selected=vars[0];const imgs=[p.image,...images,...vars.map(v=>v.image)].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i);modal.dataset.reqooProductId=p.id;form.innerHTML=`<div class="two"><div><img id="reqooV7Main" src="${esc(imgs[0]||'assets/product-1.jpg')}" alt="${esc(p.name)}" onerror="this.onerror=null;this.src='assets/product-1.jpg'"><div id="reqooV7Gallery" class="reqoo-v7-gallery"></div></div><div><label>Pilihan / variasi</label><div id="reqooV7Variants" class="reqoo-v7-variants"></div><p class="reqoo-v7-variant-note">Pilih variasi untuk melihat harga dan gambar.</p><div class="choice"><div class="field"><label style="margin-top:0">Harga seunit</label><b id="unitPrice" class="reqoo-v7-price">—</b></div><div class="field"><label style="margin-top:0">Kuantiti</label><input id="qt" type="number" min="1" value="1"></div></div><label>Nama / teks</label><input id="nm" placeholder="Contoh: Anugerah Kecemerlangan"><label>Upload logo / artwork</label><div class="uploadbox"><input id="logo" type="file" accept="image/png,image/jpeg,image/webp"><div class="muted">PNG / JPG / WEBP</div></div><label>Nota / idea custom</label><textarea id="nt" rows="4" placeholder="Saiz, warna, tarikh event, kemasan, dll."></textarea><div class="summary"><div>Anggaran</div><b id="lineTotal">—</b></div><br><button class="btn" type="button" id="reqooV7Add">Tambah ke Cart</button></div></div>`;
const vb=document.getElementById('reqooV7Variants'),main=document.getElementById('reqooV7Main'),qty=document.getElementById('qt'),unit=document.getElementById('unitPrice'),total=document.getElementById('lineTotal');vb.innerHTML=vars.map((v,i)=>`<button type="button" class="reqoo-v7-variant" data-i="${i}"><strong>${esc(v.name)}</strong><br><small>${v.price>0?money(v.price):'Quotation'}</small></button>`).join('');const refresh=()=>{const q=Math.max(1,Number(qty.value)||1),idx=vars.indexOf(selected);vb.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===idx));unit.textContent=selected.price>0?money(selected.price):'Quotation';total.textContent=selected.price>0?money(selected.price*q):'Quotation';modal.dataset.reqooVariantId=selected.id;modal.dataset.reqooVariant=selected.name;if(selected.image)main.src=selected.image};vb.querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=vars[Number(b.dataset.i)||0]||vars[0];refresh()});qty.oninput=refresh;const gb=document.getElementById('reqooV7Gallery');gb.innerHTML=imgs.map((x,i)=>`<button type="button" class="${i?'':'active'}" data-src="${esc(x)}"><img src="${esc(x)}" alt=""></button>`).join('');gb.querySelectorAll('button').forEach(b=>b.onclick=()=>{main.src=b.dataset.src;gb.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.getElementById('reqooV7Add').onclick=()=>addToCart(p,selected);refresh()}
async function addToCart(p,v){const q=Math.max(1,Number(document.getElementById('qt')?.value)||1),file=document.getElementById('logo')?.files?.[0];const read=f=>new Promise((res,rej)=>{if(!f)return res('');const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)});const logo=await read(file);window.cart=Array.isArray(window.cart)?window.cart:[];window.cart.push({product:p,variant:v.name,variantId:v.id,unitPrice:Number(v.price||0),originalUnitPrice:Number(v.price||0),q,name:(document.getElementById('nm')?.value||'').trim(),note:(document.getElementById('nt')?.value||'').trim(),logo});document.getElementById('modal')?.classList.remove('open');window.update?.();window.openCart?.()}
async function open(id){if(!state.products.length)await load();const p=state.byId.get(String(id));if(!p){alert('Produk tidak dijumpai. Sila refresh shop.');return}const modal=document.getElementById('modal');if(!modal)return;modal.classList.add('open');document.getElementById('mTag').textContent=String(p.category||'CUSTOM').toUpperCase();document.getElementById('mTitle').textContent=p.name||'Customize';const [im,vr]=await Promise.all([media('listImages',p.id),media('variantImages',p.id)]);const remoteVars=(vr.variants||[]).map(normVariant);if(remoteVars.length)p.variants=remoteVars;const images=(im.images||[]).map(x=>imageUrl(x.url||x.image||x)).filter(Boolean);buildModal(p,images)}
function intercept(){document.addEventListener('click',e=>{const b=e.target.closest?.('[data-product-id]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();open(b.getAttribute('data-product-id'))},true)}
async function start(){addStyles();intercept();await load();window.custom=(id)=>open(id);window.__REQOO_SHOP_CORE_V7=true}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();