(()=>{
'use strict';
const API='/api/shop',MEDIA='/api/shop-media';
let products=[];
const money=n=>'RM'+Number(n||0).toFixed(2);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const url=u=>{u=String(u||'').trim();if(!u)return '';if(/^https?:\/\//i.test(u)||u.startsWith('/'))return u;return new URL(u.replace(/^\.\//,''),location.href).href};
const normVariant=v=>{if(Array.isArray(v))return {id:String(v[3]??''),name:String(v[0]??''),price:Number(v[1]??0),image:String(v[2]??'')};return {id:String(v?.id??''),name:String(v?.name??v?.title??''),price:Number(v?.price??v?.priceMinor??0),image:String(v?.image??v?.imageUrl??'')};};
async function load(){try{const r=await fetch(API+'?action=listProducts&_='+Date.now(),{cache:'no-store'}),j=await r.json();if(!j.ok||!Array.isArray(j.products))throw Error(j.error||'catalogue');products=j.products.map(p=>({...p,id:String(p.id),name:String(p.name||''),category:String(p.category||''),desc:String(p.desc||''),image:url(p.image),basePrice:Number(p.basePrice||0),variants:(Array.isArray(p.variants)?p.variants:[]).map(normVariant).filter(v=>v.name)}));return true}catch(e){console.warn('[REQOO Shop Core]',e);return false}}
async function media(action,id){try{const r=await fetch(MEDIA+'?action='+action+'&productId='+encodeURIComponent(id)+'&_='+Date.now(),{cache:'no-store'}),j=await r.json();return j.ok?j:{};}catch(e){return {};}}
function selectedProduct(id){return products.find(p=>String(p.id)===String(id));}
function buildModal(p){const modal=document.getElementById('modal'),form=document.getElementById('form');if(!modal||!form)return;const vars=p.variants.length?p.variants:(p.basePrice>0?[{id:'',name:'Standard',price:p.basePrice,image:''}]:[{id:'',name:'Quotation',price:0,image:''}]);const image=p.image||'assets/product-1.jpg';form.innerHTML=`<div class="two"><div><img id="coreMainImage" src="${esc(image)}" alt="${esc(p.name)}" onerror="this.onerror=null;this.src='assets/product-1.jpg'"><div id="coreGallery" style="display:flex;gap:8px;overflow:auto;margin-top:10px"></div></div><div><label>Pilihan / variasi</label><div id="coreVariants" style="display:flex;flex-wrap:wrap;gap:8px"></div><div class="choice"><div class="field"><label style="margin-top:0">Harga seunit</label><b id="unitPrice">—</b></div><div class="field"><label style="margin-top:0">Kuantiti</label><input id="qt" type="number" min="1" value="1"></div></div><label>Nama / teks</label><input id="nm" placeholder="Contoh: Anugerah Kecemerlangan"><label>Upload logo / artwork</label><div class="uploadbox"><input id="logo" type="file" accept="image/png,image/jpeg,image/webp"><div class="muted">PNG / JPG / WEBP</div></div><label>Nota / idea custom</label><textarea id="nt" rows="4" placeholder="Saiz, warna, tarikh event, kemasan, dll."></textarea><div class="summary"><div>Anggaran</div><b id="lineTotal">—</b></div><br><button class="btn" id="coreAdd" type="button">Tambah ke Cart</button></div></div>`;
let selected=vars[0];
const variantBox=document.getElementById('coreVariants');
variantBox.innerHTML=vars.map((v,i)=>`<button type="button" data-i="${i}" style="flex:1 1 45%;min-width:120px;background:#0b0b0b;border:1px solid #333;border-radius:12px;padding:11px;text-align:left;color:#fff;cursor:pointer"><strong>${esc(v.name)}</strong><br><small style="color:#d9b45e">${v.price>0?money(v.price):'Quotation'}</small></button>`).join('');
const refresh=()=>{document.querySelectorAll('#coreVariants button').forEach((b,i)=>{b.style.borderColor=i===vars.indexOf(selected)?'#d9b45e':'#333';b.style.boxShadow=i===vars.indexOf(selected)?'0 0 0 1px #d9b45e33':''});const q=Math.max(1,Number(document.getElementById('qt')?.value)||1);document.getElementById('unitPrice').textContent=selected.price>0?money(selected.price):'Quotation';document.getElementById('lineTotal').textContent=selected.price>0?money(selected.price*q):'Quotation';if(selected.image)document.getElementById('coreMainImage').src=url(selected.image)};
variantBox.querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=vars[Number(b.dataset.i)||0]||vars[0];refresh()});document.getElementById('qt').oninput=refresh;
const gallery=async()=>{const [im,vr]=await Promise.all([media('listImages',p.id),media('variantImages',p.id)]);const imgs=[p.image,...(im.images||[]).map(x=>url(x.url||x.image||x)),...(vr.variants||[]).map(x=>url(x.image))].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i);const g=document.getElementById('coreGallery');g.innerHTML=imgs.map((x,i)=>`<button type="button" data-src="${esc(x)}" style="padding:0;border:1px solid ${i===0?'#d9b45e':'#333'};background:#080808;border-radius:8px;overflow:hidden;width:58px;height:58px;flex:0 0 auto"><img src="${esc(x)}" style="width:58px;height:58px;object-fit:cover"></button>`).join('');g.querySelectorAll('button').forEach(b=>b.onclick=()=>{document.getElementById('coreMainImage').src=b.dataset.src;g.querySelectorAll('button').forEach(x=>x.style.borderColor='#333');b.style.borderColor='#d9b45e'});};gallery();refresh();
document.getElementById('coreAdd').onclick=()=>add(p,selected);}
async function add(p,v){const q=Math.max(1,Number(document.getElementById('qt')?.value)||1),file=document.getElementById('logo')?.files?.[0];const read=f=>new Promise((res,rej)=>{if(!f)return res('');const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)});const logo=await read(file);window.cart=Array.isArray(window.cart)?window.cart:[];window.cart.push({product:p,variant:v.name,variantId:v.id,unitPrice:v.price,originalUnitPrice:v.price,q,name:(document.getElementById('nm')?.value||'').trim(),note:(document.getElementById('nt')?.value||'').trim(),logo});document.getElementById('modal').classList.remove('open');if(typeof window.update==='function')window.update();if(typeof window.openCart==='function')window.openCart();}
function install(){const native=window.custom;if(typeof native==='function'&&!native.__reqooCore){window.custom=function(id){const p=selectedProduct(id);if(!p){native(id);return;}window.current=p;document.getElementById('mTag').textContent=String(p.category||'CUSTOM').toUpperCase();document.getElementById('mTitle').textContent=p.name||'Customize';buildModal(p);document.getElementById('modal').classList.add('open')};window.custom.__reqooCore=true;}}
async function start(){await load();install();setTimeout(install,100);setTimeout(install,500);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
