(()=>{
'use strict';
const API='https://api.reqoo.co',CART='reqoo_cart_fresh_v1';
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const rm=m=>'RM'+(Number(m||0)/100).toFixed(2);const arr=v=>{try{const x=typeof v==='string'?JSON.parse(v):v;return Array.isArray(x)?x:[]}catch{return[]}};
let products=[],cart=[];try{const raw=localStorage.getItem(CART);cart=raw?JSON.parse(raw):[]}catch{cart=[]}
function save(){localStorage.setItem(CART,JSON.stringify(cart));renderCount()}
function productImage(p){return arr(p.images)[0]||''}
function renderHero(){const p=products[0],box=$('#heroProduct');if(p&&box&&productImage(p))box.innerHTML=`<img src="${esc(productImage(p))}" alt="${esc(p.name)}">`}
function renderCategories(){const g=$('#categoryGrid');if(!g)return;const cats=[...new Set(products.map(p=>p.category).filter(Boolean))];const fallback=['Custom Gifts','Ukiran & Laser','Acrylic','Kayu','Hadiah','Produk Pilihan'];const names=cats.length?cats.slice(0,6):fallback;g.innerHTML=names.map((name,i)=>{const p=products.find(x=>String(x.category||'').toLowerCase()===String(name).toLowerCase())||products[i%Math.max(products.length,1)];return `<a class="category-card" href="#products" data-category="${esc(name)}"><div class="category-image">${p&&productImage(p)?`<img src="${esc(productImage(p))}" alt="${esc(name)}">`:'<span>REQOO</span>'}</div><strong>${esc(name)}</strong><small>${p?'Produk pilihan':''}</small></a>`}).join('')}
function loadProducts(){return fetch(API+'/api/products').then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()}).then(j=>{products=Array.isArray(j.products)?j.products:[];render();renderHero();renderCategories()}).catch(()=>{const g=$('#products');if(g)g.innerHTML='<div class="empty-shop">Shop belum dapat memuatkan katalog. Cuba refresh.</div>'})}
function selectedTotal(p,card){const vs=arr(p.variations),as=arr(p.addons);let total=Number(p.base_price_minor||0);if(vs.length){total=0;vs.forEach((v,i)=>{const o=arr(v.options)[Number(card?.querySelector(`[data-v="${i}"]`)?.value||0)];if(o)total+=Math.max(0,Number(o.price_minor||0))})}as.forEach((a,i)=>{if(card?.querySelector(`[data-a="${i}"]`)?.checked)total+=Math.max(0,Number(a.price_minor||0))});return total}
function productCard(p,i){const vs=arr(p.variations),as=arr(p.addons),cs=arr(p.custom_fields),base=Number(p.base_price_minor||0);return `<article class="product-card" data-card="${esc(p.id)}"><div class="product-media">${i<2?'<span class="product-badge">PILIHAN</span>':''}${productImage(p)?`<img src="${esc(productImage(p))}" alt="${esc(p.name)}">`:'<span class="product-placeholder">REQOO</span>'}</div><div class="product-info"><h3>${esc(p.name)}</h3><p>${esc(p.description||'')}</p>${vs.map((v,j)=>`<div class="field"><label>${esc(v.name)}${v.required?' *':''}</label><select class="shop-select" data-v="${j}">${arr(v.options).map((o,k)=>`<option value="${k}">${esc(o.name)} · ${rm(o.price_minor)}</option>`).join('')}</select></div>`).join('')}${as.length?`<div class="field"><label>Add-on</label>${as.map((a,j)=>`<label style="display:block;margin:5px 0"><input type="checkbox" data-a="${j}"> ${esc(a.name)} +${rm(a.price_minor)}</label>`).join('')}</div>`:''}${cs.map((c,j)=>`<div class="field"><label>${esc(c.name)}${c.required?' *':''}</label><input class="shop-input" data-c="${j}" type="${c.type==='date'?'date':c.type==='number'?'number':'text'}" placeholder="${esc(c.name)}"></div>`).join('')}<div class="product-bottom"><span class="product-price" data-total>${vs.length?rm(Number(arr(vs[0].options)[0]?.price_minor||0)):rm(base)}</span><button class="add-btn" data-add="${esc(p.id)}">Tambah</button></div></div></article>`}
function render(list=products){const g=$('#products');if(!g)return;g.innerHTML=list.length?list.map(productCard).join(''):'<div class="empty-shop">Belum ada produk.</div>';g.querySelectorAll('[data-card]').forEach(card=>{const p=products.find(x=>String(x.id)===card.dataset.card);if(!p)return;const update=()=>{const o=card.querySelector('[data-total]');if(o)o.textContent=rm(selectedTotal(p,card))};card.addEventListener('change',update);update()})}
function renderCount(){const x=$('#cartCount');if(x)x.textContent=cart.reduce((n,x)=>n+Math.max(0,Number(x.qty||0)),0)}
function renderCheckout(){const list=$('#cartItems');if(!list)return;list.innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><div><b>${esc(x.name)}</b><div style="color:#777;margin-top:4px">${rm(x.total_minor)} × ${x.qty}</div><small>${esc(x.config||'')}</small></div><div class="cart-actions"><button class="mini-btn" data-minus="${i}">−</button><button class="mini-btn" data-plus="${i}">+</button><button class="mini-btn" data-remove="${i}">Buang</button></div></div>`).join(''):'<div style="padding:30px 0;color:#777">Cart kosong.</div>';const total=$('#cartTotal');if(total)total.textContent=rm(cart.reduce((n,x)=>n+Number(x.total_minor||0)*Math.max(0,Number(x.qty||0)),0))}
function cardConfig(card,p){const vs=arr(p.variations),as=arr(p.addons),cs=arr(p.custom_fields);let total=Number(p.base_price_minor||0),parts=[];if(vs.length){total=0;vs.forEach((v,i)=>{const o=arr(v.options)[Number(card.querySelector(`[data-v="${i}"]`)?.value||0)];if(v.required&&!o)throw Error(`Pilih ${v.name}.`);if(o){total+=Math.max(0,Number(o.price_minor||0));parts.push(`${v.name}: ${o.name}`)}})}as.forEach((a,i)=>{if(card.querySelector(`[data-a="${i}"]`)?.checked){total+=Math.max(0,Number(a.price_minor||0));parts.push(a.name)}});cs.forEach((c,i)=>{const v=card.querySelector(`[data-c="${i}"]`)?.value?.trim()||'';if(c.required&&!v)throw Error(`Isi ${c.name}.`);if(v)parts.push(`${c.name}: ${v}`)});return{total_minor:total,config:parts.join(' · ')}}
$('#products')?.addEventListener('click',e=>{const b=e.target.closest('[data-add]');if(!b)return;const p=products.find(x=>String(x.id)===String(b.dataset.add)),card=b.closest('[data-card]');if(!p||!card)return;try{const c=cardConfig(card,p),key=p.id+'|'+c.config,item=cart.find(x=>x.key===key);if(item)item.qty++;else cart.push({key,id:p.id,name:p.name,total_minor:c.total_minor,config:c.config,qty:1});save();renderCheckout();if($('#checkout'))$('#checkout').hidden=false}catch(err){alert(err.message)}});
$('#cartBtn')?.addEventListener('click',()=>{if($('#checkout'))$('#checkout').hidden=false;renderCheckout()});$('#closeCheckout')?.addEventListener('click',()=>{$('#checkout').hidden=true});$('#cartItems')?.addEventListener('click',e=>{const m=e.target.closest('[data-minus]'),p=e.target.closest('[data-plus]'),r=e.target.closest('[data-remove]');if(m){const x=cart[+m.dataset.minus];if(x){x.qty--;if(x.qty<=0)cart.splice(+m.dataset.minus,1)}}if(p){const x=cart[+p.dataset.plus];if(x)x.qty++}if(r)cart.splice(+r.dataset.remove,1);save();renderCheckout()});
document.querySelectorAll('[data-payment]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-payment]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#payment').value=b.dataset.payment;$('#qrBox').hidden=b.dataset.payment!=='qr'});
$('#categoryGrid')?.addEventListener('click',e=>{const a=e.target.closest('[data-category]');if(!a)return;const cat=a.dataset.category;const matches=products.filter(p=>String(p.category||'').toLowerCase()===cat.toLowerCase());if(matches.length){e.preventDefault();render(matches)}});
$('#searchBtn')?.addEventListener('click',()=>{$('#searchPanel').hidden=false;setTimeout(()=>$('#searchInput')?.focus(),50)});$('#closeSearch')?.addEventListener('click',()=>{$('#searchPanel').hidden=true});$('#searchPanel')?.addEventListener('click',e=>{if(e.target.id==='searchPanel')e.currentTarget.hidden=true});$('#searchInput')?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();render(q?products.filter(p=>`${p.name} ${p.description||''} ${p.category||''} ${p.sku||''}`.toLowerCase().includes(q)):products)});
function show(t){const x=$('#payMsg');if(x){x.textContent=t;x.hidden=false}}
async function createOrder(customer,payment_method){const r=await fetch(API+'/api/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...customer,payment_method})});const j=await r.json();if(!r.ok||!j.id)throw Error(j.error||'Order gagal disimpan.');return j}
async function showQR(orderNo){try{const r=await fetch(API+'/api/payment-settings'),j=await r.json();const qrUrl=(r.ok&&j.qr_url)?j.qr_url:'/assets/qr-payment.svg';const box=$('#qrBox');if(box){box.innerHTML=`<img src="${esc(qrUrl)}" alt="QR AB ART TRADING" style="max-width:260px"><div style="margin-top:8px"><b>AB ART TRADING</b><br>Order: <b>${esc(orderNo)}</b><br>Scan untuk bayaran.</div>`;box.hidden=false;show(`Order ${orderNo} direkodkan. Admin akan sahkan bayaran.`);return}}catch(e){}show('QR AB ART TRADING belum ditetapkan dalam Admin → Settings.')}
$('#payBtn')?.addEventListener('click',async()=>{if(!cart.length)return show('Cart masih kosong.');const customer={name:$('#custName')?.value.trim()||'',email:$('#custEmail')?.value.trim()||'',phone:$('#custPhone')?.value.trim()||'',items:cart,total_minor:cart.reduce((n,x)=>n+Number(x.total_minor||0)*Math.max(0,Number(x.qty||0)),0)};if(!customer.name||!customer.email||!customer.phone)return show('Lengkapkan nama, email dan telefon.');const method=$('#payment')?.value||'billplz';const btn=$('#payBtn');if(btn)btn.disabled=true;try{const order=await createOrder(customer,method);if(method==='qr'){await showQR(order.order_no);return}const r=await fetch(API+'/api/create-bill',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...customer,order_id:order.id,order_no:order.order_no})});const j=await r.json();if(!r.ok||!j.url)throw Error(j.error||'Billplz gagal');location.href=j.url}catch(e){show(e.message)}finally{if(btn)btn.disabled=false}});
renderCount();renderCheckout();loadProducts();
})();