(()=>{
'use strict';
const API='/api/shop',MEDIA='/api/shop-media';
const state={products:[],byId:new Map(),loading:null};
const money=n=>'RM'+Number(n||0).toFixed(2);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const imageUrl=u=>{u=String(u||'').trim();if(!u)return '';if(/^https?:\/\//i.test(u)||u.startsWith('/'))return u;return new URL(u.replace(/^\.\//,''),location.href).href};
function normVariant(v){if(Array.isArray(v))return {id:String(v[3]||''),name:String(v[0]||''),price:Number(v[1]||0),image:imageUrl(v[2]||'')};return {id:String(v?.id||''),name:String(v?.name||v?.title||''),price:Number(v?.salePrice??v?.price??v?.priceMinor??0),image:imageUrl(v?.image||v?.imageUrl||'')};}
function normProduct(p){return {...p,id:String(p.id),name:String(p.name||''),category:String(p.category||p.productType||''),desc:String(p.desc||p.description||''),image:imageUrl(p.image),basePrice:Number(p.basePrice||0),variants:(Array.isArray(p.variants)?p.variants:[]).map(normVariant).filter(v=>v.name)};}
async function load(){if(state.loading)return state.loading;state.loading=(async()=>{try{const r=await fetch(API+'?action=listProducts&_='+Date.now(),{cache:'no-store'}),j=await r.json();if(!j.ok)throw Error(j.error||'Gagal memuat katalog');state.products=(j.products||[]).map(normProduct);state.byId=new Map(state.products.map(p=>[p.id,p]));return state.products}catch(e){console.warn('[REQOO Shop Core v5]',e);state.products=[];state.byId.clear();return []}finally{state.loading=null}})();return state.loading;}
async function media(action,id){try{const r=await fetch(MEDIA+'?action='+action+'&productId='+encodeURIComponent(id)+'&_='+Date.now(),{cache:'no-store'}),j=await r.json();return j.ok?j:{}}catch{return {}}}
function closeModal(){document.getElementById('modal')?.classList.remove('open');}
function buildModal(p){const modal=document.getElementById('modal'),form=document.getElementById('form');if(!modal||!form)return;const vars=p.variants.length?p.variants:(p.basePrice>0?[{id:'',name:'Standard',price:p.basePrice,image:''}]:[{id:'',name:'Quotation',price:0,image:''}]);let selected=vars[0];form.innerHTML=`<div class="two"><div><img id="coreMainImage" src="${esc(p.image||'assets/product-1.jpg')}" alt="${esc(p.name)}" onerror="this.onerror=null;this.src='assets/product-1.jpg'"><div id="coreGallery" class="reqoo-core-gallery"></div></div><div><label>Pilihan / variasi</label><div id="coreVariants" class="reqoo-core-variants"></div><div class="choice"><div class="field"><label style="margin-top:0">Harga seunit</label><b id="unitPrice">—</b></div><div class="field"><label style="margin-top:0">Kuantiti</label><input id="qt" type="number" min="1" value="1"></div></div><label>Nama / teks</label><input id="nm" placeholder="Contoh: Anugerah Kecemerlangan"><label>Upload logo / artwork</label><div class="uploadbox"><input id="logo" type="file" accept="image/png,image/jpeg,image/webp"><div class="muted">PNG / JPG / WEBP</div></div><label>Nota / idea custom</label><textarea id="nt" rows="4" placeholder="Saiz, warna, tarikh event, kemasan, dll."></textarea><div class="summary"><div>Anggaran</div><b id="lineTotal">—</b></div><br><button class="btn" id="coreAdd" type="button">Tambah ke Cart</button></div></div>`;
const variantBox=document.getElementById('coreVariants');variantBox.innerHTML=vars.map((v,i)=>`<button type="button" data-i="${i}" class="reqoo-core-variant"><strong>${esc(v.name)}</strong><br><small>${Number(v.price)>0?money(v.price):'Quotation'}</small></button>`).join('');
const refresh=()=>{const idx=vars.indexOf(selected),q=Math.max(1,Number(document.getElementById('qt')?.value)||1);variantBox.querySelectorAll('button').forEach((b,i)=>{b.classList.toggle('active',i===idx)});document.getElementById('unitPrice').textContent=Number(selected.price)>0?money(selected.price):'Quotation';document.getElementById('lineTotal').textContent=Number(selected.price)>0?money(Number(selected.price)*q):'Quotation';modal.dataset.reqooProductId=p.id;modal.dataset.reqooVariant=selected.name||'Quotation';if(selected.image)document.getElementById('coreMainImage').src=selected.image;};
variantBox.querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=vars[Number(b.dataset.i)||0]||vars[0];refresh()});document.getElementById('qt').oninput=refresh;
(async()=>{const [im,vr]=await Promise.all([media('listImages',p.id),media('variantImages',p.id)]);const imgs=[p.image,...(im.images||[]).map(x=>imageUrl(x.url||x.image||x)),...(vr.variants||[]).map(x=>imageUrl(x.image))].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i);const g=document.getElementById('coreGallery');g.innerHTML=imgs.map((x,i)=>`<button type="button" data-src="${esc(x)}" class="reqoo-core-thumb ${i===0?'active':''}"><img src="${esc(x)}" alt=""></button>`).join('');g.querySelectorAll('button').forEach(b=>b.onclick=()=>{document.getElementById('coreMainImage').src=b.dataset.src;g.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active')})})().catch(()=>{});
refresh();document.getElementById('coreAdd').onclick=()=>addToCart(p,selected);}
async function addToCart(p,v){const q=Math.max(1,Number(document.getElementById('qt')?.value)||1),file=document.getElementById('logo')?.files?.[0];const read=f=>new Promise((res,rej)=>{if(!f)return res('');const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)});const logo=await read(file);window.cart=Array.isArray(window.cart)?window.cart:[];window.cart.push({product:p,variant:v.name,variantId:v.id,unitPrice:Number(v.price||0),originalUnitPrice:Number(v.price||0),q,name:(document.getElementById('nm')?.value||'').trim(),note:(document.getElementById('nt')?.value||'').trim(),logo});closeModal();window.update?.();window.openCart?.();}
async function custom(id){await load();const p=state.byId.get(String(id));if(!p)return;window.current=p;const modal=document.getElementById('modal');document.getElementById('mTag').textContent=String(p.category||'CUSTOM').toUpperCase();document.getElementById('mTitle').textContent=p.name||'Customize';buildModal(p);modal?.classList.add('open');}
function install(){window.__REQOO_SHOP_CORE_V5=true;window.custom=custom;}
async function start(){install();await load();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();