(()=>{
'use strict';
const state={products:[],byId:new Map(),selected:{},variants:{}};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=n=>'RM'+Number(n||0).toFixed(2);
async function loadProducts(){try{const r=await fetch('/api/shop?action=listProducts',{cache:'no-store'}),j=await r.json();state.products=j.products||[];state.byId=new Map(state.products.map(p=>[String(p.id),p]));}catch{}}
async function variantData(id){if(state.variants[id])return state.variants[id];try{const r=await fetch('/api/shop-media?action=variantImages&productId='+encodeURIComponent(id),{cache:'no-store'}),j=await r.json();return state.variants[id]=j.variants||[]}catch{return[]}}
async function imagesFor(id){try{const r=await fetch('/api/shop-media?action=listImages&productId='+encodeURIComponent(id),{cache:'no-store'}),j=await r.json();return j.images||[]}catch{return[]}}
function productFromModal(modal){const hs=[...modal.querySelectorAll('h1,h2,h3,h4')],text=hs.map(x=>(x.textContent||'').trim()).find(Boolean)||'';let p=state.products.find(x=>x.name.trim().toLowerCase()===text.toLowerCase());if(p)return p;const img=modal.querySelector('.two>div:first-child img,.box img'),src=img?.currentSrc||img?.src||'';p=state.products.find(x=>x.image&&src.includes(x.image));if(p)return p;return state.products.find(x=>text.toLowerCase().includes(String(x.name).toLowerCase()))||null}
function style(){if(document.getElementById('reqoo-shop-enhance-style'))return;const s=document.createElement('style');s.id='reqoo-shop-enhance-style';s.textContent='.reqoo-variant-panel{margin:12px 0;padding:14px;border:1px solid #3b3222;border-radius:16px;background:linear-gradient(180deg,#111,#0b0b0b)}.reqoo-variant-panel label{color:#aaa}.reqoo-variant-select{width:100%;background:#080808;color:#fff;border:1px solid #51452f;border-radius:10px;padding:11px}.reqoo-price-row{display:flex;align-items:center;justify-content:space-between;margin-top:10px;padding-top:10px;border-top:1px solid #292929;color:#aaa;font-size:11px}.reqoo-unit-price{font-size:18px;color:#f2d68d}.reqoo-gallery{display:flex;gap:8px;overflow:auto;margin-top:12px}.reqoo-gallery button{padding:0;border:1px solid #393939;background:#080808;border-radius:10px;overflow:hidden;min-width:64px;height:64px}.reqoo-gallery img{width:64px;height:64px;object-fit:cover;display:block}.reqoo-gallery button.active{border-color:#d9b45e;box-shadow:0 0 0 1px #d9b45e55}.reqoo-variant-note{font-size:10px;color:#8f8f8f;margin-top:6px}.reqoo-fixed-price .choice{display:none}.reqoo-fixed-price .summary b{color:#f2d68d}';document.head.appendChild(s)}
function ensurePanel(modal){let p=modal.querySelector('.reqoo-variant-panel');if(p)return p;const box=modal.querySelector('.box')||modal;p=document.createElement('div');p.className='reqoo-variant-panel';p.innerHTML='<label style="margin-top:0">Pilihan / variasi</label><select class="reqoo-variant-select"></select><div class="reqoo-price-row"><span>Harga seunit</span><b class="reqoo-unit-price">—</b></div><div class="reqoo-variant-note">Harga dan gambar mengikut variation yang dipilih.</div><div class="reqoo-gallery"></div>';const anchor=box.querySelector('.choice')||box.querySelector('.summary')||box.querySelector('label')||box.firstElementChild;if(anchor?.parentNode)anchor.parentNode.insertBefore(p,anchor.nextSibling);else box.appendChild(p);return p}
function setMainImage(modal,url){if(!url)return;const main=modal.querySelector('.two>div:first-child img,.box img');if(main)main.src=url}
function syncLegacyPrice(modal,value){const fixed=value!=='Quotation';modal.classList.toggle('reqoo-fixed-price',fixed);if(!fixed)return;const old=modal.querySelector('.summary b');if(old)old.textContent=money(value);const root=modal.querySelector('.choice,.summary');if(!root)return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];let n;while(n=w.nextNode())nodes.push(n);nodes.forEach(x=>{if(/Quotation/i.test(x.nodeValue))x.nodeValue=x.nodeValue.replace(/Quotation/gi,money(value))});root.querySelectorAll('input,textarea').forEach(x=>{if(/Quotation/i.test(x.value||''))x.value=money(value)})}
async function enhanceModal(modal){if(!modal.classList.contains('open'))return;const p=productFromModal(modal);if(!p)return;const panel=ensurePanel(modal),sel=panel.querySelector('.reqoo-variant-select'),price=panel.querySelector('.reqoo-unit-price'),gallery=panel.querySelector('.reqoo-gallery');const serverVars=await variantData(p.id),vars=serverVars.length?serverVars:(p.variants||[]).filter(v=>v.active!==false).map(v=>({name:v.name,price:v.salePrice??v.price,image:v.image||v.imageUrl||''}));if(vars.length){sel.innerHTML=vars.map(v=>`<option value="${esc(v.name)}">${esc(v.name)} — ${money(v.price)}</option>`).join('');const old=state.selected[String(p.id)];if(old&&vars.some(v=>v.name===old))sel.value=old;const update=()=>{const v=vars.find(x=>x.name===sel.value)||vars[0];state.selected[String(p.id)]=v.name;price.textContent=money(v.price);modal.dataset.reqooProductId=p.id;modal.dataset.reqooVariant=v.name;syncLegacyPrice(modal,v.price);if(v.image)setMainImage(modal,v.image);gallery.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.src===v.image))};sel.onchange=update;update()}else{const base=Number(p.basePrice||0);sel.innerHTML=base>0?'<option value="Standard">Standard</option>':'<option value="Quotation">Quotation</option>';sel.value=base>0?'Standard':'Quotation';price.textContent=base>0?money(base):'Quotation';modal.dataset.reqooProductId=p.id;modal.dataset.reqooVariant=sel.value;syncLegacyPrice(modal,base)}
if(!gallery.dataset.loaded){gallery.dataset.loaded='1';const imgs=await imagesFor(p.id),variantImgs=vars.map(v=>v.image).filter(Boolean),all=[...(imgs.length?imgs.map(x=>x.url):[]),...variantImgs,p.image].filter((u,i,a)=>u&&a.indexOf(u)===i);if(all.length>1){gallery.innerHTML=all.map((u,i)=>`<button type="button" class="${i===0?'active':''}" data-src="${esc(u)}"><img src="${esc(u)}" alt=""></button>`).join('');gallery.querySelectorAll('button').forEach(b=>b.onclick=()=>{gallery.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');setMainImage(modal,b.dataset.src)})}}}
function hookFetch(){if(window.__reqooShopVariantHook)return;window.__reqooShopVariantHook=1;const native=window.fetch.bind(window);window.fetch=async function(input,init){const url=typeof input==='string'?input:(input?.url||''),method=(init?.method||input?.method||'GET').toUpperCase();if(method==='POST'&&url.includes('/api/shop')){try{const data=typeof init?.body==='string'?JSON.parse(init.body):null;if(data?.action==='createOrder'&&Array.isArray(data.items)){data.items=data.items.map(item=>{const pid=String(item.productId||item.id||''),chosen=state.selected[pid];if(chosen&&(!item.variant||/^quotation$/i.test(String(item.variant))))item.variant=chosen;return item});return native(input,{...(init||{}),body:JSON.stringify(data)})}}catch{}}return native(input,init)}}
function boot(){style();hookFetch();document.querySelectorAll('.modal.open').forEach(enhanceModal)}
loadProducts().then(()=>{boot();new MutationObserver(boot).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']})});
})();