(()=>{
'use strict';
const API='/api/shop',MEDIA='/api/shop-media',money=n=>'RM'+Number(n||0).toFixed(2),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),img=u=>{u=String(u||'').trim();if(!u)return '';if(/^https?:\/\//i.test(u)||u.startsWith('/'))return u;return new URL(u.replace(/^\.\//,''),location.href).href};
let products=[];
async function getProducts(){try{const r=await fetch(API+'?action=listProducts&_='+Date.now(),{cache:'no-store'}),j=await r.json();products=j.ok&&Array.isArray(j.products)?j.products:[]}catch(e){products=[]}return products}
async function media(action,id){try{const r=await fetch(MEDIA+'?action='+action+'&productId='+encodeURIComponent(id)+'&_='+Date.now(),{cache:'no-store'}),j=await r.json();return j.ok?j:{}}catch(e){return {}}}
function txt(el,v){if(el)el.textContent=v}
function copyFix(){document.querySelectorAll('body *').forEach(el=>{if(el.children.length)return;const t=(el.textContent||'').trim();if(!t)return;const n=t.replace(/Checkout terus dengan Billplz — pembayaran selamat dan mudah\./i,'Checkout terus dengan QR — pembayaran mudah dan pantas.').replace(/Billplz Secure Payment/gi,'QR Secure Payment').replace(/Pilihan \/ saiz/gi,'Pilihan / variasi');if(n!==t)el.textContent=n})}
function addGallery(modal,urls){const main=modal.querySelector('.two>div:first-child');if(!main||!urls.length)return;let g=main.querySelector('.reqoo-gallery');if(!g){g=document.createElement('div');g.className='reqoo-gallery';g.style.cssText='display:flex;gap:7px;flex-wrap:wrap;margin-top:10px'}g.innerHTML=urls.map(u=>'<button type="button" data-src="'+esc(img(u))+'" style="padding:0;border:1px solid #444;background:#080808;border-radius:8px;overflow:hidden;width:58px;height:58px"><img src="'+esc(img(u))+'" style="width:58px;height:58px;object-fit:cover"></button>').join('');const mainImg=main.querySelector('img');g.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(mainImg)mainImg.src=b.dataset.src;g.querySelectorAll('button').forEach(x=>x.style.borderColor='#444');b.style.borderColor='#d9b45e'});}
async function enhance(id){const modal=document.getElementById('modal'),p=products.find(x=>String(x.id)===String(id));if(!modal?.classList.contains('open')||!p)return;const sel=modal.querySelector('#variant'),unit=modal.querySelector('#unitPrice'),total=modal.querySelector('#lineTotal'),qty=modal.querySelector('#qt');const vars=(Array.isArray(p.variants)?p.variants:[]).map(v=>Array.isArray(v)?{name:v[0],price:Number(v[1]||0),image:v[2]||''}:v).filter(v=>v&&String(v.name||'').trim());const use=vars.length?vars:(Number(p.basePrice||0)>0?[{name:'Standard',price:Number(p.basePrice)}]:[{name:'Quotation',price:0}]);if(sel){sel.innerHTML=use.map((v,i)=>'<option value="'+i+'">'+esc(v.name)+' — '+(Number(v.price)>0?money(v.price):'Quotation')+'</option>').join('');const refresh=()=>{const v=use[Math.max(0,Number(sel.value)||0)]||use[0];txt(unit,Number(v?.price)>0?money(v.price):'Quotation');txt(total,Number(v?.price)>0?money(Number(v.price)*Math.max(1,Number(qty?.value)||1)):'Quotation');if(v?.image){const m=modal.querySelector('.two>div:first-child img');if(m)m.src=img(v.image)}};sel.onchange=refresh;qty?.addEventListener('input',refresh);refresh()}
const vr=await media('variantImages',id),im=await media('listImages',id),vi=(vr.variants||[]).map(v=>v.image).filter(Boolean),gi=(im.images||[]).map(x=>x.url||x.image||x).filter(Boolean);addGallery(modal,[...new Set(gi.length?gi:vi)]);copyFix()}
function hook(){copyFix();const original=window.custom;if(typeof original==='function'&&!original.__reqooWrapped){const wrapped=function(id){const r=original.apply(this,arguments);enhance(id);setTimeout(()=>enhance(id),100);setTimeout(()=>enhance(id),500);return r};wrapped.__reqooWrapped=true;window.custom=wrapped}document.addEventListener('click',e=>{const b=e.target.closest?.('[data-product-id]');if(b)enhance(b.dataset.productId)});const mo=new MutationObserver(()=>{const m=document.getElementById('modal');if(!m?.classList.contains('open'))return;const title=m.querySelector('#mTitle')?.textContent?.trim();const p=products.find(x=>String(x.name||'').trim().toLowerCase()===String(title||'').toLowerCase());if(p)enhance(p.id)});mo.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']})}
function start(){hook();getProducts().then(()=>{const m=document.getElementById('modal');if(m?.classList.contains('open')){const title=m.querySelector('#mTitle')?.textContent?.trim(),p=products.find(x=>String(x.name||'').trim().toLowerCase()===String(title||'').toLowerCase());if(p)enhance(p.id)}});setInterval(copyFix,3000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
