import fs from 'node:fs';
import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../api/shop-admin-flow-v6.js',import.meta.url),'utf8');
assert.match(src,/stock\.restored\.payment_rejected/);assert.match(src,/stock_qty=stock_qty\+\?/);assert.match(src,/usage_count=MAX\(0,usage_count-1\)/);assert.match(src,/payment_status='failed',fulfillment_status='cancelled'/);assert.match(src,/state==='paid'/);
const v7=fs.readFileSync(new URL('../api/shop-admin-flow-v7.js',import.meta.url),'utf8');assert.match(v7,/shop-admin-flow-v6\.js/);
const v8=fs.readFileSync(new URL('../api/shop-admin-flow-v8.js',import.meta.url),'utf8');assert.match(v8,/shop-admin-flow-v7\.js/);
const v9=fs.readFileSync(new URL('../api/shop-admin-flow-v9.js',import.meta.url),'utf8');assert.match(v9,/shop-admin-flow-v8\.js/);
const v10=fs.readFileSync(new URL('../api/shop-admin-flow-v10.js',import.meta.url),'utf8');assert.match(v10,/shop-admin-flow-v9\.js/);
const v11=fs.readFileSync(new URL('../api/shop-admin-flow-v11.js',import.meta.url),'utf8');assert.match(v11,/shop-admin-flow-v10\.js/);
const v12=fs.readFileSync(new URL('../api/shop-admin-flow-v12.js',import.meta.url),'utf8');assert.match(v12,/shop-admin-flow-v11\.js/);
const v13=fs.readFileSync(new URL('../api/shop-admin-flow-v13.js',import.meta.url),'utf8');assert.match(v13,/shop-admin-flow-v12\.js/);
const v14=fs.readFileSync(new URL('../api/shop-admin-flow-v14.js',import.meta.url),'utf8');assert.match(v14,/shop-admin-flow-v13\.js/);
const v15=fs.readFileSync(new URL('../api/shop-admin-flow-v15.js',import.meta.url),'utf8');assert.match(v15,/shop-admin-flow-v14\.js/);
const v16=fs.readFileSync(new URL('../api/shop-admin-flow-v16.js',import.meta.url),'utf8');assert.match(v16,/shop-admin-flow-v15\.js/,'v16 must preserve the complete stock-safe v15 chain');
const v17=fs.readFileSync(new URL('../api/shop-admin-flow-v17.js',import.meta.url),'utf8');assert.match(v17,/shop-admin-flow-v16\.js/,'v17 must preserve stock-safe v16');
const v18=fs.readFileSync(new URL('../api/shop-admin-flow-v18.js',import.meta.url),'utf8');assert.match(v18,/shop-admin-flow-v17\.js/,'v18 must preserve the complete stock-safe chain');
const worker=fs.readFileSync(new URL('../api/worker.js',import.meta.url),'utf8');assert.match(worker,/shop-admin-flow-v18\.js/,'worker must route admin requests through latest v18 flow');
console.log('shop rejected-payment stock restoration regression: ok');