const H={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const STATUSES=['pending','processing','fulfilled','cancelled','failed'];
function json(b,s=200,t=crypto.randomUUID()){return new Response(JSON.stringify({...b,trace_id:t}),{status:s,headers:{...H,"x-reqoo-trace-id":t}})}
function id(p){return `${p}${crypto.randomUUID().replaceAll('-','')}`}
function clean(v,m=500){if(v==null)return null;const s=String(v).trim();return s?s.slice(0,m):null}
function admin(r,e,t){if(!e.ADMIN_API_KEY)return json({ok:false,error:'FULFILLMENT_ADMIN_AUTH_NOT_CONFIGURED'},503,t);if(r.headers.get('authorization')!==`Bearer ${e.ADMIN_API_KEY}`)return json({ok:false,error:'FULFILLMENT_ADMIN_UNAUTHORIZED'},401,t)}
async function create(r,e,t){let x;try{x=await r.json()}catch{return json({ok:false,error:'INVALID_JSON'},400,t)};if(!x?.order_id)return json({ok:false,error:'ORDER_ID_REQUIRED'},400,t);const o=await e.DB.prepare('SELECT * FROM orders WHERE id=?').bind(x.order_id).first();if(!o)return json({ok:false,error:'ORDER_NOT_FOUND'},404,t);if(o.payment_status!=='paid')return json({ok:false,error:'PAYMENT_NOT_SETTLED',payment_status:o.payment_status},409,t);const existing=await e.DB.prepare('SELECT * FROM fulfillments WHERE order_id=? AND status NOT IN (\'cancelled\',\'failed\') LIMIT 1').bind(o.id).first();if(existing)return json({ok:true,idempotent_replay:true,fulfillment:existing},200,t);const type=clean(x.fulfillment_type,50)||'digital',f=id('ful_'),ts=new Date().toISOString();try{await e.DB.prepare('INSERT INTO fulfillments (id,order_id,fulfillment_type,status,provider,tracking_code,delivery_data_json,started_at,completed_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(f,o.id,type,'pending',clean(x.provider,100),clean(x.tracking_code,200),JSON.stringify(x.delivery_data||{}),null,null,ts,ts).run();await e.DB.prepare('UPDATE orders SET fulfillment_status=\'pending\',updated_at=? WHERE id=?').bind(ts,o.id).run();await e.DB.prepare('INSERT INTO activity_events (id,customer_id,order_id,event_type,trace_id,metadata_json,created_at) VALUES (?,?,?,?,?,?,?)').bind(id('evt_'),o.customer_id,o.id,'fulfillment.created',t,JSON.stringify({fulfillment_id:f,type}),ts).run();return json({ok:true,fulfillment:{id:f,order_id:o.id,type,status:'pending'}},201,t)}catch(err){return json({ok:false,error:'FULFILLMENT_CREATE_FAILED'},500,t)}}
async function update(r,e,t,fid){const a=admin(r,e,t);if(a)return a;let x;try{x=await r.json()}catch{return json({ok:false,error:'INVALID_JSON'},400,t)};if(!STATUSES.includes(x?.status))return json({ok:false,error:'INVALID_FULFILLMENT_STATUS'},400,t);const f=await e.DB.prepare('SELECT * FROM fulfillments WHERE id=?').bind(fid).first();if(!f)return json({ok:false,error:'FULFILLMENT_NOT_FOUND'},404,t);const ts=new Date().toISOString(),started=x.status==='processing'?(f.started_at||ts):f.started_at,completed=x.status==='fulfilled'?ts:null;await e.DB.prepare('UPDATE fulfillments SET status=?,provider=?,tracking_code=?,delivery_data_json=?,started_at=?,completed_at=?,updated_at=? WHERE id=?').bind(x.status,x.provider??f.provider,x.tracking_code??f.tracking_code,JSON.stringify(x.delivery_data??JSON.parse(f.delivery_data_json||'{}')),started,completed,ts,fid).run();const orderStatus=x.status==='fulfilled'?'fulfilled':x.status==='cancelled'?'cancelled':x.status==='failed'?'pending':'processing';await e.DB.prepare('UPDATE orders SET fulfillment_status=?,updated_at=? WHERE id=?').bind(orderStatus,ts,f.order_id).run();await e.DB.prepare('INSERT INTO activity_events (id,order_id,event_type,trace_id,metadata_json,created_at) VALUES (?,?,?,?,?,?)').bind(id('evt_'),f.order_id,'fulfillment.updated',t,JSON.stringify({fulfillment_id:fid,status:x.status}),ts).run();return json({ok:true,fulfillment:await e.DB.prepare('SELECT * FROM fulfillments WHERE id=?').bind(fid).first()},200,t)}
export async function onRequest({request,env}){const t=request.headers.get('x-reqoo-trace-id')||crypto.randomUUID();if(!env.DB)return json({ok:false,error:'CORE_DB_BINDING_MISSING'},503,t);const p=new URL(request.url).pathname.split('/').filter(Boolean),fid=p[2]||null;if(request.method==='POST'&&!fid)return create(request,env,t);if(request.method==='GET'&&fid){const f=await env.DB.prepare('SELECT * FROM fulfillments WHERE id=?').bind(fid).first();return f?json({ok:true,fulfillment:f},200,t):json({ok:false,error:'FULFILLMENT_NOT_FOUND'},404,t)}if((request.method==='PUT'||request.method==='PATCH')&&fid)return update(request,env,t,fid);return json({ok:false,error:'METHOD_NOT_ALLOWED'},405,t)}
