const H={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const STATUSES=['pending','processing','fulfilled','cancelled'];
function json(b,s=200,t=crypto.randomUUID()){return new Response(JSON.stringify({...b,trace_id:t}),{status:s,headers:{...H,"x-reqoo-trace-id":t}})}
function id(p){return `${p}${crypto.randomUUID().replaceAll('-','')}`}
function clean(v,m=500){if(v==null)return null;const s=String(v).trim();return s?s.slice(0,m):null}
function admin(r,e,t){if(!e.ADMIN_API_KEY)return json({ok:false,error:'FULFILLMENT_ADMIN_AUTH_NOT_CONFIGURED'},503,t);if(r.headers.get('authorization')!==`Bearer ${e.ADMIN_API_KEY}`)return json({ok:false,error:'FULFILLMENT_ADMIN_UNAUTHORIZED'},401,t);return null}
async function create(r,e,t){const a=admin(r,e,t);if(a)return a;let x;try{x=await r.json()}catch{return json({ok:false,error:'INVALID_JSON'},400,t)};if(!x?.order_id)return json({ok:false,error:'ORDER_ID_REQUIRED'},400,t);const o=await e.DB.prepare('SELECT * FROM orders WHERE id=?').bind(x.order_id).first();if(!o)return json({ok:false,error:'ORDER_NOT_FOUND'},404,t);if(o.payment_status!=='paid')return json({ok:false,error:'PAYMENT_NOT_SETTLED',payment_status:o.payment_status},409,t);const existing=await e.DB.prepare("SELECT * FROM fulfillments WHERE order_id=? AND status!='cancelled' LIMIT 1").bind(o.id).first();if(existing)return json({ok:true,idempotent_replay:true,fulfillment:existing},200,t);const type=clean(x.type,50)||'digital_delivery';if(!['physical_shipping','digital_delivery','licensed_access','play_access','service_custom'].includes(type))return json({ok:false,error:'INVALID_FULFILLMENT_TYPE'},400,t);const f=id('ful_'),ts=new Date().toISOString();try{await e.DB.prepare('INSERT INTO fulfillments (id,order_id,order_item_id,type,status,payload_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)').bind(f,o.id,x.order_item_id||null,type,'pending',JSON.stringify({provider:clean(x.provider,100),tracking_code:clean(x.tracking_code,200),delivery_data:x.delivery_data||{}}),ts,ts).run();await e.DB.prepare("UPDATE orders SET fulfillment_status='pending',updated_at=? WHERE id=?").bind(ts,o.id).run();await e.DB.prepare('INSERT INTO activity_events (id,customer_id,order_id,event_type,trace_id,metadata_json,created_at) VALUES (?,?,?,?,?,?,?)').bind(id('evt_'),o.customer_id,o.id,'fulfillment.created',t,JSON.stringify({fulfillment_id:f,type}),ts).run();return json({ok:true,fulfillment:{id:f,order_id:o.id,type,status:'pending'}},201,t)}catch(err){return json({ok:false,error:'FULFILLMENT_CREATE_FAILED'},500,t)}}
async function update(r,e,t,fid){const a=admin(r,e,t);if(a)return a;let x;try{x=await r.json()}catch{return json({ok:false,error:'INVALID_JSON'},400,t)};if(!STATUSES.includes(x?.status))return json({ok:false,error:'INVALID_FULFILLMENT_STATUS'},400,t);const f=await e.DB.prepare('SELECT * FROM fulfillments WHERE id=?').bind(fid).first();if(!f)return json({ok:false,error:'FULFILLMENT_NOT_FOUND'},404,t);const payload=JSON.parse(f.payload_json||'{}');const ts=new Date().toISOString();payload.provider=x.provider??payload.provider;payload.tracking_code=x.tracking_code??payload.tracking_code;payload.delivery_data=x.delivery_data??payload.delivery_data;await e.DB.prepare('UPDATE fulfillments SET status=?,payload_json=?,updated_at=? WHERE id=?').bind(x.status,JSON.stringify(payload),ts,fid).run();const orderStatus=x.status==='fulfilled'?'fulfilled':x.status==='cancelled'?'cancelled':x.status==='processing'?'processing':'pending';await e.DB.prepare('UPDATE orders SET fulfillment_status=?,updated_at=? WHERE id=?').bind(orderStatus,ts,f.order_id).run();await e.DB.prepare('INSERT INTO activity_events (id,order_id,event_type,trace_id,metadata_json,created_at) VALUES (?,?,?,?,?,?)').bind(id('evt_'),f.order_id,'fulfillment.updated',t,JSON.stringify({fulfillment_id:fid,status:x.status}),ts).run();return json({ok:true,fulfillment:await e.DB.prepare('SELECT * FROM fulfillments WHERE id=?').bind(fid).first()},200,t)}
export async function onRequest({request,env}){const t=request.headers.get('x-reqoo-trace-id')||crypto.randomUUID();if(!env.DB)return json({ok:false,error:'CORE_DB_BINDING_MISSING'},503,t);const p=new URL(request.url).pathname.split('/').filter(Boolean),fid=p[2]||null;if(request.method==='POST'&&!fid)return create(request,env,t);if(request.method==='GET'&&fid){const a=admin(request,env,t);if(a)return a;const f=await env.DB.prepare('SELECT * FROM fulfillments WHERE id=?').bind(fid).first();return f?json({ok:true,fulfillment:f},200,t):json({ok:false,error:'FULFILLMENT_NOT_FOUND'},404,t)}if((request.method==='PUT'||request.method==='PATCH')&&fid)return update(request,env,t,fid);return json({ok:false,error:'METHOD_NOT_ALLOWED'},405,t)}
