/* REQOO PKSK V2 API
   Canonical backend for the PKSK simulator + student dashboard.
   V2 removes JSONP and legacy pksk endpoints. Client traffic is JSON POST only.
*/
const TOTAL_SETS=50;
const MAX_DEVICES=3;
const BANK_ORIGIN='https://pksk.sim.reqoo.co';

export async function onRequest(context){
  const {request,env}=context;
  if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors()});
  if(request.method!=='POST')return json({ok:false,error:'Method POST diperlukan.'},405);
  try{
    const data=await readJson(request);
    const result=await route(data,env);
    return json(result,result?.ok===false?400:200);
  }catch(e){
    return json({ok:false,error:String(e?.message||e)},500);
  }
}
function cors(){return {'access-control-allow-origin':'https://pksk.sim.reqoo.co','access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'Content-Type','cache-control':'no-store','x-content-type-options':'nosniff'}}
function json(obj,status=200){return new Response(JSON.stringify(obj),{status,headers:{'content-type':'application/json; charset=UTF-8',...cors()}})}
async function readJson(request){const ct=request.headers.get('content-type')||'';if(!ct.toLowerCase().includes('application/json'))throw new Error('Content-Type application/json diperlukan.');const body=await request.json();if(!body||typeof body!=='object'||Array.isArray(body))throw new Error('Payload tidak sah.');return body}
const str=v=>String(v??'').trim();
const codeOf=v=>str(v).toUpperCase();
const now=()=>new Date().toISOString();
const id=(p)=>`${p}_${crypto.randomUUID()}`;
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const bool=v=>v===true||v===1||v==='1'||String(v).toLowerCase()==='true';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,num(v,a)));
function deviceLabel(ua){const s=str(ua);if(/iPhone/i.test(s))return'iPhone';if(/iPad/i.test(s))return'iPad';if(/Android/i.test(s))return'Android';if(/Windows/i.test(s))return'Windows PC';if(/Macintosh|Mac OS X/i.test(s))return'Mac';return'Browser'}
async function route(d,env){switch(str(d.action)){case'validateAccess':return validateAccess(d,env);case'registerDevice':return registerDevice(d,env);case'getCustomerDashboard':return getCustomerDashboard(d,env);case'saveProgress':return saveProgress(d,env);case'logClientError':return {ok:true};default:return {ok:false,error:'Action V2 tidak disokong.'}}}
async function getLicense(code,env){return env.DB.prepare('SELECT * FROM licenses WHERE access_code=?').bind(codeOf(code)).first()}
async function requireLicense(d,env){const code=codeOf(d.code);if(!code)throw new Error('Access Code diperlukan.');const l=await getLicense(code,env);if(!l)throw new Error('Access Code tidak sah.');if(str(l.status).toLowerCase()!=='active')throw new Error('License tidak aktif.');return l}
async function ensureMaxDevices(l,env){await env.DB.prepare('UPDATE licenses SET max_devices=? WHERE id=? AND (max_devices IS NULL OR max_devices<?)').bind(MAX_DEVICES,l.id,MAX_DEVICES).run()}
async function validateAccess(d,env){const l=await requireLicense(d,env);await ensureMaxDevices(l,env);const r=await env.DB.prepare("SELECT COUNT(*) AS n FROM devices WHERE license_id=? AND status='active'").bind(l.id).first();return{ok:true,accessCode:codeOf(d.code),maxDevices:MAX_DEVICES,deviceCount:num(r?.n)}}
async function registerDevice(d,env){const l=await requireLicense(d,env);const key=str(d.deviceId);if(!key||key.length<6||key.length>200)throw new Error('Maklumat peranti tidak lengkap.');await ensureMaxDevices(l,env);const existing=await env.DB.prepare('SELECT * FROM devices WHERE license_id=? AND device_key=?').bind(l.id,key).first();if(existing){await env.DB.prepare("UPDATE devices SET last_seen=?,device_name=?,status='active' WHERE id=?").bind(now(),deviceLabel(d.userAgent),existing.id).run();const c=await countDevices(l.id,env);return{ok:true,registered:true,deviceCount:c,maxDevices:MAX_DEVICES}}const inserted=await env.DB.prepare("INSERT INTO devices (id,license_id,device_key,device_name,first_seen,last_seen,status) SELECT ?,?,?,?,?,?,'active' WHERE (SELECT COUNT(*) FROM devices WHERE license_id=? AND status='active') < ?").bind(id('dev'),l.id,key,deviceLabel(d.userAgent),now(),now(),l.id,MAX_DEVICES).run();if(!inserted.meta?.changes)return{ok:false,error:`Akses maksimum ${MAX_DEVICES} peranti telah digunakan.`,limitReached:true,deviceCount:MAX_DEVICES,maxDevices:MAX_DEVICES};return{ok:true,registered:true,deviceCount:await countDevices(l.id,env),maxDevices:MAX_DEVICES}}
async function countDevices(licenseId,env){const r=await env.DB.prepare("SELECT COUNT(*) AS n FROM devices WHERE license_id=? AND status='active'").bind(licenseId).first();return num(r?.n)}
async function requireDevice(d,l,env){const key=str(d.deviceId);if(!key)return false;return!!(await env.DB.prepare("SELECT id FROM devices WHERE license_id=? AND device_key=? AND status='active'").bind(l.id,key).first())}
async function loadBank(setNo){const groupStart=Math.floor((setNo-1)/10)*10+1;const groupEnd=groupStart+9;const group=`SET ${String(groupStart).padStart(2,'0')}-${String(groupEnd).padStart(2,'0')}`;const url=`${BANK_ORIGIN}/simulator/sets/${encodeURIComponent(group)}/data/set${String(setNo).padStart(2,'0')}.json`;const r=await fetch(url,{cf:{cacheTtl:60}});if(!r.ok)throw new Error('Bank soalan canonical tidak dapat dicapai.');const bank=await r.json();if(!Array.isArray(bank.questions)||!bank.questions.length)throw new Error('Bank soalan kosong.');return bank}
function answerIndex(q){if(Number.isInteger(Number(q.answerIndex)))return Number(q.answerIndex);if(Number.isInteger(Number(q.answer)))return Number(q.answer);if(Array.isArray(q.weights)&&q.weights.length){let best=0;for(let i=1;i<q.weights.length;i++)if(num(q.weights[i])>num(q.weights[best],-Infinity))best=i;return best}return null}
async function scoreAnswers(setNo,answers){const bank=await loadBank(setNo);let aScore=0,aMax=0,bCorrect=0,bTotal=0,aAnswered=0,bAnswered=0;for(const q of bank.questions){const v=answers?.[q.id];if(v===undefined||v===null||v==='')continue;const i=Number(v);if(!Number.isInteger(i))continue;if(q.section==='BAHAGIAN A'){const w=Array.isArray(q.weights)?q.weights:[];if(w[i]!==undefined){aScore+=num(w[i]);aAnswered++}}else if(q.section==='BAHAGIAN B'){bAnswered++;const c=answerIndex(q);if(c!==null&&i===c)bCorrect++}}for(const q of bank.questions){if(q.section==='BAHAGIAN A'){const w=Array.isArray(q.weights)?q.weights:[];if(w.length)aMax+=Math.max(...w.map(num),0)}}bTotal=bank.questions.filter(q=>q.section==='BAHAGIAN B').length||70;return{scoreA:aMax?Math.round(aScore/aMax*100):0,scoreB:bTotal?Math.round(bCorrect/bTotal*100):0,bCorrect,aAnswered,bAnswered}}
function scoreWriting(text){const t=str(text),words=t?t.split(/\s+/).length:0;const examples=(t.match(/\b(contohnya|sebagai contoh|misalnya|contoh)\b/gi)||[]).length;const connectors=(t.match(/\b(selain itu|seterusnya|oleh itu|namun|akhir sekali|kesimpulannya|pada pendapat saya)\b/gi)||[]).length;const conclusion=/\b(kesimpulannya|sebagai kesimpulan|akhir kata|ringkasnya)\b/i.test(t);const r=[words>=100?4:Math.min(4,Math.floor(words/25)),Math.min(4,Math.max(1,Math.floor(words/55))),Math.min(4,examples+(words>=140?1:0)),Math.min(4,Math.max(1,1+Math.min(connectors,3))),Math.min(4,(words>=100?2:1)+(conclusion?2:0))];return{words,total:r.reduce((a,b)=>a+b,0)}}
function validateSet(n){const x=num(n);if(!Number.isInteger(x)||x<1||x>TOTAL_SETS)throw new Error('Set tidak sah.');return x}
async function saveProgress(d,env){const l=await requireLicense(d,env);if(!(await requireDevice(d,l,env)))throw new Error('Peranti belum didaftarkan.');const setNo=validateSet(d.setNo),section=str(d.section)||'OVERALL',completed=bool(d.completed);const answersRaw=d.answers;let answers=null;if(answersRaw&&typeof answersRaw==='object'&&!Array.isArray(answersRaw))answers=answersRaw;else if(typeof answersRaw==='string'&&answersRaw.length<=100000){try{answers=JSON.parse(answersRaw)}catch(_){answers=null}}if(completed&&(!answers||typeof answers!=='object'||Array.isArray(answers)))throw new Error('Jawapan diperlukan untuk mengesahkan keputusan.');let score=num(d.score),scoreA=num(d.scoreA),scoreB=num(d.scoreB),scoreC=num(d.scoreC),answered=clamp(d.answered,0,200),essayWords=clamp(d.essayWords,0,10000);if(completed){const s=await scoreAnswers(setNo,answers);scoreA=s.scoreA;scoreB=s.scoreB;answered=s.aAnswered+s.bAnswered;const c=scoreWriting(d.essayText);scoreC=c.total;essayWords=c.words;score=Math.round((scoreA+scoreB+Math.round(scoreC/20*100))/3)}const startedAt=d.startedAt?str(d.startedAt):null;const completedAt=completed?(d.completedAt?str(d.completedAt):now()):null;const existing=await env.DB.prepare('SELECT id FROM progress WHERE license_id=? AND set_no=? AND section=?').bind(l.id,setNo,section).first();const values=[completed,score,answered,clamp(d.timeUsed,0,10000),scoreA,scoreB,scoreC,startedAt,completedAt,now()];if(existing)await env.DB.prepare('UPDATE progress SET completed=?,score=?,answered=?,time_used=?,score_a=?,score_b=?,score_c=?,started_at=?,completed_at=?,updated_at=? WHERE id=?').bind(...values,existing.id).run();else await env.DB.prepare('INSERT INTO progress (id,license_id,set_no,section,completed,score,answered,time_used,score_a,score_b,score_c,started_at,completed_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id('prog'),l.id,setNo,section,...values).run();return{ok:true,saved:true,completed,serverScore:score,scoreA,scoreB,scoreC,essayWords}}
async function getCustomerDashboard(d,env){const code=codeOf(d.code);if(!code)throw new Error('Access Code diperlukan.');const l=await env.DB.prepare('SELECT l.*,o.customer_name,o.phone FROM licenses l JOIN orders o ON o.id=l.order_id WHERE l.access_code=?').bind(code).first();if(!l)throw new Error('Access Code tidak sah.');if(str(l.status).toLowerCase()!=='active')throw new Error('License tidak aktif.');if(!(await requireDevice(d,l,env)))throw new Error('Peranti belum didaftarkan.');const rows=(await env.DB.prepare('SELECT * FROM progress WHERE license_id=? ORDER BY set_no,section').bind(l.id).all()).results||[];const overall=new Map(),any=new Map();for(const x of rows){const n=num(x.set_no);if(!n)continue;if(!any.has(n))any.set(n,{setNo:n,answered:0,updatedAt:x.updated_at||x.completed_at||x.started_at||''});const a=any.get(n);a.answered=Math.max(a.answered,num(x.answered));a.updatedAt=String(x.updated_at||x.completed_at||x.started_at||a.updatedAt);if(str(x.section).toUpperCase()==='OVERALL')overall.set(n,x)}const sets=[];for(let n=1;n<=TOTAL_SETS;n++){const o=overall.get(n),a=any.get(n);sets.push({setNo:n,status:o?.completed?'completed':a&&a.answered>0?'incomplete':'not_started',completed:Boolean(o?.completed),answered:num(o?.answered||a?.answered),score:o?.completed?num(o.score):null,scoreA:o?.completed?num(o.score_a):0,scoreB:o?.completed?num(o.score_b):0,scoreC:o?.completed?num(o.score_c):0,updatedAt:o?.updated_at||a?.updatedAt||''})}const completed=sets.filter(x=>x.completed),nextSet=completed.length?Math.max(...completed.map(x=>x.setNo))+1:1,devices=(await env.DB.prepare('SELECT * FROM devices WHERE license_id=? ORDER BY last_seen DESC').bind(l.id).all()).results||[],scores=completed.map(x=>num(x.score)).filter(Number.isFinite),activity=completed.slice().sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0,20).map(x=>({message:`Set ${String(x.setNo).padStart(2,'0')} selesai • Indeks latihan ${num(x.score)}%`,createdAt:x.updatedAt}));return{ok:true,license:{licenseCode:l.access_code,orderNo:l.order_id,name:l.customer_name,phone:l.phone,status:l.status,createdAt:l.created_at,activeAt:l.activated_at,deviceCount:devices.filter(x=>x.status==='active').length,maxDevices:MAX_DEVICES,lastSeen:devices[0]?.last_seen||''},sets,totalSets:TOTAL_SETS,nextSet:Math.min(TOTAL_SETS+1,nextSet),allComplete:completed.length>=TOTAL_SETS,summary:{completed:completed.length,incomplete:sets.filter(x=>x.status==='incomplete').length,average:scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):null,best:scores.length?Math.max(...scores):null},activity}}
