const CORS={
  'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS',
  'access-control-allow-headers':'Content-Type,X-Admin-Token','cache-control':'no-store',
  'x-content-type-options':'nosniff'
};
const str=v=>String(v??'').trim(), clean=v=>str(v).toUpperCase(), now=()=>new Date().toISOString();
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
function json(x,s=200){return new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json;charset=UTF-8',...CORS}})}
async function table(env,n){return !!(await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").bind(n).first())}
async function activeToken(env){if(await table(env,'sim_admin_settings')){const r=await env.DB.prepare('SELECT admin_token FROM sim_admin_settings WHERE id=1').first();if(r?.admin_token)return str(r.admin_token)}return str(env.PKSK_ADMIN_TOKEN)}
async function ensure(env){
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS pksk_settings (id INTEGER PRIMARY KEY CHECK(id=1),price REAL NOT NULL DEFAULT 35,commission REAL NOT NULL DEFAULT 5,updated_at TEXT NOT NULL)`).run();
 await env.DB.prepare(`INSERT OR IGNORE INTO pksk_settings(id,price,commission,updated_at) VALUES(1,35,5,?)`).bind(now()).run();
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS pksk_payouts (id TEXT PRIMARY KEY,referral_code TEXT NOT NULL,amount REAL NOT NULL,status TEXT NOT NULL DEFAULT 'PENDING',reference TEXT,created_at TEXT NOT NULL,paid_at TEXT)`).run();
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS sim_user_logs (id TEXT PRIMARY KEY,license_id TEXT,access_code TEXT,device_key TEXT,event TEXT NOT NULL,level TEXT NOT NULL DEFAULT 'info',message TEXT,meta TEXT,created_at TEXT NOT NULL)`).run();
}
async function settings(env){return await env.DB.prepare('SELECT price,commission FROM pksk_settings WHERE id=1').first()}
async function licenseRows(env){
 if(!await table(env,'licenses'))return [];
 return (await env.DB.prepare(`SELECT l.*,o.customer_name,o.phone,o.email,o.amount,o.payment_status,o.payment_ref,o.created_at order_created FROM licenses l LEFT JOIN orders o ON o.id=l.order_id ORDER BY l.created_at DESC LIMIT 500`).all()).results||[];
}
async function orderRows(env){if(!await table(env,'orders'))return [];return (await env.DB.prepare(`SELECT o.*,l.access_code,l.status license_status FROM orders o LEFT JOIN licenses l ON l.order_id=o.id ORDER BY o.created_at DESC LIMIT 500`).all()).results||[]}
function formatOrder(o){return {orderNo:o.id,name:o.customer_name||'',phone:o.phone||'',amount:num(o.amount),status:clean(o.payment_status)||'PENDING',paymentRef:o.payment_ref||'',onlinePayment:String(o.payment_ref||'').startsWith('billplz:'),proofUploaded:Boolean(o.proof_ref||o.proof_url||o.payment_proof),proofRef:o.proof_ref||o.proof_url||'',accessCode:o.access_code||'',referralCode:o.referral_code||''}}
async function progressFor(id,env){if(!await table(env,'progress'))return [];return (await env.DB.prepare('SELECT * FROM progress WHERE license_id=? ORDER BY set_no,section').bind(id).all()).results||[]}
async function devicesFor(id,env){if(!await table(env,'devices'))return [];return (await env.DB.prepare('SELECT * FROM devices WHERE license_id=? ORDER BY last_seen DESC').bind(id).all()).results||[]}
async function referralRows(env){if(!await table(env,'sim_referral_agents'))return [];return (await env.DB.prepare('SELECT id,name,phone,bank_name,bank_account,referral_code,status,commission FROM sim_referral_agents ORDER BY created_at DESC LIMIT 500').all()).results||[]}
async function referralEvents(code,env){if(!await table(env,'sim_referral_events'))return [];return (await env.DB.prepare('SELECT * FROM sim_referral_events WHERE referral_code=? ORDER BY created_at DESC').bind(code).all()).results||[]}
async function errors(env){if(!await table(env,'sim_user_logs'))return [];return (await env.DB.prepare('SELECT event type,message,access_code code,device_key deviceId,created_at createdAt FROM sim_user_logs ORDER BY created_at DESC LIMIT 100').all()).results||[]}
async function formatRefs(rows,env){return Promise.all(rows.map(async r=>{const e=await referralEvents(r.referral_code,env),paid=e.filter(x=>clean(x.status)==='PAID');const earned=paid.reduce((s,x)=>s+num(x.commission),0);const out=await env.DB.prepare("SELECT COALESCE(SUM(amount),0) n FROM pksk_payouts WHERE referral_code=? AND status='PAID'").bind(r.referral_code).first();return {referralCode:r.referral_code,name:r.name,whatsapp:r.phone,bank:r.bank_name,account:r.bank_account,paidSales:paid.length,totalSales:e.length,commissionEarned:earned,commissionPaid:num(out?.n),commissionBalance:earned-num(out?.n)}}))}
async function dashboard(env){
 const orders=await orderRows(env),licenses=await licenseRows(env),refs=await referralRows(env),cfg=await settings(env);
 const paid=orders.filter(x=>['PAID','COMPLETED','SUCCESS'].includes(clean(x.payment_status))),pending=orders.filter(x=>clean(x.payment_status)==='PENDING');
 const lic=await Promise.all(licenses.map(async l=>{const p=await progressFor(l.id,env),done=p.filter(x=>Number(x.completed)===1&&clean(x.section)==='OVERALL'),scores=done.map(x=>num(x.score)).filter(Number.isFinite),ds=await devicesFor(l.id,env);return {licenseCode:l.access_code,name:l.customer_name||'',phone:l.phone||'',orderNo:l.order_id,status:clean(l.status),deviceCount:ds.filter(x=>clean(x.status)==='ACTIVE').length,maxDevices:num(l.max_devices,3),setsCompleted:done.length,average:scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0}}));
 let balance=0;for(const r of refs){const ev=await referralEvents(r.referral_code,env);balance+=ev.filter(x=>clean(x.status)==='PAID').reduce((s,x)=>s+num(x.commission),0);const paidOut=await env.DB.prepare("SELECT COALESCE(SUM(amount),0) n FROM pksk_payouts WHERE referral_code=? AND status='PAID'").bind(r.referral_code).first();balance-=num(paidOut?.n)}
 return {ok:true,config:{price:num(cfg?.price,35),commission:num(cfg?.commission,5)},summary:{paid:paid.length,pending:pending.length,active:lic.filter(x=>x.status==='ACTIVE').length,devices:lic.reduce((s,x)=>s+x.deviceCount,0),referrals:refs.length,commissionBalance:balance},orders:orders.map(formatOrder),licenses:lic,referrals:await formatRefs(refs,env),errors:await errors(env)};
}
async function getLicense(code,env){const rows=await licenseRows(env),l=rows.find(x=>clean(x.access_code)===clean(code));if(!l)return null;const ds=await devicesFor(l.id,env);return {licenseCode:l.access_code,name:l.customer_name||'',phone:l.phone||'',orderNo:l.order_id,status:clean(l.status),deviceCount:ds.filter(x=>clean(x.status)==='ACTIVE').length,maxDevices:num(l.max_devices,3),lastSeen:ds[0]?.last_seen||'',createdAt:l.created_at,activeAt:l.activated_at,id:l.id}}
function wa(phone,code,first){let p=str(phone).replace(/\D/g,'');if(p.startsWith('0'))p='60'+p.slice(1);const text=(first?'✅ Pembayaran PKSK telah disahkan.':'🔁 Mesej akses PKSK dihantar semula.')+`\n\n🔑 Access Code: ${code}\n\n📚 Akses PKSK:\nhttps://pksk.sim.reqoo.co/access/?code=${encodeURIComponent(code)}`;return p?'https://wa.me/'+p+'?text='+encodeURIComponent(text):''}
async function verify(d,env){const o=await env.DB.prepare('SELECT * FROM orders WHERE id=?').bind(str(d.orderNo)).first();if(!o)return{ok:false,error:'Order tidak dijumpai.'};await env.DB.prepare("UPDATE orders SET payment_status='paid',paid_at=? WHERE id=?").bind(now(),o.id).run();let l=await env.DB.prepare('SELECT * FROM licenses WHERE order_id=?').bind(o.id).first();if(!l){const code='PKSK-'+crypto.randomUUID().replace(/-/g,'').slice(0,10).toUpperCase();await env.DB.prepare(`INSERT INTO licenses(id,order_id,access_code,status,max_devices,created_at,activated_at,expires_at) VALUES(?,?,?,?,?,?,?,NULL)`).bind('lic_'+crypto.randomUUID(),o.id,code,'active',3,now(),now()).run();l=await env.DB.prepare('SELECT * FROM licenses WHERE order_id=?').bind(o.id).first()}if(await table(env,'sim_referral_events'))await env.DB.prepare("UPDATE sim_referral_events SET status='paid' WHERE order_id=? AND lower(status)='pending'").bind(o.id).run();return{ok:true,accessCode:l.access_code,whatsappUrl:wa(o.phone,l.access_code,true)}}
async function getReferral(code,env){const rows=await referralRows(env),r=rows.find(x=>clean(x.referral_code)===clean(code));if(!r)return{ok:false,error:'Referral tidak dijumpai.'};const sales=await referralEvents(r.referral_code,env),payouts=(await env.DB.prepare('SELECT * FROM pksk_payouts WHERE referral_code=? ORDER BY created_at DESC').bind(r.referral_code).all()).results||[],paid=sales.filter(x=>clean(x.status)==='PAID'),earned=paid.reduce((s,x)=>s+num(x.commission),0),paidOut=payouts.filter(x=>clean(x.status)==='PAID').reduce((s,x)=>s+num(x.amount),0);return{ok:true,referral:{referralCode:r.referral_code,name:r.name,whatsapp:r.phone,bank:r.bank_name,account:r.bank_account,paidSales:paid.length,commissionEarned:earned,commissionPaid:paidOut,commissionBalance:earned-paidOut},sales,payouts}}
export async function onRequest({request,env}){
 if(request.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});
 try{const u=new URL(request.url),q=Object.fromEntries(u.searchParams.entries()),body=request.method==='POST'&&String(request.headers.get('content-type')||'').includes('json')?await request.json():{},d={...q,...body},token=request.headers.get('X-Admin-Token')||d.token||'';
  if(String(token)!==String(await activeToken(env)))return json({ok:false,error:'Unauthorized'},401);await ensure(env);const a=str(d.action);
  if(a==='getPKSKAdminDashboard'||a==='summary')return json(await dashboard(env));
  if(a==='updatePKSKSettings'){const price=num(d.price,35),commission=num(d.commission,5);if(price<1||commission<0)return json({ok:false,error:'Tetapan tidak sah.'},400);await env.DB.prepare('UPDATE pksk_settings SET price=?,commission=?,updated_at=? WHERE id=1').bind(price,commission,now()).run();return json({ok:true,config:{price,commission}})}
  if(a==='verifyPKSKOrder')return json(await verify(d,env));
  if(a==='rejectPKSKOrder'){await env.DB.prepare("UPDATE orders SET payment_status='rejected' WHERE id=?").bind(str(d.orderNo)).run();return json({ok:true})}
  if(a==='getPKSKLicense'){const l=await getLicense(d.code,env);if(!l)return json({ok:false,error:'License tidak dijumpai.'},404);return json({ok:true,license:l,devices:await devicesFor(l.id,env),progress:await progressFor(l.id,env),activity:[]})}
  if(a==='logResendAccess'){const l=await getLicense(d.code,env);if(!l)return json({ok:false,error:'License tidak dijumpai.'},404);return json({ok:true,whatsappUrl:wa(l.phone,l.licenseCode,false)})}
  if(a==='resetDevices'){const l=await getLicense(d.code,env);if(!l)return json({ok:false,error:'License tidak dijumpai.'},404);await env.DB.prepare("UPDATE devices SET status='revoked' WHERE license_id=?").bind(l.id).run();return json({ok:true})}
  if(a==='setLicenseStatus'){const s=clean(d.status);if(!['ACTIVE','BLOCKED'].includes(s))return json({ok:false,error:'Status tidak sah.'},400);await env.DB.prepare('UPDATE licenses SET status=? WHERE access_code=?').bind(s.toLowerCase(),clean(d.code)).run();return json({ok:true})}
  if(a==='getReferral')return json(await getReferral(d.referralCode,env));
  if(a==='createReferralPayout'){const r=await getReferral(d.referralCode,env);if(!r.ok)return json(r,400);const amount=num(d.amount);if(amount<=0||amount>num(r.referral.commissionBalance))return json({ok:false,error:'Jumlah payout tidak sah.'},400);const id='pay_'+crypto.randomUUID();await env.DB.prepare('INSERT INTO pksk_payouts(id,referral_code,amount,status,created_at) VALUES(?,?,?,?,?)').bind(id,clean(d.referralCode),amount,'PENDING',now()).run();return json({ok:true,payoutId:id})}
  if(a==='markReferralPayoutPaid'){await env.DB.prepare("UPDATE pksk_payouts SET status='PAID',reference=?,paid_at=? WHERE id=?").bind(str(d.reference),now(),str(d.payoutId)).run();return json({ok:true})}
  if(a==='getPKSKErrors')return json({ok:true,errors:await errors(env)});
  if(a==='getPaymentProof')return json({ok:false,error:'Bukti pembayaran imej tidak disimpan oleh payment V2.'},404);
  return json({ok:false,error:'Action PKSK Admin tidak disokong.'},400);
 }catch(e){return json({ok:false,error:String(e?.message||e)},500)}}
