const MAX_DEVICES=3;
const ALLOWED_CALLBACK=/^[A-Za-z_$][A-Za-z0-9_$]*$/;
const cors={'access-control-allow-origin':'https://pksk.sim.reqoo.co','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'Content-Type','cache-control':'no-store'};
const clean=v=>String(v||'').trim().toUpperCase();
const now=()=>new Date().toISOString();
function respond(obj,cb=''){const t=JSON.stringify(obj);return new Response(cb&&ALLOWED_CALLBACK.test(cb)?`${cb}(${t});`:t,{headers:{'content-type':cb?'application/javascript; charset=UTF-8':'application/json; charset=UTF-8',...cors}})}
async function input(request){const u=new URL(request.url),q=Object.fromEntries(u.searchParams.entries());if(request.method==='GET')return q;const ct=request.headers.get('content-type')||'';if(ct.includes('application/json'))return {...await request.json(),callback:q.callback||''};return q}
async function getLicense(code,env){return env.DB.prepare('SELECT * FROM licenses WHERE access_code=?').bind(clean(code)).first()}
async function ensureTable(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS pksk_sessions (id TEXT PRIMARY KEY, license_id TEXT NOT NULL, set_no INTEGER NOT NULL, state_json TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(license_id,set_no))`).run()}
function deviceName(ua){const s=String(ua||'');if(/iPhone/i.test(s))return'iPhone';if(/iPad/i.test(s))return'iPad';if(/Android/i.test(s))return'Android';if(/Windows/i.test(s))return'Windows PC';if(/Macintosh|Mac OS X/i.test(s))return'Mac';return'Browser'}
async function ensureDevice(d,l,env){const key=String(d.deviceId||'').trim(),name=deviceName(d.userAgent);if(!key)return false;const exact=await env.DB.prepare("SELECT * FROM devices WHERE license_id=? AND device_key=? AND status='active'").bind(l.id,key).first();if(exact){await env.DB.prepare('UPDATE devices SET last_seen=?,device_name=? WHERE id=?').bind(now(),name,exact.id).run();return true}
 const same=await env.DB.prepare("SELECT * FROM devices WHERE license_id=? AND device_name=? AND status='active' ORDER BY last_seen DESC LIMIT 1").bind(l.id,name).first();
 if(same){await env.DB.prepare('UPDATE devices SET device_key=?,last_seen=?,device_name=? WHERE id=?').bind(key,now(),name,same.id).run();return true}
 const count=await env.DB.prepare("SELECT COUNT(*) AS n FROM devices WHERE license_id=? AND status='active'").bind(l.id).first();if(Number(count?.n||0)>=MAX_DEVICES)return false;
 await env.DB.prepare("INSERT INTO devices (id,license_id,device_key,device_name,first_seen,last_seen,status) VALUES (?,?,?,?,?,?, 'active')").bind(`dev_${crypto.randomUUID()}`,l.id,key,name,now(),now()).run();return true}
async function route(d,env){await ensureTable(env);const code=clean(d.code),l=await getLicense(code,env);if(!l||String(l.status).toLowerCase()!=='active')return{ok:false,error:'License tidak aktif atau Access Code tidak sah'};if(!(await ensureDevice(d,l,env)))return{ok:false,error:`Akses maksimum ${MAX_DEVICES} peranti telah digunakan.`,limitReached:true};const set=Number(d.setNo||0);if(set<1||set>50)return{ok:false,error:'Set tidak sah'};if(d.action==='registerDevice')return{ok:true,deviceCount:Number((await env.DB.prepare("SELECT COUNT(*) AS n FROM devices WHERE license_id=? AND status='active'").bind(l.id).first())?.n||0),maxDevices:MAX_DEVICES};if(d.action==='saveSession'){const state=String(d.state||'');if(!state)return{ok:false,error:'State kosong'};await env.DB.prepare(`INSERT INTO pksk_sessions (id,license_id,set_no,state_json,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(license_id,set_no) DO UPDATE SET state_json=excluded.state_json,updated_at=excluded.updated_at`).bind(`sess_${crypto.randomUUID()}`,l.id,set,state,now()).run();return{ok:true}}if(d.action==='getSession'){const row=await env.DB.prepare('SELECT state_json,updated_at FROM pksk_sessions WHERE license_id=? AND set_no=?').bind(l.id,set).first();return{ok:true,state:row?.state_json||null,updatedAt:row?.updated_at||null}}return{ok:false,error:'Action tidak disokong'}}
export async function onRequest(context){const {request,env}=context;if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors});try{const d=await input(request);return respond(await route(d,env),d.callback||'')}catch(e){return respond({ok:false,error:String(e?.message||e)})}}
