const CORS={'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'Content-Type,X-Admin-Token','cache-control':'no-store'};
const out=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json;charset=UTF-8',...CORS}});
const id=p=>`${p}_${crypto.randomUUID()}`;
const now=()=>new Date().toISOString();
function tokenFrom(request,d){return String(request.headers.get('X-Admin-Token')||d.token||'').trim()}
async function isAdmin(request,d,env){const token=tokenFrom(request,d);if(!token)return false;const expected=String(env.SHOP_ADMIN_TOKEN||env.PKSK_ADMIN_TOKEN||'');return !!expected&&token===expected}
export async function onRequest({request,env}){
 if(request.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});
 try{const d=request.method==='GET'?Object.fromEntries(new URL(request.url).searchParams):await request.json();if(!(await isAdmin(request,d,env)))return out({ok:false,error:'Unauthorized'},401);return out(await route(d,env));}
 catch(e){return out({ok:false,error:String(e?.message||e)},500)}
}
async function route(d,env){const a=String(d.action||'');if(a==='listProducts')return listProducts(env);if(a==='saveProduct')return saveProduct(d,env);if(a==='deleteProduct')return deleteProduct(d,env);if(a==='listOrders')return listOrders(d,env);if(a==='getOrder')return getOrder(d,env);if(a==='receipt')return receipt(d,env);if(a==='generateCustomerReceipt')return {ok:true,customerReceiptUrl:`/api/shop-admin?action=receipt&orderRef=${encodeURIComponent(String(d.orderNo||d.orderRef||''))}&token=${encodeURIComponent(String(d.token||''))}`};if(a==='status')return updateOrderStatus(d,env);if(a==='listCustomers')return listCustomers(env);if(a==='getShipping')return getShipping(env);if(a==='saveShipping')return saveShipping(d,env);if(a==='listPromotions')return listPromotions(env);if(a==='savePromotion')return savePromotion(d,env);if(a==='deletePromotion')return deletePromotion(d,env);return {ok:false,error:'Action tidak dikenali'}}
async function listProducts(env){const p=await env.SHOP_DB.prepare('SELECT * FROM products ORDER BY created_at').all();const v=await env.SHOP_DB.prepare('SELECT * FROM product_variants ORDER BY created_at').all();const by={};for(const x of v.results||[])(by[x.product_id]??=[]).push(x);return {ok:true,products:(p.results||[]).map(x=>({...x,desc:x.description||'',image:x.image_url||'',v:(by[x.id]||[]).filter(z=>z.active!==0).map(z=>[z.name,Number(z.price||0)]),variants:by[x.id]||[]}))}}
async function saveProduct(d,env){const t=now(),productId=String(d.id||id('prod')),sku=String(d.sku||d.id||'').trim().toUpperCase(),name=String(d.name||'').trim();if(!sku||!name)return {ok:false,error:'SKU dan nama produk diperlukan'};const existing=await env.SHOP_DB.prepare('SELECT id FROM products WHERE id=?').bind(productId).first();if(existing)await env.SHOP_DB.prepare('UPDATE products SET sku=?,name=?,category=?,description=?,image_url=?,active=?,updated_at=? WHERE id=?').bind(sku,name,d.category||'',d.description||d.desc||'',d.imageUrl||d.image||'',d.active===false?0:1,t,productId).run();else await env.SHOP_DB.prepare('INSERT INTO products(id,sku,name,category,description,image_url,active,created_at,updated_at) VALUES(?,?,?,?,?,?,1,?,?)').bind(productId,sku,name,d.category||'',d.description||d.desc||'',d.imageUrl||d.image||'',t,t).run();if(Array.isArray(d.variants)){await env.SHOP_DB.prepare('DELETE FROM product_variants WHERE product_id=?').bind(productId).run();for(const raw of d.variants){const x=Array.isArray(raw)?{name:raw[0],price:raw[1]}:raw;if(!x?.name)continue;await env.SHOP_DB.prepare('INSERT INTO product_variants(id,product_id,name,sku,price,stock,active,created_at,updated_at) VALUES(?,?,?,?,?,?,1,?,?)').bind(id('var'),productId,String(x.name),x.sku||null,Number(x.price||0),x.stock===''||x.stock==null?null:Number(x.stock),t,t).run()}}return {ok:true,productId}}
async function deleteProduct(d,env){const productId=String(d.id||'');if(!productId)return {ok:false,error:'Product id diperlukan'};await env.SHOP_DB.prepare('UPDATE products SET active=0,updated_at=? WHERE id=?').bind(now(),productId).run();return {ok:true}}
async function syncPendingBillplz(env,orders){if(!Array.isArray(orders))return;for(const o of orders){const payment=String(o.payment_status||'').toUpperCase();if(payment==='PAID'||!o.billplz_id)continue;try{const u=`https://shop.reqoo.co/api/shop?action=syncBillStatus&orderRef=${encodeURIComponent(String(o.order_ref))}`;const r=await fetch(u,{headers:{'cache-control':'no-store'}});const d=await r.json().catch(()=>({}));if(!r.ok||d?.ok!==true)console.error('SHOP Billplz sync failed',o.order_ref,d)}catch(e){console.error('Admin Billplz sync failed',o.order_ref,e)}}}
async function listOrders(d,env){const limit=Math.min(100,Math.max(1,Number(d.limit||50)));let r=await env.SHOP_DB.prepare('SELECT o.*,c.name customer_name,c.phone,c.email FROM orders o LEFT JOIN customers c ON c.id=o.customer_id ORDER BY o.created_at DESC LIMIT ?').bind(limit).all();await syncPendingBillplz(env,r.results||[]);r=await env.SHOP_DB.prepare('SELECT o.*,c.name customer_name,c.phone,c.email FROM orders o LEFT JOIN customers c ON c.id=o.customer_id ORDER BY o.created_at DESC LIMIT ?').bind(limit).all();return {ok:true,orders:(r.results||[]).map(o=>({...o,orderNo:o.order_ref,name:o.customer_name||'',phone:o.phone||'',email:o.email||'',timestamp:o.created_at,itemCount:0,status:o.status,payment:o.payment_status}))}}
async function updateOrderStatus(d,env){const key=String(d.orderNo||d.orderRef||d.orderId||'');const status=String(d.status||'').trim().toUpperCase();if(!key||!status)return {ok:false,error:'Order dan status diperlukan'};const r=await env.SHOP_DB.prepare('UPDATE orders SET status=?,updated_at=? WHERE order_ref=? OR id=?').bind(status,now(),key,key).run();return {ok:true,changed:Number(r.meta?.changes||0)}}
async function getOrder(d,env){const key=String(d.orderRef||d.orderId||'');const o=await env.SHOP_DB.prepare('SELECT o.*,c.name customer_name,c.phone,c.email FROM orders o LEFT JOIN customers c ON c.id=o.customer_id WHERE o.order_ref=? OR o.id=? LIMIT 1').bind(key,key).first();if(!o)return {ok:false,error:'Order tidak dijumpai'};const i=await env.SHOP_DB.prepare('SELECT * FROM order_items WHERE order_id=?').bind(o.id).all();return {ok:true,order:o,items:i.results||[]}}
async function listCustomers(env){const r=await env.SHOP_DB.prepare('SELECT * FROM customers ORDER BY created_at DESC LIMIT 500').all();return {ok:true,customers:r.results||[]}}
async function getShipping(env){const r=await env.SHOP_DB.prepare('SELECT * FROM shipping_methods ORDER BY sort_order ASC,name ASC').all();return {ok:true,shipping:r.results||[]}}
async function saveShipping(d,env){const sid=String(d.id||id('ship')),name=String(d.name||'').trim(),price=Math.max(0,Number(d.price||0));if(!name)return {ok:false,error:'Nama shipping diperlukan'};const t=now(),existing=await env.SHOP_DB.prepare('SELECT id FROM shipping_methods WHERE id=?').bind(sid).first();if(existing)await env.SHOP_DB.prepare('UPDATE shipping_methods SET name=?,price=?,active=?,sort_order=?,updated_at=? WHERE id=?').bind(name,price,d.active===false?0:1,Number(d.sortOrder||0),t,sid).run();else await env.SHOP_DB.prepare('INSERT INTO shipping_methods(id,name,price,active,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(sid,name,price,d.active===false?0:1,Number(d.sortOrder||0),t,t).run();return {ok:true,id:sid}}
async function listPromotions(env){const r=await env.SHOP_DB.prepare(`SELECT pr.*,p.name product_name,p.image_url product_image,v.price original_price FROM promotions pr LEFT JOIN products p ON p.id=pr.product_id LEFT JOIN product_variants v ON v.product_id=pr.product_id AND v.name=pr.variant ORDER BY pr.created_at DESC`).all();return {ok:true,promotions:(r.results||[]).map(x=>({...x,title:x.title||x.code,slug:x.slug||x.code.toLowerCase(),subtitle:x.product_name||'',image:x.product_image||'',productName:x.product_name||'',originalPrice:Number(x.original_price||0),promoPrice:Number(x.promo_price||0),start:x.starts_at||'',end:x.ends_at||'',active:!!x.active}))}}
async function savePromotion(d,env){const pid=String(d.id||id('promo')),code=String(d.slug||d.code||'').trim().toUpperCase();if(!code)return {ok:false,error:'Slug/kod promo diperlukan'};const t=now(),original=Number(d.originalPrice||0),promo=Number(d.promoPrice||0),value=Math.max(0,original-promo),existing=await env.SHOP_DB.prepare('SELECT id FROM promotions WHERE id=?').bind(pid).first();if(existing)await env.SHOP_DB.prepare(`UPDATE promotions SET code=?,type='fixed',value=?,starts_at=?,ends_at=?,active=?,updated_at=?,title=?,product_id=?,variant=?,promo_price=?,slug=? WHERE id=?`).bind(code,value,d.start||null,d.end||null,d.active===false?0:1,t,d.title||'',d.productId||null,d.variant||null,promo,code.toLowerCase(),pid).run();else await env.SHOP_DB.prepare(`INSERT INTO promotions(id,code,type,value,min_spend,starts_at,ends_at,usage_limit,usage_count,active,created_at,updated_at,title,product_id,variant,promo_price,slug) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(pid,code,'fixed',value,0,d.start||null,d.end||null,null,0,d.active===false?0:1,t,t,d.title||'',d.productId||null,d.variant||null,promo,code.toLowerCase()).run();return {ok:true,id:pid}}
async function deletePromotion(d,env){const pid=String(d.id||'');if(!pid)return {ok:false,error:'Promotion id diperlukan'};await env.SHOP_DB.prepare('UPDATE promotions SET active=0,updated_at=? WHERE id=?').bind(now(),pid).run();return {ok:true}}
async function receipt(d,env){const r=await getOrder(d,env);if(!r.ok)return r;const o=r.order,items=r.items,esc=s=>String(s??'').replace(/[&<>\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));const rows=items.map(x=>`<tr><td>${esc(x.product_name)}${x.variant_name?`<br><small>${esc(x.variant_name)}</small>`:''}</td><td>${x.qty}</td><td>RM${Number(x.unit_price).toFixed(2)}</td><td>RM${Number(x.line_total).toFixed(2)}</td></tr>`).join('');const html=`<!doctype html><html lang="ms"><head><meta charset="utf-8"><title>REQOO Receipt ${esc(o.order_ref)}</title><style>body{font-family:Arial,sans-serif;margin:40px;color:#111}h1{margin:0;color:#b28a35}.muted{color:#666}table{width:100%;border-collapse:collapse;margin-top:25px}th,td{padding:10px;border-bottom:1px solid #ddd;text-align:left}td:nth-child(n+2),th:nth-child(n+2){text-align:right}.total{font-size:20px;font-weight:bold;text-align:right;margin-top:20px}.status{padding:6px 10px;border:1px solid #bbb;border-radius:99px}</style></head><body><h1>REQOO.CO</h1><p class="muted">CUSTOM MADE. JUST FOR YOU.</p><hr><p><b>Receipt / Resit</b><br>No: ${esc(o.order_ref)}<br>Tarikh: ${esc(o.created_at)}<br>Status: <span class="status">${esc(o.payment_status)}</span></p><p><b>Customer</b><br>${esc(o.customer_name)}<br>${esc(o.phone)}<br>${esc(o.email)}</p><table><thead><tr><th>Item</th><th>Qty</th><th>Harga</th><th>Jumlah</th></tr></thead><tbody>${rows}</tbody></table><p>Subtotal: RM${Number(o.subtotal).toFixed(2)}<br>Discount: RM${Number(o.discount).toFixed(2)}<br>Shipping: RM${Number(o.shipping).toFixed(2)}</p><div class="total">TOTAL RM${Number(o.total).toFixed(2)}</div><p class="muted">Terima kasih kerana memilih REQOO.CO.</p><script>window.print()</script></body></html>`;return new Response(html,{headers:{'content-type':'text/html;charset=UTF-8',...CORS}})}