const CORS={'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'Content-Type','cache-control':'no-store'};
const out=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json;charset=UTF-8',...CORS}});
const id=p=>`${p}_${crypto.randomUUID()}`;
const now=()=>new Date().toISOString();
export async function onRequest({request,env}){
 if(request.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});
 try{const d=request.method==='GET'?Object.fromEntries(new URL(request.url).searchParams):await request.json();return out(await route(d,env));}
 catch(e){return out({ok:false,error:String(e?.message||e)},500)}
}
async function route(d,env){
 const a=String(d.action||'');
 if(a==='listProducts')return listProducts(env);
 if(a==='saveProduct')return saveProduct(d,env);
 if(a==='deleteProduct')return deleteProduct(d,env);
 if(a==='listOrders')return listOrders(d,env);
 if(a==='getOrder')return getOrder(d,env);
 if(a==='receipt')return receipt(d,env);
 return {ok:false,error:'Action tidak dikenali'};
}
async function listProducts(env){const p=await env.SHOP_DB.prepare('SELECT * FROM products WHERE active=1 ORDER BY created_at').all();const v=await env.SHOP_DB.prepare('SELECT * FROM product_variants WHERE active=1 ORDER BY created_at').all();const by={};for(const x of v.results||[])(by[x.product_id]??=[]).push(x);return {ok:true,products:(p.results||[]).map(x=>({...x,variants:by[x.id]||[]}))}}
async function saveProduct(d,env){const t=now(),productId=String(d.id||id('prod')),sku=String(d.sku||'').trim().toUpperCase(),name=String(d.name||'').trim();if(!sku||!name)return {ok:false,error:'SKU dan nama produk diperlukan'};const existing=await env.SHOP_DB.prepare('SELECT id FROM products WHERE id=?').bind(productId).first();if(existing)await env.SHOP_DB.prepare('UPDATE products SET sku=?,name=?,category=?,description=?,image_url=?,active=?,updated_at=? WHERE id=?').bind(sku,name,d.category||'',d.description||'',d.imageUrl||'',d.active===false?0:1,t,productId).run();else await env.SHOP_DB.prepare('INSERT INTO products(id,sku,name,category,description,image_url,active,created_at,updated_at) VALUES(?,?,?,?,?,?,1,?,?)').bind(productId,sku,name,d.category||'',d.description||'',d.imageUrl||'',t,t).run();if(Array.isArray(d.variants)){await env.SHOP_DB.prepare('DELETE FROM product_variants WHERE product_id=?').bind(productId).run();for(const x of d.variants){if(!x?.name)continue;await env.SHOP_DB.prepare('INSERT INTO product_variants(id,product_id,name,sku,price,stock,active,created_at,updated_at) VALUES(?,?,?,?,?,?,1,?,?)').bind(id('var'),productId,String(x.name),x.sku||null,Number(x.price||0),x.stock===''||x.stock==null?null:Number(x.stock),t,t).run()}}return {ok:true,productId}}
async function deleteProduct(d,env){const productId=String(d.id||'');if(!productId)return {ok:false,error:'Product id diperlukan'};await env.SHOP_DB.prepare('UPDATE products SET active=0,updated_at=? WHERE id=?').bind(now(),productId).run();return {ok:true}}
async function listOrders(d,env){const limit=Math.min(100,Math.max(1,Number(d.limit||50)));const r=await env.SHOP_DB.prepare('SELECT o.*,c.name customer_name,c.phone,c.email FROM orders o LEFT JOIN customers c ON c.id=o.customer_id ORDER BY o.created_at DESC LIMIT ?').bind(limit).all();return {ok:true,orders:r.results||[]}}
async function getOrder(d,env){const key=String(d.orderRef||d.orderId||'');const o=await env.SHOP_DB.prepare('SELECT o.*,c.name customer_name,c.phone,c.email FROM orders o LEFT JOIN customers c ON c.id=o.customer_id WHERE o.order_ref=? OR o.id=? LIMIT 1').bind(key,key).first();if(!o)return {ok:false,error:'Order tidak dijumpai'};const i=await env.SHOP_DB.prepare('SELECT * FROM order_items WHERE order_id=?').bind(o.id).all();return {ok:true,order:o,items:i.results||[]}}
async function receipt(d,env){const r=await getOrder(d,env);if(!r.ok)return r;const o=r.order,items=r.items,esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));const rows=items.map(x=>`<tr><td>${esc(x.product_name)}${x.variant_name?`<br><small>${esc(x.variant_name)}</small>`:''}</td><td>${x.qty}</td><td>RM${Number(x.unit_price).toFixed(2)}</td><td>RM${Number(x.line_total).toFixed(2)}</td></tr>`).join('');const html=`<!doctype html><html lang="ms"><head><meta charset="utf-8"><title>REQOO Receipt ${esc(o.order_ref)}</title><style>body{font-family:Arial,sans-serif;margin:40px;color:#111}h1{margin:0;color:#b28a35}.muted{color:#666}table{width:100%;border-collapse:collapse;margin-top:25px}th,td{padding:10px;border-bottom:1px solid #ddd;text-align:left}td:nth-child(n+2),th:nth-child(n+2){text-align:right}.total{font-size:20px;font-weight:bold;text-align:right;margin-top:20px}.status{padding:6px 10px;border:1px solid #bbb;border-radius:99px}</style></head><body><h1>REQOO.CO</h1><p class="muted">CUSTOM MADE. JUST FOR YOU.</p><hr><p><b>Receipt / Resit</b><br>No: ${esc(o.order_ref)}<br>Tarikh: ${esc(o.created_at)}<br>Status: <span class="status">${esc(o.payment_status)}</span></p><p><b>Customer</b><br>${esc(o.customer_name)}<br>${esc(o.phone)}<br>${esc(o.email)}</p><table><thead><tr><th>Item</th><th>Qty</th><th>Harga</th><th>Jumlah</th></tr></thead><tbody>${rows}</tbody></table><p>Subtotal: RM${Number(o.subtotal).toFixed(2)}<br>Discount: RM${Number(o.discount).toFixed(2)}<br>Shipping: RM${Number(o.shipping).toFixed(2)}</p><div class="total">TOTAL RM${Number(o.total).toFixed(2)}</div><p class="muted">Terima kasih kerana memilih REQOO.CO.</p><script>window.print()</script></body></html>`;return new Response(html,{headers:{'content-type':'text/html;charset=UTF-8',...CORS}})}
