const CORS={'access-control-allow-origin':'https://shop.reqoo.co','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'Content-Type','cache-control':'no-store'};
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json;charset=UTF-8',...CORS}});
const enc=x=>encodeURIComponent(String(x??''));
async function sign(params,key){const source=Object.entries(params).filter(([k,v])=>k!=='x_signature'&&v!==undefined&&v!==null).map(([k,v])=>[k,String(v)]).sort((a,b)=>a[0].localeCompare(b[0],undefined,{sensitivity:'base'})).map(([k,v])=>k+v).join('|');const data=new TextEncoder().encode(source),secret=new TextEncoder().encode(key);const h=await crypto.subtle.importKey('raw',secret,{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',h,data);return [...new Uint8Array(sig)].map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function onRequest({request,env}){
 if(request.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});
 try{if(request.method==='POST'){const b=await request.json();if(b.action==='createBill')return createBill(b,env);if(b.action==='callback')return callback(request,env)}if(request.method==='GET')return redirect(request,env);return json({ok:false,error:'Method not allowed'},405)}catch(e){return json({ok:false,error:'Billplz integration error'},500)}}
async function createBill(b,env){const orderRef=String(b.orderRef||''),amount=Math.round(Number(b.amount||0)*100);if(!orderRef||!amount||amount<100)return json({ok:false,error:'Order/amount tidak sah'},400);const order=await env.SHOP_DB.prepare('SELECT * FROM orders WHERE order_ref=? LIMIT 1').bind(orderRef).first();if(!order)return json({ok:false,error:'Order tidak dijumpai'},404);if(order.payment_status==='PAID')return json({ok:true,paid:true,orderRef});const base=env.BILLPLZ_BASE_URL||'https://www.billplz.com/api/v3';const body=new URLSearchParams({collection_id:env.BILLPLZ_COLLECTION_ID,description:`REQOO ${orderRef}`,name:String(b.name||''),email:String(b.email||''),amount:String(amount),callback_url:`${env.PUBLIC_API_ORIGIN||'https://shop.reqoo.co'}/api/shop-billplz`,redirect_url:`${env.PUBLIC_API_ORIGIN||'https://shop.reqoo.co'}/api/shop-billplz?redirect=1&order_ref=${enc(orderRef)}`,reference_1_label:'Order',reference_1:orderRef});const basic=btoa(`${env.BILLPLZ_API_KEY}:`);const r=await fetch(`${base}/bills`,{method:'POST',headers:{Authorization:`Basic ${basic}`,'Content-Type':'application/x-www-form-urlencoded'},body});const data=await r.json();if(!r.ok)return json({ok:false,error:'Billplz gagal cipta bill'},502);await env.SHOP_DB.prepare('UPDATE orders SET billplz_id=?,updated_at=? WHERE id=?').bind(data.id,new Date().toISOString(),order.id).run();return json({ok:true,billId:data.id,url:data.url,orderRef})}
async function callback(request,env){const raw=await request.text();const p=Object.fromEntries(new URLSearchParams(raw));const supplied=p.x_signature;if(!supplied)return new Response('missing signature',{status:400});const expected=await sign(p,env.BILLPLZ_X_SIGNATURE);if(expected!==supplied)return new Response('invalid signature',{status:401});const orderRef=p.reference_1||p.order_ref;const billId=p.id;if(!orderRef&&billId)return new Response('ok');const order=await env.SHOP_DB.prepare('SELECT * FROM orders WHERE order_ref=? OR billplz_id=? LIMIT 1').bind(orderRef||'',billId||'').first();if(!order)return new Response('ok');const paid=String(p.paid)==='true'||p.state==='paid';const status=paid?'PAID':'UNPAID';await env.SHOP_DB.prepare('UPDATE orders SET payment_status=?,status=?,billplz_id=COALESCE(billplz_id,?),updated_at=? WHERE id=?').bind(status,paid?'PROCESSING':order.status,billId,new Date().toISOString(),order.id).run();if(paid){await env.SHOP_DB.prepare('UPDATE customers SET total_orders=total_orders+1,total_spend=total_spend+?,last_order_at=?,updated_at=? WHERE id=?').bind(order.total,new Date().toISOString(),new Date().toISOString(),order.customer_id).run()}return new Response('OK',{status:200})}
async function redirect(request,env){const u=new URL(request.url);if(u.searchParams.get('redirect')!=='1')return json({ok:true,service:'Billplz callback'});const orderRef=u.searchParams.get('order_ref')||'';const paid=u.searchParams.get('billplz[paid]')==='true';const dest=env.SHOP_CHECKOUT_RETURN_URL||'https://shop.reqoo.co/checkout.html';return Response.redirect(`${dest}?order_ref=${enc(orderRef)}&payment=${paid?'success':'pending'}`,302)}
