-- REQOO SHOP catalog seed
-- Run this ONLY against reqoo-shop-db.
PRAGMA foreign_keys = ON;

INSERT OR REPLACE INTO products (id,sku,name,category,description,image_url,active,created_at,updated_at) VALUES
('101','PLAQUE-BASIC','Basic Collection','Plaque','Recognition Gift — 3 saiz.','assets/plaque-basic.jpg',1,datetime('now'),datetime('now')),
('102','PLAQUE-CLASSIC','Classic Collection','Plaque','Timeless elegance — 3 saiz.','assets/plaque-classic.jpg',1,datetime('now'),datetime('now')),
('103','PLAQUE-PRESTIGE','Prestige Collection','Plaque','Timeless recognition — 3 saiz.','assets/plaque-prestige.jpg',1,datetime('now'),datetime('now')),
('104','PLAQUE-SIGNATURE','Signature Collection','Plaque','Distinctive, prestigious, timeless.','assets/plaque-signature.jpg',1,datetime('now'),datetime('now')),
('201','BROOCH-TIE-TACK','Tie Tack / Butterfly Lock','Brooch','Ukiran laser — acrylic.','assets/brooch-01-04.jpg',1,datetime('now'),datetime('now')),
('202','BROOCH-STANDARD','Standard Brooch','Brooch','Ukiran laser — acrylic.','assets/brooch-01-04.jpg',1,datetime('now'),datetime('now')),
('203','BROOCH-BABY','Baby Brooch','Brooch','Ukiran laser — acrylic.','assets/brooch-01-04.jpg',1,datetime('now'),datetime('now')),
('204','BROOCH-EXCLUSIVE-RING','Exclusive Ring','Brooch','Ukiran laser — acrylic.','assets/brooch-01-04.jpg',1,datetime('now'),datetime('now')),
('205','BROOCH-SUBLIMATION','Sublimation Brooch','Brooch','Sublimation brooch — acrylic.','assets/brooch-05-07.jpg',1,datetime('now'),datetime('now')),
('206','BROOCH-STANDARD-RING','Standard Ring','Brooch','Ukiran laser — acrylic.','assets/brooch-05-07.jpg',1,datetime('now'),datetime('now')),
('207','BROOCH-BIG','Big Brooch','Brooch','Ukiran laser — acrylic.','assets/brooch-05-07.jpg',1,datetime('now'),datetime('now')),
('301','TROPHY-QUOTE','Trophy — Quotation','Trophy','Custom trophy. Harga mengikut design & kuantiti.','assets/trophy.jpg',1,datetime('now'),datetime('now')),
('401','MEDAL-QUOTE','Medal — Quotation','Medal','Custom medal. Harga mengikut design & kuantiti.','assets/medal.jpg',1,datetime('now'),datetime('now')),
('501','3D-PRINT-SERVICE','3D Print Service','3D Print Service','Hantar STL/OBJ, pilih material dan quantity. Kami beri quotation.','assets/3d-print.jpg',1,datetime('now'),datetime('now'));

INSERT OR REPLACE INTO product_variants (id,product_id,name,sku,price,stock,active,created_at,updated_at) VALUES
('101-A5','101','A5','PLAQUE-BASIC-A5',50,NULL,1,datetime('now'),datetime('now')),
('101-A4','101','A4','PLAQUE-BASIC-A4',100,NULL,1,datetime('now'),datetime('now')),
('101-A3','101','A3','PLAQUE-BASIC-A3',150,NULL,1,datetime('now'),datetime('now')),
('102-A5','102','A5','PLAQUE-CLASSIC-A5',99,NULL,1,datetime('now'),datetime('now')),
('102-A4','102','A4','PLAQUE-CLASSIC-A4',199,NULL,1,datetime('now'),datetime('now')),
('102-A3','102','A3','PLAQUE-CLASSIC-A3',299,NULL,1,datetime('now'),datetime('now')),
('103-A5','103','A5','PLAQUE-PRESTIGE-A5',130,NULL,1,datetime('now'),datetime('now')),
('103-A4','103','A4','PLAQUE-PRESTIGE-A4',230,NULL,1,datetime('now'),datetime('now')),
('103-A3','103','A3','PLAQUE-PRESTIGE-A3',330,NULL,1,datetime('now'),datetime('now')),
('104-A5','104','A5','PLAQUE-SIGNATURE-A5',130,NULL,1,datetime('now'),datetime('now')),
('104-A4','104','A4','PLAQUE-SIGNATURE-A4',210,NULL,1,datetime('now'),datetime('now')),
('104-A3','104','A3','PLAQUE-SIGNATURE-A3',310,NULL,1,datetime('now'),datetime('now')),
('201-SQUARE','201','Petak 30×20mm','BROOCH-TIE-SQUARE',1.50,NULL,1,datetime('now'),datetime('now')),
('201-ROUND','201','Bulat 25–30mm','BROOCH-TIE-ROUND',1.50,NULL,1,datetime('now'),datetime('now')),
('202-SQUARE','202','Petak 30×20mm','BROOCH-STANDARD-SQUARE',1.30,NULL,1,datetime('now'),datetime('now')),
('202-ROUND','202','Bulat 25–30mm','BROOCH-STANDARD-ROUND',1.30,NULL,1,datetime('now'),datetime('now')),
('203-SQUARE','203','Petak 25×10mm','BROOCH-BABY-SQUARE',1.00,NULL,1,datetime('now'),datetime('now')),
('203-ROUND','203','Bulat 18–20mm','BROOCH-BABY-ROUND',1.00,NULL,1,datetime('now'),datetime('now')),
('204-SQUARE','204','Petak 50×20mm','BROOCH-EXCLUSIVE-SQUARE',3.50,NULL,1,datetime('now'),datetime('now')),
('204-ROUND','204','Bulat 50×50mm','BROOCH-EXCLUSIVE-ROUND',3.50,NULL,1,datetime('now'),datetime('now')),
('205-SQUARE','205','Petak 30×20mm','BROOCH-SUBLIMATION-SQUARE',2.50,NULL,1,datetime('now'),datetime('now')),
('205-ROUND','205','Bulat 30–35mm','BROOCH-SUBLIMATION-ROUND',2.50,NULL,1,datetime('now'),datetime('now')),
('206-SQUARE','206','Petak 30×20mm','BROOCH-RING-SQUARE',1.30,NULL,1,datetime('now'),datetime('now')),
('206-ROUND','206','Bulat 25–30mm','BROOCH-RING-ROUND',1.30,NULL,1,datetime('now'),datetime('now')),
('207-SQUARE','207','Petak 50×20mm','BROOCH-BIG-SQUARE',2.00,NULL,1,datetime('now'),datetime('now')),
('207-ROUND','207','Bulat 50×50mm','BROOCH-BIG-ROUND',2.00,NULL,1,datetime('now'),datetime('now')),
('301-QUOTE','301','Custom quotation','TROPHY-QUOTE',0,NULL,1,datetime('now'),datetime('now')),
('401-QUOTE','401','Custom quotation','MEDAL-QUOTE',0,NULL,1,datetime('now'),datetime('now')),
('501-QUOTE','501','Quotation','3D-PRINT-QUOTE',0,NULL,1,datetime('now'),datetime('now'));
