/* REQOO PKSK SIMULATOR — CANONICAL RUNTIME
   Single runtime for Set 01–50.
   Completion is written to the same V56 API used by the student dashboard.
*/
(()=>{
'use strict';
const API='/api/pksk-v56';
const $=id=>document.getElementById(id);
const pad=n=>String(n).padStart(2,'0');
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const license=()=>String(localStorage.getItem('reqoo_pksk_license')||'').trim().toUpperCase();
const SET_KEY=n=>`reqoo:pksk:${license()}:set:${pad(n)}`;
let bank=null,qs=[],writing=[];
let setNo=clamp(Number(localStorage.getItem('pksk-selected-set')||1),1,50);
let phase='idle',qidx=0,answers={},times={},qStarted=0,timer=5400,wTimer=2700;
let interval=null,winterval=null,selectedTopic=0,abStartedAt=null,cStartedAt=null;
let saving=false,completedOnce=false,completionSaved=false;
function deviceId(){let id=localStorage.getItem('reqoo_pksk_device_id');if(!id){const seed=[navigator.userAgent,navigator.language,screen.width,screen.height,screen.colorDepth].join('|');let h=2166136261;for(let i=0;i<seed.length;i++){h^=seed.charCodeAt(i);h=Math.imul(h,16777619)}id='FAM-'+(h>>>0).toString(16);try{localStorage.setItem('reqoo_pksk_device_id',id)}catch(_){}}return id}
async function api(action,data={},done,retries=2){const code=license();if(!code){done?.({ok:false,error:'Tiada lesen PKSK.'});return}for(let attempt=0;attempt<=retries;attempt++){try{const controller=new AbortController(),timerId=setTimeout(()=>controller.abort(),12000);const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...data}),signal:controller.signal,cache:'no-store'});clearTimeout(timerId);let result=null;try{result=await r.json()}catch(_){result={ok:false,error:`Server memberi respons tidak sah (${r.status}).`}}if(r.ok&&result?.ok!==false){done?.(result);return result}if(attempt<retries){await new Promise(x=>setTimeout(x,700*(attempt+1)));continue}done?.(result||{ok:false,error:'Sambungan server gagal.'});return result}catch(e){if(attempt<retries){await new Promise(x=>setTimeout(x,700*(attempt+1)));continue}const result={ok:false,error:e?.name==='AbortError'?'Server mengambil masa terlalu lama.':'Sambungan server gagal.'};done?.(result);return result}}}
function requireAccess(next){const code=license();if(!code){location.href='../access/';return}api('registerDevice',{code,deviceId:deviceId(),userAgent:navigator.userAgent,setNo},r=>{if(r?.ok)next?.();else{alert(r?.error||'Akses tidak sah.');location.href='../access/'}},2)}
function localState(n=setNo){try{return JSON.parse(localStorage.getItem(SET_KEY(n))||'null')}catch(_){return null}}
function saveLocal(n=setNo){try{localStorage.setItem(SET_KEY(n),JSON.stringify({answers,times,timer,qidx,wTimer,selectedTopic,essay:$('essay')?.value||'',updatedAt:Date.now()}))}catch(_) {}}
function restoreLocal(n=setNo){const s=localState(n);if(!s)return;answers=s.answers||{};times=s.times||{};timer=Number.isFinite(Number(s.timer))?Number(s.timer):5400;wTimer=Number.isFinite(Number(s.wTimer))?Number(s.wTimer):2700;qidx=clamp(Number(s.qidx||0),0,Math.max(0,qs.length-1));selectedTopic=clamp(Number(s.selectedTopic||0),0,Math.max(0,writing.length-1));if($('essay'))$('essay').value=String(s.essay||'')}
function clearAttempt(n=setNo){try{localStorage.removeItem(SET_KEY(n))}catch(_) {}}
function clearFreshAttempt(n=setNo){clearAttempt(n);answers={};times={};qidx=0;timer=5400;wTimer=2700;selectedTopic=0;abStartedAt=null;cStartedAt=null;completedOnce=false;completionSaved=false;saveLocal(n)}
function correctIndex(q){if(Number.isInteger(Number(q.answerIndex)))return Number(q.answerIndex);if(Number.isInteger(Number(q.answer)))return Number(q.answer);if(Array.isArray(q.weights)&&q.weights.length)return q.weights.reduce((b,v,i)=>Number(v)>Number(q.weights[b]??-Infinity)?i:b,0);return null}
function scoreAB(){let aMax=0,aScore=0,bTotal=0,bCorrect=0;qs.filter(q=>q.section==='BAHAGIAN A').forEach(q=>{const w=Array.isArray(q.weights)?q.weights:[];if(w.length)aMax+=Math.max(...w.map(Number).filter(Number.isFinite),0);const a=answers[q.id];if(a!==undefined&&w[a]!==undefined)aScore+=Number(w[a])||0});qs.filter(q=>q.section==='BAHAGIAN B').forEach(q=>{bTotal++;const c=correctIndex(q);if(c!==null&&Number(answers[q.id])===c)bCorrect++});return{aScore,aMax,bCorrect,bTotal,total:aScore+bCorrect}}
function saveServer(section='OVERALL',completed=false,done){if(!license())return done?.({ok:false});if(saving&&!completed)return;const essay=String($('essay')?.value||'');const payload={code:license(),deviceId:deviceId(),setNo,section,completed,score:scoreAB().total,answered:Object.keys(answers).length,timeUsed:Math.max(0,Math.round((5400-timer+2700-wTimer)/60)),answers:JSON.stringify(answers),essayText:essay,essayWords:essay.trim().split(/\s+/).filter(Boolean).length,startedAt:abStartedAt||cStartedAt||null,completedAt:completed?new Date().toISOString():null};saving=!completed;api('saveProgress',payload,r=>{saving=false;if(completed&&r?.ok)completionSaved=true;done?.(r)},completed?3:2);if(!completed)setTimeout(()=>{saving=false},5000)}
function saveProgress(){saveLocal();saveServer(phase==='c'?'C':'AB',false)}
function show(id){['start','briefing','exam','writing','result'].forEach(x=>$(x)?.classList.add('hidden'));$(id)?.classList.remove('hidden');window.scrollTo?.(0,0)}
function updateSetUI(){document.querySelectorAll('.set-label').forEach(e=>e.textContent='SET '+pad(setNo));const sel=$('setSelect');if(sel)sel.value=String(setNo);const next=$('nextSetLabel');if(next)next.textContent=setNo<50?'SET '+pad(setNo+1)+' →':'PILIH SET'}
function groupPath(n=setNo){const start=Math.floor((n-1)/10)*10+1;return`SET ${pad(start)}-${pad(start+9)}`}
async function load(n=setNo){n=clamp(Number(n)||1,1,50);const r=await fetch(`sets/${encodeURIComponent(groupPath(n))}/data/set${pad(n)}.json`,{cache:'no-store'});if(!r.ok)throw new Error('Set '+pad(n)+' tidak dapat dimuat.');const data=await r.json();if(!Array.isArray(data.questions))throw new Error('Format bank soalan tidak sah.');setNo=n;bank=data;qs=data.questions;writing=Array.isArray(data.writing)?data.writing:[];updateSetUI();return true}
async function selectSet(n){if(!license()){location.href='../access/';return false}clearInterval(interval);clearInterval(winterval);phase='idle';qidx=0;answers={};times={};timer=5400;wTimer=2700;selectedTopic=0;completedOnce=false;completionSaved=false;try{await load(n);localStorage.setItem('pksk-selected-set',String(setNo));show('start');return true}catch(e){alert(e.message||'Set tidak dapat dimuat.');return false}}
function goHome(){clearInterval(interval);clearInterval(winterval);phase='idle';show('start')}
function nextSet(){if(setNo<50)selectSet(setNo+1);else goHome()}
function beginABBriefing(){requireAccess(()=>{clearFreshAttempt(setNo);phase='abBrief';show('briefing');$('briefingTitle').textContent='Bahagian A + B';$('voiceText').textContent='Calon diminta memberikan perhatian. Baca arahan pada skrin sebelum memulakan ujian.';$('voiceStatus').textContent='Arahan selesai. Tekan butang MULA di bawah.';countdown(startAB)})}
function countdown(callback){const box=$('count');if(!box){callback();return}box.innerHTML='';const b=document.createElement('button');b.type='button';b.className='start-btn';b.textContent='MULA →';b.addEventListener('click',()=>{b.disabled=true;callback()},{once:true});box.appendChild(b)}
function startAB(){phase='ab';qStarted=Date.now();abStartedAt=abStartedAt||Date.now();show('exam');renderQ();renderTimer();clearInterval(interval);interval=setInterval(()=>{timer=Math.max(0,timer-1);renderTimer();if(timer<=0){clearInterval(interval);finishAB(true)}else if(timer%30===0)saveProgress()},1000)}
function renderTimer(){const m=Math.floor(timer/60),s=timer%60;if($('timer'))$('timer').textContent=pad(m)+':'+pad(s)}
function saveTime(){if(qStarted){times[qidx]=(times[qidx]||0)+(Date.now()-qStarted);qStarted=Date.now();saveLocal()}}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function answer(i){if(phase!=='ab')return;answers[qs[qidx].id]=i;saveTime();renderQ()}
function gotoQ(i){if(!qs[i])return;saveTime();qidx=i;renderQ()}
function prevQ(){if(qidx>0){saveTime();qidx--;renderQ()}}
function nextQ(){saveTime();if(qidx<qs.length-1){qidx++;renderQ()}else confirmFinish()}
function confirmFinish(){if(confirm('Hantar Bahagian A + B sekarang?'))finishAB(false)}
function renderQ(){const q=qs[qidx];if(!q)return;$('sectionPill').textContent=q.section||'';$('cat').textContent=q.category||'';$('qnum').textContent=`Soalan ${qidx+1} daripada ${qs.length}`;const visual=$('qvisual');visual.innerHTML=q.visual?`<div class="question-visual"><img src="sets/${encodeURIComponent(groupPath())}/assets/visuals/${encodeURIComponent(q.visual)}" alt="Rajah soalan"></div>`:'';$('qtext').textContent=q.question||'';$('answeredCount').textContent=`${Object.keys(answers).length} / ${qs.length}`;$('opts').innerHTML=(q.options||[]).map((o,i)=>`<label class="opt ${Number(answers[q.id])===i?'selected':''}"><input type="radio" name="opt" ${Number(answers[q.id])===i?'checked':''}><span><b>${String.fromCharCode(65+i)}.</b> ${escapeHtml(o)}</span></label>`).join('');$('opts').querySelectorAll('input').forEach((el,i)=>el.addEventListener('change',()=>answer(i)));$('prevBtn').disabled=qidx===0;$('nextBtn').textContent=qidx===qs.length-1?'HANTAR A + B →':'SETERUSNYA →';$('grid').innerHTML=qs.map((x,i)=>`<button type="button" class="${answers[x.id]!==undefined?'done ':''}${i===qidx?'current':''}">${i+1}</button>`).join('');$('grid').querySelectorAll('button').forEach((b,i)=>b.addEventListener('click',()=>gotoQ(i)))}
function toggleMobileNav(force){const nav=$('navCard');if(!nav)return;const open=typeof force==='boolean'?force:!nav.classList.contains('mobile-open');nav.classList.toggle('mobile-open',open);document.body.classList.toggle('nav-open',open)}
function finishAB(auto=false){if(phase!=='ab')return;saveTime();clearInterval(interval);phase='cBrief';show('briefing');$('briefingTitle').textContent='Bahagian C — Artikulasi Penulisan';$('voiceText').textContent=auto?'Masa Bahagian A dan B telah tamat.':'Bahagian A dan B telah selesai.';$('voiceStatus').textContent='Pilih tajuk dan tekan MULA BAHAGIAN C.';const box=$('count');box.innerHTML='';const b=document.createElement('button');b.type='button';b.className='start-btn';b.textContent='MULA BAHAGIAN C →';b.addEventListener('click',startWriting,{once:true});box.appendChild(b)}
function startWriting(){phase='c';cStartedAt=cStartedAt||Date.now();show('writing');renderWriting();renderWTimer();clearInterval(winterval);winterval=setInterval(()=>{wTimer=Math.max(0,wTimer-1);renderWTimer();if(wTimer<=0){clearInterval(winterval);finishWriting(true)}else if(wTimer%30===0)saveProgress()},1000)}
function renderWriting(){$('topics').innerHTML=writing.map((t,i)=>`<label class="topic ${i===selectedTopic?'selected':''}"><input type="radio" name="topic" ${i===selectedTopic?'checked':''}><b>${escapeHtml(t.title||'Tajuk '+(i+1))}</b><span>${escapeHtml(t.prompt||'')}</span></label>`).join('');$('topics').querySelectorAll('.topic').forEach((el,i)=>el.addEventListener('click',e=>{if(e.target.tagName!=='INPUT')el.querySelector('input').checked=true;selectTopic(i)}));const w=localState();if(w&&typeof w.essay==='string')$('essay').value=w.essay;$('essay').oninput=()=>{updateWords();saveLocal()};updateWords()}
function selectTopic(i){selectedTopic=clamp(Number(i),0,Math.max(0,writing.length-1));renderWriting()}
function updateWords(){const text=String($('essay')?.value||'').trim(),n=text?text.split(/\s+/).filter(Boolean).length:0;if($('wordCount'))$('wordCount').textContent=n+' patah perkataan';if($('minStatus')){$('minStatus').textContent=n>=100?'✓ Minimum dicapai':'Minimum 100 patah perkataan';$('minStatus').className=n>=100?'good':'warn'}}
function renderWTimer(){const m=Math.floor(wTimer/60),s=wTimer%60;if($('wTimer'))$('wTimer').textContent=pad(m)+':'+pad(s)}
function cScore(){const text=String($('essay')?.value||'').trim(),words=text?text.split(/\s+/).filter(Boolean).length:0,paragraphs=text?text.split(/\n\s*\n/).filter(Boolean).length:0;let score=0;if(words>=100)score+=35;if(words>=150)score+=10;if(paragraphs>=2)score+=15;if(paragraphs>=3)score+=10;if(/[.!?]/.test(text))score+=10;if(/[A-Za-zÀ-ÿ]/.test(text))score+=20;return{score:Math.min(100,score),words,paragraphs}}
const STOP=new Set('dan yang di ke dari untuk dengan pada adalah itu ini kamu kami mereka seorang sebuah atau kerana tidak akan telah sudah apabila sebagai tentang dalam kepada agar supaya juga lebih sangat dapat boleh perlu harus ialah serta tetapi namun oleh itu dengan'.split(' '));
function wordsOf(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').match(/[a-zA-ZÀ-ÿ]{3,}/g)||[]}
function keyTerms(text){return [...new Set(wordsOf(text).filter(w=>!STOP.has(w)))].slice(0,40)}
function analyzeWriting(){const text=String($('essay')?.value||'').trim(),topic=writing[selectedTopic]||{},title=String(topic.title||''),prompt=String(topic.prompt||''),sourceTerms=keyTerms(title+' '+prompt),essayTerms=new Set(wordsOf(text)),matched=sourceTerms.filter(w=>essayTerms.has(w)),coverage=sourceTerms.length?Math.round(matched.length/sourceTerms.length*100):0;const sentences=text.split(/[.!?]+/).map(x=>x.trim()).filter(Boolean),issues=[];if(/\s+[,.!?]/.test(text))issues.push('Terdapat ruang sebelum tanda baca.');if(/,{2,}|\.{2,}|!{2,}|\?{2,}/.test(text))issues.push('Tanda baca berulang perlu disemak.');if(/\b(yg|dgn|x|tak|nak|kat|ni|tu)\b/i.test(text))issues.push('Ada singkatan bahasa mesej; gunakan bahasa baku dalam penulisan.');const badStarts=sentences.filter(s=>/^[a-z]/.test(s));if(badStarts.length)issues.push(`${badStarts.length} ayat bermula dengan huruf kecil.`);const longSent=sentences.filter(s=>s.split(/\s+/).length>35).length;if(longSent)issues.push(`${longSent} ayat terlalu panjang; pecahkan supaya lebih jelas.`);if(!text)return{title,prompt,coverage,matched,missing:sourceTerms,issues:['Belum ada jawapan untuk dinilai.'],sentences:0,paragraphs:0,examples:0,connectors:0,conclusion:false};const examples=(text.match(/\b(contohnya|sebagai contoh|misalnya|contoh)\b/gi)||[]).length,connectors=(text.match(/\b(selain itu|seterusnya|oleh itu|namun|akhir sekali|kesimpulannya|pada pendapat saya)\b/gi)||[]).length,conclusion=/\b(kesimpulannya|sebagai kesimpulan|akhir kata|ringkasnya)\b/i.test(text),paragraphs=text.split(/\n\s*\n/).filter(Boolean).length;return{title,prompt,coverage,matched,missing:sourceTerms.filter(w=>!essayTerms.has(w)),issues,sentences:sentences.length,paragraphs,examples,connectors,conclusion}}
function bar(p){return`<div class="meter"><i style="width:${clamp(Math.round(p),0,100)}%"></i></div>`}
function tableA(){const groups={};qs.filter(q=>q.section==='BAHAGIAN A').forEach(q=>{const k=q.category||'Lain-lain';groups[k]??={score:0,max:0};const g=groups[k],w=Array.isArray(q.weights)?q.weights:[];g.max+=w.length?Math.max(...w.map(Number).filter(Number.isFinite),0):0;const a=answers[q.id];if(a!==undefined&&w[a]!==undefined)g.score+=Number(w[a])||0});return`<div class="table"><div class="row head"><div>Kategori</div><div>Skor</div><div>Maks.</div><div>%</div><div></div></div>${Object.entries(groups).map(([k,g])=>{const p=g.max?g.score/g.max*100:0;return`<div class="row"><div>${escapeHtml(k)}</div><div>${g.score}</div><div>${g.max}</div><div>${Math.round(p)}%</div><div>${bar(p)}</div></div>`}).join('')}</div>`}
function reviewB(){return`<div class="review-list">${qs.filter(q=>q.section==='BAHAGIAN B').map((q,i)=>{const a=answers[q.id],c=correctIndex(q),st=a===undefined?'skip':c!==null&&Number(a)===c?'good':'bad',your=a===undefined?'—':`${String.fromCharCode(65+Number(a))}. ${escapeHtml(q.options?.[Number(a)]||'')}`,right=c===null?'—':`${String.fromCharCode(65+c)}. ${escapeHtml(q.options?.[c]||'')}`,why=escapeHtml(q.explanation||q.scoringNote||'Jawapan betul ditentukan oleh kunci jawapan item ini.');return`<article class="review-item ${st}"><div class="review-top"><span class="review-num">${i+1}</span><div class="review-q">${escapeHtml(q.question||'')}</div><strong>${st==='good'?'✓ BETUL':st==='bad'?'✕ SALAH':'○ TIDAK DIJAWAB'}</strong></div><div class="review-answer"><div><b>Anda:</b> ${your}</div><div><b>Betul:</b> ${right}</div></div><details class="review-details"><summary>Lihat penerangan</summary><div>${why}</div></details></article>`}).join('')}</div>`}
function reviewC(){const a=analyzeWriting(),c=cScore(),match=a.matched.length?`<div class="chip-list">${a.matched.slice(0,12).map(x=>`<span class="chip good-chip">${escapeHtml(x)}</span>`).join('')}</div>`:'<span class="muted-small">Belum cukup maklumat berkaitan tajuk dikesan.</span>',missing=a.missing.length?`<div class="chip-list">${a.missing.slice(0,10).map(x=>`<span class="chip warn-chip">${escapeHtml(x)}</span>`).join('')}</div>`:'<span class="good">Isi utama tajuk kelihatan disentuh.</span>',issues=a.issues.length?`<ul class="compact-list">${a.issues.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>`:'<span class="good">Tiada isu tatabahasa asas yang dikesan oleh semakan automatik.</span>';return`<div class="c-review"><div class="c-score-grid"><div><b>Relevan dengan tajuk</b><strong>${a.coverage}%</strong>${bar(a.coverage)}</div><div><b>Panjang jawapan</b><strong>${c.words} perkataan</strong><span>${c.words>=100?'✓ minimum dicapai':'⚠ bawah minimum'}</span></div><div><b>Struktur</b><strong>${a.paragraphs} perenggan</strong><span>${a.connectors} penanda wacana</span></div><div><b>Bahasa</b><strong>${a.issues.length?'Perlu semakan':'Baik'}</strong><span>${a.issues.length} isu asas dikesan</span></div></div><div class="c-review-block"><b>Isi penting yang dikesan</b><p>Istilah/kata kunci yang berkaitan dengan tajuk muncul dalam jawapan:</p>${match}</div><div class="c-review-block"><b>Isi yang masih kurang jelas</b><p>Perkara berikut berkaitan dengan tajuk tetapi belum cukup jelas dalam jawapan:</p>${missing}</div><div class="c-review-block"><b>Huraian & sokongan</b><p>${a.examples?`Terdapat ${a.examples} contoh/penanda contoh.`:'Belum dikesan contoh yang jelas.'} ${a.connectors?`Terdapat ${a.connectors} penanda wacana.`:'Penanda wacana masih boleh ditambah untuk menghubungkan isi.'} ${a.conclusion?'Ada penutup/kesimpulan.':'Kesimpulan belum dikesan.'}</p></div><div class="c-review-block"><b>Tatabahasa, ejaan & tanda baca</b>${issues}</div><div class="c-review-note">Semakan Bahagian C ialah analisis automatik untuk latihan. Ia menilai petunjuk isi, struktur dan bahasa asas; ia bukan penilaian manusia atau pemarkahan rasmi KPM.</div></div>`}
function buildResult(){const s=scoreAB(),c=cScore(),a=analyzeWriting();show('result');$('summary').innerHTML=[['A',s.aMax?Math.round(s.aScore/s.aMax*100)+'%':'0%'],['B',s.bTotal?Math.round(s.bCorrect/s.bTotal*100)+'%':'0%'],['C',c.score+'%'],['A+B',s.aScore+s.bCorrect],['Dijawab',Object.keys(answers).length+'/'+qs.length],['Perkataan',c.words]].map(x=>`<div class="stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$('aAnalysis').innerHTML=tableA();const bp=s.bTotal?s.bCorrect/s.bTotal*100:0;$('bAnalysis').innerHTML=`<div class="b-summary"><b>${s.bCorrect}/${s.bTotal}</b> betul${bar(bp)}</div>`;$('cAnalysis').innerHTML=reviewC();$('timeAnalysis').innerHTML=`<div class="time-grid"><div><span>A + B</span><b>${Math.round((5400-timer)/60)} min</b></div><div><span>C</span><b>${Math.round((2700-wTimer)/60)} min</b></div></div>`;$('reviewB').innerHTML=reviewB();$('progress').innerHTML=`<div class="progress-wrap"><b>Set ${pad(setNo)} selesai</b><p>Keputusan telah disediakan. Status set akan dikemas kini pada dashboard selepas server mengesahkan simpanan.</p><div id="completionStatus" class="save-status">● Menyimpan keputusan…</div></div>`;const overall=Math.round((s.aMax?s.aScore/s.aMax*40:0)+(s.bTotal?s.bCorrect/s.bTotal*40:0)+c.score*.2);$('conclusionTitle').textContent=overall>=80?'Prestasi sangat baik':overall>=60?'Prestasi baik':'Masih perlu latihan';$('conclusion').textContent=`Indeks latihan ${overall}%. Bahagian C: ${a.coverage}% petunjuk isi berkaitan tajuk dikesan. Fokus seterusnya: ${a.issues.length?'kemaskan bahasa dan tanda baca.':'tambahkan huraian, contoh dan hubungan antara isi.'}`}
function goDashboardAfterSave(){const go=()=>{location.href='../access/?code='+encodeURIComponent(license())};if(!license()){go();return}saveServer('OVERALL',true,r=>{completionSaved=Boolean(r?.ok);go()})}
function exitToDashboard(){if(phase==='ab')saveTime();if(phase==='c')saveLocal();clearInterval(interval);clearInterval(winterval);if(completedOnce){goDashboardAfterSave();return}saveServer(phase==='c'?'C':'AB',false,()=>location.href='../access/?code='+encodeURIComponent(license()))}
function bindStatic(){$('setSelect')?.addEventListener('change',e=>selectSet(e.target.value));$('startABBtn')?.addEventListener('click',beginABBriefing);$('prevBtn')?.addEventListener('click',prevQ);$('nextBtn')?.addEventListener('click',nextQ);document.querySelectorAll('.exam-dash').forEach(b=>b.addEventListener('click',exitToDashboard));document.querySelectorAll('.mobile-nav-btn').forEach(b=>b.addEventListener('click',()=>toggleMobileNav()));document.querySelectorAll('.nav-close').forEach(b=>b.addEventListener('click',()=>toggleMobileNav(false)));document.querySelectorAll('.finish-btn').forEach(b=>b.addEventListener('click',confirmFinish));$('essay')?.addEventListener('input',()=>{updateWords();saveLocal()});document.querySelector('#writing .editor-foot .primary')?.addEventListener('click',()=>finishWriting(false));const ra=document.querySelectorAll('.result-actions button');if(ra[0])ra[0].addEventListener('click',exitToDashboard);if(ra[1])ra[1].addEventListener('click',goHome);if(ra[2])ra[2].addEventListener('click',()=>{clearAttempt();selectSet(setNo)});if(ra[3])ra[3].addEventListener('click',nextSet)}
function finishWriting(auto=false){if(phase!=='c')return;clearInterval(winterval);saveLocal();phase='done';completedOnce=true;buildResult();saveServer('OVERALL',true,r=>{completionSaved=Boolean(r?.ok);const st=$('completionStatus');if(st)st.textContent=r?.ok?'✓ Set disimpan ke dashboard':'⚠ Set selesai tetapi sync server gagal — cuba DASHBOARD semula.'})}
async function boot(){bindStatic();updateSetUI();try{const u=new URLSearchParams(location.search),requested=u.get('set');if(requested)await load(requested);else await load(setNo);if(u.get('start')==='1')setTimeout(beginABBriefing,80)}catch(e){console.error(e);alert(e.message||'Simulator gagal memuatkan set.')}}
window.pkskLicense=license;window.pkskDeviceId=deviceId;window.pkskApi=api;window.beginABBriefing=beginABBriefing;window.startAB=startAB;window.startWriting=startWriting;window.selectSet=selectSet;window.answer=answer;window.gotoQ=gotoQ;window.nextQ=nextQ;window.prevQ=prevQ;window.confirmFinish=confirmFinish;window.finishAB=finishAB;window.finishWriting=finishWriting;window.exitToDashboard=exitToDashboard;window.goHome=goHome;window.nextSet=nextSet;window.toggleMobileNav=toggleMobileNav;window.updateWords=updateWords;window.renderTimer=renderTimer;window.renderWTimer=renderWTimer;
boot();
})();