/* REQOO PKSK V57 — single simulator compatibility layer.
   One layer only: access/device API bridge, text briefings, set URL sync,
   verified progress sync and a bounded C-submit safety net. */
(function(){
  'use strict';
  const API='/api/pksk-v56',TOTAL=50,$=id=>document.getElementById(id);
  const license=()=>String(localStorage.getItem('reqoo_pksk_license')||'').trim().toUpperCase();
  function device(){let id=localStorage.getItem('reqoo_pksk_device_id');if(!id){id='DEV-'+crypto.getRandomValues(new Uint32Array(3)).join('-')+'-'+Date.now().toString(36);localStorage.setItem('reqoo_pksk_device_id',id)}return id}
  function jsonp(action,data,done,retries=2){const run=n=>{const cb='pkskV57_'+Date.now()+'_'+Math.floor(Math.random()*99999),sc=document.createElement('script');let finished=false;const timer=setTimeout(()=>finish({ok:false,error:'Server mengambil masa terlalu lama.'}),11000);function finish(r){if(finished)return;finished=true;clearTimeout(timer);delete window[cb];sc.remove();if(r&&r.ok!==false){done(r);return}if(n<retries){setTimeout(()=>run(n+1),700*(n+1));return}done(r||{ok:false,error:'Sambungan server gagal.'})}window[cb]=finish;sc.onerror=()=>finish({ok:false,error:'Sambungan server gagal.'});sc.src=API+'?'+new URLSearchParams(Object.assign({action,callback:cb},data||{}));document.body.appendChild(sc)};run(0)}
  window.pkskApi=function(action,data,done,retries=2){return jsonp(action,data,done||function(){},retries)};
  window.pkskDashApi=function(action,data,done){return window.pkskApi(action,data,done,2)};
  window.pkskLicense=license;window.pkskDeviceId=device;
  window.pkskReportError=function(type,message){try{jsonp('logClientError',{code:license(),errorType:type,message:String(message||'').slice(0,400),deviceId:device()},()=>{},0)}catch(_){}};
  window.pkskRequireAccess=function(next){const code=license();if(!code){location.href='../access/';return}jsonp('registerDevice',{code,deviceId:device(),userAgent:navigator.userAgent},r=>{if(r&&r.ok){next();return}localStorage.removeItem('reqoo_pksk_license');alert((r&&r.error)||'Akses tidak sah atau had peranti telah dicapai.');location.href='../access/'},2)};
  function briefing(title,text,label,next){if(typeof window.show==='function')window.show('briefing');const titleEl=$('briefingTitle'),textEl=$('voiceText'),status=$('voiceStatus'),box=$('count');if(titleEl)titleEl.textContent=title;if(textEl)textEl.textContent=text;if(status)status.textContent='Baca arahan di skrin sebelum meneruskan.';const mic=document.querySelector('.mic');if(mic)mic.style.display='none';if(!box)return next();box.innerHTML='';const btn=document.createElement('button');btn.type='button';btn.className='v57-start-btn';btn.textContent=label;btn.onclick=()=>{btn.disabled=true;next()};box.appendChild(btn)}
  window.beginABBriefing=function(){if(!license()){location.href='../access/';return}if(typeof phase!=='undefined')phase='abBrief';briefing('Bahagian A + B','Jawab semua 100 soalan dengan teliti. Anda boleh bergerak antara soalan menggunakan navigasi. Masa keseluruhan ialah 90 minit.','MULA BAHAGIAN A + B →',()=>typeof startAB==='function'&&startAB())};
  window.finishAB=function(auto){if(typeof phase!=='undefined'&&phase!=='ab')return;if(typeof saveTime==='function')saveTime();if(typeof clearInterval==='function')clearInterval(interval);if(typeof phase!=='undefined')phase='cBrief';const msg=auto?'Masa Bahagian A + B telah tamat.':'Bahagian A + B telah selesai.';briefing('Bahagian C — Artikulasi Penulisan',msg+' Pilih satu tajuk dan tulis sekurang-kurangnya 100 patah perkataan. Masa 45 minit.','MULA BAHAGIAN C →',()=>typeof startWriting==='function'&&startWriting())};
  window.playAnnouncement=function(_key,after){if(typeof after==='function')after()};window.playAudioOnly=function(){};window.countdown=function(cb){if(typeof cb==='function')cb()};
  const originalSelect=window.selectSet;
  window.selectSet=async function(n){const requested=Math.max(1,Math.min(TOTAL,Number(n)||1));const result=originalSelect?await originalSelect(requested):false;if(result!==false||!originalSelect){const u=new URL(location.href);u.searchParams.set('set',String(requested));history.replaceState(null,'',u.pathname+'?'+u.searchParams.toString()+u.hash)}return result};
  try{const u=new URL(location.href),q=Number(u.searchParams.get('set')||0),saved=Number(localStorage.getItem('pksk-selected-set')||0);if(!q&&saved>=1&&saved<=TOTAL){u.searchParams.set('set',String(saved));history.replaceState(null,'',u.pathname+'?'+u.searchParams.toString()+u.hash)}}catch(_){ }
  function essayRubric(text){const t=String(text||'').trim(),w=t?t.split(/\s+/).length:0,ex=(t.match(/\b(contohnya|sebagai contoh|misalnya|contoh)\b/gi)||[]).length,cx=(t.match(/\b(selain itu|seterusnya|oleh itu|namun|akhir sekali|kesimpulannya|pada pendapat saya)\b/gi)||[]).length,co=/\b(kesimpulannya|sebagai kesimpulan|akhir kata|ringkasnya)\b/i.test(t),r=[w>=100?4:Math.min(4,Math.floor(w/25)),Math.min(4,Math.max(1,Math.floor(w/55))),Math.min(4,ex+(w>=140?1:0)),Math.min(4,Math.max(1,1+Math.min(cx,3))),Math.min(4,(w>=100?2:1)+(co?2:0))];return{words:w,total:r.reduce((a,b)=>a+b,0),rubric:r}}
  function answerMap(){try{return Object.assign({},answers||{})}catch(_){return {}}}
  function sync(score,extra){const code=license();if(!code)return;let text='';try{text=String(essay?.value||'')}catch(_){const el=$('essay');text=el?String(el.value||''):''}const c=essayRubric(text);let currentSet=1;try{currentSet=Number(setNo||1)}catch(_){}const payload=Object.assign({code,deviceId:device(),setNo:currentSet,completed:true,score:Number(score||0),answers:JSON.stringify(answerMap()),scoreC:c.total,essayWords:c.words,essayText:text},extra||{});jsonp('saveProgress',payload,r=>{if(r&&r.ok){localStorage.setItem('pksk-last-server-sync',new Date().toISOString());localStorage.setItem('pksk-server-score',String(r.serverScore??score??0));localStorage.setItem('pksk-server-score-a',String(r.scoreA??0));localStorage.setItem('pksk-server-score-b',String(r.scoreB??0));localStorage.setItem('pksk-server-score-c',String(r.scoreC??c.total))}else if(typeof queueProgress==='function')queueProgress(payload)},2)}
  window.syncProgressServer=sync;
  const canonicalFinish=window.finishWriting;
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])}
  function safeFinish(auto){
    try{
      try{clearInterval(winterval)}catch(_){ }
      phase='done';
      const qs0=Array.isArray(qs)?qs:[],ans=answerMap(),a=qs0.filter(q=>q.section==='BAHAGIAN A'),b=qs0.filter(q=>q.section==='BAHAGIAN B');
      const aScore=a.reduce((s,q)=>{const w=Array.isArray(q.weights)?q.weights:[],v=ans[q.id];return s+(v==null?0:Number(w[v]||0))},0),aMax=a.reduce((s,q)=>s+(Array.isArray(q.weights)&&q.weights.length?Math.max(...q.weights):0),0),aPct=aMax?Math.round(aScore/aMax*100):0;
      const bCorrect=b.filter(q=>ans[q.id]!=null&&Number(ans[q.id])===Number(q.answer)).length,bPct=b.length?Math.round(bCorrect/b.length*100):0;
      const el=$('essay'),text=el?String(el.value||''):'';const c=essayRubric(text),set=Number(setNo||1),topic=(Array.isArray(writing)?writing[Number(selectedTopic||0)]:null)?.title||'Artikulasi Penulisan';
      if(typeof window.show==='function')window.show('result');
      const summary=$('summary');if(summary)summary.innerHTML=[["A indeks",aPct+"%"],["B betul",`${bCorrect}/${b.length}`],["C rubrik",`${c.total}/20`],["C perkataan",c.words],["Set",`Set ${String(set).padStart(2,'0')}`],["Status",auto?'Masa tamat':'Dihantar']].map(x=>`<div class="stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');
      const aa=$('aAnalysis');if(aa)aa.innerHTML=`<p class="note">Indeks Bahagian A: <b>${aPct}%</b> berdasarkan pemberatan respons. ${a.filter(q=>ans[q.id]!==undefined).length}/${a.length} item dijawab.</p>`;
      const bb=$('bAnalysis');if(bb)bb.innerHTML=`<p class="note">Bahagian B: <b>${bCorrect}/${b.length}</b> betul (${bPct}%).</p>`;
      const rr=$('reviewB');if(rr)rr.innerHTML=b.map((q,i)=>{const v=ans[q.id],ok=v!=null&&Number(v)===Number(q.answer),your=v==null?'Tidak dijawab':`${String.fromCharCode(65+Number(v))}. ${esc(q.options?.[v]??'')}`,correct=`${String.fromCharCode(65+Number(q.answer))}. ${esc(q.options?.[q.answer]??'')}`;return`<article class="review-item ${ok?'good':'bad'}"><div class="review-top"><b>${i+1}. ${esc(q.question||'')}</b><strong>${ok?'BETUL':'SALAH'}</strong></div><div class="review-answer"><span><b>Jawapan anda:</b> ${your}</span><span><b>Jawapan betul:</b> ${correct}</span></div><div class="review-explain"><b>Penerangan:</b> ${esc(q.explanation||'Semak sebab pilihan ini paling tepat.')}</div></article>`}).join('');
      const cc=$('cAnalysis');if(cc)cc.innerHTML=`<div class="essay-grid"><div class="essay-item"><b>Tajuk</b><p>${esc(topic)}</p></div><div class="essay-item"><b>Panjang</b><p>${c.words} patah perkataan</p></div><div class="essay-item"><b>Rubrik latihan</b><p>${c.total}/20</p></div></div><p class="note">Semakan ini ialah rubrik latihan automatik, bukan pemarkahan rasmi KPM.</p>`;
      const con=$('conclusion');if(con)con.textContent=c.words<100?'Tambah panjang karangan sehingga sekurang-kurangnya 100 patah perkataan, kemudian latih isi, huraian dan contoh.':(bPct<70?'Fokus semakan pada Bahagian B dan ulang kategori yang paling banyak salah.':'Teruskan ke set berikutnya dan kekalkan ketepatan serta pengurusan masa.');
      const title=$('conclusionTitle');if(title)title.textContent='Apa perlu dibuat seterusnya?';
      sync(bPct,{aIndex:aPct,bCorrect,bAnswered:b.filter(q=>ans[q.id]!==undefined).length,aAnswered:a.filter(q=>ans[q.id]!==undefined).length,timeUsed:0,essayWords:c.words,completed:true});
      localStorage.removeItem(`pksk-set${String(set).padStart(2,'0')}-session`);localStorage.removeItem(`pksk-set${String(set).padStart(2,'0')}-writing`);
    }catch(e){if(typeof pkskReportError==='function')pkskReportError('C_SAFE_RESULT_FAILED',String(e?.stack||e).slice(0,400));const s=$('minStatus');if(s)s.textContent='Ralat sistem. Sila refresh dan cuba sekali lagi.'}
  }
  window.finishWriting=function(auto){try{if(typeof canonicalFinish==='function')return canonicalFinish.call(this,auto)}catch(e){console.warn('[PKSK V57] canonical C result failed; safe report used',e);safeFinish(auto)}};
  const notice=document.querySelector('.notice p');if(notice)notice.textContent='Baca arahan pada skrin sebelum mula. Masa hanya bermula selepas anda menekan butang MULA.';
  const style=document.createElement('style');style.id='v57-core-style';style.textContent='.v57-start-btn{display:inline-flex;align-items:center;justify-content:center;min-width:260px;border:0;border-radius:14px;padding:16px 24px;background:linear-gradient(135deg,#123f67,#178f8a);color:#fff;font-size:15px;font-weight:900;cursor:pointer;box-shadow:0 10px 24px rgba(18,63,103,.25)}.v57-start-btn:disabled{opacity:.65}.brief-inner .voice-status{max-width:760px}.mic{display:none!important}';document.head.appendChild(style);
})();
