/* REQOO PKSK V58 — single runtime layer.
   Canonical license/device/progress sync. Text-only briefings. No voice/countdown.
   Dashboard is the resume controller: every new set starts at Q1. */
(function(){
'use strict';
const API='/api/pksk-v56',TOTAL=50,$=id=>document.getElementById(id);
const code=()=>String(localStorage.getItem('reqoo_pksk_license')||'').trim().toUpperCase();
function device(){let id=localStorage.getItem('reqoo_pksk_device_id');if(!id){id='DEV-'+crypto.getRandomValues(new Uint32Array(3)).join('-')+'-'+Date.now().toString(36);localStorage.setItem('reqoo_pksk_device_id',id)}return id}
function api(action,data,done,retries=2){const run=n=>{const cb='pkskV58_'+Date.now()+'_'+Math.floor(Math.random()*99999),sc=document.createElement('script');let ended=false,t=setTimeout(()=>finish({ok:false,error:'Server mengambil masa terlalu lama.'}),11000);function finish(r){if(ended)return;ended=true;clearTimeout(t);delete window[cb];sc.remove();if(r&&r.ok!==false)return done(r);if(n<retries)return setTimeout(()=>run(n+1),700*(n+1));done(r||{ok:false,error:'Sambungan server gagal.'})}window[cb]=finish;sc.onerror=()=>finish({ok:false,error:'Sambungan server gagal.'});sc.src=API+'?'+new URLSearchParams({action,callback:cb,...(data||{})});document.body.appendChild(sc)};run(0)}
window.pkskApi=api;window.pkskLicense=code;window.pkskDeviceId=device;
window.pkskReportError=(type,message)=>{try{api('logClientError',{code:code(),deviceId:device(),errorType:type,message:String(message||'').slice(0,500)},()=>{},0)}catch(_) {}};
/* Use the canonical V56 API for dashboard/incomplete-progress writes as well. */
window.pkskDashApi=(action,data,done)=>api(action,data,done);
/* Opening simulator directly always lands on dashboard. Only the dashboard's explicit start=1 may enter a set. */
try{const u=new URL(location.href),start=u.searchParams.get('start')==='1';if(!start){location.replace('../access/');return}if(!code()){location.replace('../access/');return}}catch(_){location.replace('../access/');return}
/* Disable every browser speech path before any later simulator interaction. */
try{if(window.speechSynthesis){speechSynthesis.cancel();speechSynthesis.speak=()=>{};speechSynthesis.resume=()=>{};speechSynthesis.pause=()=>{};speechSynthesis.cancel=()=>{}}}catch(_){ }
window.playAnnouncement=()=>{};window.playAudioOnly=()=>{};window.countdown=cb=>{if(typeof cb==='function')cb()};
function clearSetDraft(set){const s=String(set).padStart(2,'0');localStorage.removeItem(`pksk-set${s}-session`);localStorage.removeItem(`pksk-set${s}-writing`);localStorage.removeItem(`pksk-set${s}-result`)}
function textBrief(title,text,label,next){if(typeof window.show==='function')window.show('briefing');const h=$('briefingTitle'),p=$('voiceText'),s=$('voiceStatus'),box=$('count');if(h)h.textContent=title;if(p)p.textContent=text;if(s)s.textContent='Arahan dipaparkan di skrin. Baca sebelum meneruskan.';document.querySelectorAll('.mic,.voice-status').forEach(x=>x.style.display='none');if(!box)return next();box.innerHTML='';const b=document.createElement('button');b.type='button';b.className='v58-start-btn';b.textContent=label;b.onclick=()=>{b.disabled=true;next()};box.appendChild(b)}
window.beginABBriefing=function(){if(!code()){location.replace('../access/');return}const set=Number(window.setNo||new URL(location.href).searchParams.get('set')||1);clearSetDraft(set);if(typeof phase!=='undefined')phase='abBrief';textBrief('Bahagian A + B','Jawab semua 100 soalan dengan teliti. Anda boleh bergerak antara soalan menggunakan navigasi. Masa keseluruhan 90 minit.','MULA BAHAGIAN A + B →',()=>typeof startAB==='function'&&startAB())};
window.finishAB=function(auto){try{if(typeof saveTime==='function')saveTime();if(typeof interval!=='undefined')clearInterval(interval)}catch(_){}if(typeof phase!=='undefined')phase='cBrief';textBrief('Bahagian C — Artikulasi Penulisan',auto?'Masa Bahagian A + B telah tamat.':'Bahagian A + B telah selesai. Pilih satu tajuk dan tulis sekurang-kurangnya 100 patah perkataan. Masa 45 minit.','MULA BAHAGIAN C →',()=>typeof startWriting==='function'&&startWriting())};
const oldSelect=window.selectSet;window.selectSet=async function(n){const set=Math.max(1,Math.min(TOTAL,Number(n)||1));clearSetDraft(set);let r=true;try{if(oldSelect)r=await oldSelect(set)}catch(e){pkskReportError('SET_SELECT',e.stack||e);throw e}localStorage.setItem('pksk-selected-set',String(set));const u=new URL(location.href);u.searchParams.set('set',String(set));history.replaceState(null,'',u.pathname+'?'+u.searchParams.toString()+u.hash);return r};
function answers(){try{return Object.assign({},window.answers||{})}catch(_){return {}}}
function essay(){try{if(window.essay?.value!=null)return String(window.essay.value)}catch(_){}const e=$('essay');return e?String(e.value||''):''}
function rubric(text){const t=String(text||'').trim(),w=t?t.split(/\s+/).length:0,ex=(t.match(/\b(contohnya|sebagai contoh|misalnya|contoh)\b/gi)||[]).length,cx=(t.match(/\b(selain itu|seterusnya|oleh itu|namun|akhir sekali|kesimpulannya|pada pendapat saya)\b/gi)||[]).length,co=/\b(kesimpulannya|sebagai kesimpulan|akhir kata|ringkasnya)\b/i.test(t),r=[w>=100?4:Math.min(4,Math.floor(w/25)),Math.min(4,Math.max(1,Math.floor(w/55))),Math.min(4,ex+(w>=140?1:0)),Math.min(4,Math.max(1,1+Math.min(cx,3))),Math.min(4,(w>=100?2:1)+(co?2:0))];return{words:w,total:r.reduce((a,b)=>a+b,0)}}
window.syncProgressServer=function(score,extra){const c=code();if(!c)return;let set=Number(window.setNo||new URL(location.href).searchParams.get('set')||1);const e=essay(),r=rubric(e),payload=Object.assign({code:c,deviceId:device(),setNo:set,completed:true,score:Number(score||0),answers:JSON.stringify(answers()),essayText:e,scoreC:r.total,essayWords:r.words},extra||{});api('saveProgress',payload,res=>{if(!res?.ok)pkskReportError('SAVE_PROGRESS',res?.error||'unknown');else{localStorage.setItem('pksk-server-score',String(res.serverScore??0));localStorage.setItem('pksk-last-server-sync',new Date().toISOString())}},2)};
/* Correct the old progress-history copy: this product has 50 sets, not 100. */
window.progressHistory=function(score){let h=[];try{h=JSON.parse(localStorage.getItem('pksk-progress')||'[]')}catch(_){h=[]}const set=Number(window.setNo||new URL(location.href).searchParams.get('set')||1);const n=Number(score||0);const found=h.find(x=>x.set===set);if(found)found.score=n;else h.push({set,score:n});h=h.filter(x=>Number(x.set)>=1&&Number(x.set)<=TOTAL).sort((a,b)=>a.set-b.set);localStorage.setItem('pksk-progress',JSON.stringify(h));const rows=h.map(x=>`<div class="progress-row"><b>Set ${String(x.set).padStart(2,'0')}</b><div class="progress-bar"><i style="width:${Math.min(100,Math.max(0,Number(x.score)||0))}%"></i></div><span>${Number(x.score)||0}%</span></div>`).join('');return `<div class="progress-wrap">${rows||'<p>Belum ada rekod.</p>'}<p class="note">Set seterusnya akan ditambah ke graf ini apabila keputusan set baharu tersedia.</p></div>`};
/* Safety wrapper for C: use the original report if it succeeds; otherwise show a minimal verified report and sync. */
const originalFinish=window.finishWriting;
window.finishWriting=function(auto){try{if(typeof originalFinish==='function')return originalFinish.call(this,auto)}catch(e){pkskReportError('C_RESULT',e.stack||e);fallbackC(auto)}};
function fallbackC(auto){try{if(typeof interval!=='undefined')clearInterval(interval);if(typeof winterval!=='undefined')clearInterval(winterval);if(typeof phase!=='undefined')phase='done';const q=Array.isArray(window.qs)?window.qs:[],a=answers(),A=q.filter(x=>x.section==='BAHAGIAN A'),B=q.filter(x=>x.section==='BAHAGIAN B'),am=A.reduce((s,x)=>s+(Array.isArray(x.weights)&&x.weights.length?Math.max(...x.weights):0),0),as=A.reduce((s,x)=>{const w=x.weights||[],v=a[x.id];return s+(v==null?0:Number(w[v]||0))},0),ap=am?Math.round(as/am*100):0,bc=B.filter(x=>a[x.id]!=null&&Number(a[x.id])===Number(x.answer)).length,bp=B.length?Math.round(bc/B.length*100):0,c=rubric(essay()),set=Number(window.setNo||1);if(typeof window.show==='function')window.show('result');const sum=$('summary');if(sum)sum.innerHTML=[["Bahagian A",ap+'%'],["Bahagian B",bc+'/'+B.length],["Bahagian C",c.total+'/20'],["Perkataan",c.words],["Set",'Set '+String(set).padStart(2,'0')],["Status",auto?'Masa tamat':'Dihantar']].map(x=>`<div class="stat"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');const con=$('conclusion');if(con)con.textContent=c.words<100?'Karangan belum mencapai 100 patah perkataan. Latih isi, huraian dan contoh sebelum ke set seterusnya.':(bp<70?'Semak semula jawapan Bahagian B yang salah dan ulang topik yang lemah.':'Teruskan ke set berikutnya dan kekalkan pengurusan masa.');syncProgressServer(bp,{scoreA:ap,scoreB:bp,bCorrect:bc,aAnswered:A.filter(x=>a[x.id]!=null).length,bAnswered:B.filter(x=>a[x.id]!=null).length,timeUsed:0,completed:true})}catch(e){pkskReportError('C_FALLBACK',e.stack||e);const m=$('minStatus');if(m)m.textContent='Ralat laporan. Sila refresh dan cuba sekali lagi.'}}
const st=document.createElement('style');st.id='v58-style';st.textContent='.v58-start-btn{display:inline-flex;align-items:center;justify-content:center;min-width:270px;border:0;border-radius:14px;padding:16px 24px;background:linear-gradient(135deg,#123f67,#178f8a);color:#fff;font-size:15px;font-weight:900;cursor:pointer;box-shadow:0 10px 24px rgba(18,63,103,.25)}.v58-start-btn:disabled{opacity:.65}.mic,.voice-status{display:none!important}';document.head.appendChild(st);
})();