/* V63 CANONICAL SCORE BRIDGE: completed score is server-authoritative. */
(function(){
'use strict';
function currentSet(){try{const q=Number(new URLSearchParams(location.search).get('set')||0);if(q>=1&&q<=50)return q;const n=Number(localStorage.getItem('pksk-selected-set')||1);return n>=1&&n<=50?n:1}catch(_){return 1}}
function snapshot(){const setNo=currentSet(),n=String(setNo).padStart(2,'0');let answers={},essayText='';try{const s=JSON.parse(localStorage.getItem(`pksk-set${n}-session`)||'null');answers=s&&s.answers||{};const w=JSON.parse(localStorage.getItem(`pksk-set${n}-writing`)||'null');essayText=w&&typeof w.text==='string'?w.text:''}catch(_){ }return{setNo,answers,essayText}}
window.__pkskFinalSnapshot=window.__pkskFinalSnapshot||null;
const wrap=()=>{if(window.__v63FinishWrapped||typeof window.finishWriting!=='function')return;const original=window.finishWriting;window.finishWriting=function(auto){window.__pkskFinalSnapshot=snapshot();return original.call(this,auto)};window.__v63FinishWrapped=true};wrap();setTimeout(wrap,100);setTimeout(wrap,500);
window.syncProgressServer=function(_score,extra){const code=typeof pkskLicense==='function'?pkskLicense():'';if(!code)return;const snap=window.__pkskFinalSnapshot||snapshot(),payload={action:'scoreAndSave',code,deviceId:typeof pkskDeviceId==='function'?pkskDeviceId():'',setNo:snap.setNo,answers:snap.answers,essayText:snap.essayText,timeUsed:extra&&extra.timeUsed||0,startedAt:null};fetch('/api/pksk-score',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store'}).then(r=>r.json()).then(r=>{if(!r||!r.ok){if(typeof pkskReportError==='function')pkskReportError('CANONICAL_SCORE_FAILED',r&&r.error||'Skor server gagal');return}window.__canonicalResult=r;const summary=document.getElementById('summary');if(summary)summary.querySelectorAll('.stat').forEach(el=>{const label=el.querySelector('span')?.textContent||'',b=el.querySelector('b');if(!b)return;if(label==='A indeks keseluruhan')b.textContent=r.scoreA+'%';if(label==='B betul')b.textContent=r.bCorrect+'/70';if(label==='B ketepatan')b.textContent=r.scoreB+'%'});try{localStorage.setItem('pksk-last-server-sync',new Date().toISOString())}catch(_){ }}).catch(e=>{if(typeof pkskReportError==='function')pkskReportError('CANONICAL_SCORE_FAILED',e.message||e)})};
function refreshReview(){const snap=window.__pkskFinalSnapshot;if(!snap)return;const groupStart=Math.floor((snap.setNo-1)/10)*10+1,groupEnd=groupStart+9,group=`SET ${String(groupStart).padStart(2,'0')}-${String(groupEnd).padStart(2,'0')}`;fetch(`sets/${encodeURIComponent(group)}/data/set${String(snap.setNo).padStart(2,'0')}.json`,{cache:'no-store'}).then(r=>r.json()).then(bank=>{const qs=bank.questions||[],b=qs.filter(q=>q.section==='BAHAGIAN B'),canonical=q=>{if(Number.isInteger(Number(q.answerIndex)))return Number(q.answerIndex);if(Number.isInteger(Number(q.answer)))return Number(q.answer);if(Array.isArray(q.weights)&&q.weights.length)return q.weights.reduce((best,v,i)=>Number(v)>Number(q.weights[best]??-Infinity)?i:best,0);return null};const box=document.getElementById('reviewB');if(!box)return;box.innerHTML='<div class="review-list">'+b.map((q,i)=>{const a=snap.answers[q.id],correct=canonical(q),status=a===undefined?'skip':(Number(a)===correct?'good':'bad'),label=status==='good'?'✓ BETUL':status==='bad'?'✕ SALAH':'○ TIDAK DIJAWAB',your=a===undefined?'—':`${String.fromCharCode(65+Number(a))}. ${escapeHtml(q.options?.[Number(a)]||'')}`,right=correct===null?'—':`${String.fromCharCode(65+correct)}. ${escapeHtml(q.options?.[correct]||'')}`,ex=escapeHtml(q.explanation||q.scoringNote||'Semak sebab jawapan ini paling tepat.');return `<article class="review-item ${status}"><div class="review-top"><b>${i+1}. ${escapeHtml(q.question||'')}</b><strong>${label}</strong></div><div class="review-answer"><span><b>Jawapan anda:</b> ${your}</span><span><b>Jawapan betul:</b> ${right}</span></div><div class="review-explain"><b>Penerangan:</b> ${ex}</div></article>`}).join('')+'</div>'}).catch(()=>{});}
const oldBuild=window.buildResult;if(typeof oldBuild==='function'&&!window.__v63BuildWrapped){window.buildResult=function(c){const r=oldBuild.call(this,c);setTimeout(refreshReview,50);return r};window.__v63BuildWrapped=true}
})();