(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const money=n=>'RM'+Number(n||0).toFixed(2);
  let cfg={},products=[],docs=[],editId=null,images=[],variations=[],addons=[],customs=[];
  const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
  const save=()=>{localStorage.setItem('reqoo_admin_products',JSON.stringify(products));localStorage.setItem('reqoo_docs',JSON.stringify(docs));};
  const safe=(v,f)=>{try{return Array.isArray(v)?v:(JSON.parse(v||'null')||f)}catch{return f}};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const api=()=>((cfg.apiUrl||'https://api.reqoo.co').replace(/\/$/,''));
  async function req(path,opt={}){const h={...(opt.headers||{}),'X-Admin-Key':cfg.adminKey||''};if(!(opt.body instanceof FormData))h['content-type']='application/json';const r=await fetch(api()+path,{...opt,headers:h});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||('HTTP '+r.status));return j}
  function status(msg){let x=$('#builderStatus');if(!x){x=document.createElement('div');x.id='builderStatus';x.className='notice';$('#productForm')?.prepend(x)}x.textContent=msg}
  function reset(){editId=null;images=[];variations=[];addons=[];customs=[];['pName','pCategory','pMaterial','pSku','pDesc'].forEach(id=>{const x=$('#'+id);if(x)x.value=''});const f=$('#pImages');if(f)f.value='';const s=$('#uploadStatus');if(s)s.textContent='Maksimum 8 gambar.';renderBuilder()}
  function renderBuilder(){
    const p=$('#imagePreview');if(p)p.innerHTML=images.length?images.map((u,i)=>`<div class="image-item"><img src="${esc(u)}" alt=""><button type="button" data-remove-image="${i}">×</button>${i?'':'<small>Cover</small>'}</div>`).join(''):'<div class="muted">Belum ada gambar.</div>';
    const v=$('#variationList');if(v)v.innerHTML=variations.length?variations.map((x,i)=>`<div class="builder-row"><input class="input" data-v-name="${i}" value="${esc(x.name)}" placeholder="Nama variation"><label class="check"><input type="checkbox" data-v-required="${i}" ${x.required?'checked':''}> Wajib</label><button type="button" class="button small danger" data-remove-v="${i}">Padam</button><div class="option-list">${(x.options||[]).map((o,j)=>`<div class="option-row"><input class="input" data-v-opt="${i}:${j}" value="${esc(o.name)}" placeholder="A5"><input class="input" type="number" min="0" step="0.01" data-v-price="${i}:${j}" value="${Number(o.price||0)}" placeholder="30"><button type="button" class="button small danger" data-remove-opt="${i}:${j}">×</button></div>`).join('')}<button type="button" class="button small" data-add-opt="${i}">+ Pilihan</button></div></div>`).join(''):'<div class="muted">Tiada variation. Tambah jika produk ada pilihan seperti saiz.</div>';
    const a=$('#addonList');if(a)a.innerHTML=addons.length?addons.map((x,i)=>`<div class="builder-row option-row"><input class="input" data-a-name="${i}" value="${esc(x.name)}" placeholder="Contoh: Jam"><input class="input" type="number" min="0" step="0.01" data-a-price="${i}" value="${Number(x.price||0)}" placeholder="15"><label class="check"><input type="checkbox" data-a-required="${i}" ${x.required?'checked':''}> Wajib</label><button type="button" class="button small danger" data-remove-a="${i}">×</button></div>`).join(''):'<div class="muted">Tiada add-on.</div>';
    const c=$('#customList');if(c)c.innerHTML=customs.length?customs.map((x,i)=>`<div class="builder-row option-row"><input class="input" data-c-name="${i}" value="${esc(x.name)}" placeholder="Nama / Ayat / Tarikh"><select class="input" data-c-type="${i}"><option value="text" ${x.type==='text'?'selected':''}>Text</option><option value="number" ${x.type==='number'?'selected':''}>Nombor</option><option value="date" ${x.type==='date'?'selected':''}>Tarikh</option></select><label class="check"><input type="checkbox" data-c-required="${i}" ${x.required?'checked':''}> Wajib</label><button type="button" class="button small danger" data-remove-c="${i}">×</button></div>`).join(''):'<div class="muted">Tiada ruang custom.</div>';
  }
  function sync(){
    $$('[data-v-name]').forEach(x=>variations[x.dataset.vName]&&(variations[x.dataset.vName].name=x.value));$$('[data-v-required]').forEach(x=>variations[x.dataset.vRequired]&&(variations[x.dataset.vRequired].required=x.checked));
    $$('[data-v-opt]').forEach(x=>{const[i,j]=x.dataset.vOpt.split(':');if(variations[i]?.options[j])variations[i].options[j].name=x.value});$$('[data-v-price]').forEach(x=>{const[i,j]=x.dataset.vPrice.split(':');if(variations[i]?.options[j])variations[i].options[j].price=Number(x.value||0)});
    $$('[data-a-name]').forEach(x=>addons[x.dataset.aName]&&(addons[x.dataset.aName].name=x.value));$$('[data-a-price]').forEach(x=>addons[x.dataset.aPrice]&&(addons[x.dataset.aPrice].price=Number(x.value||0)));$$('[data-a-required]').forEach(x=>addons[x.dataset.aRequired]&&(addons[x.dataset.aRequired].required=x.checked));
    $$('[data-c-name]').forEach(x=>customs[x.dataset.cName]&&(customs[x.dataset.cName].name=x.value));$$('[data-c-type]').forEach(x=>customs[x.dataset.cType]&&(customs[x.dataset.cType].type=x.value));$$('[data-c-required]').forEach(x=>customs[x.dataset.cRequired]&&(customs[x.dataset.cRequired].required=x.checked));
  }
  function renderProducts(){const l=$('#productList');if(!l)return;l.innerHTML=products.length?`<table class="table"><thead><tr><th>Produk</th><th>Harga/Variation</th><th></th></tr></thead><tbody>${products.map(p=>`<tr><td>${p.image?`<img src="${esc(p.image)}" style="width:46px;height:46px;object-fit:cover;border-radius:8px;vertical-align:middle;margin-right:8px">`:''}<b>${esc(p.name)}</b></td><td>${p.options?.length?p.options.length+' pilihan':money(p.price)}</td><td><button type="button" class="button small" data-edit="${esc(p.id)}">Edit</button> <button type="button" class="button small danger" data-del="${esc(p.id)}">Padam</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">Belum ada produk.</div>';if($('#statProducts'))$('#statProducts').textContent=products.length}
  function renderDocs(){['quotation','invoice','receipt'].forEach(t=>{const l=$('#'+t+'List');if(!l)return;const r=docs.filter(d=>d.type===t);l.innerHTML=r.length?r.map(d=>`<div class="doc-row"><div><b>${esc(d.number)}</b><div class="muted">${esc(d.customer)} · ${money(d.total)}</div></div><span>${esc(d.status)}</span><button type="button" class="button small" data-print="${esc(d.id)}">Cetak</button></div>`).join(''):'<div class="empty">Belum ada dokumen.</div>';const s=$('#stat'+t[0].toUpperCase()+t.slice(1));if(s)s.textContent=r.length})}
  function tab(t){$$('.panel').forEach(x=>x.classList.add('hidden'));$('#'+t)?.classList.remove('hidden');$$('.side-btn').forEach(x=>x.classList.toggle('active',x.dataset.tab===t))}
  async function upload(list){for(const f of [...list].slice(0,8-images.length)){if(!f.type.startsWith('image/')){status('Fail bukan gambar: '+f.name);continue}if(f.size>10*1024*1024){status('Gambar melebihi 10MB: '+f.name);continue}try{const s=$('#uploadStatus');if(s)s.textContent='Uploading '+f.name+'...';const fd=new FormData();fd.append('file',f);const j=await req('/api/admin/media',{method:'POST',body:fd});if(!j.url)throw Error('URL gambar tiada');images.push(j.url);renderBuilder()}catch(e){status('Upload gagal: '+e.message)}}const s=$('#uploadStatus');if(s)s.textContent=images.length+' gambar dimuat naik.'}
  async function saveProduct(){sync();const p={id:editId||crypto.randomUUID(),name:($('#pName')?.value||'').trim(),category:($('#pCategory')?.value||'').trim(),material:($('#pMaterial')?.value||'').trim(),sku:($('#pSku')?.value||'').trim(),description:($('#pDesc')?.value||'').trim(),price:0,image:images[0]||'',images,options:[...variations.map(x=>({type:'variation',...x})),...addons.map(x=>({type:'addon',...x})),...customs.map(x=>({type:'custom',...x}))],active:true};if(!p.name){status('Isi nama produk.');return}if(variations.some(v=>!v.name||!v.options.length||v.options.some(o=>!o.name||o.price<0))){status('Semak variation dan harga.');return}try{await req('/api/admin/products',{method:'POST',body:JSON.stringify(p)});status('Produk berjaya disimpan.')}catch(e){status('Simpan gagal: '+e.message);return}products=[p,...products.filter(x=>x.id!==p.id)];save();renderProducts();$('#productForm')?.classList.add('hidden');reset()}
  async function load(){try{const j=await req('/api/admin/products');products=j.products||[];products.forEach(p=>{p.images=safe(p.images,p.image?[p.image]:[]);p.options=safe(p.options,[])});save()}catch(e){status('API gagal: '+e.message+' — butang UI kekal aktif.')}renderProducts()}
  async function doc(t){const customer=prompt('Nama pelanggan?');if(!customer)return;const total=Number(prompt('Jumlah (RM)?','0')||0);const d={id:crypto.randomUUID(),type:t,number:t.toUpperCase().slice(0,3)+'-'+Date.now().toString().slice(-6),customer,email:'',items:[],total,status:'draft',created_at:new Date().toISOString()};docs.unshift(d);save();try{await req('/api/admin/documents',{method:'POST',body:JSON.stringify(d)})}catch{}renderDocs()}
  function print(id){const d=docs.find(x=>x.id===id);if(!d)return;const w=window.open('','_blank');if(!w){alert('Popup disekat browser.');return}w.document.write(`<html><body style="font-family:Arial;padding:40px"><h1>AB ART TRADING</h1><p>${esc(d.type.toUpperCase())}: <b>${esc(d.number)}</b></p><p>Pelanggan: ${esc(d.customer)}</p><h2>${money(d.total)}</h2><button onclick="print()">Print</button></body></html>`);w.document.close()}
  function bind(){
    cfg=read('reqoo_admin_cfg',{});products=read('reqoo_admin_products',[]);docs=read('reqoo_docs',[]);renderBuilder();renderProducts();renderDocs();
    document.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;
      if(b.classList.contains('side-btn')){e.preventDefault();tab(b.dataset.tab);return} if(b.id==='newProduct'){e.preventDefault();reset();$('#productForm')?.classList.remove('hidden');tab('products');return} if(b.id==='cancelProduct'){e.preventDefault();$('#productForm')?.classList.add('hidden');reset();return}
      if(b.id==='addVariation'){e.preventDefault();sync();variations.push({name:'Saiz',required:true,options:[{name:'A5',price:0}]});renderBuilder();return} if(b.id==='addAddon'){e.preventDefault();sync();addons.push({name:'Add-on',price:0,required:false});renderBuilder();return} if(b.id==='addCustom'){e.preventDefault();sync();customs.push({name:'Nama',type:'text',required:true});renderBuilder();return} if(b.id==='saveProduct'){e.preventDefault();await saveProduct();return}
      if(b.dataset.removeImage!==undefined){e.preventDefault();images.splice(+b.dataset.removeImage,1);renderBuilder();return} if(b.dataset.removeV!==undefined){e.preventDefault();sync();variations.splice(+b.dataset.removeV,1);renderBuilder();return} if(b.dataset.addOpt!==undefined){e.preventDefault();sync();variations[+b.dataset.addOpt].options.push({name:'Pilihan',price:0});renderBuilder();return} if(b.dataset.removeOpt!==undefined){e.preventDefault();sync();const[i,j]=b.dataset.removeOpt.split(':');variations[i].options.splice(+j,1);renderBuilder();return} if(b.dataset.removeA!==undefined){e.preventDefault();sync();addons.splice(+b.dataset.removeA,1);renderBuilder();return} if(b.dataset.removeC!==undefined){e.preventDefault();sync();customs.splice(+b.dataset.removeC,1);renderBuilder();return}
      if(b.dataset.edit!==undefined){e.preventDefault();const p=products.find(x=>String(x.id)===String(b.dataset.edit));if(!p)return;editId=p.id;images=safe(p.images,p.image?[p.image]:[]);const o=safe(p.options,[]);variations=o.filter(x=>x.type==='variation').map(({type,...x})=>x);addons=o.filter(x=>x.type==='addon').map(({type,...x})=>x);customs=o.filter(x=>x.type==='custom').map(({type,...x})=>x);[['pName',p.name],['pCategory',p.category],['pMaterial',p.material],['pSku',p.sku],['pDesc',p.description]].forEach(([id,v])=>{if($('#'+id))$('#'+id).value=v||''});renderBuilder();$('#productForm')?.classList.remove('hidden');tab('products');return}
      if(b.dataset.del!==undefined){e.preventDefault();const id=b.dataset.del;products=products.filter(x=>String(x.id)!==String(id));save();try{await req('/api/admin/products/'+encodeURIComponent(id),{method:'DELETE'})}catch{}renderProducts();return} if(b.dataset.doc){e.preventDefault();await doc(b.dataset.doc);return} if(b.dataset.print){e.preventDefault();print(b.dataset.print);return}
      if(b.id==='saveSettings'){e.preventDefault();cfg={apiUrl:($('#apiUrl')?.value||'').trim(),adminKey:$('#adminKey')?.value||'',qrUrl:($('#qrUrl')?.value||'').trim()};localStorage.setItem('reqoo_admin_cfg',JSON.stringify(cfg));try{await req('/api/admin/settings',{method:'POST',body:JSON.stringify({qr_url:cfg.qrUrl||''})});status('Tetapan disimpan ke server.')}catch{status('Tetapan disimpan pada browser.')}return}
    },false);
    document.addEventListener('change',e=>{if(e.target?.id==='pImages')upload(e.target.files)},false);
    document.addEventListener('submit',e=>e.preventDefault(),false);
    load();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
