(()=>{
'use strict';
const API='/api/shop-admin',TOKEN_KEY='reqoo_admin_token';
let customers=[],orders=[],rows=[];
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const token=()=>localStorage.getItem(TOKEN_KEY)||'';
const money=n=>'RM'+(Number(n||0)/100).toFixed(2);
function toast(msg,err=false){const el=$('customerToast');el.textContent=msg;el.className='rqCustomerToast show'+(err?' err':'');clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='rqCustomerToast',2400)}
async function api(action,extra={}){const u=new URL(API,location.origin);u.searchParams.set('action',action);Object.entries(extra).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,v)});const r=await fetch(u,{headers:{'X-Admin-Token':token()},cache:'no-store'});let d={};try{d=await r.json()}catch{}if(r.status===401){location.href='/admin/?return='+encodeURIComponent(location.pathname);throw Error('Sesi Admin tamat.')}if(!r.ok||!d.ok)throw Error(d.error||'Request gagal');return d}
function orderCustomerId(o){return o.customer_id||o.customerId||''}
function orderPhone(o){return String(o.phone||o.customer_phone||o.customerPhone||'').replace(/\D/g,'')}
function orderEmail(o){return String(o.email||o.customer_email||o.customerEmail||'').toLowerCase()}
function customerPhone(c){return String(c.phone||'').replace(/\D/g,'')}
function customerEmail(c){return String(c.email||'').toLowerCase()}
function totalMinor(o){if(o.total_minor!=null)return Number(o.total_minor||0);if(o.totalMinor!=null)return Number(o.totalMinor||0);return Math.round(Number(o.total||0)*100)}
function paid(o){return String(o.payment_status||o.paymentStatus||o.payment||'').toLowerCase()==='paid'}
function created(o){return o.created_at||o.createdAt||o.timestamp||''}
function buildRows(){rows=customers.map(c=>{const match=orders.filter(o=>String(orderCustomerId(o))===String(c.id)||(customerPhone(c)&&orderPhone(o)===customerPhone(c))||(customerEmail(c)&&orderEmail(o)===customerEmail(c)));const paidOrders=match.filter(paid);const spend=paidOrders.reduce((a,o)=>a+totalMinor(o),0);const last=match.map(created).filter(Boolean).sort().reverse()[0]||c.updated_at||c.created_at||'';return{c,orders:match,paidOrders,spend,last}})}
function fmtDate(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('ms-MY',{day:'2-digit',month:'short',year:'numeric'})}
function waNumber(v){let n=String(v||'').replace(/\D/g,'');if(n.startsWith('0'))n='60'+n.slice(1);return n}
function renderStats(){const repeat=rows.filter(x=>x.orders.length>1).length,revenue=rows.reduce((a,x)=>a+x.spend,0);$('statCustomers').textContent=rows.length;$('statRepeat').textContent=repeat;$('statRevenue').textContent=money(revenue);$('statAov').textContent=money(rows.length?Math.round(revenue/rows.length):0)}
function render(){const q=$('customerSearch').value.trim().toLowerCase(),sort=$('customerSort').value;let list=rows.filter(x=>!q||[x.c.name,x.c.phone,x.c.email].join(' ').toLowerCase().includes(q));if(sort==='spend')list.sort((a,b)=>b.spend-a.spend);else if(sort==='orders')list.sort((a,b)=>b.orders.length-a.orders.length);else if(sort==='name')list.sort((a,b)=>String(a.c.name||'').localeCompare(String(b.c.name||'')));else list.sort((a,b)=>String(b.last).localeCompare(String(a.last)));$('customerList').innerHTML=list.map((x,i)=>`<article class="rqCustomerRow" data-customer="${esc(x.c.id||String(i))}"><div class="rqCustomerName"><b>${esc(x.c.name||'Tanpa nama')}</b><span>${esc(x.c.phone||'Tiada telefon')}${x.c.email?` · ${esc(x.c.email)}`:''}</span></div><div class="rqCustomerMetric">${x.orders.length} order</div><div class="rqCustomerMetric hideMobile">${money(x.spend)}</div><div class="hideTablet"><span class="rqCustomerBadge ${x.orders.length>1?'repeat':''}">${x.orders.length>1?'REPEAT':'NEW'}</span></div><div class="rqCustomerOpen"><span class="rqCustomerMeta">${fmtDate(x.last)}</span></div></article>`).join('')||'<div class="rqCustomerState">Tiada pelanggan dijumpai.</div>';document.querySelectorAll('[data-customer]').forEach(el=>el.addEventListener('click',()=>openCustomer(el.dataset.customer)))}
function openCustomer(id){const x=rows.find(r=>String(r.c.id)===String(id))||rows.find((r,i)=>String(i)===String(id));if(!x)return;const c=x.c,n=waNumber(c.phone);$('drawerTitle').textContent=c.name||'Customer';$('drawerBody').innerHTML=`<section class="rqCustomerProfile"><div class="rqCustomerMeta">${esc(c.phone||'Tiada telefon')}${c.email?` · ${esc(c.email)}`:''}</div><div class="rqCustomerProfileGrid"><div class="rqCustomerMini"><span>TOTAL ORDERS</span><b>${x.orders.length}</b></div><div class="rqCustomerMini"><span>PAID ORDERS</span><b>${x.paidOrders.length}</b></div><div class="rqCustomerMini"><span>PAID VALUE</span><b>${money(x.spend)}</b></div><div class="rqCustomerMini"><span>LAST ORDER</span><b>${fmtDate(x.last)}</b></div></div><div class="rqCustomerActions">${n?`<button class="btn primary" id="waCustomer">WhatsApp Customer</button>`:''}<a class="btn" href="/shop/admin.html#orders">Buka Orders</a></div></section><section class="rqCustomerOrders"><h3>Order History</h3>${x.orders.sort((a,b)=>String(created(b)).localeCompare(String(created(a)))).map(o=>`<div class="rqCustomerOrder"><div><b>${esc(o.order_no||o.orderNo||o.order_ref||o.id||'Order')}</b><span class="rqCustomerMeta">${fmtDate(created(o))}</span></div><div>${money(totalMinor(o))}</div><div class="rqCustomerStatus ${paid(o)?'paid':'pending'}">${paid(o)?'PAID':'PENDING'}</div></div>`).join('')||'<div class="rqCustomerState">Belum ada order.</div>'}</section>`;$('customerDrawer').classList.add('open');$('customerDrawer').setAttribute('aria-hidden','false');if(n)$('waCustomer').addEventListener('click',()=>window.open('https://wa.me/'+n,'_blank','noopener'))}
function closeDrawer(){$('customerDrawer').classList.remove('open');$('customerDrawer').setAttribute('aria-hidden','true')}
async function load(){try{$('customerState').textContent='Memuatkan pelanggan…';const [c,o]=await Promise.all([api('listCustomers'),api('listOrders',{limit:500})]);customers=Array.isArray(c.customers)?c.customers:[];orders=Array.isArray(o.orders)?o.orders:[];buildRows();renderStats();render();$('customerState').textContent=rows.length?'':'Belum ada pelanggan.'}catch(e){$('customerState').textContent=e.message;toast(e.message,true)}}
$('refreshCustomers').addEventListener('click',load);$('customerSearch').addEventListener('input',render);$('customerSort').addEventListener('change',render);$('drawerClose').addEventListener('click',closeDrawer);$('customerDrawer').addEventListener('click',e=>{if(e.target.id==='customerDrawer')closeDrawer()});if(!token())location.href='/admin/?return='+encodeURIComponent(location.pathname);else load();
})();
