(()=>{
'use strict';
const API='/api/shop-admin';
let rows=[],stats={customers:0,repeatCustomers:0,collectedMinor:0,outstandingMinor:0},loadSeq=0,detailSeq=0,currentCustomerId='',activeTab='activity',detailSearchTimer=0;
let tabState={orders:freshTab(),documents:freshTab(),payments:freshTab()};
const deepParams=new URLSearchParams(location.search),initialCustomer=deepParams.get('customer')||'',initialCustomerQuery=deepParams.get('q')||'';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'RM'+(Number(n||0)/100).toFixed(2),normPhone=v=>String(v||'').replace(/\D/g,'');
function freshTab(){return{items:[],offset:0,hasMore:false,loaded:false,seq:0,query:''}}
function resetTabs(){tabState={orders:freshTab(),documents:freshTab(),payments:freshTab()}}
function toast(msg,err=false){const el=$('customerToast');el.textContent=msg;el.className='rqCustomerToast show'+(err?' err':'');clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='rqCustomerToast',2400)}
async function api(action,extra={}){const u=new URL(API,location.origin);u.searchParams.set('action',action);Object.entries(extra).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,v)});const r=await fetch(u,{cache:'no-store'});let d={};try{d=await r.json()}catch{}if(r.status===401){location.href='/admin/?return='+encodeURIComponent(location.pathname+location.search);throw Error('Sesi Admin tamat.')}if(!r.ok||!d.ok)throw Error(d.error||'Request gagal');return d}
function fmtDate(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('ms-MY',{day:'2-digit',month:'short',year:'numeric'})}
function fmtDateTime(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('ms-MY',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function waNumber(v){let n=normPhone(v);if(n.startsWith('0'))n='60'+n.slice(1);return n}
function typeLabel(t){return({quotation:'Quotation',invoice:'Invoice',receipt:'Receipt',delivery_order:'Delivery Order',order:'Order',payment:'Payment'})[t]||'Document'}
function typeCode(t){return({quotation:'QT',invoice:'INV',receipt:'RC',delivery_order:'DO',order:'OR',payment:'PAY'})[t]||'DOC'}
function renderStats(){const total=Number(stats.customers||0),collected=Number(stats.collectedMinor||0);$('statCustomers').textContent=total;$('statRepeat').textContent=Number(stats.repeatCustomers||0);$('statRevenue').textContent=money(collected);$('statOutstanding').textContent=money(stats.outstandingMinor||0);$('statAov').textContent=money(total?Math.round(collected/total):0)}
function render(){const list=rows;$('customerList').innerHTML=list.map(x=>`<article class="rqCustomerRow" data-customer="${esc(x.id)}" tabindex="0"><div class="rqCustomerName"><b>${esc(x.name||'Tanpa nama')}</b><span>${esc(x.phone||'Tiada telefon')}${x.email?` · ${esc(x.email)}`:''}</span></div><div class="rqCustomerMetric">${Number(x.order_count||0)} order</div><div class="rqCustomerMetric hideMobile">${money(x.collected_minor||0)}</div><div class="hideTablet"><span class="rqCustomerBadge ${Number(x.outstanding_minor||0)>0?'owes':Number(x.order_count||0)>1?'repeat':''}">${Number(x.outstanding_minor||0)>0?`DUE ${money(x.outstanding_minor)}`:Number(x.order_count||0)>1?'REPEAT':'NEW'}</span></div><div class="rqCustomerOpen"><span class="rqCustomerMeta">${fmtDate(x.last_activity||x.updated_at||x.created_at)}</span></div></article>`).join('')||'<div class="rqCustomerState">Tiada pelanggan dijumpai.</div>';document.querySelectorAll('[data-customer]').forEach(el=>{el.addEventListener('click',()=>openCustomer(el.dataset.customer));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openCustomer(el.dataset.customer)}})})}
function renderActivity(activity=[]){if(!activity.length)return'<div class="rqCustomerEmpty">Belum ada aktiviti.</div>';return activity.map(v=>`<div class="rqCrmEvent"><span class="rqCrmDot ${esc(v.kind||'document')}"></span><div><b>${esc(typeLabel(v.kind))} · ${esc(v.title||'')}</b><span>${fmtDateTime(v.date)}${v.method?` · ${esc(v.method)}`:''}</span></div><div class="rqCrmEventSide">${v.amountMinor?money(v.amountMinor):''}<small>${esc(v.status||'')}</small></div></div>`).join('')}
function renderRecordItems(type,items=[]){
 if(!items.length)return'<div class="rqCustomerEmpty">Tiada rekod dijumpai.</div>';
 if(type==='documents')return items.map(d=>`<div class="rqCrmDoc"><span class="rqCrmDocCode">${esc(typeCode(d.type))}</span><div><a class="rqCrmRecordLink" href="/admin/documents.html?order=${encodeURIComponent(d.order_id||'')}"><b>${esc(d.number||typeLabel(d.type))}</b></a><span>${esc(typeLabel(d.type))} · ${fmtDate(d.issued_at||d.created_at)}</span></div><div class="rqCrmDocAmount">${d.total_minor!=null?money(d.total_minor):''}</div></div>`).join('');
 if(type==='payments')return items.map(p=>`<div class="rqCrmPayment"><div><b>${esc(p.receipt_number||'Payment')}</b><span>${fmtDateTime(p.paid_at||p.created_at)}${p.method?` · ${esc(p.method)}`:''}${p.invoice_number?` · ${esc(p.invoice_number)}`:''}</span></div><strong>${money(p.amount_minor)}</strong></div>`).join('');
 return items.map(o=>{const balance=Number(o.balanceMinor||0),status=String(o.paymentStatus||o.payment_status||'pending').toLowerCase(),isPaid=balance<=0&&status==='paid';return`<div class="rqCustomerOrder"><div><a class="rqCustomerOrderLink" href="/admin/orders.html?order=${encodeURIComponent(o.id||o.order_no||'')}"><b>${esc(o.order_no||o.id||'Order')}</b></a><span class="rqCustomerMeta">${fmtDate(o.created_at)}</span></div><div>${money(o.totalMinor??o.total_minor??0)}${balance>0?`<small class="rqOrderBalance">Balance ${money(balance)}</small>`:''}</div><div class="rqCustomerStatus ${isPaid?'paid':'pending'}">${balance>0?'OUTSTANDING':isPaid?'PAID':esc(status.toUpperCase())}</div></div>`}).join('')
}
function renderTab(type){const s=tabState[type],host=document.querySelector(`[data-crm-records="${type}"]`),more=document.querySelector(`[data-crm-more="${type}"]`),state=document.querySelector(`[data-crm-state="${type}"]`);if(!host)return;host.innerHTML=renderRecordItems(type,s.items);if(state)state.textContent=s.loaded?`${s.items.length} rekod dimuat`:'Belum dimuat';if(more){more.hidden=!s.hasMore;more.disabled=false;more.textContent='Load More'}}
async function loadRecords(type,reset=true){if(!currentCustomerId||!tabState[type])return;const s=tabState[type],seq=++s.seq,q=($('customerDetailSearch')?.value||'').trim();if(reset){s.items=[];s.offset=0;s.query=q;renderTab(type)}const state=document.querySelector(`[data-crm-state="${type}"]`);if(state)state.textContent=reset?'Memuatkan…':'Memuatkan lagi…';try{const d=await api('customerRecords',{customerId:currentCustomerId,type,q,limit:40,offset:s.offset});if(seq!==s.seq)return;const batch=Array.isArray(d.records)?d.records:[],seen=new Set(s.items.map(x=>String(x.id)));for(const x of batch)if(!seen.has(String(x.id))){s.items.push(x);seen.add(String(x.id))}s.offset=Number(d.offset||0)+batch.length;s.hasMore=!!d.hasMore;s.loaded=true;renderTab(type)}catch(e){if(seq!==s.seq)return;if(state)state.textContent=e.message;toast(e.message,true)}}
function bindDrawerControls(){
 document.querySelectorAll('[data-crm-tab]').forEach(b=>b.addEventListener('click',()=>{activeTab=b.dataset.crmTab;document.querySelectorAll('[data-crm-tab]').forEach(v=>v.classList.toggle('active',v===b));document.querySelectorAll('[data-crm-pane]').forEach(p=>p.classList.toggle('active',p.dataset.crmPane===activeTab));const search=$('customerDetailSearch');if(search)search.hidden=activeTab==='activity';if(activeTab!=='activity'&&!tabState[activeTab].loaded)loadRecords(activeTab,true)}));
 document.querySelectorAll('[data-crm-more]').forEach(b=>b.addEventListener('click',()=>loadRecords(b.dataset.crmMore,false)));
 const search=$('customerDetailSearch');if(search)search.addEventListener('input',()=>{if(activeTab==='activity')return;clearTimeout(detailSearchTimer);detailSearchTimer=setTimeout(()=>loadRecords(activeTab,true),260)})
}
function renderDrawer(x){const c=x.customer,n=waNumber(c.phone),s=x.summary||{};$('drawerTitle').textContent=c.name||'Customer';$('drawerBody').innerHTML=`<section class="rqCustomerProfile"><div class="rqCustomerMeta">${esc(c.phone||'Tiada telefon')}${c.email?` · ${esc(c.email)}`:''}</div><div class="rqCustomerProfileGrid crm"><div class="rqCustomerMini"><span>LIFETIME COLLECTED</span><b>${money(s.collectedMinor||0)}</b></div><div class="rqCustomerMini due"><span>OUTSTANDING</span><b>${money(s.outstandingMinor||0)}</b></div><div class="rqCustomerMini"><span>TOTAL ORDERS</span><b>${Number(s.orderCount||0)}</b></div><div class="rqCustomerMini"><span>DOCUMENTS</span><b>${Number(s.documentCount||0)}</b></div><div class="rqCustomerMini"><span>QUOTATIONS</span><b>${Number(s.quotationCount||0)}</b></div><div class="rqCustomerMini"><span>RECEIPTS</span><b>${Number(s.receiptCount||0)}</b></div></div><div class="rqCustomerActions">${n?'<button class="btn primary" id="waCustomer">WhatsApp Customer</button>':''}<a class="btn" href="/admin/documents.html?q=${encodeURIComponent(c.phone||c.email||c.name||'')}">Documents</a><a class="btn" href="/admin/orders.html?q=${encodeURIComponent(c.phone||c.email||c.name||'')}">Orders</a></div></section><div class="rqCrmTabs"><button class="active" data-crm-tab="activity">Activity</button><button data-crm-tab="documents">Documents</button><button data-crm-tab="payments">Payments</button><button data-crm-tab="orders">Orders</button></div><div class="rqCrmDetailSearch"><input id="customerDetailSearch" hidden placeholder="Cari dalam tab customer"></div><section class="rqCrmPane active" data-crm-pane="activity"><h3>Recent Customer Timeline</h3><div class="rqCrmPaneState">30 aktiviti terbaru maksimum</div>${renderActivity(x.activity||[])}</section><section class="rqCrmPane" data-crm-pane="documents"><h3>Documents</h3><div class="rqCrmPaneState" data-crm-state="documents">Buka tab untuk muat rekod.</div><div data-crm-records="documents"></div><div class="rqCrmMore"><button class="btn" data-crm-more="documents" hidden>Load More</button></div></section><section class="rqCrmPane" data-crm-pane="payments"><h3>Payment History</h3><div class="rqCrmPaneState" data-crm-state="payments">Buka tab untuk muat rekod.</div><div data-crm-records="payments"></div><div class="rqCrmMore"><button class="btn" data-crm-more="payments" hidden>Load More</button></div></section><section class="rqCrmPane" data-crm-pane="orders"><h3>Order History</h3><div class="rqCrmPaneState" data-crm-state="orders">Buka tab untuk muat rekod.</div><div data-crm-records="orders"></div><div class="rqCrmMore"><button class="btn" data-crm-more="orders" hidden>Load More</button></div></section>`;if(n)$('waCustomer').addEventListener('click',()=>window.open('https://wa.me/'+n,'_blank','noopener'));bindDrawerControls()}
async function openCustomer(id){const seq=++detailSeq;currentCustomerId=id;activeTab='activity';resetTabs();$('customerDrawer').classList.add('open');$('customerDrawer').setAttribute('aria-hidden','false');$('drawerTitle').textContent='Customer';$('drawerBody').innerHTML='<div class="rqCustomerState">Memuatkan profile customer…</div>';try{const d=await api('customerDetail',{customerId:id});if(seq!==detailSeq)return;renderDrawer(d)}catch(e){if(seq!==detailSeq)return;$('drawerBody').innerHTML='<div class="rqCustomerState">'+esc(e.message)+'</div>';toast(e.message,true)}}
function closeDrawer(){detailSeq++;currentCustomerId='';activeTab='activity';resetTabs();$('customerDrawer').classList.remove('open');$('customerDrawer').setAttribute('aria-hidden','true')}
async function load(){const seq=++loadSeq;try{$('customerState').textContent='Memuatkan pelanggan…';const d=await api('customerDashboard',{q:$('customerSearch').value.trim(),sort:$('customerSort').value,limit:160});if(seq!==loadSeq)return;rows=Array.isArray(d.customers)?d.customers:[];stats=d.stats||stats;renderStats();render();$('customerState').textContent=`${rows.length} customer dipaparkan · ${Number(stats.customers||0)} keseluruhan · detail dimuat bila dibuka.`}catch(e){if(seq!==loadSeq)return;$('customerState').textContent=e.message;toast(e.message,true)}}
let searchTimer;function queueLoad(){clearTimeout(searchTimer);searchTimer=setTimeout(load,260)}
if(initialCustomerQuery)$('customerSearch').value=initialCustomerQuery;
$('refreshCustomers').addEventListener('click',load);$('customerSearch').addEventListener('input',queueLoad);$('customerSort').addEventListener('change',load);$('drawerClose').addEventListener('click',closeDrawer);$('customerDrawer').addEventListener('click',e=>{if(e.target.id==='customerDrawer')closeDrawer()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});
load().then(()=>{if(initialCustomer)openCustomer(initialCustomer)});
})();