(()=>{'use strict';
const API='/api/shop-admin';
let transactions=[],txOffset=0,txHasMore=false,loadSeq=0;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>'RM'+(Number(n||0)/100).toLocaleString('en-MY',{minimumFractionDigits:2,maximumFractionDigits:2});
function toast(m,e=false){const x=$('financeToast');x.textContent=m;x.className='rqFinanceToast show'+(e?' err':'');clearTimeout(toast.t);toast.t=setTimeout(()=>x.className='rqFinanceToast',2400)}
async function api(action,extra={}){const u=new URL(API,location.origin);u.searchParams.set('action',action);Object.entries(extra).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,v)});const r=await fetch(u,{cache:'no-store'});let d={};try{d=await r.json()}catch{}if(r.status===401){location.href='/admin/?return='+encodeURIComponent(location.pathname+location.search);throw Error('Sesi Admin tamat.')}if(!r.ok||!d.ok)throw Error(d.error||'Request gagal');return d}
const paidAt=p=>p.paid_at||p.created_at||'',fmt=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('ms-MY',{day:'2-digit',month:'short',year:'numeric'})};
function renderTransactions(){const el=$('financeTransactions');el.innerHTML=transactions.length?'<div class="rqFinanceList">'+transactions.map(p=>`<div class="rqFinanceRow"><div><b>${esc(p.receipt_number||p.order_no||'Payment')}</b><small>${fmt(paidAt(p))} · ${esc((p.payment_type||'payment').toUpperCase())} · ${esc(p.order_no||p.order_id||'')}${p.customer_name?' · '+esc(p.customer_name):''}</small></div><div class="rqFinanceAmount">${money(p.amount_minor||0)}</div></div>`).join('')+'</div>':'<div class="rqFinanceState">Tiada bayaran disahkan untuk tempoh ini.</div>';const more=$('loadMoreFinance');if(more){more.hidden=!txHasMore;more.disabled=false;more.textContent='Load More'}}
function render(d){const s=d.summary||{},trend=Array.isArray(d.trend)?d.trend:[],products=Array.isArray(d.products)?d.products:[],breakdown=d.breakdown||{};$('finRevenue').textContent=money(s.collectedMinor||0);$('finPaidOrders').textContent=Number(s.paidOrders||0)+' orders with payment';$('finPending').textContent=money(s.outstandingMinor||0);$('finPendingOrders').textContent=Number(s.outstandingOrders||0)+' orders with balance';$('finAov').textContent=money(s.averageCollectedMinor||0);$('finRate').textContent=Number(s.ordersWithPaymentRate||0)+'%';
 const max=Math.max(1,...trend.map(x=>Number(x.collected_minor||0)));$('revenueChart').innerHTML=trend.length?trend.map(x=>{const dt=new Date(String(x.month||'')+'-01T00:00:00');return `<div class="rqBarCol"><div class="rqBarValue">${money(x.collected_minor||0).replace('.00','')}</div><div class="rqBar" style="height:${Math.max(2,Math.round(Number(x.collected_minor||0)/max*135))}px"></div><div class="rqBarLabel">${Number.isNaN(dt.getTime())?esc(x.month):dt.toLocaleDateString('ms-MY',{month:'short'})}</div></div>`}).join(''):'<div class="rqFinanceState">Belum ada kutipan untuk tempoh ini.</div>';
 $('topProducts').innerHTML=products.length?'<div class="rqFinanceList">'+products.map(x=>`<div class="rqFinanceRow"><div><b>${esc(x.product_name||'Produk')}</b><small>${Number(x.units_sold||0)} unit · ${Number(x.orders||0)} order berbayar</small></div><div class="rqFinanceAmount">${money(x.collected_minor||0)}</div></div>`).join('')+'</div>':'<div class="rqFinanceState">Tiada data produk berbayar untuk tempoh ini.</div>';
 const cats=[['Paid in full',Number(breakdown.paid||0)],['Deposit / partial',Number(breakdown.partial||0)],['Unpaid',Number(breakdown.pending||0)]],mx=Math.max(1,...cats.map(x=>x[1]));$('paymentBreakdown').innerHTML=cats.map(([n,v])=>`<div class="rqPayLine"><b>${n}</b><div class="rqPayTrack"><div class="rqPayFill" style="width:${Math.round(v/mx*100)}%"></div></div><div class="rqPayValue">${v}</div></div>`).join('');
 transactions=Array.isArray(d.transactions)?d.transactions:[];txOffset=transactions.length;txHasMore=!!d.transactionsHasMore;renderTransactions();$('financeState').textContent=`${Number(s.validOrders||0)} order dianalisis · data aggregate server-side · kutipan berdasarkan confirmed payment ledger.`}
async function load(){const seq=++loadSeq;try{$('financeState').textContent='Memuatkan data kewangan…';const d=await api('financeDashboard',{range:$('financeRange').value});if(seq!==loadSeq)return;render(d)}catch(e){if(seq!==loadSeq)return;$('financeState').textContent=e.message;toast(e.message,true)}}
async function loadMore(){const b=$('loadMoreFinance');if(b){b.disabled=true;b.textContent='Memuatkan…'}try{const d=await api('financeTransactions',{range:$('financeRange').value,limit:25,offset:txOffset}),seen=new Set(transactions.map(x=>String(x.id)));for(const p of d.transactions||[])if(!seen.has(String(p.id))){transactions.push(p);seen.add(String(p.id))}txOffset=Number(d.offset||0)+(d.transactions||[]).length;txHasMore=!!d.hasMore;renderTransactions()}catch(e){toast(e.message,true)}finally{if(b){b.disabled=false;b.textContent='Load More'}}}
$('refreshFinance').addEventListener('click',load);$('financeRange').addEventListener('change',load);$('loadMoreFinance')?.addEventListener('click',loadMore);load();
})();