(()=>{'use strict';
const API='/api/shop-admin';
let orders=[],payments=[],summaries=[],productInsights=[];
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>'RM'+(Number(n||0)/100).toLocaleString('en-MY',{minimumFractionDigits:2,maximumFractionDigits:2});
function toast(m,e=false){const x=$('financeToast');x.textContent=m;x.className='rqFinanceToast show'+(e?' err':'');clearTimeout(toast.t);toast.t=setTimeout(()=>x.className='rqFinanceToast',2400)}
async function api(action,extra={}){const u=new URL(API,location.origin);u.searchParams.set('action',action);Object.entries(extra).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{cache:'no-store'});let d={};try{d=await r.json()}catch{}if(r.status===401){location.href='/admin/?return='+encodeURIComponent(location.pathname+location.search);throw Error('Sesi Admin tamat.')}if(!r.ok||!d.ok)throw Error(d.error||'Request gagal');return d}
const status=o=>String(o.payment_status||o.paymentStatus||o.payment||'pending').toLowerCase(),cancelled=o=>['cancelled','failed','refunded','rejected'].includes(String(o.status||o.order_status||'').toLowerCase())||['cancelled','failed','refunded','rejected'].includes(status(o)),minor=o=>o.total_minor!=null?Number(o.total_minor||0):o.totalMinor!=null?Number(o.totalMinor||0):Math.round(Number(o.total||0)*100),created=o=>o.created_at||o.createdAt||o.timestamp||'',paidAt=p=>p.paid_at||p.created_at||'',fmt=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('ms-MY',{day:'2-digit',month:'short',year:'numeric'})};
function inRange(v){const r=$('financeRange').value;if(r==='all')return true;const t=new Date(v).getTime();return !Number.isNaN(t)&&t>=Date.now()-Number(r)*86400000}
function filteredOrders(){return orders.filter(o=>inRange(created(o)))}
function filteredPayments(){return payments.filter(p=>String(p.status||'confirmed').toLowerCase()==='confirmed'&&inRange(paidAt(p)))}
function summaryMap(){return new Map(summaries.map(s=>[String(s.orderId),s]))}
function paymentState(o,map){const s=map.get(String(o.id||''));if(s){if(Number(s.balanceMinor||0)<=0&&Number(s.totalMinor||0)>0)return'paid';if(Number(s.paidMinor||0)>0)return'partial';return'pending'}const p=status(o);return p==='paid'?'paid':p==='partial'?'partial':'pending'}
function render(){
 const list=filteredOrders(),valid=list.filter(o=>!cancelled(o)),pays=filteredPayments(),smap=summaryMap();
 const collected=pays.reduce((a,p)=>a+Number(p.amount_minor||0),0),payOrderIds=new Set(pays.map(p=>String(p.order_id||'')).filter(Boolean));
 const outstanding=valid.reduce((a,o)=>{const s=smap.get(String(o.id||''));return a+(s?Math.max(0,Number(s.balanceMinor||0)):(status(o)==='paid'?0:minor(o)))},0);
 const outstandingCount=valid.filter(o=>{const s=smap.get(String(o.id||''));return s?Number(s.balanceMinor||0)>0:status(o)!=='paid'}).length;
 const withPayment=valid.filter(o=>{const s=smap.get(String(o.id||''));return s?Number(s.paidMinor||0)>0:['paid','partial'].includes(status(o))}).length;
 $('finRevenue').textContent=money(collected);$('finPaidOrders').textContent=payOrderIds.size+' orders with payment';$('finPending').textContent=money(outstanding);$('finPendingOrders').textContent=outstandingCount+' orders with balance';$('finAov').textContent=money(payOrderIds.size?Math.round(collected/payOrderIds.size):0);$('finRate').textContent=(valid.length?Math.round(withPayment/valid.length*100):0)+'%';
 const months={};pays.forEach(p=>{const d=new Date(paidAt(p));if(Number.isNaN(d.getTime()))return;const k=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');months[k]=(months[k]||0)+Number(p.amount_minor||0)});
 const series=Object.entries(months).sort(([a],[b])=>a.localeCompare(b)).slice(-12),max=Math.max(1,...series.map(x=>x[1]));$('revenueChart').innerHTML=series.map(([k,v])=>{const d=new Date(k+'-01T00:00:00');return `<div class="rqBarCol"><div class="rqBarValue">${money(v).replace('.00','')}</div><div class="rqBar" style="height:${Math.max(2,Math.round(v/max*135))}px"></div><div class="rqBarLabel">${d.toLocaleDateString('ms-MY',{month:'short'})}</div></div>`}).join('')||'<div class="rqFinanceState">Belum ada kutipan untuk tempoh ini.</div>';
 $('topProducts').innerHTML=productInsights.length?'<div class="rqFinanceList">'+productInsights.slice().sort((a,b)=>Number(b.revenue_minor||0)-Number(a.revenue_minor||0)).slice(0,6).map(x=>`<div class="rqFinanceRow"><div><b>${esc(x.product_name||'Produk')}</b><small>${Number(x.units_sold||0)} unit · ${Number(x.paid_orders||0)} paid order</small></div><div class="rqFinanceAmount">${money(x.revenue_minor||0)}</div></div>`).join('')+'</div>':'<div class="rqFinanceState">Tiada data produk.</div>';
 const states={paid:[],partial:[],pending:[]};valid.forEach(o=>states[paymentState(o,smap)].push(o));const cats=[['Paid in full',states.paid],['Deposit / partial',states.partial],['Unpaid',states.pending]],mx=Math.max(1,...cats.map(x=>x[1].length));$('paymentBreakdown').innerHTML=cats.map(([n,x])=>`<div class="rqPayLine"><b>${n}</b><div class="rqPayTrack"><div class="rqPayFill" style="width:${Math.round(x.length/mx*100)}%"></div></div><div class="rqPayValue">${x.length}</div></div>`).join('');
 $('financeTransactions').innerHTML=pays.length?'<div class="rqFinanceList">'+pays.slice().sort((a,b)=>String(paidAt(b)).localeCompare(String(paidAt(a)))).slice(0,12).map(p=>`<div class="rqFinanceRow"><div><b>${esc(p.receipt_number||p.order_no||'Payment')}</b><small>${fmt(paidAt(p))} · ${esc((p.payment_type||'payment').toUpperCase())} · ${esc(p.order_no||p.order_id||'')}</small></div><div class="rqFinanceAmount">${money(p.amount_minor||0)}</div></div>`).join('')+'</div>':'<div class="rqFinanceState">Tiada bayaran disahkan untuk tempoh ini.</div>';
 $('financeState').textContent=`${valid.length} order dianalisis · ${pays.length} confirmed payment · Kutipan berdasarkan payment ledger.`;
}
async function load(){try{$('financeState').textContent='Memuatkan data kewangan…';const [o,p,s,pr]=await Promise.all([api('listOrders',{limit:2000}),api('listPayments',{limit:2000}),api('paymentSummary'),api('productsDashboard')]);orders=Array.isArray(o.orders)?o.orders:[];payments=Array.isArray(p.payments)?p.payments:[];summaries=Array.isArray(s.summaries)?s.summaries:[];productInsights=Array.isArray(pr.insights)?pr.insights:[];render()}catch(e){$('financeState').textContent=e.message;toast(e.message,true)}}
$('refreshFinance').addEventListener('click',load);$('financeRange').addEventListener('change',render);load();
})();