(()=>{
'use strict';
const API='/api/shop-admin';
let orders=[],current=null,drawerSeq=0,initialOrder='';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'RM'+(Number(n||0)/100).toLocaleString('en-MY',{minimumFractionDigits:2,maximumFractionDigits:2});
function toast(m,e=false){const x=$('ordersToast');x.textContent=m;x.className='rqOrdersToast show'+(e?' err':'');clearTimeout(toast.t);toast.t=setTimeout(()=>x.className='rqOrdersToast',e?4200:2400)}
async function get(action,extra={}){const u=new URL(API,location.origin);u.searchParams.set('action',action);Object.entries(extra).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{cache:'no-store'}),d=await r.json().catch(()=>({}));if(r.status===401){location.href='/admin/?return='+encodeURIComponent(location.pathname+location.search);throw Error('Sesi Admin tamat.')}if(!r.ok||!d.ok)throw Error(d.error||'Request gagal');return d}
async function post(action,data={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data}),cache:'no-store'}),d=await r.json().catch(()=>({}));if(r.status===401){location.href='/admin/?return='+encodeURIComponent(location.pathname+location.search);throw Error('Sesi Admin tamat.')}if(!r.ok||!d.ok)throw Error(d.error||'Request gagal');return d}
const pstat=o=>String(o?.payment_status||o?.paymentStatus||o?.payment||'pending').toLowerCase();
const fstat=o=>String(o?.fulfillment_status||o?.fulfillmentStatus||o?.status||'pending').toLowerCase();
const key=o=>String(o?.id||o?.orderId||o?.orderNo||o?.order_ref||'');
const ref=o=>o?.orderNo||o?.order_no||o?.order_ref||o?.id||'Order';
const name=o=>o?.name||o?.customer_name||o?.customerName||'—';
const phone=o=>o?.phone||o?.customer_phone||o?.customerPhone||'—';
const email=o=>o?.email||o?.customer_email||o?.customerEmail||'';
const created=o=>o?.created_at||o?.createdAt||'';
const totalMinor=o=>o?.total_minor!=null?Number(o.total_minor||0):o?.totalMinor!=null?Number(o.totalMinor||0):Math.round(Number(o?.total||0)*100);
const itemMinor=x=>x?.line_total_minor!=null?Number(x.line_total_minor||0):Math.round(Number(x?.line_total||0)*100);
const parse=v=>{try{return JSON.parse(v||'{}')||{}}catch{return{}}};
function bucket(o){const p=pstat(o),f=fstat(o);if(['failed','cancelled','refunded','rejected'].includes(p)||['failed','cancelled'].includes(f))return'closed';if(!['paid','partial'].includes(p))return'pending';if(f==='fulfilled')return'fulfilled';if(f==='processing')return'processing';return'paid'}
function label(s,o){return s==='paid'&&pstat(o)==='partial'?'Deposit Paid':({pending:'Pending Payment',paid:'Paid',processing:'In Production',fulfilled:'Fulfilled',closed:'Closed'})[s]||s}
function fmt(v){const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('ms-MY',{day:'2-digit',month:'short',year:'numeric'})}
function fmtTime(v){const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('ms-MY',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function waNumber(v){let n=String(v||'').replace(/\D/g,'');if(n.startsWith('0'))n='60'+n.slice(1);return n}
function filtered(){const q=$('orderSearch').value.trim().toLowerCase(),f=$('orderFilter').value;return orders.filter(o=>{const b=bucket(o),match=!q||[ref(o),name(o),phone(o),email(o)].some(x=>String(x).toLowerCase().includes(q));const fm=f==='active'?b!=='closed':b===f;return match&&fm})}
function render(){const all=orders;$('ordTotal').textContent=all.length;$('ordPending').textContent=all.filter(o=>bucket(o)==='pending').length;$('ordPaid').textContent=all.filter(o=>bucket(o)==='paid').length;$('ordProcessing').textContent=all.filter(o=>bucket(o)==='processing').length;const matches=filtered(),list=matches.slice(0,250);$('ordersList').innerHTML=list.length?list.map(o=>{const b=bucket(o);return `<article class="rqOrderRow" data-order="${esc(key(o))}"><div><div class="rqOrderRef">${esc(ref(o))}</div><span class="rqStatus ${b}">${esc(label(b,o))}</span></div><div class="rqOrderCustomer"><b>${esc(name(o))}</b><small>${esc(phone(o))}</small></div><div class="rqOrderAmount">${money(totalMinor(o))}</div><div class="rqOrderDate">${fmt(created(o))}</div><div>›</div></article>`}).join(''):'<div class="rqOrdersState">Tiada order untuk filter ini.</div>';$_state(matches.length>list.length?`${list.length} daripada ${matches.length} padanan dipaparkan · ${orders.length} order dimuatkan.`:`${matches.length} order dipaparkan · ${orders.length} order dimuatkan.`)}
function $_state(t){$('ordersState').textContent=t}
function summaryHtml(o,s){const paid=s?Number(s.paidMinor||0):(pstat(o)==='paid'?totalMinor(o):0),balance=s?Number(s.balanceMinor||0):Math.max(0,totalMinor(o)-paid),shipping=o.shipping_minor!=null?Number(o.shipping_minor||0):Math.round(Number(o.shipping||0)*100);return `<div class="rqDetailGrid"><div class="rqDetail"><small>CUSTOMER</small><b>${esc(name(o))}</b>${email(o)?`<span>${esc(email(o))}</span>`:''}</div><div class="rqDetail"><small>WHATSAPP</small><b>${esc(phone(o))}</b></div><div class="rqDetail"><small>PAYMENT</small><b>${esc((s?.paymentStatus||pstat(o)).toUpperCase())}</b></div><div class="rqDetail"><small>FULFILLMENT</small><b>${esc(fstat(o).toUpperCase())}</b></div><div class="rqDetail"><small>ORDER TOTAL</small><b>${money(s?.totalMinor??totalMinor(o))}</b></div><div class="rqDetail"><small>PAID</small><b class="rqMoneyOk">${money(paid)}</b></div><div class="rqDetail"><small>BALANCE</small><b class="${balance>0?'rqMoneyDue':''}">${money(balance)}</b></div><div class="rqDetail"><small>SHIPPING</small><b>${money(shipping)}</b></div><div class="rqDetail rqDetailWide"><small>CREATED</small><b>${fmtTime(created(o))}</b></div></div>`}
function addressHtml(o){const a=o.address||{};if(!a.address)return'';return `<section class="rqOrderSection"><div class="rqOrderSectionHead"><small>DELIVERY</small><h3>Alamat penghantaran</h3></div><div class="rqOrderAddress"><b>${esc(a.name||name(o))}</b><span>${esc(a.phone||phone(o))}</span><p>${esc(a.address)}</p></div></section>`}
function itemsHtml(items,o){return `<section class="rqOrderSection"><div class="rqOrderSectionHead"><small>ORDER ITEMS</small><h3>Apa yang perlu disiapkan</h3></div><div class="rqOrderItems">${items.length?items.map((x,i)=>{const c=parse(x.customization_snapshot_json),txt=String(c.text||'').trim(),note=String(c.note||'').trim(),hasArt=!!c.artworkKey,variant=x.variant_name||parse(x.variation_snapshot_json).name||'Standard',qty=Number(x.qty||x.quantity||1);return `<article class="rqOrderItem"><div class="rqOrderItemTop"><div><small>ITEM ${i+1}</small><h4>${esc(x.product_name||x.product_name_snapshot||'Produk')}</h4><span>${esc(variant)} · Qty ${qty}</span></div><b>${money(itemMinor(x))}</b></div>${txt||note?`<div class="rqOrderCustom">${txt?`<div><span>TEKS / NAMA</span><strong>${esc(txt)}</strong></div>`:''}${note?`<div><span>NOTA CUSTOMER</span><strong>${esc(note)}</strong></div>`:''}</div>`:'<div class="rqOrderNoCustom">Tiada arahan tambahan.</div>'}${hasArt?`<button type="button" class="btn rqArtworkBtn" data-artwork-item="${esc(x.id)}" data-artwork-order="${esc(o.id||key(o))}">Lihat Artwork Customer</button>`:''}</article>`}).join(''):'<div class="rqOrderEmpty">Tiada item dijumpai.</div>'}</div></section>`}
function paymentsHtml(s){const ps=Array.isArray(s?.payments)?s.payments:[];return `<section class="rqOrderSection"><div class="rqOrderSectionHead"><small>PAYMENT LEDGER</small><h3>Sejarah bayaran</h3></div>${ps.length?`<div class="rqOrderPayments">${ps.slice().reverse().map(p=>`<div class="rqOrderPayment"><div><b>${esc(p.receipt_number||'Payment')}</b><span>${fmtTime(p.paid_at||p.created_at)} · ${esc(String(p.payment_type||'payment').toUpperCase())}${p.method?' · '+esc(p.method):''}</span></div><strong>${money(p.amount_minor||0)}</strong></div>`).join('')}</div>`:'<div class="rqOrderEmpty">Belum ada payment ledger.</div>'}</section>`}
function actionHtml(o){const b=bucket(o),acts=[];if(b==='pending'){acts.push('<button class="btn primary" data-action="verify">Sahkan Bayaran</button>','<button class="btn danger" data-action="reject">Tolak Bayaran</button>')}if(b==='paid')acts.push('<button class="btn primary" data-action="processing">Mula Proses</button>');if(b==='processing')acts.push('<button class="btn primary" data-action="fulfilled">Tanda Siap</button>');if(b==='fulfilled')acts.push('<button class="btn" data-action="processing">Buka Semula</button>');const wa=waNumber(phone(o));if(wa)acts.push(`<a class="btn" target="_blank" rel="noopener" href="https://wa.me/${wa}">WhatsApp</a>`);acts.push(`<a class="btn" href="/admin/documents.html?order=${encodeURIComponent(key(o))}">Documents / Payment</a>`);const cid=o.customer_id||o.customerId;if(cid)acts.push(`<a class="btn" href="/admin/customers.html?customer=${encodeURIComponent(cid)}">Customer</a>`);return acts.join('')}
function renderDrawer(o,items=[],summary=null){current=o;$('drawerRef').textContent=ref(o);const b=bucket(o);$('drawerBody').innerHTML=`<div class="rqDrawerStatus"><span class="rqStatus ${b}">${esc(label(b,o))}</span>${summary?.invoiceNumber?`<span>Invoice ${esc(summary.invoiceNumber)}</span>`:''}</div>${summaryHtml(o,summary)}${addressHtml(o)}${itemsHtml(items,o)}${paymentsHtml(summary)}`;$('drawerActions').innerHTML=actionHtml(o)}
async function openDrawer(seed){const seq=++drawerSeq;current=seed;$('drawerRef').textContent=ref(seed);$('drawerBody').innerHTML='<div class="rqOrderLoading">Memuatkan item, shipping dan payment…</div>';$('drawerActions').innerHTML='';$('orderDrawer').classList.add('open');$('orderDrawer').setAttribute('aria-hidden','false');$('orderDrawer').setAttribute('aria-busy','true');try{const id=key(seed),[detail,pay]=await Promise.all([get('getOrder',{orderId:id}),get('paymentSummary',{orderId:id})]);if(seq!==drawerSeq)return;const o=detail.order||seed,items=Array.isArray(detail.items)?detail.items:[],summary=pay.summary||null;renderDrawer(o,items,summary)}catch(e){if(seq!==drawerSeq)return;renderDrawer(seed,[],null);toast(e.message||'Detail order tidak dapat dimuatkan.',true)}finally{if(seq===drawerSeq)$('orderDrawer').setAttribute('aria-busy','false')}}
function closeDrawer(){drawerSeq++;$('orderDrawer').classList.remove('open');$('orderDrawer').setAttribute('aria-hidden','true');$('orderDrawer').setAttribute('aria-busy','false');current=null}
async function artwork(itemId,orderId,btn){btn.disabled=true;const old=btn.textContent;btn.textContent='Membuka…';try{const u=new URL(API,location.origin);u.searchParams.set('action','artwork');u.searchParams.set('itemId',itemId);u.searchParams.set('orderId',orderId);const r=await fetch(u,{cache:'no-store'});if(!r.ok){const j=await r.json().catch(()=>({}));throw Error(j.error||'Artwork tidak dapat dibuka.')}const blob=await r.blob(),obj=URL.createObjectURL(blob),w=window.open(obj,'_blank','noopener');if(!w)throw Error('Popup disekat. Benarkan popup untuk lihat artwork.');setTimeout(()=>URL.revokeObjectURL(obj),60000)}catch(e){toast(e.message||'Artwork tidak dapat dibuka.',true)}finally{btn.disabled=false;btn.textContent=old}}
async function change(action,btn){if(!current)return;const id=key(current);let text='';if(action==='verify')text='Sahkan bayaran selepas bukti disemak?';if(action==='reject')text='Tolak bayaran dan batalkan order ini? Stok akan dipulangkan.';if(action==='fulfilled')text='Tandakan order ini sebagai siap?';if(action==='processing'&&bucket(current)==='fulfilled')text='Buka semula order ini ke Dalam Proses?';if(text&&!confirm(text))return;btn.disabled=true;try{if(action==='verify')await post('verifyPayment',{orderId:id});else if(action==='reject')await post('rejectPayment',{orderId:id});else await post('status',{orderId:id,status:action});toast('Order dikemas kini.');closeDrawer();await load()}catch(e){toast(e.message,true)}finally{btn.disabled=false}}
async function load(){try{$_state('Memuatkan orders…');const d=await get('listOrders',{limit:1000});orders=Array.isArray(d.orders)?d.orders:[];render();if(initialOrder){const exact=initialOrder,target=orders.find(o=>key(o)===exact||ref(o)===exact)||{id:exact,orderNo:exact};initialOrder='';openDrawer(target)}}catch(e){$_state(e.message);toast(e.message,true)}}
$('ordersList').addEventListener('click',e=>{const r=e.target.closest('[data-order]');if(r){const o=orders.find(x=>key(x)===r.dataset.order);if(o)openDrawer(o)}});
$('orderDrawer').addEventListener('click',e=>{if(e.target===$('orderDrawer'))closeDrawer();const b=e.target.closest('[data-action]');if(b)change(b.dataset.action,b);const a=e.target.closest('[data-artwork-item]');if(a)artwork(a.dataset.artworkItem,a.dataset.artworkOrder,a)});
$('closeDrawer').addEventListener('click',closeDrawer);
$('refreshOrders').addEventListener('click',load);
$('orderSearch').addEventListener('input',render);
$('orderFilter').addEventListener('change',render);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('orderDrawer').classList.contains('open'))closeDrawer()});
const initialParams=new URLSearchParams(location.search),initialQ=initialParams.get('q')||'';initialOrder=initialParams.get('order')||'';if(initialQ)$('orderSearch').value=initialQ;load();
})();