(()=>{'use strict';
const API='/api/shop-admin',TOKEN_KEY='reqoo_admin_token';
let products=[],insights=new Map(),editing=null,imageUrls=[];
const $=id=>document.getElementById(id);
const token=()=>localStorage.getItem(TOKEN_KEY)||localStorage.getItem('REQOO_ADMIN_TOKEN')||'';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const moneyMinor=n=>'RM'+(Number(n||0)/100).toLocaleString('en-MY',{minimumFractionDigits:2,maximumFractionDigits:2});
const money=n=>'RM'+Number(n||0).toLocaleString('en-MY',{minimumFractionDigits:2,maximumFractionDigits:2});
function toast(m,e=false){const x=$('productsToast');x.textContent=m;x.className='rqProductsToast show'+(e?' err':'');clearTimeout(toast.t);toast.t=setTimeout(()=>x.className='rqProductsToast',2400)}
async function get(action,extra={}){const u=new URL(API,location.origin);u.searchParams.set('action',action);Object.entries(extra).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{headers:{'X-Admin-Token':token()},cache:'no-store'}),d=await r.json().catch(()=>({}));if(r.status===401){location.href='/admin/?return='+encodeURIComponent(location.pathname);throw Error('Sesi Admin tamat.')}if(!r.ok||!d.ok)throw Error(d.error||'Request gagal');return d}
async function post(action,data={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','X-Admin-Token':token()},body:JSON.stringify({action,...data}),cache:'no-store'}),d=await r.json().catch(()=>({}));if(r.status===401){location.href='/admin/?return='+encodeURIComponent(location.pathname);throw Error('Sesi Admin tamat.')}if(!r.ok||!d.ok)throw Error(d.error||'Request gagal');return d}
function info(p){const v=p.variants||[],tracked=v.filter(x=>x.stock!==null&&x.stock!==''&&x.stock!==undefined),units=tracked.reduce((a,x)=>a+Math.max(0,Number(x.stock||0)),0),out=tracked.length>0&&tracked.every(x=>Number(x.stock||0)<=0),low=tracked.length>0&&!out&&tracked.some(x=>Number(x.stock||0)<=5),untracked=tracked.length===0;return{tracked,units,out,low,untracked}}
function insight(p){return insights.get(String(p.id))||{revenue_minor:0,units_sold:0,paid_orders:0}}
function filtered(){const q=$('productSearch').value.trim().toLowerCase(),f=$('productFilter').value;return products.filter(p=>{const i=info(p),hay=[p.name,p.category,p.sku,...(p.variants||[]).map(v=>v.sku||'')].join(' ').toLowerCase();if(q&&!hay.includes(q))return false;if(f==='active'&&!p.active)return false;if(f==='hidden'&&p.active)return false;if(f==='low'&&!i.low)return false;if(f==='out'&&!i.out)return false;if(f==='untracked'&&!i.untracked)return false;return true})}
function stockChip(i){if(i.out)return '<span class="rqChip bad">Out of stock</span>';if(i.low)return '<span class="rqChip warn">Low stock</span>';if(i.untracked)return '<span class="rqChip">Not tracked</span>';return '<span class="rqChip ok">In stock</span>'}
function render(){const all=products.map(info);$('prdTotal').textContent=products.length;$('prdActive').textContent=products.filter(p=>p.active).length;$('prdLow').textContent=all.filter(x=>x.low).length;$('prdOut').textContent=all.filter(x=>x.out).length;$('prdRevenue').textContent=moneyMinor([...insights.values()].reduce((a,x)=>a+Number(x.revenue_minor||0),0));const list=filtered();$('productsList').innerHTML=list.length?list.map(p=>{const i=info(p),s=insight(p),stock=i.untracked?'Inventory not tracked':`${i.units} units available`,img=p.image||p.imageUrl||'';return `<tr><td><div class="rqProductCell">${img?`<img class="rqProductThumb" src="${esc(img)}" alt="">`:'<div class="rqProductThumb"></div>'}<div><div class="rqProductName">${esc(p.name||'Untitled product')}</div><div class="rqProductMeta">${esc(p.category||'Uncategorized')} · ${esc(p.sku||'No SKU')} · ${money(p.basePrice||0)}</div></div></div></td><td>${p.active?'<span class="rqChip ok">Active</span>':'<span class="rqChip">Draft</span>'}</td><td><div>${stockChip(i)}</div><div class="rqProductMeta">${esc(stock)}</div></td><td>${Number(s.units_sold||0)} sold</td><td><b>${moneyMinor(s.revenue_minor||0)}</b></td><td><div class="rqRowActions"><button class="btn" data-edit="${esc(p.id)}">Edit</button><button class="btn" data-toggle="${esc(p.id)}">${p.active?'Hide':'Activate'}</button></div></td></tr>`}).join(''):'<tr><td colspan="6" class="rqProductsState">Tiada produk untuk filter ini.</td></tr>';$('productsState').textContent=`${list.length} / ${products.length} products · sales based on PAID orders.`}
async function load(){try{$('productsState').textContent='Memuatkan products…';const d=await get('productsDashboard');products=Array.isArray(d.products)?d.products:[];insights=new Map((d.insights||[]).map(x=>[String(x.product_id),x]));render()}catch(e){$('productsState').textContent=e.message;toast(e.message,true)}}
function variantRow(v={}){const el=document.createElement('div');el.className='rqVariant';el.dataset.id=v.id||'';el.innerHTML=`<input data-v-name placeholder="Variant name" value="${esc(v.name||'')}"><input data-v-sku placeholder="SKU" value="${esc(v.sku||'')}"><input data-v-price type="number" min="0" step="0.01" placeholder="Price" value="${v.price??''}"><input data-v-stock type="number" min="0" step="1" placeholder="Stock" value="${v.stock??''}"><button type="button" data-v-remove title="Remove">×</button>`;return el}
function renderImages(){const box=$('productImages');box.innerHTML=imageUrls.map((url,i)=>`<div class="rqMediaItem"><img src="${esc(url)}" alt=""><button type="button" class="rqMediaRemove" data-img-remove="${i}" title="Remove">×</button>${i===0?'<span class="rqMediaCover">Cover</span>':''}</div>`).join('');$('mediaEmpty').style.display=imageUrls.length?'none':'block'}
async function loadImages(p){imageUrls=[];if(p?.id){try{const d=await get('listImages',{productId:p.id});imageUrls=(d.images||[]).map(x=>x.url).filter(Boolean)}catch(e){if(p.image)imageUrls=[p.image]}}renderImages()}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Gagal membaca gambar.'));reader.readAsDataURL(file)})}
function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('Format gambar tidak dapat dibaca.'));img.src=src})}
async function compressImage(file){if(!/^image\/(jpeg|png|webp)$/i.test(file.type))throw Error('Hanya JPG, PNG atau WebP dibenarkan.');if(file.size>15*1024*1024)throw Error('Saiz gambar terlalu besar. Maksimum 15MB.');const src=await fileToDataUrl(file),img=await loadImage(src),max=1400,scale=Math.min(1,max/Math.max(img.naturalWidth||img.width,img.naturalHeight||img.height)),w=Math.max(1,Math.round((img.naturalWidth||img.width)*scale)),h=Math.max(1,Math.round((img.naturalHeight||img.height)*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,w,h);return canvas.toDataURL('image/jpeg',0.82)}
async function addImageFiles(files){const items=[...files].slice(0,8);if(!items.length)return;const btn=$('addImageFile');btn.disabled=true;btn.textContent='Processing…';try{for(const file of items){if(imageUrls.length>=8){toast('Maksimum 8 gambar setiap produk.',true);break}imageUrls.push(await compressImage(file));renderImages()}toast(`${Math.min(items.length,8)} gambar ditambah.`)}catch(e){toast(e.message,true)}finally{btn.disabled=false;btn.textContent='+ Choose images';$('productImageFile').value=''}}
function slugify(v){return String(v||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,160)}
async function openEditor(p=null){editing=p;$('productSlug').dataset.edited='';$('productId').value=p?.id||'';$('productName').value=p?.name||'';$('productCategory').value=p?.category||'';$('productPrice').value=p?.basePrice??'';$('productComparePrice').value=p?.salePriceMinor?Number(p.salePriceMinor)/100:'';$('productSku').value=p?.sku||'';$('productSlug').value=p?.slug||slugify(p?.name||'');$('productShortDescription').value=p?.shortDescription||p?.short_description||'';$('productType').value=p?.productType||p?.product_type||'physical';$('productFulfillment').value=p?.fulfillmentType||p?.fulfillment_type||'physical_shipping';$('productActive').value=p?.active===false?'0':'1';$('productDescription').value=p?.description||'';$('variantList').innerHTML='';const vs=p?.variants?.length?p.variants:[{name:'Standard',price:p?.basePrice||'',stock:null}];vs.forEach(v=>$('variantList').appendChild(variantRow(v)));$('productDrawerTitle').textContent=p?.name||'Add product';$('toggleProduct').textContent=p?.active===false?'Activate product':'Hide product';$('dangerZone').style.display=p?.id?'block':'none';$('productDrawer').classList.add('open');$('productDrawer').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';await loadImages(p)}
function closeEditor(){$('productDrawer').classList.remove('open');$('productDrawer').setAttribute('aria-hidden','true');editing=null;imageUrls=[];document.body.style.overflow=''}
async function save(e){e.preventDefault();const b=$('saveProduct'),variants=[...$('variantList').children].map(r=>({id:r.dataset.id||undefined,name:r.querySelector('[data-v-name]').value.trim(),sku:r.querySelector('[data-v-sku]').value.trim(),price:r.querySelector('[data-v-price]').value,stock:r.querySelector('[data-v-stock]').value===''?null:Number(r.querySelector('[data-v-stock]').value)})).filter(x=>x.name);if(!$('productName').value.trim())return toast('Nama produk diperlukan.',true);b.disabled=true;try{const sale=$('productComparePrice').value;const d=await post('saveProduct',{id:$('productId').value||undefined,name:$('productName').value.trim(),sku:$('productSku').value.trim(),slug:$('productSlug').value.trim()||slugify($('productName').value),category:$('productCategory').value.trim(),basePrice:Number($('productPrice').value||0),salePriceMinor:sale===''?null:Math.round(Number(sale||0)*100),active:$('productActive').value==='1',description:$('productDescription').value.trim(),shortDescription:$('productShortDescription').value.trim(),productType:$('productType').value,fulfillmentType:$('productFulfillment').value,variants});const pid=d.productId||$('productId').value;if(pid)await post('saveImages',{productId:pid,images:imageUrls});closeEditor();await load();toast('Produk disimpan.')}catch(err){toast(err.message,true)}finally{b.disabled=false}}
async function toggle(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;try{await post('saveProduct',{id:p.id,active:!p.active});await load();toast(p.active?'Produk disembunyikan.':'Produk diaktifkan.')}catch(e){toast(e.message,true)}}
async function deleteCurrent(){if(!editing?.id)return;const name=editing.name||'produk ini';if(!confirm(`Padam ${name}? Tindakan ini tidak boleh dibatalkan.`))return;try{await post('deleteProduct',{id:editing.id});closeEditor();await load();toast('Produk dipadam.')}catch(e){toast(e.message,true)}}
$('refreshProducts').addEventListener('click',load);
$('productSearch').addEventListener('input',render);
$('productFilter').addEventListener('change',()=>{document.querySelectorAll('[data-filter-tab]').forEach(x=>x.classList.toggle('active',x.dataset.filterTab===$('productFilter').value));render()});
document.querySelectorAll('[data-filter-tab]').forEach(b=>b.addEventListener('click',()=>{$('productFilter').value=b.dataset.filterTab;document.querySelectorAll('[data-filter-tab]').forEach(x=>x.classList.toggle('active',x===b));render()}));
$('addProduct').addEventListener('click',()=>openEditor());
$('closeProductDrawer').addEventListener('click',closeEditor);
$('cancelProductEdit').addEventListener('click',closeEditor);
$('addVariant').addEventListener('click',()=>$('variantList').appendChild(variantRow()));
$('variantList').addEventListener('click',e=>{const b=e.target.closest('[data-v-remove]');if(b)b.parentElement.remove()});
$('addImageFile').addEventListener('click',()=>$('productImageFile').click());
$('productImageFile').addEventListener('change',e=>addImageFiles(e.target.files));
$('addImageUrl').addEventListener('click',()=>{const url=prompt('Masukkan URL gambar produk');if(url&&/^https?:\/\//i.test(url.trim())){if(imageUrls.length>=8)return toast('Maksimum 8 gambar setiap produk.',true);imageUrls.push(url.trim());renderImages()}else if(url)toast('URL gambar tidak sah.',true)});
$('productImages').addEventListener('click',e=>{const b=e.target.closest('[data-img-remove]');if(!b)return;imageUrls.splice(Number(b.dataset.imgRemove),1);renderImages()});
$('productName').addEventListener('input',()=>{if(!editing&&!$('productSlug').dataset.edited)$('productSlug').value=slugify($('productName').value)});
$('productSlug').addEventListener('input',()=>{$('productSlug').dataset.edited='1'});
$('productForm').addEventListener('submit',save);
$('productsList').addEventListener('click',e=>{const ed=e.target.closest('[data-edit]');if(ed)return openEditor(products.find(x=>String(x.id)===String(ed.dataset.edit)));const tg=e.target.closest('[data-toggle]');if(tg)toggle(tg.dataset.toggle)});
$('toggleProduct').addEventListener('click',async()=>{if(!editing?.id)return;await toggle(editing.id);closeEditor()});
$('deleteProduct').addEventListener('click',deleteCurrent);
$('productDrawer').addEventListener('click',e=>{if(e.target===$('productDrawer'))closeEditor()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('productDrawer').classList.contains('open'))closeEditor()});
if(!token())location.href='/admin/?return='+encodeURIComponent(location.pathname);else load();
})();