(()=>{'use strict';
const SHOP='/api/shop',CORE='/api/core',ATTR_KEY='reqoo_tumbler_attribution_v1';const $=id=>document.getElementById(id);let product=null,shipping=[],busy=false,activeSize='',qty={};
const money=n=>'RM'+Number(n||0).toFixed(2),esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const meta=(event,params={})=>{try{window.REQOO_META?.track?.(event,params)}catch{}};
function cleanTag(v,max=28){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,max)}
function captureAttribution(){const q=new URLSearchParams(location.search),a={utm_source:q.get('utm_source')||'',utm_medium:q.get('utm_medium')||'',utm_campaign:q.get('utm_campaign')||'',utm_content:q.get('utm_content')||'',fbclid:q.get('fbclid')||''};if(Object.values(a).some(Boolean)){try{sessionStorage.setItem(ATTR_KEY,JSON.stringify(a))}catch{}return a}try{return JSON.parse(sessionStorage.getItem(ATTR_KEY)||'{}')||{}}catch{return{}}}
const attribution=captureAttribution();
function orderSource(){const src=cleanTag(attribution.utm_source,14),campaign=cleanTag(attribution.utm_campaign,26);if(src||campaign)return['tumbler',src||'direct',campaign].filter(Boolean).join('-').slice(0,50);return'tumbler-landing-v2'}
async function get(url,opt){const r=await fetch(url,opt),j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw new Error(j.error||'Sambungan gagal');return j}
function parseName(name){const parts=String(name||'').split('/').map(x=>x.trim()).filter(Boolean);return parts.length>=2?{size:parts[0],color:parts.slice(1).join(' / ')}:{size:'Pilihan',color:String(name||'Pilihan')}}
function normShop(p){return {...p,_source:'shop',description:p.desc||p.description||'',image:p.image||'',variants:(p.variants||[]).map(v=>{const name=Array.isArray(v)?String(v[0]||'Pilihan'):String(v.name||'Pilihan'),pc=parseName(name);return {id:Array.isArray(v)?null:v.id||null,name,size:pc.size,color:pc.color,price:Number(Array.isArray(v)?v[1]:v.price||0),image:Array.isArray(v)?v[2]||'':v.image||v.imageUrl||'',stock:Array.isArray(v)?null:v.stock}}).filter(v=>v.name&&v.price>0)}}
function normCore(p){return {...p,_source:'core',description:p.short_description||p.description||'',image:(p.images||[])[0]?.url||'',variants:(p.variations||[]).filter(v=>!v.status||v.status==='active').map(v=>{const name=String(v.name||'Pilihan'),pc=parseName(name);return {id:v.id||null,name,size:pc.size,color:pc.color,price:Number(v.sale_price_minor??v.price_minor??p.sale_price_minor??p.base_price_minor??0)/100,image:v.image_url||'',stock:v.stock??null}}).filter(v=>v.name&&v.price>0)}}
function score(p){const t=(p.name||'')+' '+(p.description||'');return (/tumbler/i.test(t)?20:0)+(p.variants?.length?10:0)+(p._source==='shop'?2:0)}
function chooseProduct(list){return list.filter(p=>/tumbler/i.test((p.name||'')+' '+(p.description||''))&&p.variants?.length).sort((a,b)=>score(b)-score(a))[0]||null}
const sizes=()=>[...new Set(product.variants.map(v=>v.size))];const visible=()=>product.variants.filter(v=>v.size===activeSize);const key=v=>String(v.id||v.name);const clamp=v=>Math.max(0,Math.min(99,Math.round(Number(v)||0)));const inStock=v=>v.stock==null||v.stock===''||Number(v.stock)>0;
function ship(){return shipping.find(x=>String(x.id)===String($('shipping').value))||null}
function selectedItems(){return product.variants.map(v=>({variant:v,qty:clamp(qty[key(v)])})).filter(x=>x.qty>0)}
function selectImage(v){const src=v?.image||product.image;if(src){$('heroImg').src=src;$('sumImg').src=src;$('gallery').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.src===src))}}
function renderSizes(){const ss=sizes();$('sizes').innerHTML=ss.map(s=>{const prices=product.variants.filter(v=>v.size===s).map(v=>v.price).filter(Boolean),from=Math.min(...prices);return `<button type="button" class="sizeBtn ${s===activeSize?'active':''}" data-size="${esc(s)}">${esc(s)}<small>${Number.isFinite(from)?money(from):''}</small></button>`}).join('');$('sizes').querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{activeSize=b.dataset.size;renderSizes();renderColors();update()})}
function renderColors(){const vs=visible();$('colors').innerHTML=vs.map(v=>{const q=clamp(qty[key(v)]),ok=inStock(v),label=esc(v.size+' '+v.color);return `<div class="colorRow ${q?'active':''} ${ok?'':'out'}" data-key="${esc(key(v))}"><div class="colorInfo"><b>${esc(v.color)}</b><small>${money(v.price)} / unit${ok?'':' · Stok habis'}</small></div><div class="qty"><button type="button" aria-label="Kurangkan ${label}" data-minus="${esc(key(v))}" ${ok?'':'disabled'}>−</button><input aria-label="Kuantiti ${label}" data-qty="${esc(key(v))}" type="number" min="0" max="99" value="${q}" ${ok?'':'disabled'}><button type="button" aria-label="Tambah ${label}" data-plus="${esc(key(v))}" ${ok?'':'disabled'}>+</button></div></div>`}).join('');
 $('colors').querySelectorAll('.colorRow').forEach(r=>r.onclick=e=>{const v=product.variants.find(x=>key(x)===r.dataset.key);if(v&&!e.target.closest('button,input'))selectImage(v)});
 $('colors').querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>setQty(b.dataset.minus,(qty[b.dataset.minus]||0)-1));$('colors').querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>setQty(b.dataset.plus,(qty[b.dataset.plus]||0)+1));$('colors').querySelectorAll('[data-qty]').forEach(i=>i.oninput=()=>setQty(i.dataset.qty,i.value,false))
}
function setQty(k,v,rerender=true){qty[k]=clamp(v);const variant=product.variants.find(x=>key(x)===k);if(qty[k]>0&&variant)selectImage(variant);if(rerender)renderColors();update()}
function update(){if(!product)return;const items=selectedItems(),q=items.reduce((s,x)=>s+x.qty,0),sub=items.reduce((s,x)=>s+x.variant.price*x.qty,0),sp=Number(ship()?.price||0),total=sub+sp;$('sumQty').textContent=q+' unit';$('subtotal').textContent=money(sub);$('shippingPrice').textContent=money(sp);$('total').textContent=money(total);$('mobileTotal').textContent=money(total);$('sumVariant').textContent=items.length?items.length+' pilihan':'Belum pilih warna';$('selected').innerHTML=items.length?items.map(x=>`<div class="selectedItem"><span>${esc(x.variant.size)} · ${esc(x.variant.color)} × ${x.qty}</span><b>${money(x.variant.price*x.qty)}</b></div>`).join(''):'<div class="selectedEmpty">Belum ada pilihan.</div>';const ps=visible().map(v=>v.price).filter(Boolean);$('heroPrice').textContent=ps.length?'Dari '+money(Math.min(...ps)):'—';$('buy').disabled=!items.length;$('mobileBuy').disabled=!items.length}
async function gallery(){let imgs=[product.image,...product.variants.map(v=>v.image)].filter(Boolean);try{if(product._source==='shop'){const d=await get(SHOP+'?action=listProductImages&productId='+encodeURIComponent(product.id)+'&_='+Date.now());imgs.push(...(d.images||[]).map(x=>x.url).filter(Boolean))}}catch{}imgs=[...new Set(imgs)];if(imgs[0]){product.image=product.image||imgs[0];selectImage(null)}$('gallery').innerHTML=imgs.slice(0,8).map((u,i)=>`<button type="button" aria-label="Gambar tumbler ${i+1}" data-src="${esc(u)}" class="${i===0?'active':''}"><img src="${esc(u)}" alt="Tumbler ${i+1}"></button>`).join('');$('gallery').querySelectorAll('button').forEach(b=>b.onclick=()=>{const u=b.dataset.src;$('heroImg').src=u;$('sumImg').src=u;$('gallery').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b))})}
async function load(){try{const [sj,cj,sh]=await Promise.all([get(SHOP+'?action=listProducts&_='+Date.now()).catch(()=>({products:[]})),get(CORE+'?action=listProducts&_='+Date.now()).catch(()=>({products:[]})),get(SHOP+'?action=getShipping&_='+Date.now()).catch(()=>({shipping:[]}))]);product=chooseProduct([...(sj.products||[]).map(normShop),...(cj.products||[]).map(normCore)]);if(!product)throw new Error('Produk Tumbler aktif ada, tetapi variation/harga belum dapat dibaca. Semak produk di Admin.');shipping=Array.isArray(sh.shipping)?sh.shipping:[];activeSize=sizes()[0]||'';$('sumName').textContent=product.name;$('shipping').innerHTML='<option value="">Pickup / urus kemudian — RM0.00</option>'+shipping.map(x=>`<option value="${esc(x.id)}">${esc(x.name||'Penghantaran')} — ${money(x.price)}</option>`).join('');renderSizes();renderColors();$('loading').hidden=true;$('orderGrid').hidden=false;update();gallery();const prices=product.variants.map(v=>Number(v.price||0)).filter(n=>n>0);meta('ViewContent',{content_ids:[product.id],content_name:product.name,content_category:'Tumbler',content_type:'product_group',currency:'MYR',value:prices.length?Math.min(...prices):0})}catch(e){$('loading').textContent=e.message||'Tidak dapat memuatkan produk sekarang.';$('loading').style.color='#b34b46'}}
async function artworkData(file){if(!file)return'';if(file.size>2*1024*1024)throw Error('Artwork melebihi 2MB.');if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Artwork mesti PNG, JPG atau WEBP.');return await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||''));reader.onerror=()=>reject(Error('Artwork tidak dapat dibaca.'));reader.readAsDataURL(file)})}
async function submitShop(base,items){const artwork=await artworkData(base.file),subtotal=items.reduce((sum,x)=>sum+Number(x.variant.price||0)*x.qty,0),total=subtotal+Number(ship()?.price||0),payload={action:'createOrder',payment:'toyyibpay',name:base.name,customerName:base.name,phone:base.phone,email:base.email,address:base.address,shippingId:$('shipping').value,source:orderSource(),expectedTotalMinor:Math.round(total*100),items:items.map((x,i)=>({productId:product.id,variantId:x.variant.id||undefined,variant:x.variant.name,variantName:x.variant.name,qty:x.qty,nameText:base.customText,note:base.note,artwork:i===0?artwork:''}))};return get(SHOP,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})}
async function submitCore(base,items){const c=await get('/api/customer-v1',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:base.name,phone:base.phone,email:base.email})});const ik='tumbler-'+Date.now()+'-'+Math.random().toString(36).slice(2);return get('/api/order-v1',{method:'POST',headers:{'Content-Type':'application/json','idempotency-key':ik},body:JSON.stringify({customer_id:c.customer.id,source:'whatsapp-tumbler',currency:'MYR',shipping_minor:Math.round(Number(ship()?.price||0)*100),items:items.map(x=>({product_id:product.id,variation_id:x.variant.id||null,quantity:x.qty,customization:{name:base.customText,note:base.note,address:base.address,artwork_name:base.file?.name||'',artwork_type:base.file?.type||''}}))})})}
function fail(field,message){$('status').className='status error';$('status').textContent=message;if(field){field.focus({preventScroll:true});field.scrollIntoView({behavior:'smooth',block:'center'})}}
async function submit(){if(busy||!product)return;const items=selectedItems();if(!items.length){fail($('sizes'),'Pilih sekurang-kurangnya 1 warna.');return}const base={name:$('name').value.trim(),phone:$('phone').value.trim(),email:$('email').value.trim(),address:$('address').value.trim(),customText:$('customText').value.trim(),note:$('note').value.trim(),file:$('artwork').files[0]};if(!base.name){fail($('name'),'Sila isi nama penuh.');return}const phone=base.phone.replace(/\D/g,'');if(phone.length<9||phone.length>15){fail($('phone'),'Sila isi nombor WhatsApp yang sah.');return}if(!$('email').checkValidity()){fail($('email'),'Sila semak alamat email.');return}if(Number(ship()?.price||0)>0&&!base.address){fail($('address'),'Sila isi alamat lengkap untuk penghantaran.');return}const total=items.reduce((sum,x)=>sum+Number(x.variant.price||0)*x.qty,0)+Number(ship()?.price||0);meta('InitiateCheckout',{content_ids:[product.id],content_name:product.name,content_category:'Tumbler',content_type:'product',currency:'MYR',value:Number(total.toFixed(2)),num_items:items.reduce((sum,x)=>sum+x.qty,0)});busy=true;[$('buy'),$('mobileBuy')].forEach(b=>b.disabled=true);$('status').className='status';$('status').textContent='Mencipta tempahan…';try{const d=product._source==='shop'?await submitShop(base,items):await submitCore(base,items),billUrl=d.billUrl||d.payment?.billUrl;$('status').className='status ok';$('status').textContent='Tempahan berjaya masuk sistem REQOO.';sessionStorage.setItem('reqoo_last_order',JSON.stringify(d));if(billUrl){location.href=billUrl;return}}catch(e){$('status').className='status error';$('status').textContent=e.message||'Tempahan gagal.';busy=false;update()}}
function pickRequestedSize(requested){if(!product||!requested)return;const target=sizes().find(s=>String(s).toLowerCase().includes(String(requested).toLowerCase()));if(target){activeSize=target;renderSizes();renderColors();update()}}
function openOrder(requested){if(product){const prices=visible().map(v=>Number(v.price||0)).filter(n=>n>0);meta('AddToCart',{content_ids:[product.id],content_name:product.name,content_category:'Tumbler',content_type:'product',currency:'MYR',value:prices.length?Math.min(...prices):0,num_items:1})}$('orderModal').classList.add('open');$('orderModal').setAttribute('aria-hidden','false');document.body.classList.add('modalOpen');pickRequestedSize(requested);if(matchMedia('(max-width:700px)').matches)$('mobileBar').hidden=false}
function closeOrder(){if(busy)return;$('orderModal').classList.remove('open');$('orderModal').setAttribute('aria-hidden','true');document.body.classList.remove('modalOpen');$('mobileBar').hidden=true}
$('shipping').onchange=update;$('buy').onclick=submit;$('mobileBuy').onclick=submit;document.querySelectorAll('[data-open-order]').forEach(b=>b.onclick=()=>openOrder(b.dataset.openOrder));document.querySelectorAll('[data-close-order]').forEach(b=>b.onclick=closeOrder);document.querySelectorAll('.js-wa-contact').forEach(a=>a.addEventListener('click',()=>meta('Contact',{content_name:'REQOO Custom Tumbler',content_category:'Tumbler'})));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('orderModal').classList.contains('open'))closeOrder()});load();
})();