(()=>{'use strict';
const SHOP='/api/shop',WA='60103982803',ATTR_KEY='reqoo_plaque_attribution_v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const CURATED={basic:'/plaque/assets/v5/hero-plaque.webp?v=2',classic:'/plaque/assets/v5/corporate-plaque.webp?v=2',prestige:'/plaque/assets/v5/premium-3d-plaque.webp?v=2',signature:'/plaque/assets/v5/portrait-plaque.webp?v=2'};
let products=[],shipping=[],selected=null,selectedVariant=0,busy=false,gallery=[];
const money=n=>'RM'+Number(n||0).toFixed(2),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const meta=(event,params={})=>{try{window.REQOO_META?.track?.(event,params)}catch{}};
function cleanTag(v,max=28){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,max)}
function captureAttribution(){const q=new URLSearchParams(location.search),a={utm_source:q.get('utm_source')||'',utm_medium:q.get('utm_medium')||'',utm_campaign:q.get('utm_campaign')||'',utm_content:q.get('utm_content')||'',fbclid:q.get('fbclid')||''};if(Object.values(a).some(Boolean)){try{sessionStorage.setItem(ATTR_KEY,JSON.stringify(a))}catch{}return a}try{return JSON.parse(sessionStorage.getItem(ATTR_KEY)||'{}')||{}}catch{return{}}}
const attribution=captureAttribution();
function orderSource(){const src=cleanTag(attribution.utm_source,14),campaign=cleanTag(attribution.utm_campaign,26);if(src||campaign)return['plaque',src||'direct',campaign].filter(Boolean).join('-').slice(0,50);return'plaque-landing-v8'}
async function get(url,opt){const r=await fetch(url,opt),j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw Error(j.error||'Sambungan gagal');return j}
function image(v){v=String(v||'').trim();if(!v)return'';if(/^https?:\/\//i.test(v)||v.startsWith('/'))return v;v=v.replace(/^\.\//,'');if(v.startsWith('assets/'))return'/shop/'+v;if(v.startsWith('shop/'))return'/'+v;try{return new URL(v,location.origin+'/shop/').href}catch{return''}}
function normVariant(v){if(Array.isArray(v))return{id:'',name:String(v[0]||'Pilihan'),price:Number(v[1]||0),image:image(v[2])};return{id:String(v?.id||''),name:String(v?.name||v?.title||'Pilihan'),price:v?.price!=null?Number(v.price):Number(v?.priceMinor||0)/100,image:image(v?.image||v?.imageUrl)}}
function normProduct(p){let variants=(Array.isArray(p.variants)?p.variants:[]).map(normVariant).filter(v=>v.name&&Number.isFinite(v.price));if(!variants.length){const price=p.price!=null?Number(p.price):Number(p.priceMinor||0)/100;variants=[{id:'',name:'Pilihan standard',price:Number.isFinite(price)?price:0,image:image(p.image||p.imageUrl)}]}return{...p,id:String(p.id),name:String(p.name||'Plaque Custom'),desc:String(p.desc||p.description||''),category:String(p.category||p.productType||''),slug:String(p.slug||''),image:image(p.image||p.imageUrl||p.cover),variants}}
function isPlaque(p){const hay=[p.name,p.category,p.desc,p.slug,p.productType,p.product_type,p.type].filter(Boolean).join(' ').toLowerCase();return hay.includes('plaque')||hay.includes('plak')}
function minPrice(p){const a=p.variants.map(v=>Number(v.price)).filter(n=>n>0);return a.length?Math.min(...a):0}
function overallMinPrice(){const a=products.map(minPrice).filter(n=>n>0);return a.length?Math.min(...a):0}
function firstProduct(){const paid=products.filter(p=>minPrice(p)>0).sort((a,b)=>minPrice(a)-minPrice(b));return paid[0]||products[0]||null}
function curatedCover(p){const live=p?.image||p?.variants?.find(v=>v.image)?.image;if(live)return live;const n=String(p?.name||'').toLowerCase();for(const [key,url] of Object.entries(CURATED))if(n.includes(key))return url;return'/plaque/assets/v5/hero-plaque.webp?v=2'}
function ship(){return shipping.find(x=>String(x.id)===String($('#mShipping')?.value||''))||null}
function variant(){return selected?.variants[selectedVariant]||selected?.variants[0]||null}
function qty(){return Math.max(1,Math.min(999,Number($('#mQty')?.value||1)||1))}
function shortDesc(s){s=String(s||'').replace(/\s+/g,' ').trim();return s.length>92?s.slice(0,89)+'…':s}
function renderProducts(){const grid=$('#plaqueProducts');if(!grid)return;if(!products.length){grid.innerHTML='<div class="productEmpty">Produk plaque sedang dikemaskini. Boleh WhatsApp REQOO untuk tempahan custom.</div>';return}grid.innerHTML=products.map(p=>`<article class="productCard"><button class="productMedia productMediaBtn" type="button" data-buy="${esc(p.id)}" aria-label="Pilih ${esc(p.name)}"><img src="${esc(curatedCover(p))}" alt="${esc(p.name)}" loading="lazy"></button><div class="productBody"><span class="productTag">REQOO PLAQUE</span><h3>${esc(p.name)}</h3>${p.desc?`<p class="productMiniDesc">${esc(shortDesc(p.desc))}</p>`:''}<div class="productBottom"><span class="productPrice">${minPrice(p)?'Dari '+money(minPrice(p)):'Minta sebutharga'}</span><button class="productBtn" data-buy="${esc(p.id)}" type="button">Pilih & Tempah</button></div></div></article>`).join('');$$('[data-buy]').forEach(b=>b.onclick=()=>openProduct(b.dataset.buy))}
function updateShippingAddress(){const field=$('#mAddress')?.closest('.field');if(!field)return;const needed=Number(ship()?.price||0)>0;field.hidden=!needed;if(!needed)$('#mAddress').value=''}
function updateSummary(){if(!selected)return;const v=variant(),price=Number(v?.price||0),q=qty(),sp=Number(ship()?.price||0),quote=!(price>0),sub=price*q,total=sub+sp;$('#mUnit').value=quote?'Sebutharga':money(price);$('#mSubtotal').textContent=quote?'Sebutharga':money(sub);$('#mShipPrice').textContent=money(sp);$('#mTotal').textContent=quote?'Sebutharga':money(total);$('#mPay').textContent=quote?'Minta Sebutharga via WhatsApp':'Tempah & Bayar '+money(total);$('#mobileMiniText').textContent=quote?'Sebutharga':money(total);$('#mobileMiniBtn').textContent=quote?'WhatsApp':'Bayar';updateShippingAddress()}
async function loadGallery(){const cover=curatedCover(selected);gallery=[cover];try{const d=await get(SHOP+'?action=listProductImages&productId='+encodeURIComponent(selected.id)+'&_='+Date.now());gallery.push(...(d.images||[]).map(x=>image(x.url||x.image||x)).filter(Boolean))}catch{}gallery.push(selected.image,...selected.variants.map(v=>v.image));gallery=[...new Set(gallery.filter(Boolean))];if(!gallery.length)gallery=[cover];const w=$('#mThumbs');w.innerHTML=gallery.slice(0,8).map((u,i)=>`<button type="button" class="${i===0?'active':''}" data-src="${esc(u)}"><img src="${esc(u)}" alt="Gambar ${i+1}"></button>`).join('');w.querySelectorAll('button').forEach(b=>b.onclick=()=>{w.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));$('#mMainImg').src=b.dataset.src});$('#mMainImg').src=gallery[0]}
async function openProduct(id){selected=products.find(p=>p.id===String(id));if(!selected)return;selectedVariant=Math.max(0,selected.variants.findIndex(v=>Number(v.price)>0));$('#mName').textContent=selected.name;$('#mDesc').textContent=selected.desc||'Pilih saiz / variasi. Hanya nama pembeli dan nombor WhatsApp wajib untuk mula.';$('#mVariant').innerHTML=selected.variants.map((v,i)=>`<option value="${i}">${esc(v.name)}${Number(v.price)>0?' · '+money(v.price):' · Sebutharga'}</option>`).join('');$('#mVariant').value=String(selectedVariant);['#mCustom','#mNote','#mBuyer','#mPhone','#mEmail','#mAddress'].forEach(s=>$(s).value='');$('#mArtwork').value='';$('#mQty').value='1';$('#mStatus').textContent='';$('#mStatus').className='modalStatus';const optional=$('.optionalOrderDetails');if(optional)optional.open=false;$('#mMainImg').src=curatedCover(selected);const wa='Salam REQOO, saya nak tanya tentang '+selected.name+'.';$('#mWaHelp').href='https://wa.me/'+WA+'?text='+encodeURIComponent(wa);$('#plaqueModal').classList.add('open');$('#plaqueModal').setAttribute('aria-hidden','false');document.body.classList.add('modalOpen');$('#mobileMini').classList.toggle('show',matchMedia('(max-width:700px)').matches);$('#mobileLandingBar')?.classList.add('hiddenByModal');const price=Number(variant()?.price||0);meta('AddToCart',{content_ids:[selected.id],content_name:selected.name,content_type:'product',currency:'MYR',value:price>0?price:0,num_items:1});updateSummary();loadGallery()}
function closeModal(){if(busy)return;$('#plaqueModal').classList.remove('open');$('#plaqueModal').setAttribute('aria-hidden','true');document.body.classList.remove('modalOpen');$('#mobileMini').classList.remove('show');$('#mobileLandingBar')?.classList.remove('hiddenByModal')}
async function artworkData(file){if(!file)return'';if(file.size>2*1024*1024)throw Error('Artwork melebihi 2MB.');if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Artwork mesti PNG, JPG atau WEBP.');return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result||''));r.onerror=()=>rej(Error('Artwork tidak dapat dibaca.'));r.readAsDataURL(file)})}
function fail(el,msg){const s=$('#mStatus');s.className='modalStatus error';s.textContent=msg;if(el){el.focus({preventScroll:true});el.scrollIntoView({behavior:'smooth',block:'center'})}}
async function submit(){if(busy||!selected)return;const v=variant(),price=Number(v?.price||0),q=qty(),custom=$('#mCustom').value.trim(),note=$('#mNote').value.trim();if(!(price>0)){let msg='Salam REQOO, saya ingin sebut harga untuk '+selected.name+(v?' ('+v.name+')':'')+'. Kuantiti: '+q+'.';if(custom)msg+=' Teks/Nama: '+custom+'.';if(note)msg+=' Catatan: '+note+'.';meta('Contact',{content_name:selected.name,content_category:'Plaque Quote'});location.href='https://wa.me/'+WA+'?text='+encodeURIComponent(msg);return}const name=$('#mBuyer').value.trim(),phone=$('#mPhone').value.trim(),email=$('#mEmail').value.trim(),address=$('#mAddress').value.trim();if(!name)return fail($('#mBuyer'),'Sila isi nama anda.');const digits=phone.replace(/\D/g,'');if(digits.length<9||digits.length>15)return fail($('#mPhone'),'Sila isi nombor WhatsApp yang sah.');if(email&&!$('#mEmail').checkValidity())return fail($('#mEmail'),'Sila semak alamat email.');if(Number(ship()?.price||0)>0&&!address)return fail($('#mAddress'),'Sila isi alamat lengkap untuk penghantaran.');const subtotal=price*q,total=subtotal+Number(ship()?.price||0);meta('InitiateCheckout',{content_ids:[selected.id],content_name:selected.name,content_type:'product',currency:'MYR',value:Number(total.toFixed(2)),num_items:q});busy=true;$('#mPay').disabled=true;$('#mobileMiniBtn').disabled=true;$('#mStatus').className='modalStatus';$('#mStatus').textContent='Mencipta tempahan & bayaran…';try{const artwork=await artworkData($('#mArtwork').files[0]),payload={action:'createOrder',payment:'toyyibpay',name,customerName:name,phone,email,address,shippingId:$('#mShipping').value,source:orderSource(),expectedTotalMinor:Math.round(total*100),items:[{productId:selected.id,variantId:v?.id||undefined,variant:v?.name||'Pilihan',variantName:v?.name||'Pilihan',qty:q,nameText:custom,note,artwork}]};const d=await get(SHOP,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),billUrl=d.billUrl||d.payment?.billUrl;sessionStorage.setItem('reqoo_last_order',JSON.stringify(d));$('#mStatus').textContent='Tempahan berjaya masuk sistem REQOO.';if(billUrl){location.href=billUrl;return}$('#mStatus').textContent='Order berjaya. Bayaran akan disahkan oleh REQOO.'}catch(e){$('#mStatus').className='modalStatus error';$('#mStatus').textContent=e.message||'Tempahan gagal. Cuba semula.'}finally{busy=false;$('#mPay').disabled=false;$('#mobileMiniBtn').disabled=false}}
function bindCtas(){$$('[data-open-first]').forEach(x=>x.onclick=e=>{e.preventDefault();const p=firstProduct();if(p)openProduct(p.id);else $('#shop')?.scrollIntoView({behavior:'smooth'})});$$('.js-wa-contact').forEach(a=>a.addEventListener('click',()=>meta('Contact',{content_name:'REQOO Plaque Custom',content_category:'Plaque'})))}
async function load(){const grid=$('#plaqueProducts');try{const [p,s]=await Promise.all([get(SHOP+'?action=listProducts&_='+Date.now()),get(SHOP+'?action=getShipping&_='+Date.now()).catch(()=>({shipping:[]}))]);products=(p.products||[]).map(normProduct).filter(x=>x.active!==false&&isPlaque(x));shipping=Array.isArray(s.shipping)?s.shipping:[];$('#mShipping').innerHTML='<option value="">Pickup / urus kemudian — RM0.00</option>'+shipping.map(x=>`<option value="${esc(x.id)}">${esc(x.name||'Penghantaran')} — ${money(x.price)}</option>`).join('');renderProducts();const low=overallMinPrice();const label=low?'Dari '+money(low):'Lihat harga';if($('#heroFromPrice'))$('#heroFromPrice').textContent=label;if($('#mobileFromPrice'))$('#mobileFromPrice').textContent=label;meta('ViewContent',{content_name:'REQOO Plaque Custom',content_category:'Plaque',content_type:'product_group',currency:'MYR',value:low||0})}catch(e){if(grid)grid.innerHTML='<div class="productEmpty">Produk tidak dapat dimuatkan sekarang. '+esc(e.message)+'</div>'}}
$('#mVariant').onchange=e=>{selectedVariant=Number(e.target.value)||0;updateSummary()};$('#mQty').oninput=updateSummary;$('#mShipping').onchange=updateSummary;$('#mPay').onclick=submit;$('#mobileMiniBtn').onclick=submit;$$('[data-close-modal]').forEach(x=>x.onclick=closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#plaqueModal').classList.contains('open'))closeModal()});$('#mobileMini').classList.remove('show');bindCtas();load();
})();