const JSON_HEADERS = { 'Content-Type': 'application/json; charset=utf-8' };
const ALLOWED_ORIGINS = new Set(['https://admin.reqoo.co','https://shop.reqoo.co','https://reqoo.co','https://www.reqoo.co']);
function json(data,status,origin){const h=new Headers(JSON_HEADERS);h.set('Access-Control-Allow-Origin',ALLOWED_ORIGINS.has(origin)?origin:'null');h.set('Access-Control-Allow-Methods','GET,POST,OPTIONS');h.set('Access-Control-Allow-Headers','Content-Type, X-Admin-Key');h.set('Vary','Origin');return new Response(JSON.stringify(data),{status,headers:h})}
function okAdmin(r,e){const k=r.headers.get('X-Admin-Key');return Boolean(e.ADMIN_KEY&&k&&k===e.ADMIN_KEY)}
async function safeAll(e,sql,...args){try{const {results}=await e.DB.prepare(sql).bind(...args).all();return results||[]}catch{return []}}
function qrValue(raw){let s=String(raw||'').trim();try{if(/^https?:/i.test(s)){const u=new URL(s);s=u.searchParams.get('code')||u.searchParams.get('access')||u.searchParams.get('license')||u.searchParams.get('id')||s}}catch{};s=s.replace(/^REQOO[-_ ]?LICENSE[:# ]/i,'').trim();return s}
async function verify(e,input){const raw=String(input?.qr||input?.code||input?.value||'').trim();if(!raw)throw new Error('QR / license code diperlukan');const value=qrValue(raw);const license=await e.DB.prepare("SELECT id,customer_id,product_id,order_id,access_code,status,max_devices,starts_at,expires_at,created_at,updated_at FROM licenses WHERE access_code=? OR id=? LIMIT 1").bind(value,value).first();if(license){const customer=license.customer_id?await e.DB.prepare('SELECT id,name,phone,email,status FROM customers WHERE id=?').bind(license.customer_id).first():null;const devices=await safeAll(e,'SELECT id,license_id,device_id,device_name,status,first_seen_at,last_seen_at,created_at,updated_at FROM license_devices WHERE license_id=? ORDER BY last_seen_at DESC',license.id);return{valid:true,type:'license',license,customer,devices,raw:value}}
const order=await e.DB.prepare('SELECT id,customer_id,total_minor,payment_status,fulfillment_status,created_at,updated_at FROM orders WHERE id=? LIMIT 1').bind(value).first();if(order){const customer=await e.DB.prepare('SELECT id,name,phone,email,status FROM customers WHERE id=?').bind(order.customer_id).first();return{valid:true,type:'order',order,customer,raw:value}}
return{valid:false,raw:value}}
async function fetchData(e,path){if(path==='/summary'){const [licenses,devices,orders,errors]=await Promise.all([safeAll(e,"SELECT status,COUNT(*) count FROM licenses GROUP BY status"),safeAll(e,"SELECT status,COUNT(*) count FROM license_devices GROUP BY status"),safeAll(e,"SELECT payment_status,COUNT(*) count FROM orders GROUP BY payment_status"),safeAll(e,"SELECT * FROM error_events LIMIT 20")]);return{licenses,devices,orders,error_count:errors.length}}
if(path==='/licenses')return safeAll(e,'SELECT id,customer_id,product_id,order_id,access_code,status,max_devices,starts_at,expires_at,created_at,updated_at FROM licenses ORDER BY created_at DESC LIMIT 200');
if(path==='/devices')return safeAll(e,'SELECT id,license_id,device_id,device_name,status,first_seen_at,last_seen_at,created_at,updated_at FROM license_devices ORDER BY last_seen_at DESC LIMIT 300');
if(path==='/logs'){const activity=await safeAll(e,'SELECT * FROM activity_events ORDER BY created_at DESC LIMIT 100');const errors=await safeAll(e,'SELECT * FROM error_events ORDER BY created_at DESC LIMIT 100');return{activity,errors}}
throw new Error('Unknown PKSK admin resource')}
export async function pkskAdmin(request,env){const origin=request.headers.get('Origin')||'';if(request.method==='OPTIONS')return json({},204,origin);if(!env.DB)return json({error:'D1 binding DB is not configured'},500,origin);if(!okAdmin(request,env))return json({error:'Admin Key required'},401,origin);try{const u=new URL(request.url);if(u.pathname==='/pksk-admin/verify'&&request.method==='POST')return json(await verify(env,await request.json()),200,origin);if(u.pathname.startsWith('/pksk-admin/'))return json(await fetchData(env,u.pathname.slice('/pksk-admin'.length)),200,origin);return json({error:'Not found'},404,origin)}catch(err){return json({error:err?.message||'PKSK admin error'},400,origin)}}
