const TOTAL_SETS=50;
const MAX_DEVICES=3;
const BANK_ORIGIN='https://pksk.sim.reqoo.co';
const AI_WRITING_LIMIT=100;
const AI_WRITING_RPM=60;
const AI_QUESTION_RPM=120;
const AI_WRITING_COOLDOWN_MS=10000;
const H={'content-type':'application/json; charset=UTF-8','cache-control':'no-store','access-control-allow-origin':'https://pksk.sim.reqoo.co','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'Content-Type'};
const clean=v=>String(v??'').trim();
const code=v=>clean(v).toUpperCase();
const now=()=>new Date().toISOString();
const id=p=>`${p}_${crypto.randomUUID()}`;
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:H});
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const envInt=(env,name,fallback,min,max)=>Math.max(min,Math.min(max,Number.parseInt(clean(env?.[name]),10)||fallback));
async function sha256(value){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(value)));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function deviceLabel(ua){const s=String(ua||'');if(/iPhone/i.test(s))return'iPhone';if(/iPad/i.test(s))return'iPad';if(/Android/i.test(s))return'Android';if(/Windows/i.test(s))return'Windows PC';if(/Macintosh|Mac OS X/i.test(s))return'Mac';return'Browser'}
async function license(db,access){return db.prepare('SELECT l.*,c.name AS customer_name,c.phone AS customer_phone,c.email AS customer_email FROM licenses l LEFT JOIN customers c ON c.id=l.customer_id WHERE l.access_code=? LIMIT 1').bind(code(access)).first()}
async function activeLicense(db,access){const l=await license(db,access);if(!l)return null;if(String(l.status).toLowerCase()!=='active')return null;const t=Date.now(),s=Date.parse(l.starts_at||'');if(Number.isFinite(s)&&t<s)return null;const e=Date.parse(l.expires_at||'');if(Number.isFinite(e)&&t>e)return null;return l}
async function ensureDevice(db,l,raw,ua){const key=await sha256(raw);const existing=await db.prepare('SELECT * FROM license_devices WHERE license_id=? AND device_key_hash=? LIMIT 1').bind(l.id,key).first();if(existing){await db.prepare("UPDATE license_devices SET last_seen_at=?,device_label=?,status='active' WHERE id=?").bind(now(),deviceLabel(ua),existing.id).run();return true}const count=await db.prepare("SELECT COUNT(*) AS n FROM license_devices WHERE license_id=? AND status='active'").bind(l.id).first();const limit=Math.max(1,Math.min(MAX_DEVICES,Number(l.max_devices||MAX_DEVICES)));if(Number(count?.n||0)>=limit)return false;await db.prepare("INSERT INTO license_devices (id,license_id,device_key_hash,device_label,first_seen_at,last_seen_at,status) VALUES (?,?,?,?,?,?,?)").bind(id('dev'),l.id,key,deviceLabel(ua),now(),now(),'active').run();return true}
async function requireDevice(db,l,raw){if(!raw)return false;const key=await sha256(raw);return !!(await db.prepare("SELECT id FROM license_devices WHERE license_id=? AND device_key_hash=? AND status='active' LIMIT 1").bind(l.id,key).first())}
function groupPath(n){const start=Math.floor((n-1)/10)*10+1;return`SET ${String(start).padStart(2,'0')}-${String(start+9).padStart(2,'0')}`}
async function loadBank(setNo){const n=Number(setNo);if(!Number.isInteger(n)||n<1||n>TOTAL_SETS)throw Error('Set tidak sah');const u=`${BANK_ORIGIN}/simulator/sets/${encodeURIComponent(groupPath(n))}/data/set${String(n).padStart(2,'0')}.json`;const r=await fetch(u,{cf:{cacheTtl:60}});if(!r.ok)throw Error('Bank soalan canonical tidak dapat dicapai');const b=await r.json();if(!Array.isArray(b.questions)||!b.questions.length)throw Error('Bank soalan kosong');return b}
function answerIndex(q){if(Number.isInteger(Number(q.answerIndex)))return Number(q.answerIndex);if(Number.isInteger(Number(q.answer)))return Number(q.answer);if(Array.isArray(q.weights)&&q.weights.length){let best=0;for(let i=1;i<q.weights.length;i++)if(Number(q.weights[i])>Number(q.weights[best]))best=i;return best}return null}
function scoreWriting(text){const t=String(text||'').trim(),words=t?t.split(/\s+/).length:0,examples=(t.match(/\b(contohnya|sebagai contoh|misalnya|contoh)\b/gi)||[]).length,connectors=(t.match(/\b(selain itu|seterusnya|oleh itu|namun|akhir sekali|kesimpulannya|pada pendapat saya)\b/gi)||[]).length,conclusion=/\b(kesimpulannya|sebagai kesimpulan|akhir kata|ringkasnya)\b/i.test(t);const r=[words>=100?4:Math.min(4,Math.floor(words/25)),Math.min(4,Math.max(1,Math.floor(words/55))),Math.min(4,examples+(words>=140?1:0)),Math.min(4,Math.max(1,1+Math.min(connectors,3))),Math.min(4,(words>=100?2:1)+(conclusion?2:0))];return{words,total:r.reduce((a,b)=>a+b,0)}}
function safeJson(text){try{return JSON.parse(String(text||'').replace(/^```json\s*|\s*```$/g,''))}catch{return null}}
function parseReview(row){return safeJson(row?.review_json)}
async function readyCache(db,cacheKey){const row=await db.prepare("SELECT review_json FROM pksk_ai_cache WHERE cache_key=? AND state='ready' LIMIT 1").bind(cacheKey).first();const review=parseReview(row);return review?{ok:true,review,cached:true}:null}
async function claimCache(db,cacheKey,kind,licenseId=''){const ts=now(),cutoff=new Date(Date.now()-120000).toISOString();await db.prepare("DELETE FROM pksk_ai_cache WHERE cache_key=? AND state='pending' AND created_at<?").bind(cacheKey,cutoff).run();const r=await db.prepare("INSERT OR IGNORE INTO pksk_ai_cache (cache_key,kind,license_id,state,review_json,created_at,updated_at) VALUES (?,?,?,'pending',NULL,?,?)").bind(cacheKey,kind,licenseId||null,ts,ts).run();return Number(r?.meta?.changes||0)>0}
async function waitForCache(db,cacheKey){for(let i=0;i<12;i++){await sleep(750);const hit=await readyCache(db,cacheKey);if(hit)return hit;const row=await db.prepare('SELECT state FROM pksk_ai_cache WHERE cache_key=? LIMIT 1').bind(cacheKey).first();if(!row)return null}return null}
async function saveCache(db,cacheKey,review){await db.prepare("UPDATE pksk_ai_cache SET state='ready',review_json=?,updated_at=? WHERE cache_key=?").bind(JSON.stringify(review),now(),cacheKey).run()}
async function clearPendingCache(db,cacheKey){await db.prepare("DELETE FROM pksk_ai_cache WHERE cache_key=? AND state='pending'").bind(cacheKey).run()}
async function aiRateGate(db,kind,limit){const minute=new Date().toISOString().slice(0,16),windowKey=`${kind}:${minute}`,ts=now();const row=await db.prepare('INSERT INTO pksk_ai_rate_windows (window_key,count,updated_at) VALUES (?,1,?) ON CONFLICT(window_key) DO UPDATE SET count=count+1,updated_at=excluded.updated_at RETURNING count').bind(windowKey,ts).first();return Number(row?.count||1)<=limit}
async function recentWriting(db,licenseId){return db.prepare("SELECT created_at FROM pksk_ai_cache WHERE kind='writing' AND license_id=? ORDER BY created_at DESC LIMIT 1").bind(licenseId).first()}
async function writingUsage(db,licenseId){const row=await db.prepare("SELECT COUNT(*) AS n FROM pksk_ai_usage WHERE license_id=? AND kind='writing'").bind(licenseId).first();return Number(row?.n||0)}
async function logAiUsage(db,licenseId,kind,cacheKey){await db.prepare('INSERT INTO pksk_ai_usage (id,license_id,kind,cache_key,created_at) VALUES (?,?,?,?,?)').bind(id('aiu'),licenseId,kind,cacheKey,now()).run()}
async function aiReview(env,kind,payload){
 const key=clean(env.OPENAI_API_KEY);if(!key)return{ok:false,errorCode:'AI_CONFIG',error:'Semakan AI belum diaktifkan. Hubungi REQOO untuk menyemak API key. [AI_CONFIG]'};
 const isWriting=kind==='writing',text=clean(payload.text).slice(0,isWriting?8000:1800);if(!text)return{ok:false,error:isWriting?'Tulis jawapan dahulu.':'Soalan tidak lengkap.'};
 const schema=isWriting?{type:'object',additionalProperties:false,required:['summary','strengths','improvements','nextSteps','disclaimer'],properties:{summary:{type:'string'},strengths:{type:'array',items:{type:'string'}},improvements:{type:'array',items:{type:'string'}},nextSteps:{type:'array',items:{type:'string'}},disclaimer:{type:'string'}}}:{type:'object',additionalProperties:false,required:['explanation','workingSteps','tip','disclaimer'],properties:{explanation:{type:'string'},workingSteps:{type:'array',items:{type:'string'}},tip:{type:'string'},disclaimer:{type:'string'}}};
 const instruction=isWriting?'Anda guru Bahasa Melayu yang membina keyakinan murid Tahun 6. Semak penulisan latihan, bukan peperiksaan rasmi. Beri maklum balas khusus berpandukan teks, jangan tulis semula karangan penuh, jangan beri markah rasmi, dan jangan minta data peribadi.':'Anda guru Matematik/penaakulan Tahun 6. Terangkan jawapan yang betul secara ringkas dan berlangkah. Hadkan explanation kepada 1-2 ayat, workingSteps maksimum 4 langkah pendek, dan tip kepada 1 ayat. Jika maklumat tidak mencukupi, nyatakan dengan jujur. Jangan reka fakta, jangan beri markah rasmi.';
 const user=isWriting?`Tajuk: ${clean(payload.title).slice(0,500)}\nArahan: ${clean(payload.prompt).slice(0,1000)}\nKarangan murid:\n${text}`:`Soalan: ${text}\nPilihan jawapan: ${clean(payload.options).slice(0,1200)}\nJawapan betul: ${clean(payload.correct).slice(0,300)}`;
 const model=clean(env.PKSK_AI_MODEL)||'gpt-5-mini';
 const body={model,store:false,max_output_tokens:1200,input:[{role:'system',content:[{type:'input_text',text:instruction}]},{role:'user',content:[{type:'input_text',text:user}]}],text:{format:{type:'json_schema',name:isWriting?'pksk_writing_review':'pksk_question_review',strict:true,schema}}};
 if(!isWriting&&/^gpt-5(?:\.|-|$)/i.test(model))body.reasoning={effort:'minimal'};
 let r;try{r=await fetch('https://api.openai.com/v1/responses',{method:'POST',signal:AbortSignal.timeout(45000),headers:{'content-type':'application/json','authorization':`Bearer ${key}`},body:JSON.stringify(body)})}catch(e){const timeout=e?.name==='TimeoutError'||e?.name==='AbortError',errorCode=timeout?'AI_TIMEOUT':'AI_NETWORK';console.warn('pksk_ai_failure',{kind,status:0,errorCode});return{ok:false,errorCode,error:`${timeout?'Semakan AI mengambil masa terlalu lama. Cuba lagi sebentar.':'Sambungan ke perkhidmatan AI gagal. Cuba lagi sebentar.'} [${errorCode}]`}}
 if(!r.ok){
  const body=await r.json().catch(()=>null),providerCode=clean(body?.error?.code),providerType=clean(body?.error?.type);
  let errorCode='AI_PROVIDER_ERROR',message='Perkhidmatan semakan AI tergendala. Cuba lagi sebentar.';
  if([providerCode,providerType].some(x=>['insufficient_quota','billing_hard_limit_reached','billing_not_active','usage_limit_reached'].includes(x))){errorCode='AI_QUOTA';message='Kuota semakan AI tidak tersedia. Hubungi REQOO untuk menyemak kredit atau had penggunaan API.'}
  else if(r.status===401){errorCode='AI_AUTH';message='Sambungan semakan AI belum disahkan. Hubungi REQOO untuk menyemak API key.'}
  else if(providerCode==='model_not_found'||r.status===404){errorCode='AI_MODEL';message='Model semakan AI tidak tersedia. Hubungi REQOO untuk menyemak tetapan model.'}
  else if(r.status===403){errorCode='AI_ACCESS';message='Akses penyedia semakan AI ditolak. Hubungi REQOO untuk menyemak kebenaran API.'}
  else if(r.status===429){errorCode='AI_RATE_LIMIT';message='Semakan AI sedang sibuk. Tunggu sebentar sebelum cuba semula.'}
  else if(r.status===400||r.status===422){errorCode='AI_REQUEST';message='Tetapan permintaan semakan AI tidak diterima. Hubungi REQOO.'}
  console.warn('pksk_ai_failure',{kind,status:r.status,errorCode});
  return{ok:false,errorCode,error:`${message} [${errorCode}]`};
 }
 const data=await r.json(),outputText=data.output_text||(data.output||[]).filter(x=>x.type==='message').flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text).join(''),out=safeJson(outputText);if(out)return{ok:true,review:out};const truncated=clean(data?.incomplete_details?.reason)==='max_output_tokens'||data?.status==='incomplete';if(truncated){console.warn('pksk_ai_failure',{kind,status:r.status,errorCode:'AI_TRUNCATED'});return{ok:false,errorCode:'AI_TRUNCATED',error:'Respons semakan AI terpotong. Cuba lagi. [AI_TRUNCATED]'}}return{ok:false,errorCode:'AI_RESPONSE',error:'Respons semakan AI tidak sah. Cuba lagi. [AI_RESPONSE]'}
}
async function reviewQuestionCached(env,d){const text=clean(d.text).slice(0,1800),options=clean(d.options).slice(0,1200),correct=clean(d.correct).slice(0,300);if(!text||!options||!correct)return{ok:false,error:'Maklumat soalan tidak lengkap.'};const signature=await sha256(JSON.stringify([text,options,correct])),cacheKey=`question:${signature}`;const hit=await readyCache(env.DB,cacheKey);if(hit)return hit;const owner=await claimCache(env.DB,cacheKey,'question','');if(!owner){const waited=await waitForCache(env.DB,cacheKey);return waited||{ok:false,errorCode:'AI_PENDING',error:'Penerangan sedang disediakan. Cuba lagi dalam beberapa saat. [AI_PENDING]'}}const rpm=envInt(env,'PKSK_AI_QUESTION_RPM',AI_QUESTION_RPM,10,1000);if(!(await aiRateGate(env.DB,'question',rpm))){await clearPendingCache(env.DB,cacheKey);return{ok:false,errorCode:'AI_BUSY',error:'Semakan soalan sedang menerima trafik tinggi. Cuba lagi sebentar. [AI_BUSY]'}}const result=await aiReview(env,'question',{text,options,correct});if(result.ok)await saveCache(env.DB,cacheKey,result.review);else await clearPendingCache(env.DB,cacheKey);return result.ok?{...result,cached:false}:result}
async function reviewWritingGuarded(env,l,d){const text=clean(d.text).slice(0,8000),title=clean(d.title).slice(0,500),prompt=clean(d.prompt).slice(0,1000);if(!text)return{ok:false,error:'Tulis jawapan dahulu.'};const signature=await sha256(JSON.stringify([l.id,title,prompt,text])),cacheKey=`writing:${l.id}:${signature}`;const hit=await readyCache(env.DB,cacheKey);if(hit)return hit;const limit=envInt(env,'PKSK_AI_WRITING_LIMIT',AI_WRITING_LIMIT,1,1000),used=await writingUsage(env.DB,l.id);if(used>=limit)return{ok:false,errorCode:'AI_LIMIT',error:`Had semakan AI penulisan untuk lesen ini telah digunakan (${limit}/${limit}). [AI_LIMIT]`};const recent=await recentWriting(env.DB,l.id);if(recent?.created_at){const age=Date.now()-Date.parse(recent.created_at);if(Number.isFinite(age)&&age<AI_WRITING_COOLDOWN_MS)return{ok:false,errorCode:'AI_COOLDOWN',error:`Tunggu ${Math.max(1,Math.ceil((AI_WRITING_COOLDOWN_MS-age)/1000))} saat sebelum semakan AI seterusnya. [AI_COOLDOWN]`}}const owner=await claimCache(env.DB,cacheKey,'writing',l.id);if(!owner){const waited=await waitForCache(env.DB,cacheKey);return waited||{ok:false,errorCode:'AI_PENDING',error:'Semakan penulisan sedang diproses. Cuba lagi dalam beberapa saat. [AI_PENDING]'}}const rpm=envInt(env,'PKSK_AI_WRITING_RPM',AI_WRITING_RPM,10,1000);if(!(await aiRateGate(env.DB,'writing',rpm))){await clearPendingCache(env.DB,cacheKey);return{ok:false,errorCode:'AI_BUSY',error:'Semakan AI sedang menerima trafik tinggi. Cuba lagi sebentar. [AI_BUSY]'}}const result=await aiReview(env,'writing',{text,title,prompt});if(result.ok){await saveCache(env.DB,cacheKey,result.review);await logAiUsage(env.DB,l.id,'writing',cacheKey);return{...result,cached:false,usageRemaining:Math.max(0,limit-used-1)}}await clearPendingCache(env.DB,cacheKey);return result}
async function scoreSet(setNo,answers){const b=await loadBank(setNo);let aScore=0,aMax=0,bCorrect=0,aAnswered=0,bAnswered=0;for(const q of b.questions){if(q.section==='BAHAGIAN A'){const w=Array.isArray(q.weights)?q.weights:[];if(w.length)aMax+=Math.max(...w.map(Number).filter(Number.isFinite),0)}}for(const q of b.questions){const v=answers?.[q.id];if(v===undefined||v===null||v==='')continue;const i=Number(v);if(!Number.isInteger(i))continue;if(q.section==='BAHAGIAN A'){const w=Array.isArray(q.weights)?q.weights:[];if(w[i]!==undefined){aScore+=Number(w[i])||0;aAnswered++}}else if(q.section==='BAHAGIAN B'){bAnswered++;const c=answerIndex(q);if(c!==null&&i===c)bCorrect++}}const bMax=b.questions.filter(q=>q.section==='BAHAGIAN B').length||70;return{scoreA:aMax?Math.round(aScore/aMax*100):0,scoreB:bMax?Math.round(bCorrect/bMax*100):0,aAnswered,bAnswered}}
async function handle(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:H});if(!env.DB)return json({ok:false,error:'CORE_DB_BINDING_MISSING'},503);let d={};try{const u=new URL(request.url);if(request.method==='GET')d=Object.fromEntries(u.searchParams.entries());else if((request.headers.get('content-type')||'').includes('application/json'))d=await request.json();else d=Object.fromEntries(u.searchParams.entries())}catch{return json({ok:false,error:'INVALID_INPUT'},400)}
try{const action=clean(d.action);if(action==='validateAccess'){const l=await activeLicense(env.DB,d.code);if(!l)return json({ok:false,error:'Access Code tidak sah atau license tidak aktif'},401);return json({ok:true,accessCode:l.access_code,maxDevices:Math.max(1,Math.min(MAX_DEVICES,Number(l.max_devices||MAX_DEVICES)))})}
if(action==='registerDevice'){const l=await activeLicense(env.DB,d.code);if(!l)return json({ok:false,error:'Access Code tidak sah atau license tidak aktif'},401);const raw=clean(d.deviceId);if(!raw)return json({ok:false,error:'Maklumat peranti tidak lengkap'},400);const ok=await ensureDevice(env.DB,l,raw,d.userAgent);if(!ok)return json({ok:false,error:`Akses maksimum ${Math.max(1,Math.min(MAX_DEVICES,Number(l.max_devices||MAX_DEVICES)))} peranti telah digunakan.`,limitReached:true},403);const c=await env.DB.prepare("SELECT COUNT(*) AS n FROM license_devices WHERE license_id=? AND status='active'").bind(l.id).first();return json({ok:true,registered:true,deviceCount:Number(c?.n||0),maxDevices:Math.max(1,Math.min(MAX_DEVICES,Number(l.max_devices||MAX_DEVICES)))})}
if(action==='reviewWritingAI'||action==='reviewQuestionAI'){const l=await activeLicense(env.DB,d.code);if(!l)return json({ok:false,error:'Access Code tidak sah atau license tidak aktif'},401);if(!(await requireDevice(env.DB,l,clean(d.deviceId))))return json({ok:false,error:'Peranti belum didaftarkan'},403);return json(action==='reviewWritingAI'?await reviewWritingGuarded(env,l,d):await reviewQuestionCached(env,d))}
if(action==='saveProgress'){const l=await activeLicense(env.DB,d.code);if(!l)return json({ok:false,error:'License tidak aktif'},401);if(!(await requireDevice(env.DB,l,clean(d.deviceId))))return json({ok:false,error:'Peranti belum didaftarkan'},403);const setNo=Number(d.setNo||0),section=clean(d.section||'OVERALL')||'OVERALL';if(!Number.isInteger(setNo)||setNo<1||setNo>TOTAL_SETS)return json({ok:false,error:'Data progress tidak sah'},400);let completed=Boolean(d.completed),score=Number(d.score||0),scoreA=Number(d.scoreA||0),scoreB=Number(d.scoreB||0),scoreC=Number(d.scoreC||0),answered=Number(d.answered||0),essayWords=Number(d.essayWords||0);if(completed){let answers=d.answers;if(typeof answers==='string'){try{answers=JSON.parse(answers)}catch{answers=null}}if(!answers||typeof answers!=='object')return json({ok:false,error:'Jawapan diperlukan untuk mengesahkan skor'},400);const s=await scoreSet(setNo,answers);const c=scoreWriting(d.essayText||'');scoreA=s.scoreA;scoreB=s.scoreB;scoreC=c.total;essayWords=c.words;answered=s.aAnswered+s.bAnswered;score=Math.round((scoreA+scoreB+Math.round(scoreC/20*100))/3)}const ts=now();const old=await env.DB.prepare('SELECT id FROM pksk_progress WHERE license_id=? AND set_no=? AND section=? LIMIT 1').bind(l.id,setNo,section).first();const vals=[l.id,setNo,section,completed?1:0,score,answered,Number(d.timeUsed||0),scoreA,scoreB,scoreC,essayWords,d.answers?String(d.answers).slice(0,200000):'{}',clean(d.startedAt)||null,clean(d.completedAt)||(completed?ts:null),ts];if(old)await env.DB.prepare(`UPDATE pksk_progress SET completed=?,score=?,answered=?,time_used=?,score_a=?,score_b=?,score_c=?,essay_words=?,answers_json=?,started_at=?,completed_at=?,updated_at=? WHERE id=?`).bind(vals.slice(3),old.id).run();else await env.DB.prepare(`INSERT INTO pksk_progress (id,license_id,set_no,section,completed,score,answered,time_used,score_a,score_b,score_c,essay_words,answers_json,started_at,completed_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id('prog'),...vals).run();return json({ok:true,serverScore:score,scoreA,scoreB,scoreC,essayWords})}
if(action==='getCustomerDashboard'){const l=await activeLicense(env.DB,d.code);if(!l)return json({ok:false,error:'Access Code tidak sah atau license tidak aktif'},401);if(!(await requireDevice(env.DB,l,clean(d.deviceId))))return json({ok:false,error:'Peranti belum didaftarkan'},403);const rows=(await env.DB.prepare('SELECT * FROM pksk_progress WHERE license_id=? ORDER BY set_no,section').bind(l.id).all()).results||[],overall=new Map(),any=new Map();for(const x of rows){const n=Number(x.set_no);if(!n)continue;if(!any.has(n))any.set(n,{setNo:n,answered:0,updatedAt:x.updated_at||''});const a=any.get(n);a.answered=Math.max(a.answered,Number(x.answered||0));a.updatedAt=String(x.updated_at||a.updatedAt);if(String(x.section).toUpperCase()==='OVERALL')overall.set(n,x)}const sets=[];for(let n=1;n<=TOTAL_SETS;n++){const o=overall.get(n),a=any.get(n);sets.push({setNo:n,status:o?.completed?'completed':a?.answered>0?'incomplete':'not_started',completed:Boolean(o?.completed),answered:Number(o?.answered||a?.answered||0),score:o?.completed?Number(o.score||0):null,scoreA:o?.completed?Number(o.score_a||0):0,scoreB:o?.completed?Number(o.score_b||0):0,scoreC:o?.completed?Number(o.score_c||0):0,updatedAt:o?.updated_at||a?.updatedAt||''})}const completed=sets.filter(x=>x.completed),scores=completed.map(x=>Number(x.score)).filter(Number.isFinite),devices=(await env.DB.prepare('SELECT id,device_label,first_seen_at,last_seen_at,status FROM license_devices WHERE license_id=? ORDER BY last_seen_at DESC').bind(l.id).all()).results||[],activity=completed.slice().sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0,20).map(x=>({message:`Set ${String(x.setNo).padStart(2,'0')} selesai • Indeks latihan ${x.score}%`,createdAt:x.updatedAt}));return json({ok:true,license:{licenseCode:l.access_code,orderNo:l.order_id,name:l.customer_name,phone:l.customer_phone,status:l.status,createdAt:l.created_at,activeAt:l.starts_at,deviceCount:devices.filter(x=>x.status==='active').length,maxDevices:Math.max(1,Math.min(MAX_DEVICES,Number(l.max_devices||MAX_DEVICES))),lastSeen:devices[0]?.last_seen_at||''},sets,totalSets:TOTAL_SETS,nextSet:Math.min(TOTAL_SETS,completed.length?Math.max(...completed.map(x=>x.setNo))+1:1),allComplete:completed.length>=TOTAL_SETS,summary:{completed:completed.length,incomplete:sets.filter(x=>x.status==='incomplete').length,average:scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):null,best:scores.length?Math.max(...scores):null},activity})}
if(action==='logClientError')return json({ok:true});return json({ok:false,error:'Action PKSK tidak disokong'},400)}catch(e){return json({ok:false,error:e?.message||'Server error'},500)}}
export {handle};