const TOTAL_SETS=50;
const MAX_DEVICES=3;
const BANK_ORIGIN='https://pksk.sim.reqoo.co';
const H={'content-type':'application/json; charset=UTF-8','cache-control':'no-store','access-control-allow-origin':'https://pksk.sim.reqoo.co','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'Content-Type'};
const clean=v=>String(v??'').trim();
const code=v=>clean(v).toUpperCase();
const now=()=>new Date().toISOString();
const id=p=>`${p}_${crypto.randomUUID()}`;
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:H});
async function sha256(value){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(value)));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function deviceLabel(ua){const s=String(ua||'');if(/iPhone/i.test(s))return'iPhone';if(/iPad/i.test(s))return'iPad';if(/Android/i.test(s))return'Android';if(/Windows/i.test(s))return'Windows PC';if(/Macintosh|Mac OS X/i.test(s))return'Mac';return'Browser'}
async function license(db,access){return db.prepare('SELECT l.*,c.name AS customer_name,c.phone AS customer_phone,c.email AS customer_email FROM licenses l LEFT JOIN customers c ON c.id=l.customer_id WHERE l.access_code=? LIMIT 1').bind(code(access)).first()}
async function activeLicense(db,access){const l=await license(db,access);if(!l)return null;if(String(l.status).toLowerCase()!=='active')return null;const t=Date.now(),s=Date.parse(l.starts_at||'');if(Number.isFinite(s)&&t<s)return null;const e=Date.parse(l.expires_at||'');if(Number.isFinite(e)&&t>e)return null;return l}
async function ensureDevice(db,l,raw,ua){const key=await sha256(raw);const existing=await db.prepare('SELECT * FROM license_devices WHERE license_id=? AND device_key_hash=? LIMIT 1').bind(l.id,key).first();if(existing){await db.prepare("UPDATE license_devices SET last_seen_at=?,device_label=?,status='active' WHERE id=?").bind(now(),deviceLabel(ua),existing.id).run();return true}const count=await db.prepare("SELECT COUNT(*) AS n FROM license_devices WHERE license_id=? AND status='active'").bind(l.id).first();const limit=Math.max(1,Math.min(MAX_DEVICES,Number(l.max_devices||MAX_DEVICES)));if(Number(count?.n||0)>=limit)return false;await db.prepare("INSERT INTO license_devices (id,license_id,device_key_hash,device_label,first_seen_at,last_seen_at,status) VALUES (?,?,?,?,?,?,?)").bind(id('dev'),l.id,key,deviceLabel(ua),now(),now(),'active').run();return true}
async function requireDevice(db,l,raw){if(!raw)return false;const key=await sha256(raw);return !!(await db.prepare("SELECT id FROM license_devices WHERE license_id=? AND device_key_hash=? AND status='active' LIMIT 1").bind(l.id,key).first())}
function groupPath(n){const start=Math.floor((n-1)/10)*10+1;return`SET ${String(start).padStart(2,'0')}-${String(start+9).padStart(2,'0')}`}
async function loadBank(setNo){const n=Number(setNo);if(!Number.isInteger(n)||n<1||n>TOTAL_SETS)throw Error('Set tidak sah');const u=`${BANK_ORIGIN}/simulator/sets/${encodeURIComponent(groupPath(n))}/data/set${String(n).padStart(2,'0')}.json`;const r=await fetch(u,{cf:{cacheTtl:60}});if(!r.ok)throw Error('Bank soalan canonical tidak dapat dicapai');const b=await r.json();if(!Array.isArray(b.questions)||!b.questions.length)throw Error('Bank soalan kosong');return b}
function answerIndex(q){if(Number.isInteger(Number(q.answerIndex)))return Number(q.answerIndex);if(Number.isInteger(Number(q.answer)))return Number(q.answer);if(Array.isArray(q.weights)&&q.weights.length){let best=0;for(let i=1;i<q.weights.length;i++)if(Number(q.weights[i])>Number(q.weights[best]))best=i;return best}return null}
function scoreWriting(text){const t=String(text||'').trim(),words=t?t.split(/\s+/).length:0,examples=(t.match(/\b(contohnya|sebagai contoh|misalnya|contoh)\b/gi)||[]).length,connectors=(t.match(/\b(selain itu|seterusnya|oleh itu|namun|akhir sekali|kesimpulannya|pada pendapat saya)\b/gi)||[]).length,conclusion=/\b(kesimpulannya|sebagai kesimpulan|akhir kata|ringkasnya)\b/i.test(t);const r=[words>=100?4:Math.min(4,Math.floor(words/25)),Math.min(4,Math.max(1,Math.floor(words/55))),Math.min(4,examples+(words>=140?1:0)),Math.min(4,Math.max(1,1+Math.min(connectors,3))),Math.min(4,(words>=100?2:1)+(conclusion?2:0))];return{words,total:r.reduce((a,b)=>a+b,0)}}
async function scoreSet(setNo,answers){const b=await loadBank(setNo);let aScore=0,aMax=0,bCorrect=0,aAnswered=0,bAnswered=0;for(const q of b.questions){if(q.section==='BAHAGIAN A'){const w=Array.isArray(q.weights)?q.weights:[];if(w.length)aMax+=Math.max(...w.map(Number).filter(Number.isFinite),0)}}for(const q of b.questions){const v=answers?.[q.id];if(v===undefined||v===null||v==='')continue;const i=Number(v);if(!Number.isInteger(i))continue;if(q.section==='BAHAGIAN A'){const w=Array.isArray(q.weights)?q.weights:[];if(w[i]!==undefined){aScore+=Number(w[i])||0;aAnswered++}}else if(q.section==='BAHAGIAN B'){bAnswered++;const c=answerIndex(q);if(c!==null&&i===c)bCorrect++}}const bMax=b.questions.filter(q=>q.section==='BAHAGIAN B').length||70;return{scoreA:aMax?Math.round(aScore/aMax*100):0,scoreB:bMax?Math.round(bCorrect/bMax*100):0,aAnswered,bAnswered}}
async function handle(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:H});if(!env.DB)return json({ok:false,error:'CORE_DB_BINDING_MISSING'},503);let d={};try{const u=new URL(request.url);if(request.method==='GET')d=Object.fromEntries(u.searchParams.entries());else if((request.headers.get('content-type')||'').includes('application/json'))d=await request.json();else d=Object.fromEntries(u.searchParams.entries())}catch{return json({ok:false,error:'INVALID_INPUT'},400)}
try{const action=clean(d.action);if(action==='validateAccess'){const l=await activeLicense(env.DB,d.code);if(!l)return json({ok:false,error:'Access Code tidak sah atau license tidak aktif'},401);return json({ok:true,accessCode:l.access_code,maxDevices:Math.max(1,Math.min(MAX_DEVICES,Number(l.max_devices||MAX_DEVICES)))})}
if(action==='registerDevice'){const l=await activeLicense(env.DB,d.code);if(!l)return json({ok:false,error:'Access Code tidak sah atau license tidak aktif'},401);const raw=clean(d.deviceId);if(!raw)return json({ok:false,error:'Maklumat peranti tidak lengkap'},400);const ok=await ensureDevice(env.DB,l,raw,d.userAgent);if(!ok)return json({ok:false,error:`Akses maksimum ${Math.max(1,Math.min(MAX_DEVICES,Number(l.max_devices||MAX_DEVICES)))} peranti telah digunakan.`,limitReached:true},403);const c=await env.DB.prepare("SELECT COUNT(*) AS n FROM license_devices WHERE license_id=? AND status='active'").bind(l.id).first();return json({ok:true,registered:true,deviceCount:Number(c?.n||0),maxDevices:Math.max(1,Math.min(MAX_DEVICES,Number(l.max_devices||MAX_DEVICES)))})}
if(action==='saveProgress'){const l=await activeLicense(env.DB,d.code);if(!l)return json({ok:false,error:'License tidak aktif'},401);if(!(await requireDevice(env.DB,l,clean(d.deviceId))))return json({ok:false,error:'Peranti belum didaftarkan'},403);const setNo=Number(d.setNo||0),section=clean(d.section||'OVERALL')||'OVERALL';if(!Number.isInteger(setNo)||setNo<1||setNo>TOTAL_SETS)return json({ok:false,error:'Data progress tidak sah'},400);let completed=Boolean(d.completed),score=Number(d.score||0),scoreA=Number(d.scoreA||0),scoreB=Number(d.scoreB||0),scoreC=Number(d.scoreC||0),answered=Number(d.answered||0),essayWords=Number(d.essayWords||0);if(completed){let answers=d.answers;if(typeof answers==='string'){try{answers=JSON.parse(answers)}catch{answers=null}}if(!answers||typeof answers!=='object')return json({ok:false,error:'Jawapan diperlukan untuk mengesahkan skor'},400);const s=await scoreSet(setNo,answers);const c=scoreWriting(d.essayText||'');scoreA=s.scoreA;scoreB=s.scoreB;scoreC=c.total;essayWords=c.words;answered=s.aAnswered+s.bAnswered;score=Math.round((scoreA+scoreB+Math.round(scoreC/20*100))/3)}const ts=now();const old=await env.DB.prepare('SELECT id FROM pksk_progress WHERE license_id=? AND set_no=? AND section=? LIMIT 1').bind(l.id,setNo,section).first();const vals=[l.id,setNo,section,completed?1:0,score,answered,Number(d.timeUsed||0),scoreA,scoreB,scoreC,essayWords,d.answers?String(d.answers).slice(0,200000):'{}',clean(d.startedAt)||null,clean(d.completedAt)||(completed?ts:null),ts];if(old)await env.DB.prepare(`UPDATE pksk_progress SET completed=?,score=?,answered=?,time_used=?,score_a=?,score_b=?,score_c=?,essay_words=?,answers_json=?,started_at=?,completed_at=?,updated_at=? WHERE id=?`).bind(vals.slice(3),old.id).run();else await env.DB.prepare(`INSERT INTO pksk_progress (id,license_id,set_no,section,completed,score,answered,time_used,score_a,score_b,score_c,essay_words,answers_json,started_at,completed_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id('prog'),...vals).run();return json({ok:true,serverScore:score,scoreA,scoreB,scoreC,essayWords})}
if(action==='getCustomerDashboard'){const l=await activeLicense(env.DB,d.code);if(!l)return json({ok:false,error:'Access Code tidak sah atau license tidak aktif'},401);if(!(await requireDevice(env.DB,l,clean(d.deviceId))))return json({ok:false,error:'Peranti belum didaftarkan'},403);const rows=(await env.DB.prepare('SELECT * FROM pksk_progress WHERE license_id=? ORDER BY set_no,section').bind(l.id).all()).results||[],overall=new Map(),any=new Map();for(const x of rows){const n=Number(x.set_no);if(!n)continue;if(!any.has(n))any.set(n,{setNo:n,answered:0,updatedAt:x.updated_at||''});const a=any.get(n);a.answered=Math.max(a.answered,Number(x.answered||0));a.updatedAt=String(x.updated_at||a.updatedAt);if(String(x.section).toUpperCase()==='OVERALL')overall.set(n,x)}const sets=[];for(let n=1;n<=TOTAL_SETS;n++){const o=overall.get(n),a=any.get(n);sets.push({setNo:n,status:o?.completed?'completed':a?.answered>0?'incomplete':'not_started',completed:Boolean(o?.completed),answered:Number(o?.answered||a?.answered||0),score:o?.completed?Number(o.score||0):null,scoreA:o?.completed?Number(o.score_a||0):0,scoreB:o?.completed?Number(o.score_b||0):0,scoreC:o?.completed?Number(o.score_c||0):0,updatedAt:o?.updated_at||a?.updatedAt||''})}const completed=sets.filter(x=>x.completed),scores=completed.map(x=>Number(x.score)).filter(Number.isFinite),devices=(await env.DB.prepare('SELECT id,device_label,first_seen_at,last_seen_at,status FROM license_devices WHERE license_id=? ORDER BY last_seen_at DESC').bind(l.id).all()).results||[],activity=completed.slice().sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0,20).map(x=>({message:`Set ${String(x.setNo).padStart(2,'0')} selesai • Indeks latihan ${x.score}%`,createdAt:x.updatedAt}));return json({ok:true,license:{licenseCode:l.access_code,orderNo:l.order_id,name:l.customer_name,phone:l.customer_phone,status:l.status,createdAt:l.created_at,activeAt:l.starts_at,deviceCount:devices.filter(x=>x.status==='active').length,maxDevices:Math.max(1,Math.min(MAX_DEVICES,Number(l.max_devices||MAX_DEVICES))),lastSeen:devices[0]?.last_seen_at||''},sets,totalSets:TOTAL_SETS,nextSet:Math.min(TOTAL_SETS,completed.length?Math.max(...completed.map(x=>x.setNo))+1:1),allComplete:completed.length>=TOTAL_SETS,summary:{completed:completed.length,incomplete:sets.filter(x=>x.status==='incomplete').length,average:scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):null,best:scores.length?Math.max(...scores):null},activity})}
if(action==='logClientError')return json({ok:true});return json({ok:false,error:'Action PKSK tidak disokong'},400)}catch(e){return json({ok:false,error:e?.message||'Server error'},500)}}
export {handle};
