const C={
  'access-control-allow-origin':'*',
  'access-control-allow-methods':'GET,POST,OPTIONS',
  'access-control-allow-headers':'Content-Type,X-Admin-Token',
  'cache-control':'no-store'
};
const S=v=>String(v??'').trim();
const ID=p=>`${p}_${crypto.randomUUID()}`;
const NOW=()=>new Date().toISOString();
const R=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json;charset=UTF-8',...C}});
async function body(request){const u=new URL(request.url),q=Object.fromEntries(u.searchParams.entries());if(request.method==='GET')return q;const ct=(request.headers.get('content-type')||'').toLowerCase();if(ct.includes('json'))return {...q,...await request.json()};return q}
async function ensure(env){await env.DB.batch([
  env.DB.prepare("CREATE TABLE IF NOT EXISTS shipping_methods(id TEXT PRIMARY KEY,name TEXT NOT NULL,price_minor INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS promotions(id TEXT PRIMARY KEY,code TEXT NOT NULL UNIQUE,type TEXT NOT NULL DEFAULT 'fixed',value INTEGER NOT NULL DEFAULT 0,min_spend INTEGER NOT NULL DEFAULT 0,starts_at TEXT,ends_at TEXT,usage_limit INTEGER,usage_count INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,title TEXT,product_id TEXT,variant TEXT,promo_price_minor INTEGER,slug TEXT)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS shop_settings(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT NOT NULL)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS order_addresses(order_id TEXT PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,name TEXT,phone TEXT,address TEXT,shipping_method_id TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)")
]);}
async function setting(env,key){return (await env.DB.prepare('SELECT value FROM shop_settings WHERE key=?').bind(key).first())?.value||'';}
function paymentQr(env){return setting(env,'payment_qr_url').then(v=>/maybank-qr-premium\.svg(?:\?|$)/i.test(S(v))?'/shop/maybank-qr.jpg':S(v)||'/shop/maybank-qr.jpg');}
async function trace(env,orderId,type,meta={},customerId=null,productId=null){return env.DB.prepare('INSERT INTO activity_events(id,customer_id,product_id,order_id,event_type,trace_id,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(ID('evt'),customerId,productId,orderId,type,orderId,JSON.stringify(meta),NOW()).run();}
function normPhone(value){let p=S(value).replace(/\D/g,'');if(p.startsWith('0'))p='6'+p;return p;}
function decodeDataUrl(data,allowed,maxBytes){const m=S(data).match(/^data:([^;]+);base64,(.+)$/);if(!m)throw Error('Fail tidak sah');const type=m[1].toLowerCase();if(!allowed.includes(type))throw Error('Format fail tidak disokong');const raw=atob(m[2]);if(raw.length>maxBytes)throw Error(`Fail terlalu besar (maksimum ${Math.round(maxBytes/1024/1024)}MB)`);return{type,bytes:Uint8Array.from(raw,c=>c.charCodeAt(0))}}
async function storeDataUrl(env,data,key,name,allowed,maxBytes){if(!S(data))return null;if(!env.MEDIA)throw Error('Storage fail belum tersedia');const decoded=decodeDataUrl(data,allowed,maxBytes),ext=decoded.type==='application/pdf'?'pdf':decoded.type.split('/')[1].replace(/[^a-z0-9]/gi,'')||'bin',safeName=S(name||'file').replace(/[^a-z0-9._-]/gi,'_').slice(0,120),finalKey=`${key}.${ext}`;await env.MEDIA.put(finalKey,decoded.bytes,{httpMetadata:{contentType:decoded.type,cacheControl:'private, max-age=0'},customMetadata:{originalName:safeName}});return{key:finalKey,name:safeName,type:decoded.type};}
export async function onRequest({request,env}){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:C});if(!env.DB)return R({ok:false,error:'D1 binding DB tidak dijumpai'},503);try{const d=await body(request);await ensure(env);switch(S(d.action||'health')){case'health':return R({ok:true,service:'REQOO SHOP FLOW',version:'QR-V5',db:true});case'paymentConfig':return R({ok:true,method:'QR',qrUrl:await paymentQr(env),accountName:await setting(env,'payment_account_name'),instructions:await setting(env,'payment_instructions')});case'listProducts':return listProducts(env);case'getShipping':return getShipping(env);case'listPromotions':return listPromotions(env);case'getPromotion':return getPromotion(d,env);case'createOrder':return createOrder(d,env);case'getOrder':return getOrder(d,env);case'customerOrders':return customerOrders(d,env);default:return R({ok:false,error:'Action tidak dikenali'},400)}}catch(error){console.error(error);return R({ok:false,error:error?.message||String(error)},500)}}
async function listProducts(env){const products=(await env.DB.prepare("SELECT * FROM products WHERE status='active' ORDER BY created_at DESC").all()).results||[];const variants=(await env.DB.prepare("SELECT * FROM product_variations WHERE status='active' ORDER BY created_at").all()).results||[];const images=(await env.DB.prepare('SELECT * FROM product_images ORDER BY is_cover DESC,sort_order,id').all()).results||[];return R({ok:true,products:products.map(p=>({id:p.id,sku:p.sku||'',name:p.name,category:p.category||p.product_type,productType:p.product_type,fulfillmentType:p.fulfillment_type,description:p.description||'',desc:p.short_description||p.description||'',image:images.find(i=>i.product_id===p.id)?.url||'',basePrice:Number(p.base_price_minor||0)/100,variants:variants.filter(v=>v.product_id===p.id).map(v=>({id:v.id,name:v.name,sku:v.sku||'',price:Number((v.sale_price_minor??v.price_minor)||0)/100,priceMinor:Number((v.sale_price_minor??v.price_minor)||0),stock:v.stock_qty,active:v.status==='active',image:v.image_url||''}))}))});}
async function getShipping(env){const rows=(await env.DB.prepare('SELECT id,name,price_minor,active,sort_order FROM shipping_methods WHERE active=1 ORDER BY sort_order,name').all()).results||[];return R({ok:true,shipping:rows.map(x=>({...x,price:Number(x.price_minor||0)/100,active:!!x.active}))});}
async function listPromotions(env){const t=NOW(),rows=(await env.DB.prepare("SELECT pr.*,p.name product_name,i.url product_image FROM promotions pr LEFT JOIN products p ON p.id=pr.product_id LEFT JOIN product_images i ON i.product_id=pr.product_id AND i.is_cover=1 WHERE pr.active=1 AND (pr.starts_at IS NULL OR pr.starts_at<=?) AND (pr.ends_at IS NULL OR pr.ends_at>=?) AND (pr.usage_limit IS NULL OR pr.usage_count<pr.usage_limit) ORDER BY pr.created_at DESC").bind(t,t).all()).results||[];return R({ok:true,promotions:rows.map(x=>({id:x.id,code:x.code,title:x.title||x.product_name||x.code,slug:x.slug||String(x.code).toLowerCase(),productId:x.product_id||'',variant:x.variant||'',image:x.product_image||'',promoPrice:Number(x.promo_price_minor||0)/100,start:x.starts_at||'',end:x.ends_at||''}))});}
async function getPromotion(d,env){const r=await listPromotions(env),j=await r.json();return R({ok:true,promotion:(j.promotions||[]).find(x=>x.slug===S(d.slug))||null});}
async function createOrder(d,env){const name=S(d.name||d.customerName),phone=normPhone(d.phone),email=S(d.email),address=S(d.address),items=Array.isArray(d.items)?d.items:[];if(!name||!phone||!items.length)return R({ok:false,error:'Maklumat order tidak lengkap'},400);const rows=[];for(const item of items){const productId=S(item.productId||item.id),variantId=S(item.variantId),variantName=S(item.variant||item.variantName||item.size),qty=Math.max(1,Math.min(999,Number(item.qty||1)));if(!productId||(!variantId&&!variantName))return R({ok:false,error:'Item order tidak lengkap'},400);const product=variantId?await env.DB.prepare("SELECT p.id,p.sku,p.name,p.product_type,p.fulfillment_type,p.base_price_minor,p.status,v.id variation_id,v.sku variation_sku,v.name variation_name,v.price_minor,v.sale_price_minor,v.stock_qty,v.status variation_status FROM products p JOIN product_variations v ON v.product_id=p.id WHERE p.id=? AND v.id=? LIMIT 1").bind(productId,variantId).first():await env.DB.prepare("SELECT p.id,p.sku,p.name,p.product_type,p.fulfillment_type,p.base_price_minor,p.status,v.id variation_id,v.sku variation_sku,v.name variation_name,v.price_minor,v.sale_price_minor,v.stock_qty,v.status variation_status FROM products p JOIN product_variations v ON v.product_id=p.id WHERE p.id=? AND v.name=? LIMIT 1").bind(productId,variantName).first();if(!product||product.status!=='active'||product.variation_status!=='active')return R({ok:false,error:`Produk/variant tidak tersedia: ${productId} / ${variantName||variantId}`},400);if(product.stock_qty!=null&&Number(product.stock_qty)<qty)return R({ok:false,error:`Stok tidak mencukupi: ${product.name} / ${product.variation_name}`},400);let unit=Number(product.sale_price_minor??product.price_minor??0);if(unit<=0&&Number(product.base_price_minor||0)>0)unit=Number(product.base_price_minor);if(product.product_type==='physical'&&unit<=0)return R({ok:false,error:`Harga belum ditetapkan untuk produk: ${product.name} / ${product.variation_name}`},400);const promo=await env.DB.prepare("SELECT * FROM promotions WHERE active=1 AND product_id=? AND variant=? AND (starts_at IS NULL OR starts_at<=?) AND (ends_at IS NULL OR ends_at>=?) AND (usage_limit IS NULL OR usage_count<usage_limit) ORDER BY created_at DESC LIMIT 1").bind(productId,product.variation_name,NOW(),NOW()).first();if(promo&&promo.promo_price_minor!=null){const pp=Number(promo.promo_price_minor);if(pp>0&&pp<unit)unit=pp;}rows.push({productId:product.id,variationId:product.variation_id,sku:product.variation_sku||product.sku||'',name:product.name,variant:product.variation_name,qty,unit,line:unit*qty,promoId:promo?.id||'',text:S(item.nameText||item.name),note:S(item.note),artwork:S(item.artwork)});}
const subtotal=rows.reduce((sum,row)=>sum+row.line,0);let shipping=0,shippingId=S(d.shippingId);if(shippingId){const sh=await env.DB.prepare('SELECT id,price_minor FROM shipping_methods WHERE id=? AND active=1').bind(shippingId).first();if(!sh)return R({ok:false,error:'Kaedah penghantaran tidak sah'},400);shipping=Number(sh.price_minor||0)}const total=subtotal+shipping;if(total<=0)return R({ok:false,error:'Jumlah order mesti lebih daripada RM0.'},400);const t=NOW(),orderNo=`RQ${t.slice(0,10).replace(/-/g,'')}-${crypto.randomUUID().slice(0,5).toUpperCase()}`;
const receipt=S(d.receipt?.data)?await storeDataUrl(env,d.receipt.data,`shop/receipts/${orderNo}/${crypto.randomUUID()}`,S(d.receipt.name),['image/png','image/jpeg','image/webp','application/pdf'],5*1024*1024):null;for(let i=0;i<rows.length;i++){const row=rows[i];if(row.artwork)row.artworkMeta=await storeDataUrl(env,row.artwork,`shop/artwork/${orderNo}/${crypto.randomUUID()}`,`artwork-${i+1}`,['image/png','image/jpeg','image/webp'],2*1024*1024);delete row.artwork;}
const customerId=ID('cus'),orderId=ID('ord');let customer=await env.DB.prepare('SELECT * FROM customers WHERE phone=? LIMIT 1').bind(phone).first();if(customer)await env.DB.prepare('UPDATE customers SET name=?,email=?,updated_at=? WHERE id=?').bind(name,email,t,customer.id).run();else{customer={id:customerId};await env.DB.prepare('INSERT INTO customers(id,name,phone,email,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(customerId,name,phone,email,'active',t,t).run();}
await env.DB.prepare("INSERT INTO orders(id,customer_id,source,currency,subtotal_minor,discount_minor,shipping_minor,tax_minor,total_minor,payment_status,fulfillment_status,referral_code,order_no,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(orderId,customer.id,'shop','MYR',subtotal,0,shipping,0,total,'pending','pending',S(d.referralCode)||null,orderNo,t,t).run();for(const row of rows)await env.DB.prepare('INSERT INTO order_items(id,order_id,product_id,variation_id,product_name_snapshot,sku_snapshot,variation_snapshot_json,customization_snapshot_json,addons_snapshot_json,unit_price_minor,quantity,line_total_minor,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(ID('item'),orderId,row.productId,row.variationId,row.name,row.sku,JSON.stringify({name:row.variant,promoId:row.promoId}),JSON.stringify({text:row.text,note:row.note,artworkKey:row.artworkMeta?.key||'',artworkName:row.artworkMeta?.name||'',artworkType:row.artworkMeta?.type||''}),JSON.stringify([]),row.unit,row.qty,row.line,t).run();await env.DB.prepare('INSERT OR REPLACE INTO order_addresses(order_id,name,phone,address,shipping_method_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(orderId,name,phone,address,shippingId||null,t,t).run();const receiptMeta=receipt?{receiptKey:receipt.key,receiptName:receipt.name,receiptType:receipt.type,receiptUploadedAt:t}:{};const paymentId=ID('pay');await env.DB.prepare('INSERT INTO payments(id,order_id,provider,method,amount_minor,currency,status,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(paymentId,orderId,'manual_qr','qr',total,'MYR','pending',JSON.stringify(receiptMeta),t,t).run();await trace(env,orderId,'order.created',{orderNo,total,items:rows.length,receipt:!!receiptMeta.receiptKey},customer.id,rows[0]?.productId||null);if(receiptMeta.receiptKey)await trace(env,orderId,'payment.receipt_uploaded',{name:receiptMeta.receiptName,type:receiptMeta.receiptType},customer.id,null);for(const row of rows.filter(x=>x.promoId))await env.DB.prepare('UPDATE promotions SET usage_count=usage_count+1,updated_at=? WHERE id=? AND active=1 AND (usage_limit IS NULL OR usage_count<usage_limit)').bind(t,row.promoId).run();return R({ok:true,orderId,orderRef:orderNo,status:'PENDING_PAYMENT',amount:total/100,payment:{provider:'MANUAL_QR',method:'QR',status:'PENDING',qrUrl:await paymentQr(env)}});}
async function getOrder(d,env){const key=S(d.orderRef||d.orderId||d.orderNo),order=await env.DB.prepare('SELECT o.*,c.name customer_name,c.phone,c.email FROM orders o LEFT JOIN customers c ON c.id=o.customer_id WHERE o.id=? OR o.order_no=? LIMIT 1').bind(key,key).first();if(!order)return R({ok:false,error:'Order tidak dijumpai'},404);const items=(await env.DB.prepare('SELECT * FROM order_items WHERE order_id=? ORDER BY created_at').bind(order.id).all()).results||[],payments=(await env.DB.prepare('SELECT id,order_id,provider,provider_reference,method,amount_minor,currency,status,metadata_json,paid_at,created_at,updated_at FROM payments WHERE order_id=? ORDER BY created_at DESC').bind(order.id).all()).results||[],address=await env.DB.prepare('SELECT name,phone,address,shipping_method_id FROM order_addresses WHERE order_id=?').bind(order.id).first();return R({ok:true,order:{...order,orderNo:order.order_no,name:order.customer_name||'',total:Number(order.total_minor||0)/100,subtotal:Number(order.subtotal_minor||0)/100,shipping:Number(order.shipping_minor||0)/100,discount:Number(order.discount_minor||0)/100,items,payments,address:address||null}});}
async function customerOrders(d,env){const phone=normPhone(d.phone);if(!phone)return R({ok:false,error:'No. WhatsApp diperlukan'},400);const customer=await env.DB.prepare('SELECT id,name,phone,email FROM customers WHERE phone=? LIMIT 1').bind(phone).first();if(!customer)return R({ok:false,error:'Pelanggan tidak dijumpai'},404);const orders=(await env.DB.prepare('SELECT * FROM orders WHERE customer_id=? ORDER BY created_at DESC LIMIT 100').bind(customer.id).all()).results||[];return R({ok:true,customer,orders:orders.map(o=>({...o,orderNo:o.order_no,total:Number(o.total_minor||0)/100}))});}