const CORS={'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'Content-Type,X-Admin-Token','cache-control':'no-store'};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json;charset=UTF-8',...CORS}});
const s=v=>String(v??'').trim();
const id=p=>`${p}_${crypto.randomUUID()}`;
function adminOK(r,e,d){const supplied=s(r.headers.get('X-Admin-Token')||d?.token);const expected=s(e.REQOO_ADMIN_TOKEN||e.PKSK_ADMIN_TOKEN||e.ADMIN_KEY);return !!expected&&supplied===expected}
async function input(request){if(request.method==='GET')return Object.fromEntries(new URL(request.url).searchParams);try{return await request.json()}catch{return{}}}
async function summary(e){const q=async sql=>e.DB.prepare(sql).first();const [customers,orders,paid,pending,licenses,devices,completed,incomplete,referrals,userLogs,adminActions]=await Promise.all([
 q('SELECT COUNT(*) n FROM customers'),q('SELECT COUNT(*) n FROM orders'),q("SELECT COUNT(*) n FROM orders WHERE payment_status='paid'"),q("SELECT COUNT(*) n FROM orders WHERE payment_status='pending'"),q("SELECT COUNT(*) n FROM licenses WHERE status='active'"),q("SELECT COUNT(*) n FROM license_devices WHERE status='active'"),q('SELECT COUNT(*) n FROM pksk_progress WHERE completed=1'),q('SELECT COUNT(*) n FROM pksk_progress WHERE completed=0 AND answered>0'),q("SELECT COUNT(*) n FROM referrals WHERE lower(status)='active'"),q('SELECT COUNT(*) n FROM activity_events'),q('SELECT COUNT(*) n FROM admin_audit_events')
]);return{ok:true,customers:Number(customers?.n||0),orders:Number(orders?.n||0),paid:Number(paid?.n||0),pending:Number(pending?.n||0),activeLicenses:Number(licenses?.n||0),activeDevices:Number(devices?.n||0),completedSets:Number(completed?.n||0),incompleteSets:Number(incomplete?.n||0),referrals:Number(referrals?.n||0),userLogs:Number(userLogs?.n||0),adminActions:Number(adminActions?.n||0),devices:Number(devices?.n||0)}}
async function licenses(d,e){const lim=Math.min(500,Math.max(1,Number(d.limit||200)));const r=(await e.DB.prepare(`SELECT l.*,c.name customer_name,c.phone,c.email,o.payment_status,o.order_no FROM licenses l LEFT JOIN customers c ON c.id=l.customer_id LEFT JOIN orders o ON o.id=l.order_id ORDER BY l.created_at DESC LIMIT ?`).bind(lim).all()).results||[];return{ok:true,licenses:r}}
async function orders(d,e){const lim=Math.min(500,Math.max(1,Number(d.limit||200)));const r=(await e.DB.prepare(`SELECT o.*,c.name customer_name,c.phone,c.email,p.provider_reference payment_ref,p.paid_at FROM orders o LEFT JOIN customers c ON c.id=o.customer_id LEFT JOIN payments p ON p.id=(SELECT id FROM payments WHERE order_id=o.id ORDER BY created_at DESC LIMIT 1) ORDER BY o.created_at DESC LIMIT ?`).bind(lim).all()).results||[];return{ok:true,orders:r.map(x=>({...x,amount:Number(x.total_minor||0)/100,orderNo:x.order_no||x.id,access_code:null}))}}
async function devices(d,e){const lim=Math.min(1000,Math.max(1,Number(d.limit||500)));const r=(await e.DB.prepare(`SELECT ld.id,ld.device_key_hash device_key,ld.device_label device_name,l.access_code,c.name customer_name,c.phone,ld.first_seen_at first_seen,ld.last_seen_at last_seen,ld.status FROM license_devices ld JOIN licenses l ON l.id=ld.license_id LEFT JOIN customers c ON c.id=l.customer_id ORDER BY ld.last_seen_at DESC LIMIT ?`).bind(lim).all()).results||[];return{ok:true,devices:r}}
async function progress(d,e){const lim=Math.min(2000,Math.max(1,Number(d.limit||1000)));const r=(await e.DB.prepare(`SELECT p.*,l.access_code,c.name customer_name FROM pksk_progress p JOIN licenses l ON l.id=p.license_id LEFT JOIN customers c ON c.id=l.customer_id ORDER BY p.updated_at DESC LIMIT ?`).bind(lim).all()).results||[];return{ok:true,progress:r}}
async function referrals(d,e){const lim=Math.min(500,Math.max(1,Number(d.limit||200)));const agents=(await e.DB.prepare('SELECT * FROM referrals ORDER BY created_at DESC LIMIT ?').bind(lim).all()).results||[];const events=(await e.DB.prepare(`SELECT ra.code_snapshot referral_code,ra.order_id,c.phone,o.total_minor,r.default_commission_value,r.commission_type,rc.amount_minor commission,rc.status,ra.created_at FROM referral_attributions ra JOIN referrals r ON r.id=ra.referral_id LEFT JOIN customers c ON c.id=ra.customer_id LEFT JOIN orders o ON o.id=ra.order_id LEFT JOIN referral_commissions rc ON rc.order_id=ra.order_id ORDER BY ra.created_at DESC LIMIT ?`).bind(lim).all()).results||[];return{ok:true,agents:agents.map(x=>({referral_code:x.code,name:x.name,status:x.status,commission:x.commission_type==='percent'?`${x.default_commission_value}%`:`RM${Number(x.default_commission_value||0).toFixed(2)}`})),events:events.map(x=>({...x,amount:Number(x.total_minor||0)/100,commission:Number(x.commission||0)/100}))}}
async function logs(d,e){const lim=Math.min(1000,Math.max(1,Number(d.limit||300)));const user=(await e.DB.prepare(`SELECT 'activity' level,event_type event,created_at,metadata_json,'-' access_code,'-' device_key_hash FROM activity_events ORDER BY created_at DESC LIMIT ?`).bind(lim).all()).results||[];const errs=(await e.DB.prepare(`SELECT 'error' level,error_code event,created_at,message,metadata_json,'-' access_code,'-' device_key_hash FROM error_events ORDER BY created_at DESC LIMIT ?`).bind(lim).all()).results||[];const audits=(await e.DB.prepare(`SELECT 'admin' level,action event,created_at,reason message,after_json metadata_json,'-' access_code,'-' device_key_hash FROM admin_audit_events ORDER BY created_at DESC LIMIT ?`).bind(lim).all()).results||[];return{ok:true,userLogs:[...user,...errs].sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,lim),adminLogs:audits}}
async function lookup(d,e){const access=s(d.code||d.access_code).toUpperCase();if(!access)return{ok:false,error:'Access Code diperlukan'};const l=await e.DB.prepare(`SELECT l.*,c.name customer_name,c.phone,c.email,o.order_no,o.payment_status,o.total_minor FROM licenses l LEFT JOIN customers c ON c.id=l.customer_id LEFT JOIN orders o ON o.id=l.order_id WHERE l.access_code=? LIMIT 1`).bind(access).first();if(!l)return{ok:false,error:'License tidak dijumpai'};const [dev,prog,orders,activity,errors]=await Promise.all([e.DB.prepare('SELECT id,device_label,first_seen_at,last_seen_at,status FROM license_devices WHERE license_id=? ORDER BY last_seen_at DESC').bind(l.id).all(),e.DB.prepare('SELECT * FROM pksk_progress WHERE license_id=? ORDER BY set_no,section').bind(l.id).all(),e.DB.prepare('SELECT o.*,p.provider_reference,p.status payment_status,p.paid_at FROM orders o LEFT JOIN payments p ON p.order_id=o.id WHERE o.id=? ORDER BY p.created_at DESC').bind(l.order_id).all(),e.DB.prepare('SELECT * FROM activity_events WHERE license_id=? ORDER BY created_at DESC LIMIT 100').bind(l.id).all(),e.DB.prepare('SELECT * FROM error_events WHERE customer_id=? ORDER BY created_at DESC LIMIT 100').bind(l.customer_id).all()]);return{ok:true,license:l,devices:dev.results||[],progress:prog.results||[],orders:orders.results||[],activity:activity.results||[],errors:errors.results||[]}}
async function reset(d,e){const access=s(d.code||d.access_code).toUpperCase(),l=await e.DB.prepare('SELECT id,customer_id,access_code FROM licenses WHERE access_code=? LIMIT 1').bind(access).first();if(!l)return{ok:false,error:'License tidak dijumpai'};await e.DB.prepare('DELETE FROM pksk_progress WHERE license_id=?').bind(l.id).run();await e.DB.prepare('INSERT INTO admin_audit_events (id,actor_id,action,target_type,target_id,reason,before_json,after_json,trace_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id('audit'),null,'pksk.progress.reset','license',l.id,s(d.reason)||'Admin reset progress',null,JSON.stringify({access_code:access}),s(d.trace_id)||null,new Date().toISOString()).run();return{ok:true,reset:true,access_code:access}}
async function remove(d,e){const access=s(d.code||d.access_code).toUpperCase(),l=await e.DB.prepare('SELECT * FROM licenses WHERE access_code=? LIMIT 1').bind(access).first();if(!l)return{ok:false,error:'License tidak dijumpai'};await e.DB.prepare('DELETE FROM licenses WHERE id=?').bind(l.id).run();await e.DB.prepare('INSERT INTO admin_audit_events (id,actor_id,action,target_type,target_id,reason,before_json,after_json,trace_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id('audit'),null,'pksk.license.delete','license',l.id,s(d.reason)||'Admin delete license',JSON.stringify(l),null,s(d.trace_id)||null,new Date().toISOString()).run();return{ok:true,deleted:true,access_code:access}}
async function resend(d,e){const access=s(d.code||d.access_code).toUpperCase(),l=await e.DB.prepare('SELECT l.*,c.name customer_name,c.phone,c.email FROM licenses l LEFT JOIN customers c ON c.id=l.customer_id WHERE l.access_code=? LIMIT 1').bind(access).first();if(!l)return{ok:false,error:'License tidak dijumpai'};await e.DB.prepare('INSERT INTO activity_events (id,customer_id,product_id,order_id,license_id,event_type,trace_id,metadata_json,created_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(id('evt'),l.customer_id,l.product_id,l.order_id,l.id,'license.resend',s(d.trace_id)||null,JSON.stringify({access_code:access}),new Date().toISOString()).run();return{ok:true,access_code:access,customer:l.customer_name,phone:l.phone,email:l.email}}
async function seedLog(d,e){const access=s(d.code||d.access_code).toUpperCase(),l=access?await e.DB.prepare('SELECT * FROM licenses WHERE access_code=? LIMIT 1').bind(access).first():null;await e.DB.prepare('INSERT INTO error_events (id,customer_id,order_id,trace_id,endpoint,error_code,message,metadata_json,created_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(id('err'),l?.customer_id||null,l?.order_id||null,s(d.trace_id)||null,'/api/sim-admin-v2','ADMIN_SEED_LOG',s(d.message)||'Admin test log',JSON.stringify({access_code:access}),new Date().toISOString()).run();return{ok:true}}
export async function onRequest({request,env}){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});if(!env.DB)return json({ok:false,error:'D1 binding DB tidak dijumpai'},503);try{const d=await input(request);if(!adminOK(request,env,d))return json({ok:false,error:'Unauthorized'},401);const a=s(d.action||'summary');const map={summary,licenses,orders,devices,progress,referrals,logs,lookup,reset,delete:remove,resend,seedLog};const fn=map[a];if(!fn)return json({ok:false,error:'Action tidak dikenali'},400);return json(await fn(d,env))}catch(e){console.error(e);return json({ok:false,error:e?.message||String(e)},500)}}
