const CORS={'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'Content-Type,X-Admin-Token','cache-control':'no-store'};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json;charset=UTF-8',...CORS}});
const s=v=>String(v??'').trim();
function ok(r,e,d){const supplied=s(r.headers.get('X-Admin-Token')||d.token),expected=s(e.REQOO_ADMIN_TOKEN||e.PKSK_ADMIN_TOKEN||e.ADMIN_KEY);return !!expected&&supplied===expected}
export async function onRequest({request,env}){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});if(!env.DB)return json({ok:false,error:'D1 binding DB tidak dijumpai'},503);try{const d=request.method==='GET'?Object.fromEntries(new URL(request.url).searchParams):await request.json();if(!ok(request,env,d))return json({ok:false,error:'Unauthorized'},401);const a=s(d.action||'summary');if(a==='summary')return summary(env);if(a==='listCustomers')return customers(d,env);if(a==='listOrders')return orders(d,env);if(a==='listReferrals')return referrals(d,env);if(a==='checkPhone')return checkPhone(d,env);if(a==='listTables')return tables(env);return json({ok:false,error:'Action tidak dikenali'},400)}catch(e){return json({ok:false,error:String(e?.message||e)},500)}}
async function summary(e){const c=await e.DB.prepare('SELECT COUNT(*) n FROM customers').first(),o=await e.DB.prepare('SELECT COUNT(*) n FROM orders').first(),r=await e.DB.prepare("SELECT COUNT(*) n FROM referrals WHERE lower(status)='active'").first();return{ok:true,customers:Number(c?.n||0),orders:Number(o?.n||0),paid:Number((await e.DB.prepare("SELECT COUNT(*) n FROM orders WHERE payment_status='paid'").first())?.n||0),pending:Number((await e.DB.prepare("SELECT COUNT(*) n FROM orders WHERE payment_status='pending'").first())?.n||0),referrals:Number(r?.n||0)}}
async function customers(d,e){const lim=Math.min(500,Math.max(1,Number(d.limit||100)));const rows=(await e.DB.prepare('SELECT * FROM customers ORDER BY created_at DESC LIMIT ?').bind(lim).all()).results||[];return{ok:true,customers:rows}}
async function orders(d,e){const lim=Math.min(500,Math.max(1,Number(d.limit||100)));const rows=(await e.DB.prepare('SELECT o.*,c.name customer_name,c.phone,c.email FROM orders o LEFT JOIN customers c ON c.id=o.customer_id ORDER BY o.created_at DESC LIMIT ?').bind(lim).all()).results||[];return{ok:true,orders:rows.map(o=>({...o,name:o.customer_name||'',orderNo:o.order_no||o.id,amount:Number(o.total_minor||0)/100,timestamp:o.created_at}))}}
async function referrals(d,e){const lim=Math.min(500,Math.max(1,Number(d.limit||100)));const rows=(await e.DB.prepare('SELECT * FROM referrals ORDER BY created_at DESC LIMIT ?').bind(lim).all()).results||[];return{ok:true,referrals:rows.map(x=>({...x,code:x.code}))}}
async function checkPhone(d,e){const p=s(d.phone);if(!p)return{ok:false,error:'Nombor telefon diperlukan'};const c=await e.DB.prepare('SELECT * FROM customers WHERE phone=? LIMIT 1').bind(p).first();return{ok:true,phone:p,exists:!!c,customer:c||null}}
async function tables(e){const r=await e.DB.prepare("SELECT name,type FROM sqlite_master WHERE type IN ('table','trigger','index') ORDER BY type,name").all();return{ok:true,objects:r.results||[]}}
