const JSON_HEADERS = { 'Content-Type': 'application/json; charset=utf-8' };

function allowedOrigin(origin) { return ['https://admin.reqoo.co','https://shop.reqoo.co','https://reqoo.co','https://www.reqoo.co'].includes(origin); }
function headers(origin) { return { ...JSON_HEADERS, 'Access-Control-Allow-Origin': allowedOrigin(origin) ? origin : 'null', 'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type, X-Admin-Key', Vary: 'Origin' }; }
function json(data,status,origin){ return new Response(JSON.stringify(data),{status:status??200,headers:headers(origin)}); }
function admin(request,env){ const key=request.headers.get('X-Admin-Key'); return Boolean(env.ADMIN_KEY&&key&&key===env.ADMIN_KEY); }
function now(){ return new Date().toISOString(); }
function slugify(v){ return String(v||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''); }
function cleanProduct(input){
 const name=String(input?.name||'').trim(); if(!name) throw new Error('Product name is required');
 const slug=slugify(input?.slug||name); if(!slug) throw new Error('Product slug is required');
 const priceRM=Number(input?.price??0); if(!Number.isFinite(priceRM)||priceRM<0) throw new Error('Invalid product price');
 const base=Number.isInteger(input?.base_price_minor)?input.base_price_minor:Math.round(priceRM*100);
 const sale=input?.sale_price_minor==null||input?.sale_price_minor===''?null:Number(input.sale_price_minor);
 const status=input?.status||(input?.published?'active':'draft'); if(!['draft','active','hidden','out_of_stock','archived'].includes(status)) throw new Error('Invalid product status');
 const product_type=input?.product_type||'physical', fulfillment_type=input?.fulfillment_type||'physical_shipping';
 if(!['physical','digital','licensed','play_access','service'].includes(product_type)) throw new Error('Invalid product type');
 if(!['physical_shipping','digital_delivery','licensed_access','play_access','service_custom'].includes(fulfillment_type)) throw new Error('Invalid fulfillment type');
 return {name,slug,description:String(input?.description||'').trim(),short_description:String(input?.short_description||'').trim(),product_type,fulfillment_type,base_price_minor:base,sale_price_minor:sale,currency:String(input?.currency||'MYR'),status,internal_notes:String(input?.internal_notes||'').trim(),production_instructions:String(input?.production_instructions||'').trim(),seo_title:String(input?.seo_title||'').trim(),seo_description:String(input?.seo_description||'').trim(),images:Array.isArray(input?.images)?input.images.map(v=>String(v).trim()).filter(Boolean).slice(0,12):[]};
}
function cleanCustomer(input){ const name=String(input?.name||'').trim(); if(!name) throw new Error('Customer name is required'); return {id:crypto.randomUUID(),name,phone:String(input?.phone||'').trim()||null,email:String(input?.email||'').trim().toLowerCase()||null,status:input?.status||'active'}; }
function cleanOrder(input){ const currency=String(input?.currency||'MYR').toUpperCase(),source=String(input?.source||'shop'),items=Array.isArray(input?.items)?input.items:[]; if(!items.length) throw new Error('Order requires at least one item'); if(!['shop','admin','sim','play','other'].includes(source)) throw new Error('Invalid order source'); if(currency.length!==3) throw new Error('Invalid currency'); return {currency,source,customer_id:input?.customer_id||null,items,referral_code:input?.referral_code||null}; }
async function productRow(env,id){ const row=await env.DB.prepare('SELECT id,sku,name,slug,product_type,fulfillment_type,description,short_description,base_price_minor,sale_price_minor,currency,status,internal_notes,production_instructions,seo_title,seo_description,created_at,updated_at FROM products WHERE id=?').bind(id).first(); if(!row)return null; const {results}=await env.DB.prepare('SELECT id,url,alt_text,sort_order,is_cover FROM product_images WHERE product_id=? ORDER BY sort_order ASC').bind(id).all(); return {...row,price:Number(row.sale_price_minor??row.base_price_minor??0)/100,published:row.status==='active',images:(results||[]).map(x=>x.url)}; }
async function listProducts(env,publishedOnly){ const sql=publishedOnly?"SELECT id FROM products WHERE status='active' ORDER BY updated_at DESC":"SELECT id FROM products WHERE status<>'archived' ORDER BY updated_at DESC"; const {results}=await env.DB.prepare(sql).all(); return Promise.all((results||[]).map(r=>productRow(env,r.id))); }
async function replaceImages(env,id,images){ await env.DB.prepare('DELETE FROM product_images WHERE product_id=?').bind(id).run(); const t=now(); for(let i=0;i<images.length;i++) await env.DB.prepare('INSERT INTO product_images (id,product_id,url,alt_text,sort_order,is_cover,created_at) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),id,images[i],'',i,i===0?1:0,t).run(); }
async function customerRow(env,id){ return env.DB.prepare('SELECT id,name,phone,email,status,created_at,updated_at FROM customers WHERE id=?').bind(id).first(); }
async function orderRow(env,id){ const order=await env.DB.prepare('SELECT id,customer_id,source,currency,subtotal_minor,discount_minor,shipping_minor,tax_minor,total_minor,payment_status,fulfillment_status,referral_code,created_at,updated_at FROM orders WHERE id=?').bind(id).first(); if(!order)return null; const {results}=await env.DB.prepare('SELECT id,product_id,variation_id,product_name_snapshot,sku_snapshot,variation_snapshot_json,customization_snapshot_json,addons_snapshot_json,unit_price_minor,quantity,line_total_minor,created_at FROM order_items WHERE order_id=? ORDER BY created_at ASC').bind(id).all(); return {...order,items:results||[]}; }
async function adminStatus(env){ const tables=['customers','products','orders','payments','fulfillments','licenses','access_grants','referrals','documents','activity_events','error_events']; const counts={}; for(const table of tables){const r=await env.DB.prepare(`SELECT COUNT(*) AS count FROM ${table}`).first(); counts[table]=Number(r?.count||0);} return {ok:true,service:'reqoo-api',api_version:'core-foundation-2',database:'reqoo-rebuild',counts}; }
async function createOrder(env,input){ const o=cleanOrder(input); if(o.customer_id&&!(await customerRow(env,o.customer_id))) throw new Error('Customer not found'); const normalized=[]; let subtotal=0; for(const raw of o.items){ const pid=String(raw?.product_id||''),qty=Number(raw?.quantity??1); if(!pid||!Number.isInteger(qty)||qty<1) throw new Error('Invalid order item'); const p=await env.DB.prepare('SELECT id,sku,name,product_type,fulfillment_type,base_price_minor,sale_price_minor,status FROM products WHERE id=?').bind(pid).first(); if(!p)throw new Error(`Product not found: ${pid}`); if(p.status!=='active')throw new Error(`Product is not active: ${pid}`); const unit=Number(p.sale_price_minor??p.base_price_minor??0),line=unit*qty; subtotal+=line; normalized.push({id:crypto.randomUUID(),product_id:p.id,variation_id:raw?.variation_id||null,product_name_snapshot:p.name,sku_snapshot:p.sku||null,variation_snapshot_json:JSON.stringify(raw?.variation_snapshot||{}),customization_snapshot_json:JSON.stringify(raw?.customization||{}),addons_snapshot_json:JSON.stringify(Array.isArray(raw?.addons)?raw.addons:[]),unit_price_minor:unit,quantity:qty,line_total_minor:line}); }
 const orderId=crypto.randomUUID(),t=now(),st=[env.DB.prepare('INSERT INTO orders (id,customer_id,source,currency,subtotal_minor,discount_minor,shipping_minor,tax_minor,total_minor,payment_status,fulfillment_status,referral_code,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(orderId,o.customer_id,o.source,o.currency,subtotal,0,0,0,subtotal,'pending','pending',o.referral_code,t,t)]; for(const i of normalized) st.push(env.DB.prepare('INSERT INTO order_items (id,order_id,product_id,variation_id,product_name_snapshot,sku_snapshot,variation_snapshot_json,customization_snapshot_json,addons_snapshot_json,unit_price_minor,quantity,line_total_minor,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(i.id,orderId,i.product_id,i.variation_id,i.product_name_snapshot,i.sku_snapshot,i.variation_snapshot_json,i.customization_snapshot_json,i.addons_snapshot_json,i.unit_price_minor,i.quantity,i.line_total_minor,t)); await env.DB.batch(st); return orderRow(env,orderId); }
async function createPayment(env,input){ const orderId=String(input?.order_id||''); if(!orderId)throw new Error('Order id required'); const order=await env.DB.prepare('SELECT id,total_minor,currency,payment_status FROM orders WHERE id=?').bind(orderId).first(); if(!order)throw new Error('Order not found'); const amount=Number(input?.amount_minor??order.total_minor); if(!Number.isInteger(amount)||amount<0)throw new Error('Invalid payment amount'); const paymentId=crypto.randomUUID(),t=now(); await env.DB.prepare('INSERT INTO payments (id,order_id,provider,provider_reference,method,amount_minor,currency,status,metadata_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(paymentId,orderId,String(input?.provider||'manual'),input?.provider_reference||null,input?.method||null,amount,order.currency,'pending',JSON.stringify(input?.metadata||{}),t,t).run(); return env.DB.prepare('SELECT * FROM payments WHERE id=?').bind(paymentId).first(); }
async function fulfillPaidOrder(env,orderId){ const {results:items}=await env.DB.prepare('SELECT oi.*,p.product_type,p.fulfillment_type FROM order_items oi LEFT JOIN products p ON p.id=oi.product_id WHERE oi.order_id=?').bind(orderId).all(); const t=now(),created=[]; for(const item of items||[]){ const type=item.fulfillment_type||'service_custom'; const existing=await env.DB.prepare('SELECT id FROM fulfillments WHERE order_id=? AND order_item_id=? LIMIT 1').bind(orderId,item.id).first(); if(!existing){ const fid=crypto.randomUUID(); await env.DB.prepare('INSERT INTO fulfillments (id,order_id,order_item_id,type,status,payload_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)').bind(fid,orderId,item.id,type,'pending','{}',t,t).run(); created.push(fid); }
 if(type==='licensed_access'||type==='play_access'||item.product_type==='licensed'||item.product_type==='play_access'){ const customer=await env.DB.prepare('SELECT customer_id FROM orders WHERE id=?').bind(orderId).first(); if(!customer?.customer_id) continue; const existingLicense=await env.DB.prepare('SELECT id FROM licenses WHERE order_id=? AND product_id=? LIMIT 1').bind(orderId,item.product_id).first(); if(existingLicense)continue; const lid=crypto.randomUUID(),code=`RQ-${crypto.randomUUID().replaceAll('-','').slice(0,12).toUpperCase()}`; await env.DB.prepare('INSERT INTO licenses (id,customer_id,product_id,order_id,access_code,status,max_devices,starts_at,expires_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(lid,customer.customer_id,item.product_id,orderId,code,'active',1,t,null,t,t).run(); const gid=crypto.randomUUID(); await env.DB.prepare('INSERT INTO access_grants (id,customer_id,product_id,order_id,access_type,status,access_payload_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(gid,customer.customer_id,item.product_id,orderId,type==='play_access'?'play':'sim','active',JSON.stringify({license_id:lid,access_code:code}),t,t).run(); } }
 await env.DB.prepare("UPDATE orders SET fulfillment_status='processing',updated_at=? WHERE id=?").bind(t,orderId).run(); return created; }
async function markPaymentPaid(env,paymentId){ const p=await env.DB.prepare('SELECT * FROM payments WHERE id=?').bind(paymentId).first(); if(!p)throw new Error('Payment not found'); if(p.status==='paid')return p; const t=now(); await env.DB.prepare("UPDATE payments SET status='paid',paid_at=?,updated_at=? WHERE id=?").bind(t,t,paymentId).run(); await env.DB.prepare("UPDATE orders SET payment_status='paid',updated_at=? WHERE id=?").bind(t,p.order_id).run(); await fulfillPaidOrder(env,p.order_id); return env.DB.prepare('SELECT * FROM payments WHERE id=?').bind(paymentId).first(); }
export default { async fetch(request,env){ const origin=request.headers.get('Origin')||''; if(request.method==='OPTIONS')return new Response(null,{status:204,headers:headers(origin)}); const url=new URL(request.url); if(url.pathname==='/health')return json({ok:true,service:'reqoo-api',database:'reqoo-rebuild',api_version:'core-foundation-2'},200,origin); try{
 if(url.pathname==='/admin/status'){if(!admin(request,env))return json({error:'Admin key required'},401,origin);return json(await adminStatus(env),200,origin);}
 if(url.pathname==='/customers'){if(!admin(request,env))return json({error:'Admin key required'},401,origin);if(request.method==='GET'){const {results}=await env.DB.prepare("SELECT id,name,phone,email,status,created_at,updated_at FROM customers WHERE status<>'archived' ORDER BY updated_at DESC LIMIT 200").all();return json(results||[],200,origin);}if(request.method==='POST'){const c=cleanCustomer(await request.json());if(!['active','blocked','archived'].includes(c.status))return json({error:'Invalid customer status'},400,origin);const t=now();await env.DB.prepare('INSERT INTO customers (id,name,phone,email,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').bind(c.id,c.name,c.phone,c.email,c.status,t,t).run();return json(await customerRow(env,c.id),201,origin);}return json({error:'Method not allowed'},405,origin);}
 if(url.pathname==='/orders'){if(request.method==='GET'){if(!admin(request,env))return json({error:'Admin key required'},401,origin);const {results}=await env.DB.prepare('SELECT * FROM orders ORDER BY created_at DESC LIMIT 200').all();return json(results||[],200,origin);}if(request.method==='POST')return json(await createOrder(env,await request.json()),201,origin);return json({error:'Method not allowed'},405,origin);}
 if(url.pathname.startsWith('/orders/')){if(!admin(request,env))return json({error:'Admin key required'},401,origin);const id=decodeURIComponent(url.pathname.split('/')[2]||'');if(request.method==='GET'){const o=await orderRow(env,id);return o?json(o,200,origin):json({error:'Order not found'},404,origin);}return json({error:'Method not allowed'},405,origin);}
 if(url.pathname==='/payments'){if(request.method==='POST')return json(await createPayment(env,await request.json()),201,origin);if(request.method==='GET'){if(!admin(request,env))return json({error:'Admin key required'},401,origin);const {results}=await env.DB.prepare('SELECT * FROM payments ORDER BY created_at DESC LIMIT 200').all();return json(results||[],200,origin);}return json({error:'Method not allowed'},405,origin);}
 if(url.pathname.startsWith('/admin/payments/')&&url.pathname.endsWith('/mark-paid')){if(!admin(request,env))return json({error:'Admin key required'},401,origin);if(request.method!=='POST')return json({error:'Method not allowed'},405,origin);const id=decodeURIComponent(url.pathname.split('/')[3]||'');return json(await markPaymentPaid(env,id),200,origin);}
 if(url.pathname==='/fulfillments'){if(!admin(request,env))return json({error:'Admin key required'},401,origin);const {results}=await env.DB.prepare('SELECT * FROM fulfillments ORDER BY created_at DESC LIMIT 200').all();return json(results||[],200,origin);}
 if(url.pathname==='/licenses'){if(!admin(request,env))return json({error:'Admin key required'},401,origin);const {results}=await env.DB.prepare('SELECT * FROM licenses ORDER BY created_at DESC LIMIT 200').all();return json(results||[],200,origin);}
 if(url.pathname==='/access-grants'){if(!admin(request,env))return json({error:'Admin key required'},401,origin);const {results}=await env.DB.prepare('SELECT * FROM access_grants ORDER BY created_at DESC LIMIT 200').all();return json(results||[],200,origin);}
 if(url.pathname==='/products' || url.pathname.startsWith('/products/')){if(request.method==='GET'){const pub=url.searchParams.get('published')==='true';if(!pub&&!admin(request,env))return json({error:'Admin key required'},401,origin);return json(await listProducts(env,pub),200,origin);}if(!admin(request,env))return json({error:'Admin key required'},401,origin);const id=decodeURIComponent(url.pathname.split('/')[2]||'');if(request.method==='POST'){const p=cleanProduct(await request.json()),pid=crypto.randomUUID(),t=now();await env.DB.prepare('INSERT INTO products (id,name,slug,product_type,fulfillment_type,description,short_description,base_price_minor,sale_price_minor,currency,status,internal_notes,production_instructions,seo_title,seo_description,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(pid,p.name,p.slug,p.product_type,p.fulfillment_type,p.description,p.short_description,p.base_price_minor,p.sale_price_minor,p.currency,p.status,p.internal_notes,p.production_instructions,p.seo_title,p.seo_description,t,t).run();await replaceImages(env,pid,p.images);return json(await productRow(env,pid),201,origin);}if(!id)return json({error:'Product id required'},400,origin);if(request.method==='PUT'){const p=cleanProduct(await request.json()),t=now();await env.DB.prepare('UPDATE products SET name=?,slug=?,product_type=?,fulfillment_type=?,description=?,short_description=?,base_price_minor=?,sale_price_minor=?,currency=?,status=?,internal_notes=?,production_instructions=?,seo_title=?,seo_description=?,updated_at=? WHERE id=?').bind(p.name,p.slug,p.product_type,p.fulfillment_type,p.description,p.short_description,p.base_price_minor,p.sale_price_minor,p.currency,p.status,p.internal_notes,p.production_instructions,p.seo_title,p.seo_description,t,id).run();await replaceImages(env,id,p.images);return json(await productRow(env,id),200,origin);}if(request.method==='DELETE'){await env.DB.prepare("UPDATE products SET status='archived',updated_at=? WHERE id=?").bind(now(),id).run();return json({ok:true,id},200,origin);}return json({error:'Method not allowed'},405,origin);}
 return json({error:'Not found'},404,origin);
 }catch(error){console.error(error);return json({error:error?.message||'Server error'},400,origin);} } };