import { onRequest as handleCore } from '../functions/api/core.js';
import { onRequestPost as handleCustomer } from '../functions/api/customer-v1.js';
import { onRequest as handleOrder } from '../functions/api/order-v1.js';
import { onRequest as handleSimAdmin } from './sim-admin.js';
import { onRequest as handleShopFlow } from './shop-flow-v5.js';
import { onRequest as handleShopAdminFlow } from './shop-admin-flow-v18.js';
// v18 adds document payment ledger while preserving the complete v17 -> v16 chain.
import { onRequest as handleShopMedia } from './shop-media.js';
import { onRequest as handleProductImage } from '../functions/api/product-image.js';
import { onRequest as handleInvoice } from '../functions/api/invoice-v1.js';
import { onRequest as handleLicense } from '../functions/api/license-v1.js';
import { onRequest as handlePkskPaymentV2 } from '../functions/api/pksk-payment-v2.js';
import { onRequest as handleShop } from './shop-v2.js';
import { handle as handlePksk } from './pksk.js';
import { handle as handleHero } from './hero.js';
import { handle as handleShopContent } from './shop-content.js';
function withAdminEnv(env) { const out={...env};out.DB=env.DB;out.MEDIA=env.MEDIA;out.SHOP_DB=env.DB;out.PR00FS=env.MEDIA;const admin=env.REQOO_ADMIN_TOKEN||env.ADMIN_KEY||env.SHOP_ADMIN_TOKEN||'';out.REQOO_ADMIN_TOKEN=admin;out.SHOP_ADMIN_TOKEN=env.SHOP_ADMIN_TOKEN||admin;out.PKSK_ADMIN_TOKEN=env.PKSK_ADMIN_TOKEN||admin;out.ADMIN_API_KEY=env.ADMIN_API_KEY||admin;out.BILLPLZ_API_KEY=env.BILLPLZ_API_KEY||env.BILLPLZ_KEY||'';out.BILLPLZ_COLLECTION_ID=env.BILLPLZ_COLLECTION_ID||'';out.BILLPLZ_X_SIGNATURE_KEY=env.BILLPLZ_X_SIGNATURE_KEY||env.BILLPLZ_X_SIGNATURE||'';out.TOYYIBPAY_USER_SECRET_KEY=env.TOYYIBPAY_USER_SECRET_KEY||'';out.TOYYIBPAY_CATEGORY_CODE=env.TOYYIBPAY_CATEGORY_CODE||'';out.TOYYIBPAY_ENV=env.TOYYIBPAY_ENV||'production';out.TOYYIBPAY_CHARGE_TO_CUSTOMER=env.TOYYIBPAY_CHARGE_TO_CUSTOMER||'0';out.OPENAI_API_KEY=env.OPENAI_API_KEY||'';out.PKSK_AI_MODEL=env.PKSK_AI_MODEL||'gpt-5-mini';return out; }
async function withShopAdminEnv(env) {const out=withAdminEnv(env);let active='';try { active=String((await env.DB.prepare('SELECT admin_token FROM sim_admin_settings WHERE id=1 LIMIT 1').first())?.admin_token||'').trim(); } catch {}const admin=active||String(env.REQOO_ADMIN_TOKEN||env.ADMIN_KEY||env.SHOP_ADMIN_TOKEN||'').trim();out.REQOO_ADMIN_TOKEN=admin;out.SHOP_ADMIN_TOKEN=admin;out.ADMIN_KEY=admin;return out;}
const ADMIN_SESSION_COOKIE='rq_admin_session',ADMIN_SESSION_TTL=8*60*60;
function cookieValue(request,name){const raw=String(request.headers.get('cookie')||'');for(const part of raw.split(';')){const i=part.indexOf('=');if(i<0)continue;if(part.slice(0,i).trim()===name)return decodeURIComponent(part.slice(i+1).trim())}return''}
async function hmacHex(secret,message){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(message));return[...new Uint8Array(sig)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function safeEqual(a,b){a=String(a||'');b=String(b||'');if(a.length!==b.length)return false;let out=0;for(let i=0;i<a.length;i++)out|=a.charCodeAt(i)^b.charCodeAt(i);return out===0}
async function issueAdminSession(secret){const exp=Math.floor(Date.now()/1000)+ADMIN_SESSION_TTL,sig=await hmacHex(secret,`reqoo-admin:${exp}`);return`${exp}.${sig}`}
async function validAdminSession(request,secret){if(!secret)return false;const raw=cookieValue(request,ADMIN_SESSION_COOKIE),m=raw.match(/^(\d{10})\.([a-f0-9]{64})$/i);if(!m)return false;const exp=Number(m[1]),now=Math.floor(Date.now()/1000);if(!Number.isFinite(exp)||exp<=now||exp>now+ADMIN_SESSION_TTL+60)return false;const expected=await hmacHex(secret,`reqoo-admin:${exp}`);return safeEqual(m[2].toLowerCase(),expected)}
function sessionCookie(value,maxAge){return`${ADMIN_SESSION_COOKIE}=${encodeURIComponent(value)}; Path=/api/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Strict`}
function sessionJson(body,status=200,cookie=''){const h=new Headers({'content-type':'application/json;charset=UTF-8','cache-control':'no-store','pragma':'no-cache','x-content-type-options':'nosniff'});if(cookie)h.set('set-cookie',cookie);return new Response(JSON.stringify(body),{status,headers:h})}
async function handleAdminSession(request,env){const adminEnv=await withShopAdminEnv(env),expected=String(adminEnv.REQOO_ADMIN_TOKEN||'').trim();if(!expected)return sessionJson({ok:false,error:'Admin secret belum dikonfigurasi.'},503);if(request.method==='GET'){return await validAdminSession(request,expected)?sessionJson({ok:true,authenticated:true}):sessionJson({ok:false,authenticated:false,error:'Unauthorized'},401)}if(request.method==='DELETE')return sessionJson({ok:true,authenticated:false},200,sessionCookie('',0));if(request.method!=='POST')return sessionJson({ok:false,error:'Method tidak disokong.'},405);let d={};try{d=await request.clone().json()}catch{}const supplied=String(d.token||request.headers.get('X-Admin-Token')||'').trim();if(!safeEqual(supplied,expected))return sessionJson({ok:false,error:'Unauthorized'},401);return sessionJson({ok:true,authenticated:true,expiresIn:ADMIN_SESSION_TTL},200,sessionCookie(await issueAdminSession(expected),ADMIN_SESSION_TTL))}
async function authorizeAdminRequest(request,env){const adminEnv=await withShopAdminEnv(env),expected=String(adminEnv.REQOO_ADMIN_TOKEN||'').trim(),supplied=String(request.headers.get('X-Admin-Token')||request.headers.get('X-Admin-Key')||'').trim();if(expected&&safeEqual(supplied,expected))return{request,env:adminEnv};if(await validAdminSession(request,expected)){const headers=new Headers(request.headers);headers.set('X-Admin-Token',expected);headers.delete('X-Admin-Key');return{request:new Request(request,{headers}),env:adminEnv}}return{request,env:adminEnv}}
function signaturePayload(d){return Object.entries(d).filter(([k,v])=>k!=='x_signature'&&v!==undefined&&v!==null).map(([k,v])=>[k,String(v)]).sort((a,b)=>a[0].toLowerCase().localeCompare(b[0].toLowerCase())).map(([k,v])=>k+v).join('|')}
async function validBillplzCallback(request,env){const secret=String(env.BILLPLZ_X_SIGNATURE_KEY||'').trim();if(!secret)return false;let d={};try{const ct=(request.headers.get('content-type')||'').toLowerCase();d=ct.includes('application/json')?await request.clone().json():Object.fromEntries(new URLSearchParams(await request.clone().text()))}catch{return false}const supplied=String(d.x_signature||'').trim();if(!supplied)return false;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const digest=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(signaturePayload(d)));const computed=[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');return computed.toLowerCase()===supplied.toLowerCase()}
async function secureShop(request,env){
  if(request.method==='POST'){
    try{
      const u=new URL(request.url);
      if(u.pathname==='/api/billplz'||u.searchParams.get('action')==='billplz-callback'){
        if(!(await validBillplzCallback(request,env)))return new Response('invalid signature',{status:400});
      }
    }catch{
      return new Response('invalid signature',{status:400});
    }
  }
  return handleShop({request,env});
}
export default {async fetch(request,env,ctx){const url=new URL(request.url),path=url.pathname,bridgedEnv=withAdminEnv(env);if(path==='/api/admin-session')return handleAdminSession(request,env);if(path==='/api/shop')return handleShopFlow({request,env});if(path==='/api/shop-admin'){const a=await authorizeAdminRequest(request,env);return handleShopAdminFlow({request:a.request,env:a.env});}if(path==='/api/shop-media'){const a=await authorizeAdminRequest(request,env);return handleShopMedia({request:a.request,env:a.env});}if(path==='/api/billplz')return secureShop(request,bridgedEnv);if(path==='/api/pksk')return handlePksk(request,bridgedEnv);if(path==='/api/pksk-payment-v2')return handlePkskPaymentV2({request,env:bridgedEnv});if(path==='/api/shop-hero'){if(request.method==='POST'){const a=await authorizeAdminRequest(request,env);return handleHero(a.request,a.env)}return handleHero(request,bridgedEnv)}if(path==='/api/shop-content'){if(request.method==='POST'){const a=await authorizeAdminRequest(request,env);return handleShopContent(a.request,a.env)}return handleShopContent(request,bridgedEnv)}if(path==='/api/core')return handleCore({request,env:bridgedEnv});if(path==='/api/customer-v1'||path.startsWith('/api/customer-v1/'))return handleCustomer({request,env:bridgedEnv});if(path==='/api/order-v1'||path.startsWith('/api/order-v1/'))return handleOrder({request,env:bridgedEnv});if(path==='/api/sim-admin'||path==='/api/sim-admin-v2'){const a=await authorizeAdminRequest(request,env);return handleSimAdmin({request:a.request,env:a.env});}if(path==='/api/product-image'){if(request.method!=='GET'&&request.method!=='HEAD'){const a=await authorizeAdminRequest(request,env);return handleProductImage({request:a.request,env:a.env,ctx})}const shopAdminEnv=await withShopAdminEnv(env);return handleProductImage({request,env:shopAdminEnv,ctx});}if(path==='/api/invoice-v1'||path.startsWith('/api/invoice-v1/'))return handleInvoice({request,env:bridgedEnv});if(path==='/api/license-v1'||path.startsWith('/api/license-v1/'))return handleLicense({request,env:bridgedEnv});if(path==='/api/health')return new Response(JSON.stringify({ok:!!env.DB,service:'reqoo-api',db:!!env.DB,media:!!env.MEDIA}),{status:env.DB?200:503,headers:{'content-type':'application/json; charset=UTF-8','cache-control':'no-store','access-control-allow-origin':'*'}});return new Response(JSON.stringify({ok:false,error:'Not found'}),{status:404,headers:{'content-type':'application/json; charset=UTF-8','cache-control':'no-store','access-control-allow-origin':'*'}})}};
